### ISSUE TITLE
[BUG] Cannot Access User Profile when too many spaces 

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#100]
Environment: production

One image a thousand words :P

![image](https://user-images.githubusercontent.com/19268853/119238255-205ef480-bb4a-11eb-8d57-a1e6c90a7644.png)

![image](https://user-images.githubusercontent.com/19268853/119238173-a75f9d00-bb49-11eb-85c3-b7183553b9a7.png)

When a user is a member of many spaces the User Avatar icon is pushed outside of the area the user can interact with. The bar on the left doesn't support scrolling  so the user has to delete a space so the user avatar can be visible again.

**Comment by jacekkolasa** [comment]
fixed in https://github.com/netdata/cloud-frontend/pull/2798
released in https://github.com/netdata/cloud-frontend/releases/tag/2.14.1
