### ISSUE TITLE
[Bug]: Light theme Alerts tab tooltip is not neadable

### ISSUE THREAD

**Issue by Ancairon** [netdata/netdata-cloud#1000]
### Bug description

The tooltip is not readable in light theme

### Expected behavior

The tooltip should be readable in both themes

### Steps to reproduce

1. hover over the tab

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/70198089/1a593775-dac3-4c80-a8ed-7334c6872f86)

### Desktop

app related issue, not browser specific

### Additional context

IMO we should have some system that stores text colors and background colors for the themes that they honor the proper contrast ratios and the themes to be picking from these, because this looks like it was either assigned wrongly or was carried over from dark theme which should not be happening between light and dark themes (completely different contrast ratios there)

**Comment by hugovalente-pm** [comment]
@christophidesp could you please take a look at this one?

**Comment by hugovalente-pm** [comment]
this is fixed
