### ISSUE TITLE
[Bug]: Alert details on `Community` plan should be visible when below the node limit

### ISSUE THREAD

**Issue by papazach** [netdata/netdata-cloud#1002]
### Bug description

My space is in `Community` plan and even _though I only have one node_, when I attempt to check the details of an alert I'm presented with the following message:

![Screenshot 2024-04-09 at 7 30 12 PM](https://github.com/netdata/netdata-cloud/assets/8328670/d9ef838e-65d6-4ebc-b5dc-c7257424e1bc)

Furthermore when I try to 'Change the active node selection' (which I should not in the first place) as I am prompted, nothing happens.

### Expected behavior

I would expect to be able to see the alert details without any issues, similar to the fact that I can see my metrics for the room and the node etc.

### Steps to reproduce

1. Create a space in the `Community` plan (note that the first space of a new user always gets a Business Trial, if a second one gets created it will be on `Community`
2. Claim a node to that space
3. Try to check an alert that occurred (you can try to force one)
4. Get that message in the right sidebar

### Screenshots

![Screenshot 2024-04-09 at 6 57 40 PM](https://github.com/netdata/netdata-cloud/assets/8328670/ac395d28-64c5-4232-9f81-44ba61a43c1b)

### Desktop

OS: MacOS 14.3.1 (arm64)
Browser: Latest Brave (Version 1.64.116 Chromium: 123.0.6312.105 (Official Build)  (arm64))

### Additional context

No 4XX or 5XX response seem to be returned and given the fact that the dashboards for that node load as expected, perhaps the front-end client would be a place to start the investigation.

**Comment by hugovalente-pm** [comment]
this is fixed
