### ISSUE TITLE
[Bug]: Netdata is one of the most starred projects in the CNCF landscape.

### ISSUE THREAD

**Issue by unclehowell** [netdata/netdata-cloud#1007]
### Bug description

Your website footer has the text "Netdata is a member of the Cloud Native Computing Foundation (CNCF), and it is one of the most starred projects in the [CNCF landscape](https://landscape.cncf.io/card-mode?grouping=no&sort=stars)." but the link goes to a 404

### Expected behavior

Expect the link to link to some info. 

### Steps to reproduce

1. click the link on your website footer 

### Screenshots

![Screenshot from 2024-04-14 12-00-48](https://github.com/netdata/netdata-cloud/assets/10119070/365a7834-469b-4888-8bff-b936049cd5f9)
![Screenshot from 2024-04-14 12-00-56](https://github.com/netdata/netdata-cloud/assets/10119070/87cee369-ac0e-43a2-8377-4fee9de7dd70)

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
thanks for the report we are working on fixing it

**Comment by hugovalente-pm** [comment]
this is fixed
