### ISSUE TITLE
[BUG] Duplicate services in /claimed-nodes response

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#101]
When FE requests the available claimed-nodes in a room some services are reported as multiple times.

Below you can see the response for request to https://staging.netdata.cloud/api/v1/spaces/8a999544-9974-4fad-bea3-77fa1a8bfe65/claimed-nodes

{
  "updatedAt": "2021-05-25T12:20:43.19974468Z",
  "results": [
    {
      "nodeID": "699bedf8-a195-11ea-8ea2-96000034ea9c",
      "name": "debian-2gb-nbg1-1",
      "services": [
        "Squid",
        "Web Log"
      ],
      "os": "debian",
      "claimedAt": "2020-07-16T11:29:48.22Z",
      "state": "current"
    },
    **{
      "nodeID": "db0116a8-9222-11ea-ad55-9600003504c9",
      "name": "debian-2gb-nbg1-2",
      "services": [
        "Apache",
        "Squid",
        "Web Log",
        "Web Log"
      ],
      "os": "debian",
      "claimedAt": "2020-07-16T11:33:31.921Z",
      "state": "current"
    },**
    {
      "nodeID": "939b9392-9222-11ea-8c72-960000424015",
      "name": "n3.katsuna.com",
      "services": null,
      "os": "debian",
      "claimedAt": "2020-07-16T11:36:38.817Z",
      "state": "current"
    },
    {
      "nodeID": "e49c072c-b860-11ea-b68e-960000490f9b",
      "name": "debian-2gb-nbg1-4",
      "services": null,
      "os": "debian",
      "claimedAt": "2020-07-16T11:39:49.422Z",
      "state": "current"
    },
    {
      "nodeID": "f7e183a6-7624-497a-b26d-3f581e18bcc7",
      "name": "ubuntu-raspberry",
      "services": null,
      "os": "ubuntu",
      "claimedAt": "2020-07-27T11:52:53.812Z",
      "state": "current"
    },
    {
      "nodeID": "b2e2e3e6-cd91-11e9-a422-00d8610eba2c",
      "name": "CentOS-7-mfundul",
      "services": null,
      "os": "unknown",
      "claimedAt": "2020-07-27T16:16:39.11Z",
      "state": "current"
    },
    {
      "nodeID": "e99fc3fe-1930-11eb-a0fd-9600006b5765",
      "name": "debian-2gb-nbg1-6",
      "services": null,
      "os": "debian",
      "claimedAt": "2020-10-28T16:02:22.273Z",
      "state": "current"
    },
    {
      "nodeID": "b574d408-1d0d-11eb-b342-9600005f449c",
      "name": "debian-2gb-nbg1-5",
      "services": null,
      "os": "debian",
      "claimedAt": "2020-11-02T13:17:13.893Z",
      "state": "current"
    }
  ]
}

As a result node __debian-2gb-nbg1-2__ is displayed twice under the __Web Log__ service

![image](https://user-images.githubusercontent.com/19268853/119787489-ed19be00-bed9-11eb-8eda-37b94c83d7e4.png)

**Comment by TonyPath** [comment]
fixed by this [PR](https://github.com/netdata/cloud-nodes-service/pull/342)
