### ISSUE TITLE
[Bug]: Anomaly Advisor tab bug

### ISSUE THREAD

**Issue by Ancairon** [netdata/netdata-cloud#1011]
### Bug description

1. When I highlight a timeframe there is no loading indicator, and if the space has a lot of nodes the feature seems like it does not work
2. When I highlight a timeframe the prompt `You haven't highlighted any timeframe yet.` does not change
3. Once the Anomaly Advisor eventually runs, if I click on a chart from the right column, the `You haven't highlighted any timeframe yet.` modal is hiding half the chart.

### Expected behavior

1. There should be an indication that the feature actually processes something.
2. The prompt should indicate that I have indeed highlighted something, or vanish all-together.
3. The bug should not be present

### Steps to reproduce

1. just use the feature

### Screenshots

1. I have highlighted a timeframe and nothing seems to happen. If I wait X amount of time it might bring results. 
![image](https://github.com/netdata/netdata-cloud/assets/70198089/45b45557-1437-4cbb-9019-66203ac84bb3)
2. Take a look at the grey top prompt, it says that I got no timeframe highlighted
![image](https://github.com/netdata/netdata-cloud/assets/70198089/5a539893-2be6-4d83-bedb-bc4ab7e116ff)
3. ![image](https://github.com/netdata/netdata-cloud/assets/70198089/d6d27bee-18ff-4111-a041-d1b44b900bfa)

### Desktop

Chrome, but not important I think

**Comment by Ancairon** [comment]
Similar to #819, but this exposes some different issues with the tab, so not a duplicate.

**Comment by hugovalente-pm** [comment]
> There should be an indication that the feature actually processes something.

This point was working in the past with some animation, just sharing that this is something we can do Surface a component that shows the progress when a transaction is initiated from the FE [#4467](https://github.com/netdata/cloud-frontend/issues/4467)

**Comment by hugovalente-pm** [comment]
some feedback on this ticket

> 1. When I highlight a timeframe there is no loading indicator, and if the space has a lot of nodes the feature seems like it does not work
> 2. When I highlight a timeframe the prompt You haven't highlighted any timeframe yet. does not change

@kapantzak already fixed the above two points and this is released on Production

> 3. Once the Anomaly Advisor eventually runs, if I click on a chart from the right column, the You haven't highlighted any timeframe yet. modal is hiding half the chart.

for this 3rd one the div is always there (sticky position to the top), to not go into a lot of work to change this behaviour the suggestion is to change the message displayed there to what it was before

```
Anomalous metrics in the selected timeframe sorted from most anomalous to least.
```

**Comment by hugovalente-pm** [comment]
this is now fixed
