### ISSUE TITLE
[Bug]: Some of my VM doesn't report CPU usage

### ISSUE THREAD

**Issue by foux** [netdata/netdata-cloud#1014]
### Bug description

Hi. FOr a reason I don't know, some of my VMs aren't reporting CPU usage
All VMs have the same configuration so I can't understand why I have CPU for some and not for others

### Expected behavior

CPU usage visible for all nodes

### Steps to reproduce

1. Go to netdata cloud

### Screenshots

![CleanShot 2024-05-03 at 13 49 18](https://github.com/netdata/netdata-cloud/assets/246550/5f63adfe-8933-4657-95ce-8e9fafb49f22)

### Desktop

OS: Debian on LXC
Browser Chrome

**Comment by hugovalente-pm** [comment]
if you access the local agent's dashboard can you see those metrics?

could you share these details for both a machine that is reporting and one that isn't
* System info - Provide information about your system. To get this information, execute one of the following commands based on your OS:
```
# Linux
uname -a; grep -HvE "^#|URL" /etc/*release
# BSD
uname -a; uname -K
# macOS
uname -a; sw_vers
```
* Netdata build info - Provide Netdata Agent version and build info. To get this information, execute:
```
netdata -W buildinfo
# If get "netdata: command not found", try (required running Netdata)
$(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo

```

**Comment by foux** [comment]
I solve the issue just on rebooting the VMs, it's kinda weird
