### ISSUE TITLE
[Feat]: Flood protection alert nonfiction should give more context

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#1017]
### Problem

When Netdata Cloud triggers a Flood Protection notification it isn't possible to have an idea what could be main cause of it

![image](https://github.com/netdata/netdata-cloud/assets/82235632/6c59d788-ce02-46a5-b169-0fd46859d658)

### Description

If some more context was added, similar to what is on the Home tab, users could understand if:
* one machine is having some network issue or CPU consumption spikes that could be flip-flopping the alerts, or
* major incident is happening and multiple machines are affected

![image](https://github.com/netdata/netdata-cloud/assets/82235632/69c13100-c2b4-4504-b731-42afa65a871b)

### Importance

really want

### Value proposition

1. Users would immediately be able to assess the importance of what's happening

### Proposed implementation

Add some stats like the Home tab for:
* Nodes with most alerts in the last X hours/minutes
* Top alerts in the last X hours/minutes

**Comment by sashwathn** [comment]
@car12o : Do we have some statistical information available on the offender for notifications so we can add it to the flood protection template?

**Comment by car12o** [comment]
> @car12o : Do we have some statistical information available on the offender for notifications so we can add it to the flood protection template?

yes, flood protection is per account/email and we have the latest notifications (node + alarm name + chart) we send to the account.

**Comment by sashwathn** [comment]
@car12o : Do you mean we already have a new notification template that sends this information to the account? I still see this one on my mailbox. 
<img width="1228" alt="image" src="https://github.com/user-attachments/assets/0f8bd40d-903c-432e-89fa-d4f8883b1c7d">

**Comment by car12o** [comment]
> @car12o : Do you mean we already have a new notification template that sends this information to the account? I still see this one on my mailbox.

no, I meant we have this data but the email content is not enriched with that.

**Comment by sashwathn** [comment]
Thanks @car12o : I have added this to our initiative list and we can pick it up when we are done with some of the higher priority stuff.

**Comment by car12o** [comment]
deployed on all envs
