### ISSUE TITLE
[BUG] When I click on an alarm, I usually see an empty chart

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#102]
Regardless of an individual agent's retention, users should NEVER see this:

![image](https://user-images.githubusercontent.com/43294513/119701001-c2136980-be08-11eb-949f-9b9a100282e7.png)

**Comment by cakrit** [comment]
There was work done from the FE for this, but we saw yesterday with @novykh that the BE returned strange responses in certain cases, not respecting the `before` and `after` sent in the request.

**Comment by papazach** [comment]
Hello, is this a critical production bug which we'll have to look into asap? Just wanted to be sure about this because I noticed the `priority/high` label.

**Comment by manos-saratsis** [comment]
Fixed, there is user feedback now
<img width="901" alt="Screen Shot 2021-06-18 at 9 03 30 AM" src="https://user-images.githubusercontent.com/19746055/122514112-b08a3f80-d00b-11eb-8d0b-1cbbca48f24e.png">
