### ISSUE TITLE
[Feat]: Telegram notifications support groups with topics 

### ISSUE THREAD

**Issue by WavesFunnyNode** [netdata/netdata-cloud#1021]
### Problem

No option to send messages to the group topic.

### Description

After the Telegram update, now all groups can enable topics in their group (similar to Discord). More details can be found [here](https://telegram.org/blog/topics-in-groups-collectible-usernames)

### Importance

really want

### Value proposition

1. We use it for our monitoring alerts to notify us.
2. Over the past few years, Telegram has gained many cool new features that are much better than others.
3. It allows us to organize discussions into specific topics, making it easier to follow conversations.

### Proposed implementation

Basically, it's just a one-word addition to the message-sending process with **message_thread_id=TOPIC_ID**.

```
async def async_send_message(message):
    bot = Bot(token=TOKEN)
    try:
        await bot.send_message(chat_id=chat_id, **message_thread_id=TOPIC_ID**, text=message, parse_mode='HTML', disable_web_page_preview=True)
        logger.info("Telegram: Message sent successfully")
    except Exception as e:
        logger.error(f"Telegram: Error sending message: {e}")

def send_message(message):
    asyncio.run(async_send_message(message, disable_notification))
```

Here are some guides:
[Telegram documentation](https://core.telegram.org/bots/api#sendmessage)
[How to get topic ID for Telegram group chat](https://stackoverflow.com/questions/74773675/how-to-get-topic-id-for-telegram-group-chat)
[Send notifications to a specific topic in the Telegram chat](https://medium.com/@rezvovvad/send-notifications-to-a-specific-topic-in-the-telegram-chat-1f570b7ab929)"

**Comment by juacker** [comment]
thanks for contacting us @WavesFunnyNode,

To better understand the request, are you proposing that we accept the `topic_id` parameter as part of the Telegram integration configuration, in order to send messages to a user-specified topic?

**Comment by WavesFunnyNode** [comment]
@juacker That's right!

**Comment by papazach** [comment]
Hello @WavesFunnyNode I'm in the pleasant position to let you know that the _optional_ **Topic ID** parameter is now available to our Cloud Telegram integration!

![Screenshot 2024-06-13 at 4 43 07 PM](https://github.com/netdata/netdata-cloud/assets/8328670/5e5c00cd-ac36-45a7-aca9-af3cc99bfcfb)

Our docs will be updated soon as well ([link](https://github.com/netdata/netdata/pull/17873)), but I thought it would make sense to give you an early heads up.
In the meantime you can check the PR's instructions on how to get your topic ID but I suppose you already know that 😎 

Happy monitoring!

PS: Feel free to close this issue given that everything works as expected.

**Comment by WavesFunnyNode** [comment]
Thank you!
