### ISSUE TITLE
[Bug]: Web-UI chart metric tooltip ordering fixed to alphabetical ascending on Firefox

### ISSUE THREAD

**Issue by dogsbody-josh** [netdata/netdata-cloud#1024]
### Bug description

Mouse over tooltips on chart metrics provide a quick pop-up visual indication of dimension values/anomaly rate. In Chromium, Dimensions are ordered by "Value Descending" (largest Value at the top). This provides useful insight into the particular Dimension consuming the largest Value - a service consuming RAM or CPU for example. 

On Firefox, the Dimension's in tooltips are ordered by "Dimension Alphabetical Ascending" (fixed Dimension name A-Z). This often provides no useful information as to what Dimension is consuming which Value the most. 

### Expected behavior

It is expected that the behaviour of chart metric tooltips on Firefox would be the same as that on Chromium

### Steps to reproduce

1. Select any chart - I suggest Applications > Memory and time set to last 15 minutes in order to easily see the issue.
2. Place your mouse over the graph and observe the tooltip
3. Dimension ordering is different between Firefox/Chromium

## Chromium tooltip example
![netdata-chromium-tooltip](https://static.dogsbody.com/screenshots/netdata-chromium-tooltip.png)
## Firefox tooltip example
![netdata-firefox-tooltip](https://static.dogsbody.com/screenshots/netdata-firefox-tooltip.png)

### Error Logs

N/A

### Desktop

OS: [e.g. iOS]	Tested on Linux and MacOS
Browser [e.g. chrome, safari]	Tested on Firefox and Chromium
Browser Version [e.g. 22] Firefox 127.0 / Chromium 126.0.6478.55

### Additional context

I believe this is different to #736 as that specifically requests control of the ordering and this bug report describes possibly unintended differences in behaviour between browsers.

**Comment by dogsbody** [comment]
This is really doing our head in.  We use Firefox as our everyday browser and we are now having to open Chromium just to use Netdata :-(

**Comment by novykh** [comment]
There seems to be an issue with firefox not giving event offset position. From your screenshot it seems like you are always hovering on the anomaly part of the chart - hence Anomaly column in popover is bold. I just released a fix for this, closing it and feel free to re-open in case something doesn't work for you [dogsbody](https://github.com/dogsbody).

**Comment by dogsbody** [comment]
This looks to be working great now. Thank you so much :+1: :1st_place_medal:
