### ISSUE TITLE
[BUG] Visited Nodes trashcans icons not displayed correctly

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#103]
When nodes' urls are long visited nodes trashcans have different sizes and some times they are not even visible

![image](https://user-images.githubusercontent.com/19268853/119789888-20f5e300-bedc-11eb-90fb-7d807761e944.png)

**Comment by BenJule** [comment]
![screen-2021-08-25-17-45-44](https://user-images.githubusercontent.com/7575797/130822913-1b696a61-5288-4cb8-9e71-ecb95ba1f4e4.png)

yeah i have the same issue!

**Comment by jacekkolasa** [comment]
fixed in https://github.com/netdata/cloud-frontend/pull/2798
released in https://github.com/netdata/cloud-frontend/releases/tag/2.14.1
