### ISSUE TITLE
[Bug]: when filtering is active, colors on the chart do not match the legend

### ISSUE THREAD

**Issue by intelfx** [netdata/netdata-cloud#1031]
### Bug description

When label filtering is used on a (line) chart, colors in the legend and in the actual chart are mismatched.

### Expected behavior

Colors in the legend should match colors in the chart.

### Steps to reproduce

1. Visit any Netdata dashboard
2. Navigate to a chart with non-trivial labels (that would allow to select a subset of dimensions)
3. Select some of the label values

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/1158172/5bcb16db-cdd7-499d-88a4-4c27d0d94e1d)

### Desktop

- OS: Any
- Browser: Firefox, Chromium
- Browser Version: latest applicable

**Comment by novykh** [comment]
Should be fixed.
