### ISSUE TITLE
[Bug]: local dashboard disappears after a couple days

### ISSUE THREAD

**Issue by intelfx** [netdata/netdata-cloud#1034]
### Bug description

The "local-custom-dashboard" that one can customize locally resets to empty state spontaneusly.

### Expected behavior

"local-custom-dashboard" does not reset spontaneously and is as durable as the local browser profile.

### Steps to reproduce

1. Go to netdata agent dashboard
2. Add some charts to the local dashboard, customize them
3. Click "save"
4. Close the browser
5. Wait a few days
6. Go to netdata dashboard again and try to open the local dashboard

### Desktop

- OS: Linux
- Browser: Firefox, Chromium
- Browser Version: latest applicable

**Comment by intelfx** [comment]
It would seem that netdata somehow loses the ability to display the custom dashboard, but the data is still there.

![image](https://github.com/netdata/netdata-cloud/assets/1158172/ee9c2488-3f27-400c-b299-1fb146512ab8)

**Comment by sashwathn** [comment]
@intelfx : Custom dashboards on the local agent are not saved and remain in the browser cache. You can only save custom dashboards on the Cloud dashboard if you use our SaaS offering.
Closing this issue.
