### ISSUE TITLE
Fix the post-signup experience on mobile

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#1038]
### Bug description

Netdata's UI is intended for use on large screens, and is NOT optimized for mobiles. 

However we notice that a significant % of users (up to 40%) sign up initially from their mobile devices. These users get a poor experience after signing up and this needs to be improved.

### Expected behavior

1. **Landing page redirect**: Create a mobile-optimized landing page that detects mobile users and redirects them after sign-up. This page could:

- Run the user survey to discover more info about the user/use-case
- Explain that Netdata is best experienced on larger screens
- Provide instructions on how to access Netdata from a desktop
- Embed/Link to video on how to get started with Netdata

2. **Email follow-up**: Send an automated email to users who sign up from mobile devices, encouraging them to access Netdata from a larger screen for the best experience.

(Longer term action: Develop a mobile-optimized Netdata UI -- this is out of scope for this particular issue)

### Steps to reproduce

1. Just try signing up from mobile device.

### Desktop

Browser Version [e.g. 22]

**Comment by kapantzak** [comment]
@shyamvalsan version 6.151.0 of cloud FE has been released and it fixes the unusable typeform on mobile devices.

Please let me know if we want to change anything.

**Comment by shyamvalsan** [comment]
@kapantzak the typeform survey looks good on mobile now. The intent of this issue is also to do the following

- Post the survey show this message on the screen (it should be dismissible)
> Netdata works best on larger screens. Try logging in from a laptop, desktop or tablet for the ultimate dashboard adventure.

- (Optionally) Link to the installation [video](https://www.youtube.com/watch?v=z5m8JdwMOn8&t)
> Installing the Netdata agent takes less than a minute, check out the [video ](https://www.youtube.com/watch?v=z5m8JdwMOn8&t)and try it out yourself!

**Comment by kapantzak** [comment]
@shyamvalsan I added a post-signup modal that shows up after typeform submit and shows the video link. If the screen is narrow, we also show the relevant message that it's better to use Netdata on a wide screen.

Check [PR](https://github.com/netdata/cloud-frontend/pull/4649)
