### ISSUE TITLE
[BUG] Visited Node doesn't disappear directly after deletion

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#104]
When a user clicks on the trashcan to delete a visited note, the trashcan and the visited url disappears but the node remains in the list until user refreshes the page

![image](https://user-images.githubusercontent.com/19268853/119790245-729e6d80-bedc-11eb-84ee-aa1412219a23.png)

**Comment by jacekkolasa** [comment]
fixed in https://github.com/netdata/cloud-frontend/pull/2798
released in https://github.com/netdata/cloud-frontend/releases/tag/2.14.1
