### ISSUE TITLE
[Bug]: Metrics Correlation doesn't shortlist the correlated metrics with the new TOC dashboard

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#1043]
### Bug description

When the "New Metrics Dashboard Table of Contents" early access is turned ON (which it is by default now) and metrics correlation is run, the dashboard continues to show ALL metrics and doesn't short list to correlated metrics. 

Disabling the feature from early access menu toggle - fixes the issue.

### Expected behavior

Metrics Correlation should shortlist ONLY the correlated metrics.

### Steps to reproduce

1. Just try running metrics correlation on any space with the new dashboard enabled

### Screenshots

![image](https://github.com/user-attachments/assets/fea88ed9-133a-4fa1-a894-7debe7518697)

### Error Logs

N/A

### Desktop

N/A

**Comment by ralphm** [comment]
Similarly, the anomalies tab only seems to filter for the dimension, not the instance.

**Comment by novykh** [comment]
> Similarly, the anomalies tab only seems to filter for the dimension, not the instance.

Weights endpoint doesn't provide such info.

UPDATE: We talked with agent and will be added in next release.

**Comment by ralphm** [comment]
Thanks, @novykh!
