### ISSUE TITLE
[Bug]: Misspelling in the Kubernetes/K8s metrics Network menu item (Nework)

### ISSUE THREAD

**Issue by linkev** [netdata/netdata-cloud#1046]
### Bug description

The menu item that is supposed to be "Network" is misspelt to be "Nework"
This bug exists in Netdata Cloud and a selfhosted version of Netdata (Kubernetes Helm Chart version at least)

### Expected behavior

The menu item should be spelt as "Network"

### Steps to reproduce

1. Go to a node and then the "K8s" tab at the top in Netdata cloud. Look on the right, in the dropdown menus, the "Network" item is named as "Nework"
2. Same goes for a self hosted installation, local install doesn't have the "K8s" tab at the top in "local" room, but the Kubernetes metrics are still on the right and can see "Nework" in the dropdowns

### Screenshots

Netdata Cloud
![image](https://github.com/user-attachments/assets/557ca4dd-a50a-4708-8e32-9ed39ee4c6fc)

Netdata Self Hosted Kubernetes via Helm
![image](https://github.com/user-attachments/assets/8c91a653-70c2-4a28-980d-380d6a98a998)

### Desktop

OS: Windows
Browser: Chrome
Browser Version: 129.0.6668.90

**Comment by novykh** [comment]
Should be fixed already.
