### ISSUE TITLE
[BUG] OS is set to Linux when user opens node in tab

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#105]
Reported OS is set to Linux when user clicks to open a node in a different tab.

When user refreshes page, OS resets to the original value.

This also affects the icons displayed in table view, as well as grouping in Nodes Tab and Alerts Smartboard.

![image](https://user-images.githubusercontent.com/19268853/119823423-7b536b80-befd-11eb-8cef-9774a2d19d3e.png)

After visiting the node

![image](https://user-images.githubusercontent.com/19268853/119823522-9b832a80-befd-11eb-82ef-51a0be5ee88e.png)

![image](https://user-images.githubusercontent.com/19268853/119823594-b48bdb80-befd-11eb-8b67-dcb930994d05.png)

Another Example:

![image](https://user-images.githubusercontent.com/19268853/119860032-9edade00-bf1e-11eb-9378-7b9c42360d82.png)

After opening node in tab:

![image](https://user-images.githubusercontent.com/19268853/119860196-c3cf5100-bf1e-11eb-8f19-164e9285fd01.png)

Grouping is also affected:

Original State:

![image](https://user-images.githubusercontent.com/19268853/119860457-02650b80-bf1f-11eb-95cf-56e9c6eeab5e.png)

After opening the node in tab:

![image](https://user-images.githubusercontent.com/19268853/119860532-14df4500-bf1f-11eb-86e2-c2edcf3650bb.png)

**Comment by hugovalente-pm** [comment]
This seems to be fixed, so closing it
