### ISSUE TITLE
[BUG] Datetime picker set to specific timestamp after user clicks active alert

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#106]
This is more of a user experience issue. Not a bug in the code.

The issue is more "dominant" when user clicks an alert that points to a timestamp outside of agent data retention. 

Steps to reproduce:

1.  Navigate to Alerts Smartboard
2. Click on an active alert that points to an old timestamp for which the agent doesn't have any data.
3. User is re-directed to single node view tab to the chart containing that alert
4. Navigate back to Nodes Tab (table view)
5. Datetime picker is set and paused to the timestamp the alert occurred
6. Data for that agent are displayed as empty.

Refreshing the page resets the datetime picker to a "Playing" state and data are displayed live.

The main issue is that is difficult for the user to understand that datetime has been set to that specific timestamp since no notification is displayed.

**Ideally, checking an alert should not affect the global date time picker**

![image](https://user-images.githubusercontent.com/19268853/119970291-34767c00-bfb8-11eb-8702-f49bd24f58aa.png)

**Comment by manos-saratsis** [comment]
@dimko It's intended that clicking on an alert changes the date-time picker

**Comment by dimko** [comment]
@manos-saratsis the issue is that it is confusing for the user because we do not notify him somehow that the selected datetime will be preserved. Even if it was designed this way doesn't mean that the user experience is the optimal. 

@novykh what do you think about this?
