### ISSUE TITLE
[BUG] Filter service or group by service does not return all  possible results

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#107]
**Describe the bug**	
Services are autodiscovered and are shown in the single node right bar but when you filter by service or group by service not all available services are shown. See NC space
**To Reproduce**	
Go to Overview and filter by service
Go to Alert smartboard and group by service

**Expected behavior**	
I would expect when grouping or filtering by service that all recognized services are shown. 
For a demonstration of the issue please reach out

**Comment by cakrit** [comment]
The service grouping has some hard-coded mappings from certain collectors to certain groups of "Services". It was based on an old workbook that was also used to initially map those collectors to the same groups in the old website we had. Not sure where that mapping is stored in our implementation, perhaps it's a JSON that the FE uses, or it comes back from the BE. It's a matter of seeing what's not mapped that should be added. Note that we didn't have the Prometheus collector back then, so a ton of monitored services via that will also be missing from that mapping. Let's start by finding where it is, understanding what exactly it maps (I think it's just plugin/module) and update to include newer collectors first. Then we see how we should extend it to cover prometheus-plugin services as well.
