### ISSUE TITLE
[BUG] Nodes removed from War Room, may still appear to other users due to caching

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#108]
Space X, with Room Y with 10 nodes and 2 members (User A, User B)

5 of the nodes are unreachable

1. User A logs in and deletes the 4 unreachable nodes.
2. **User B is not logged in**.

Expected behaviour:

When User B logs in and visits Space X and Room Y she should see 6 nodes in total.

What happens:
User B logs in and visits Space X and Room Y, but she still sees 10 nodes inside the room.
User B hasn't been notified that those Nodes have been deleted.

Only way for User B to see the real state of the room and its nodes is to clear her caches.

Screenshots below taken from staging environment. Same Space/Room, 2 different users.

What user A sees:

![image](https://user-images.githubusercontent.com/19268853/119998341-474d7880-bfd9-11eb-8fa6-077c8b986499.png)

What user B sees:

![image](https://user-images.githubusercontent.com/19268853/119998247-33a21200-bfd9-11eb-9a01-f4b1e12e0f61.png)

**Comment by dimko** [comment]
@jacekkolasa Do we have any update on this one?

**Comment by novykh** [comment]
@jacekkolasa @dimko could you verify this is fixed on prod and close it if it is? Thank you

**Comment by ivangergo3** [comment]
@novykh @dionysis-netdata I have checked, please see my findings below

Some of the unreachable nodes are disappearing for the B user, but not all
And if I have been there already, checked what about the live noes, and they have the same problem.
I removed 4 unreachable nodes, logged in and checked. Logged out then removed 4 reachable nodes. And logged in to check again.

3 of the unreachable nodes are still visible (1 is the expected)
2 of the reachable nodes are still visible (1 is expected)
Attached 2 pictures 
![reachable_nodes.JPG](https://images.zenhubusercontent.com/61dc07142e85a53934e62c71/188eeb20-e5e1-43ef-adc9-08e010f0beff)
![unreachable_nodes.JPG](https://images.zenhubusercontent.com/61dc07142e85a53934e62c71/224161bf-0547-4c40-b864-aea33d4ab3d2)
