### ISSUE TITLE
Randomly changing chart background in Netdata cloud [BUG]

### ISSUE THREAD

**Issue by dim08** [netdata/netdata-cloud#11]
**Describe the bug**	
- While scrolling up/down in the Netdata cloud node view, the background of some charts is changing randomly.

**To Reproduce**	
- go to metric correlations 
- select a window 
- scroll up/down 

**Screenshots**	
![image](https://user-images.githubusercontent.com/60917629/99817437-95c71980-2b55-11eb-9cca-76aee73f4b7e.png)

**Desktop (please complete the following information):**	
 - MacOS 11.0.1
 - Chrome Version 87.0.4280.67 (Official Build) (x86_64)

**Comment by jacekkolasa** [comment]
fixed on production
