### ISSUE TITLE
[BUG] Highlighted chart in sidebar doesn't correspond to the one displayed after checking an alert

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#112]
Environment production.

Steps to reproduce:

1. Navigate to Alerts Smartboard
2. Click to check an alert on a node with active alerts.
3. User is re-directed to single node's tab and affected chart is highlighted and marked.

What happens:
The chart selected on the side bar doesn't correspond to the one displayed and marked as affected with the alert.

![image](https://user-images.githubusercontent.com/19268853/120987505-51643980-c786-11eb-88af-0b3de2ac4562.png)

**Comment by jjtsou** [comment]
https://github.com/netdata/cloud-frontend/pull/2768

**Comment by dimko** [comment]
Fixed
