### ISSUE TITLE
[BUG] User redirected to the agent while signing up to the cloud

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#115]
Original report was in an internal project, history below. Several users have reported the same issue.

User is not able to sign-up to the cloud
#2062
dim08 opened this issue 12 days ago · 3 comments
Comments
@dim08
 
dim08 commented 12 days ago • 
User has installed netdata docket image
clicks on "sign-up to the cloud" on the the agent dashboard
adds his email
gets join the cloud email
clicks on join the cloud and the he gets redirected to the agent, the cloud onboarding process does not start.

@dim08 dim08 added bug 🐛 cloud-backend labels 12 days ago
@dim08 dim08 assigned amalkov and manos-saratsis 12 days ago
@papazach papazach self-assigned this 12 days ago
@papazach
 
papazach commented 12 days ago
Hello 👋. , has. anyone managed to reproduce this?

@dim08 , @amalkov , @manos-saratsis

I just tried with the latest docker image, and the onboarding process started as expected etc.

@papazach
 
papazach commented 12 days ago
I tried several times again and recorded one of them here:

https://drive.google.com/file/d/1Il5Ytptux-J2mtn3g3XlpGODd86pnzSZ/view

Each time I went through the onboarding process as expected and finally to my newly created space/room.

Grafana registration related metrics also seem to show nothing out of the ordinary:

https://grafana.corp.app.netdata.cloud/d/traefik/traefik-app-netdata-cloud?orgId=1

If you manage to reproduce this please provide exact reproduction steps (ideally screenshots and/or video).
Thanks.

@cakrit cakrit added the priority/high label 2 minutes ago
@cakrit
 
cakrit commented 2 minutes ago
Many people have reported this, not just this one user and it has to do with a redirect back to the agent, which I know is a feature we have had from the beginning, under certain conditions.

**Comment by novykh** [comment]
It's easily fixed by the frontend - to not redirect the user after sign in, even if there is a `redirect_uri`, but I believe we need to figure out what are the specs for that, before jumping into fixing this, and break something else - for example, we used to redirect for some reason, is there a flag that separates the two different states?

**Comment by novykh** [comment]
So after checking the code (historically) this was happening since always, but only when signing up through oauth buttons. I believe a quick fix for that, is to provide a flag on the url (on newly created users) by the backend, like `new_account=true`. Thoughts?

**Comment by manos-saratsis** [comment]
With the new onboarding after signing in the user is on Cloud, no redirection, works as expected.
Both on case of new account and sign in on existing
