### ISSUE TITLE
[BUG] Alert has been raised but the combination of alert value and alert timestamp is missing

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#116]
**Describe the bug**	
When I go to chart from an alert on the Cloud, I see when the alert is raised but:
1)the combination of alert value:alert timestamp is not correct

**To Reproduce**	
Go to a chart in Cloud from an alert

**Expected behavior**	
The timestamp of an alert should have the corresponding alert value
The unit should be present

**Comment by dimko** [comment]
Changing to medium since only units seem to be missing
