### ISSUE TITLE
[BUG] down arrow stucks on the status charts

### ISSUE THREAD

**Issue by apostolidhs** [netdata/netdata-cloud#117]
**Describe the bug**	
I press the down arrow and consistently get stuck on the status 

**To Reproduce**	
I press the down arrow and consistently get stuck on the status charts and I have to again click somewhere to restart scrolling.

**Expected behavior**	
Should scroll without stucking

**Additional context**	
Haven't noticed this behavior anywhere else

**Comment by hugovalente-pm** [comment]
Can't reproduce
