### ISSUE TITLE
[BUG] User sees blank screen after signing to Netdata with Firefox on Windows 10

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#118]
**Describe the bug**	

**To Reproduce**	
Steps to reproduce the behavior:	 Firefox at desktop windows 10, signing to Cloud
Chrome and Edge worked fine

**Expected behavior**	
The user expected to go to Cloud

**Comment by cakrit** [comment]
Fix has been deployed to production and user verified it works yesterday.
