### ISSUE TITLE
[BUG] Node unreachable, no email alert

### ISSUE THREAD

**Issue by jackbucinskas** [netdata/netdata-cloud#119]
**Describe the bug**	
Suspended a cloud VM, Netdata Cloud acknowledged that the node was unreachable although no email was sent to say it was unreachable.

**To Reproduce**
1. Turn off node	
2. Look at Netdata Cloud to see if the node is unreachable (this should send an email alert?)

**Expected behavior**	

https://learn.netdata.cloud/docs/monitor/enable-notifications

**Desktop (please complete the following information):**	
 - OS: [e.g. iOS] macOS 12
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 15.0

![image](https://user-images.githubusercontent.com/20350221/125365852-5e450000-e3b8-11eb-881d-8a01b5974a47.png)

**Comment by OdysLam** [comment]
Thanks, @jackbucinskas for posting the error here. I have notified our engineers and we will come back soon for triage. 

it's unfortunate, but we will get to the bottom of it.

**Comment by manos-saratsis** [comment]
@jackbucinskas Please check that reachability notifications are enabled by going to your Account/Profile/Notifications and check "All alerts and unreachable".

**Comment by jackbucinskas** [comment]
@manos-saratsis hey there, I attached a screenshot on my initial bug report. I have enabled "All alerts and unreachable" on all of my Netdata spaces on my account. Many thanks

**Comment by avallintine** [comment]
Same problem here. Server running on VM and reporting data to Netdata Cloud just fine. Received a couple of warning email notifications while server was running, in fact. Shut down VM. Netdata shows status of server as unreachable, but I never received an email notification. Under Profile > Notifications have "E-mail" enabled and "All alerts and unreachable" selected.

**Comment by manos-saratsis** [comment]
@avallintine  and  @jackbucinskas we are working on this but it will take some weeks to see it fixed. Closing as a duplicate, let's track with https://github.com/netdata/netdata-cloud/issues/97
