### ISSUE TITLE
[BUG] Width of most screens not resizing properly

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#12]
**Describe the bug**	
System overview, node view, overview screens don't resize when we reduce the available width.

**To Reproduce**	
Make the window smaller, or hit F12 with the console appearing on the right side.

**Expected behavior**	
Resize the main contents of the screen

**Screenshots**	
![image](https://user-images.githubusercontent.com/43294513/99827665-c9328580-2b0e-11eb-8417-a0280221940d.png)

**Error logs**	

**Desktop (please complete the following information):**	
 - OS: Windows 10
 - Browser: Chrome Version 86.0.4240.198 (Official Build) (64-bit)

**Comment by jacekkolasa** [comment]
fixed with https://github.com/netdata/cloud-frontend/pull/2448 (in review right now)
