### ISSUE TITLE
[BUG] Broken link

### ISSUE THREAD

**Issue by cjcox17** [netdata/netdata-cloud#124]
**Describe the bug**	
Broken read the documentation link

**To Reproduce**	

From the left menu, if you click Claim Nodes, use the right pane, then scroll down to the link in green that says 

> Currently unclaiming is not supported but to reclaim your nodes  read our documentation

The

> read our documentation

link is broken.

**Expected behavior**	
Link not to be broken

**Desktop (please complete the following information):**	
 - OS: MacOS 12	
 - Browser Safari
 - Version 15.0 (17612.1.18.1.3)

**Comment by manos-saratsis** [comment]
@cjcox17 thx for raising it

**Comment by hugovalente-pm** [comment]
Thanks @cjcox17 for spotting this. 
This was fixed with a release we did yesterday so closing the bug.
