### ISSUE TITLE
[BUG] Single Node view chart description different from charts directly on the Agent 

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#126]
**Describe the bug**	
When looking to the same node on Cloud on Single Node view and on the Agent directly we see differences on chart descriptions.

**To Reproduce**	
Open one node on the Cloud on Single Node view and open the Agent page and see that there are differences on descriptions of some charts.

[List of the of the identified differences](https://docs.google.com/spreadsheets/d/1uuMiiI37UknFjf9WL-DIFlNz95Tda9l4HQ3Mh3nwtgE/edit#gid=0)

**Expected behavior**	
There shouldn't be differences, where there isn't a need to have differences, between the Single Node view on the Cloud and the Agent charts.

**Screenshots**	
One example:
* CPU on the Agent
![image](https://user-images.githubusercontent.com/82235632/128163683-ffcba97a-5451-4236-85c4-21a28ad355ee.png)

* CPU on the Cloud
![image](https://user-images.githubusercontent.com/82235632/128163763-7bc2d5e3-2cec-4c85-9f8d-e957ab23607a.png)

**Comment by cakrit** [comment]
Apparently this has been forgotten for almost a year. We need to look where we get the descriptions and why they are different. It makes sense to have differences in context charts, but not in single node charts. I don't see this as a medium prio bug though, the effect is very minor.

**Comment by hugovalente-pm** [comment]
I guess this can be closed due to the plan of achieving this https://github.com/netdata/product/issues/3033
