### ISSUE TITLE
[BUG] Highlighting does not render from a url

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#127]
**Describe the bug**	
Highlighted regions are not being respected by netdata cloud under certain circumstances.

**To Reproduce**	

If i highlight an area in netdata cloud on a node:

![image](https://user-images.githubusercontent.com/2178292/128172693-d36e4154-aa7d-4665-a43a-05841ec14b2e.png)

And i try copy and paste that url (with the `highlight_after` and `highlight_before`) to open the same view, i lose the highlighting.

![image](https://user-images.githubusercontent.com/2178292/128172880-10cee689-e5bb-4ef0-9671-e6a08ba478f0.png)
	

**Expected behavior**	

Netdata cloud should highlight as per the url.

**Desktop (please complete the following information):**	
 - OS: windows
 - Browser:  chrome

**Comment by manos-saratsis** [comment]
@apostolidhs this is in between a bug and a missing feature

**Comment by hugovalente-pm** [comment]
Closing this since it seems to be fixed
