### ISSUE TITLE
[BUG] Charts in new dashboard resize on hover

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata-cloud#13]
**Describe the bug**	

When I build a new dashboard in Netdata Cloud, the charts seem to auto-resize on hover, which makes interacting with them quite difficult, and then reduces their height, which gives less precise metrics. I only see this happen in Firefox.

**To Reproduce**	

- Create a new dashboard
- Add one or more charts to the dashboard
- Hover over the chart

**Expected behavior**	

- Charts in a dashboard should not resize on hover

**Screenshots**	

![Peek 2020-11-20 10-05 mp4](https://user-images.githubusercontent.com/1153921/99828636-6fcf5400-2b18-11eb-9991-b5d954c63c9e.gif)

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	

**Desktop (please complete the following information):**	
 - OS: Fedora 33
 - Browser: Firefox
 - Version: 83.0

**Additional context**

**Comment by jacekkolasa** [comment]
the fix is in production, thanks @joelhans for submitting
