### ISSUE TITLE
[Bug] Last Chart cannot be stretched on cloud

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata-cloud#132]
@underhood commented on [Wed Jun 03 2020](https://github.com/netdata/netdata/issues/9259)

##### Bug report summary
On the screenshot below, you can see the local dashboard on left side and cloud one on right.
Due to cloud missing copyright information in the bottom you are not able to increase the vertical size of chart easily with the button marked red (red arrow pointing to it) if the window is maximized/fullscreen.

![Screenshot from 2020-06-03 16-13-57](https://user-images.githubusercontent.com/6674623/83647880-b3a7be80-a5b5-11ea-9e06-6706d66e4534.png)

##### OS / Environment
FC31 AMD64 (although not related to this issue IMHO)
Firefox
##### Netdata version
master branch, custom build 

##### Component Name
Cloud

##### Expected behavior
I can resize the last chart without leaving fullscreen/maximized mode. Suggested -> add some whitespace on the bottom of page.

**Comment by cakrit** [comment]
This still exists

<img width="822" alt="image" src="https://user-images.githubusercontent.com/43294513/170501589-338c3b19-c1bc-4ba0-92d4-4e57fa7260b7.png">

**Comment by cakrit** [comment]
Very low priority.
