### ISSUE TITLE
[BUG] Dimensions/Nodes across charts don't keep the same colour

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#136]
**Describe the bug**	
When I'm looking to charts, for example, that are grouped by Node on the Overview screen the dimensions colouring isn't kept.

This doesn't allow for easy readability and processing of the data on the charts since one node in one chart has one colour and on the other it can have another.

**To Reproduce**	

1. Go to Overview screen - ensure you have more than one node on your War Room
2. Change the Group By to **Node** on two charts, e.g. System Load Average (system.load) and Total CPU utilization (system.cpu)
3. See that dimensions/node names colour isn't kept consistent across charts 

**Expected behavior**	

The dimension colouring should be consistent across all charts.

**Screenshots**	

![image](https://user-images.githubusercontent.com/82235632/134475690-de754f6e-7dc1-41ae-aec0-b98b5f4efbe1.png)

**Error logs**	
N/A

**Dovetail link**
https://dovetailapp.com/insights/68ZIr7NSvjNLTx3N96AW87

**Comment by hugovalente-pm** [comment]
@novykh @papazach I know we spoke about this in the past to try to identify a solution for this issue, but we didn't agree/identify the solution.
Let's bring this back again for discussion

This is linked to netdata/product#1429

**Comment by hugovalente-pm** [comment]
Not released yet, on staging

**Comment by hugovalente-pm** [comment]
@novykh not sure if this has been released or not, related with this an issue has been reported by a user on discord about two different dimensions having the same color - I was able to see this in a Single Node view page here for example https://app.netdata.cloud/spaces/tsaousis/rooms/general/nodes/01702efd-af72-45b0-8e2f-33d806e5699f#chartName=menu_system_submenu_ram&metrics_correlation=false&after=-21600&before=0&utc=Europe%2FLisbon&offset=%2B0

![image](https://user-images.githubusercontent.com/82235632/159482023-f536f7d4-cfe8-4b6f-a827-a30b3624b950.png)

**Comment by novykh** [comment]
Different issue.

**Comment by hugovalente-pm** [comment]
Closing since this was released yesterday

**Comment by hugovalente-pm** [comment]
@novykh opened it here https://github.com/netdata/netdata-cloud/issues/361
