### ISSUE TITLE
[BUG] Last space deletion should not be allowed

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#138]
When a user has just a single space in her account, it is not possible for her to **leave or delete** that space.

Front-end disallows such actions with messages "User is not allowed to delete the last space".

However, we do not have such controls in the Backend.
A **DELETE** request targeting a user's **last space id** can be issued and delete the space, causing the account to be in an un-recoverable state.

**Comment by ivangergo3** [comment]
I have just tested on staging, I cannot leave the last room "General" and the last space.

**Comment by dimko** [comment]
Re-oppening this one as it has been incorrectly closed

**Comment by hugovalente-pm** [comment]
this is still present because we don't have the validation on BE and FE is showing a wrong message
![image](https://user-images.githubusercontent.com/82235632/201079340-14542215-6112-4464-9006-66a4f99aaf39.png)

**Comment by car12o** [comment]
this is fixed
https://github.com/netdata/cloud-spaceroom-service/pull/675

**Comment by car12o** [comment]
this is fixed
https://github.com/netdata/cloud-spaceroom-service/pull/675
