### ISSUE TITLE
[BUG] Charts shown on top of the same chart when switching tabs

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#14]
**Describe the bug**	
When switching tabs, charts appear on top of other charts

**To Reproduce**	
Switch tabs often enough, at some point it will appear

**Expected behavior**	

**Screenshots**	
![image](https://user-images.githubusercontent.com/43294513/99829038-a3a67b80-2b10-11eb-981b-f81beea6199d.png)

**Error logs**		

**Desktop (please complete the following information):**	
 - OS: Windows 10
 - Browser : Chrome latest

**Comment by apostolidhs** [comment]
I have tried it many times and I cannot reproduce the behavior. I am on Macbook. Can someone take a look on windows environment?

**Comment by manos-saratsis** [comment]
@cakrit do we have concrete steps to reproduce or is it shown only from time to time?

**Comment by cakrit** [comment]
Since we're refactoring the entire FE I'm closing this and we'll see if it occurs again after the new code is in production.
