### ISSUE TITLE
[BUG] Broken layout on Adding chart to dashboards

### ISSUE THREAD

**Issue by vinnygats** [netdata/netdata-cloud#140]
**Describe the bug**	
Layout breaks after a certain amount of dashboards.

**To Reproduce**	
Go to a chart > hit the three dots of the panel on the top right of the chart > hit "add to dashboard"
Make sure you have a populated amount of dashboards. 
Can also check in the following link:
https://app.netdata.cloud/spaces/tsaousis/rooms/general/overview?modal=addToDashboardModal&chartId=system.cpu#chartName=menu_system&_f=&utc=Europe%2FAthens

**Expected behavior**	
Could apply scrolling functionality within Dashboards selection section.

**Screenshots**	
![image](https://user-images.githubusercontent.com/7236896/135443452-496175be-80e5-40b7-a640-e09a1e8170db.png)

**Comment by dimko** [comment]
Closing
