### ISSUE TITLE
[BUG] Deleting a space results in an error.

### ISSUE THREAD

**Issue by LeCodeCo** [netdata/netdata-cloud#142]
**Describe the bug**	
Deleting a space results in an error. This only appears to happen on some spaces as I have successfully managed to delete a newly created one.

**To Reproduce**	
Manage Space -> Delete Space -> Error in browser console

**Expected behaviour**	
I expect the space to be deleted.

**Screenshots**	
![image](https://user-images.githubusercontent.com/20425781/136179715-77c69f63-8b46-4220-8486-27f0e5c198fc.png)

**Error logs**	
See prior screenshot

**Desktop (please complete the following information):**	
 - OS: [e.g. iOS]	Windows 11
 - Browser [e.g. chrome, safari]	Chrome
 - Version [e.g. 22]	94

**Additional context**	
I do apologise for only including a screenshot with the error. I had managed to delete the space by putting the following in my browser console, and it appears deleting new spaces works so I cannot replicate and copy the error. Prior to running the following JS, I have had this issue for several months now. 
```js
fetch("https://app.netdata.cloud/api/v1/spaces/<uuid>", { method: "DELETE"} )
```

**Comment by manos-saratsis** [comment]
@LeCodeCo Apologies for the late response. You cannot delete your last space. We should be providing some feedback and is a known thing to improve. Cc @Yannis-San 
In case you want to have your last space deleted you need to delete your account.
Is it the case with your bug?

**Comment by dimko** [comment]
Closing as duplicate of https://github.com/netdata/netdata-cloud/issues/138
