### ISSUE TITLE
[BUG] Internal error handling 

### ISSUE THREAD

**Issue by kaskavel** [netdata/netdata-cloud#144]
**Describe the bug**	
There are several cases where from the user's perspective, in the UI we give some very generic Server Errors (like the ones attached in the Screenshots), without really passing to the user more information that we might have available.  

**To Reproduce**	
We got these errors during an Alerts DB failover test. 

**Expected behavior**	
We should be giving the user a better understanding of the failure, at least if we can do so. 

**Screenshots**	

![Screen Shot 2021-10-07 at 3 09 56 PM](https://user-images.githubusercontent.com/31739664/136774804-209b6425-2fce-49b4-9413-e6be55c6bcbe.png)
![Screen Shot 2021-10-07 at 3 09 36 PM](https://user-images.githubusercontent.com/31739664/136774819-65444e6e-9b36-4488-af54-2662e4dcb046.png)
![Screen Shot 2021-10-07 at 2 56 28 PM](https://user-images.githubusercontent.com/31739664/136774833-a7188fc0-5b93-4cd1-bd7c-a89a6b18ad6b.png)

**Error logs**	

**Desktop (please complete the following information):**	
 - OS: iOS	
 - Browser Chrome	
 - Version 94.0.4606.61

**Additional context**

**Comment by manos-saratsis** [comment]
@kaskavel we have features to be shipped soon handling this case. Thx for raising
