### ISSUE TITLE
[BUG] Polling requests' optimisation

### ISSUE THREAD

**Issue by kaskavel** [netdata/netdata-cloud#145]
**Describe the bug**	
There are several requests the FE does to the BE (eg: /active), which in case we have a large number of nodes within a room have large response times. Some of these, are polling with a certain frequency. When the response times are high enough, this results in a very heavy UI leading to an unresponsive tab or even a blank screen. 

For example, these response times were logged during our latest stress test for these endpoints:

![image](https://user-images.githubusercontent.com/31739664/136779083-d281b0a8-79b1-417a-896d-a1a0893b3d19.png)

We should distinguish these requests per endpoint and think of ways to improve them, in a similar way we did with /charts. 

**To Reproduce**	
Issue is reproduced either in stressed rooms (with more than 200 agents) or during an alerts DB failover. 

**Expected behavior**	
Rationalize our requests by requesting only the data we really need and perhaps using specific time windows. 

**Screenshots**	
![Screen Shot 2021-10-07 at 3 09 56 PM](https://user-images.githubusercontent.com/31739664/136779379-3392ac28-ea0b-41b4-b364-d67c790ce473.png)

**Desktop (please complete the following information):**	
 - OS: iOS 
 - Browser Chrome
 - Version 94.0.4606.61

**Comment by novykh** [comment]
Fixed some time ago.
