### ISSUE TITLE
[BUG] Check your email message form comes on display while user relogs via e-mail

### ISSUE THREAD

**Issue by vinnygats** [netdata/netdata-cloud#146]
**Describe the bug**	
As an existing user of Netdata cloud, if I sign out and attempt to sign in again by clicking "Sign in by e-mail" the "check your e-mail" form comes back on display. It forces me to go to my email and click the link provided.
This does not occur when I sign in by clicking "continue with google".
**To Reproduce**	
As an existing Netdata Cloud user>
1) Sign out.
2) Try to sign in again by clicking "Sign in by email"

**Expected behavior**	
Existing users should be able to sign in normally, without redirecting them to their e-mail, when they act on the same [browser.](url)

**Screenshots**	
![image](https://user-images.githubusercontent.com/7236896/136958527-755b88cc-3772-4fb1-83d6-1cb0fcbc3725.png)
![image](https://user-images.githubusercontent.com/7236896/136958602-e8deb6d1-b171-4e0e-86bc-6b172660e682.png)
![image](https://user-images.githubusercontent.com/7236896/136958648-0b8b6dc0-7af4-4c10-929c-b5d46d8cd17a.png)
![image](https://user-images.githubusercontent.com/7236896/136958689-1f95201f-95e4-41f5-b2cf-ebe6e7aea8e1.png)

**Desktop (please complete the following information):**	
 - OS: iOS
 - Browser Chrome,Safari,Firefox

**Additional context**	
It is expected when user tries from different browser, this case is on the same

**Comment by manos-saratsis** [comment]
@vinnygats
