### ISSUE TITLE
[BUG] By node overview chart broke when zooming in

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#15]
**Describe the bug**	
Zoomed into an "overview" chart that was "by node" and the chart stopped working due to invalid `data` calls

**To Reproduce**	
Zoom In/Out and see if "after" is always an integer, or if there's a chance of it becoming a float.

**Expected behavior**	
Zooming in/out doesn't break the chart

**Screenshots**	
![image](https://user-images.githubusercontent.com/43294513/99844500-048d7e00-2b28-11eb-988f-b61ea3bf2099.png)

**Error logs**	

`{"errorMsgKey":"ErrParsingRequestBody","errorMessage":"json: cannot unmarshal number -361.6898148148149 into Go struct field dataRequestBody.after of type int64","errorCode":"lk20X34j9o-061919"}`

**Desktop (please complete the following information):**	
 - OS: Windows 10
 - Browser : Chrome latest

**Comment by jacekkolasa** [comment]
fix is in production
