### ISSUE TITLE
[BUG] Dimension/node name gets cut on legend at the bottom of the chart when it is big

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#151]
**Describe the bug**	

When the dimension/node name is very big this get's cut on the tooltip	

**To Reproduce**	
1. Go to a chart
2. Choose group by node - you need to have a node with more than , e.g. netdata-parent-1234567890-xyz12
3. See that it gets cut after the 22nd character

**Expected behavior**	
There should be a way where name should be distinguishable among the list, for example with a tooltip.

**Screenshots**	

![image](https://user-images.githubusercontent.com/82235632/137096354-ecc3d16f-383d-469d-9bae-3141fe8620c2.png)

**Error logs**	

N/A

**Desktop (please complete the following information):**	
- OS: Windows
- Browser: Chrome
- Version: 94.0.4606.81 (Official Build) (64-bit)

**Additional context**	

N/A

**Comment by anastako** [comment]
@hugovalente-pm @novykh @apostolidhs 

Due design's current limitations, it is better to have an approach like on the nodes page (with three dots in the middle) and to add a tooltip to show the whole name. 

Example on Nodes 
![image](https://user-images.githubusercontent.com/23135936/137129886-dc490645-2acb-438f-986e-c79df580bd6a.png)
