### ISSUE TITLE
[BUG] Time measurement based charts get value reset after 24h

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#156]
**Describe the bug**	

When you have a time measurement based chart when the value exceeds the 24h this is reset, it doesn't show more than one day.

**To Reproduce**	
1. Enable Charts 2.0
2. Go to a time measurement based chart, e.g. `netdata.uptime`
3. If the value is longer than 24h it resets

**Expected behavior**	

After 24h we should be counting days plus the hours/minutes it has elapsed

**Screenshots**	

**Charts 1.0**
![image](https://user-images.githubusercontent.com/82235632/137276839-480bbad5-92da-47ca-8ab9-33ac87a0244a.png)

**Charts 2.0**
![image](https://user-images.githubusercontent.com/82235632/137276762-04e04936-11e3-4814-b64e-4f9b06dd9fe1.png)

**Error logs**	
N/A

**Desktop (please complete the following information):**	
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94.0.4606.81 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by Jayto1** [comment]
Thanks hugo 👍
