### ISSUE TITLE
[BUG] Failed to connect to https://app.netdata.cloud, return code 60

### ISSUE THREAD

**Issue by Z-Zen** [netdata/netdata-cloud#157]
**Describe the bug**	
Trying to install `Netdata` on a machine with a connection to `Netdata Cloud` using the token. `Netdata` gets installed but the connection to the cloud fails by giving the following error:
```bash
 --- Attempting to claim agent to https://app.netdata.cloud ---
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Token: ****************
Base URL: https://app.netdata.cloud
Id: 4bde1972-2cd5-
Rooms: 4014f62e-9f88-
Hostname: arthur
Proxy:
Netdata user: netdata
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 1 failed. Retry in 1s.
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 2 failed. Retry in 2s.
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 3 failed. Retry in 3s.
grep: /var/lib/netdata/cloud.d/tmpout.txt: No such file or directory
grep: /var/lib/netdata/cloud.d/tmpout.txt: No such file or directory
Failed to claim node with the following error message:"Unknown HTTP error message"
 FAILED
```

**To Reproduce**	
Command line given:
```bash
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-telemetry --claim-token my-token  --claim-rooms myroom --claim-url https://app.netdata.cloud
```

**Desktop (please complete the following information):**	
 - OS: Debian GNU/Linux 9 (stretch)

**Additional context**	
The same command line has been executed on other machines and they successfully connected. I got 2 machines in this state that refuses to connect to the cloud.

**Comment by manos-saratsis** [comment]
@Z-Zen did you check if this is related to the [link](https://community.netdata.cloud/t/certificate-verification-error-connecting-to-the-cloud/1790) above

**Comment by Z-Zen** [comment]
Hello,

Sorry for coming back late.

Before anything else, I tried to re-run the command line, both with and without claiming a room. And this is what I got:

```bash
CCLD     cgroup-network
  CCLD     perf.plugin
  CCLD     slabinfo.plugin
  GEN      netdatacli
  CCLD     apps.plugin
  GEN      netdata
/tmp/netdata-kickstart-eGydS7SVbB/netdata-v1.31.0-459-gc0df28606/externaldeps/libwebsockets/libwebsockets.a(openssl-server.c.o): In function `lws_tls_server_vhost_backend_init':
openssl-server.c:(.text+0x7b5): undefined reference to `SSL_CTX_set_ciphersuites'
/tmp/netdata-kickstart-eGydS7SVbB/netdata-v1.31.0-459-gc0df28606/externaldeps/libwebsockets/libwebsockets.a(openssl-client.c.o): In function `lws_tls_client_create_vhost_context':
openssl-client.c:(.text+0xa5d): undefined reference to `SSL_CTX_set_ciphersuites'
collect2: error: ld returned 1 exit status
Makefile:4906: recipe for target 'netdata' failed
make[2]: *** [netdata] Error 1
make[2]: Leaving directory '/tmp/netdata-kickstart-eGydS7SVbB/netdata-v1.31.0-459-gc0df28606'
Makefile:6148: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/netdata-kickstart-eGydS7SVbB/netdata-v1.31.0-459-gc0df28606'
Makefile:3213: recipe for target 'all' failed
make: *** [all] Error 2
 FAILED

 FAILED

 ABORTED  netdata-installer.sh exited with error
```

**Comment by MrZammler** [comment]
Hi @Z-Zen !

Both of these errors seem to be related to SSL. The first one should be a `SSL certificate problem: unable to get local issuer certificate`, and should be resolved by updating your local ca certificates. Please make sure your packages `policy` and `ca-certificates` are up to date, and also try to run `update-ca-certificates`.

The second error you are getting is more weird... It seems there is a problem linking with libssl library. Again, first thing to try is that the proper packages (`libssl-dev` most likely) is up to date on your system. If it is possible, could you please send the complete installer output to manolis at nedata dot cloud please? Would like to have a look at it.

Thanks!

**Comment by MrZammler** [comment]
Hi!

Ok, there seems to be something weird with `openssl` and/or `libssl-dev` packages.

During configure of `libwebsockets`, it picks up version `1.1.1g`:

```
Compiling with SSL support
-- Found OpenSSL: /usr/local/lib/libssl.so;/usr/local/lib/libcrypto.so (found version "1.1.1g")
OpenSSL include dir: /usr/local/include
OpenSSL libraries: /usr/local/lib/libssl.so;/usr/local/lib/libcrypto.so
```

This version apparently has support for `SSL_CTX_set_ciphersuites`:

```
-- Looking for SSL_CTX_set_ciphersuites
-- Looking for SSL_CTX_set_ciphersuites - found
```

whereas `openssl 1.1.0l-1~deb9u4` which is installed on my test debian 9 does not.

The linker will try to link with `libssl-dev 1.1.0l-1~deb9u4` which apparently does not contain the function.

Can you check please again, by trying to match the versions on those two packages? I would think that if you install `openssl 1.1.0l-1~deb9u4` will fix the linker problem.

**Comment by Z-Zen** [comment]
Hey again,

Thanks for pointing out the possible issue. However, I am not sure how can I match the versions of those two packages. Would you please give me some guidance?

Thanks!

**Comment by MrZammler** [comment]
Hi!

Ok, let's try to check first. Can you please paste the output from:

`apt-cache policy openssl`
and
`apt-cache policy libssl-dev`

?

**Comment by Z-Zen** [comment]
Hello!

here's the output:
```bash
# apt-cache policy libssl-dev
libssl-dev:
  Installed: 1.1.0l-1~deb9u4
  Candidate: 1.1.0l-1~deb9u4
  Version table:
 *** 1.1.0l-1~deb9u4 500
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.0l-1~deb9u1 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
```

and

```bash
# apt-cache policy openssl
openssl:
  Installed: 1.1.0l-1~deb9u4
  Candidate: 1.1.0l-1~deb9u4
  Version table:
 *** 1.1.0l-1~deb9u4 500
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.0l-1~deb9u1 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
```

**Comment by MrZammler** [comment]
Ok, so it seems there are 2 versions of openssl installed. `1.1.0l` via the package manager, and `1.1.1g` via what seems to be a local compile and install. Indeed, and I should have picked it up before, libwebsockets during the configure phase, finds a copy of openssl in `/usr/local/`, which is not where the package manager typically installs software.

In order not to disturb any other software installed on your machine, the easiest work-around at this point it to install a system version of `libwebsockets` via -> `apt install libwebsockets-dev` and then use the parameter `--use-system-lws` in the kickstart script. It should then compile and install Netdata.

Please let us know if the above works!

Thanks!

**Comment by Z-Zen** [comment]
Hey again,

I followed your instructions and launched kickstart script, it was able to compile successfully. Netdata is live!

Thanks a lot!

**Comment by MrZammler** [comment]
Thanks! Glad it worked out!
