### ISSUE TITLE
[BUG] CPU needle doesn't move anymore on different CPU load

### ISSUE THREAD

**Issue by acsfer** [netdata/netdata-cloud#158]
**Describe the bug**	
CPU needle is static.	

**To Reproduce**	
Move cursor on metrics, needle should follow the CPU load.

**Expected behavior**	
Move cursor on metrics, needle should follow the CPU load.

**Screenshots**	
![image](https://user-images.githubusercontent.com/12234510/137347386-d74d64c3-c5b6-48b3-bdd8-7f58fa491359.png)

**Desktop (please complete the following information):**	
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Brave 	
 - Version [e.g. 22] V1.30.89

**Comment by hugovalente-pm** [comment]
This seems to be fixed, so closing the ticket
