### ISSUE TITLE
[BUG] Top bar badges get cut with lower resolutions

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#159]
**Describe the bug**	

With the introduction of the `Lab features` component the existing responsiveness issue of the top bar was highlighted, we took free space that gave _manouvering_ margin on smaller screens.

Now the top bar War Room members and Nodes information badges gets cut on lower resolutions, e.g. 1152x732

Note: There is also a ticket on the Agent for this Agent dashboard top bar gets cut with lower resolutions [#11735](https://github.com/netdata/netdata/issues/11735)

**To Reproduce**	
1. Lower the resolution on your browser, using dev tools console for example
2. Go to 1152x732 or lower
3. See that War Room members badge is not there and Nodes one is cut

**Expected behavior**	

Figma  link - https://www.figma.com/file/tUaZl2Wzh8KQZYdfdqBf4A/%23159--Top-bar-badges-get-cut-with-lower-resolutions?node-id=0%3A1

**Screenshots**	

![image](https://user-images.githubusercontent.com/82235632/137478908-465b4ff5-c32f-4298-a46a-7768ab1ae43e.png)

**Error logs**	

N/A

**Desktop (please complete the following information):**	
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94.0.4606.81 (Official Build) (64-bit)

**Additional context**	

N/A

**Comment by anastako** [comment]
Figma File : 
https://www.figma.com/file/tUaZl2Wzh8KQZYdfdqBf4A/%23159--Top-bar-badges-get-cut-with-lower-resolutions?node-id=0%3A1
