### ISSUE TITLE
[BUG] cloud not reflecting local agent alarm status

### ISSUE THREAD

**Issue by luisj1983** [netdata/netdata-cloud#16]
**Describe the bug**	
Alarm is showing for lowest_entropy in Netdata cloud but there is no alarm on the local node's web UI and there should be no alarm since I have disabled the entropy plugin.
The alarm is now 5 hours old.

**To Reproduce**	
Agent v1.26.0-222-nightly
Trigger alarm for lowest_entropy.
Set "/proc/sys/kernel/random/entropy_avail = no" in "/etc/netdata/netdata.conf"
Restart agent.
Optionally: delete "/etc/netdata/health.d/entropy.conf"

**Expected behavior**	
I expect the alarm status to:
a. be the same on local node web UI and cloud
b. For the cloud UI to clear the alarm

**Screenshots**	

**Error logs**	
Logs included but am not sure how much use they'll be :)	
I've generated a HAR file but don't fancy sharing that on a public tracker. Let me know if you think it'll help and I can ping it over to the support email address.

**Desktop (please complete the following information):**	
 - OS: Windows 10	
 - Browser Edge Chromium
 - Version 86.0.622.69	

**Additional context**	
Have tried using Google Chrome as well as Edge Chromium but issue is on both.
Tried service restarts and even a full system reboot but still persists
[app.netdata.cloud-1605907164843.log](https://github.com/netdata/netdata-cloud/files/5576177/app.netdata.cloud-1605907164843.log)

**Comment by luisj1983** [comment]
oops, sorry looks like a Duplicate of #4 
Anything you guys need from me?

**Comment by manos-saratsis** [comment]
@luisj1983 thx for sharing. Closing this due to the duplicate https://github.com/netdata/netdata-cloud/issues/4
