### ISSUE TITLE
[BUG] Composite charts appear empty even though 1 node has data to provide

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#162]
**Describe the bug**	

A composite chart that retrieves data from multiple nodes appears as empty even though, at least, one node has data to provide

**To Reproduce**	
1. Go to a composite chart on the Overview tab, e.g. systen.cpu_pressure
2. Check that more than one node should provide data for it and others are unreachable
3. Data on the chart appears as empty
4. Going to the specific node, Single Node view, you see data on it's chart

**Expected behavior**	

At least the data for the node(s) that provided it should be visible	

**Screenshots**	

![qOTVR7RNDA](https://user-images.githubusercontent.com/82235632/138497961-e9bbcd0a-cbf9-47fb-b315-d5e0c44f2664.gif)

**Error logs**	

N/A

**Desktop (please complete the following information):**	
 - OS: Windows 10	
 - Browser: Chrome
 - Version: 94.0.4606.81 (Official Build) (64-bit)

**Additional context**	

We see that `after` and `before` fields are 0 and there a strange timestamp at the bottom of the empty chart
![image](https://user-images.githubusercontent.com/82235632/138498086-4b4d440b-ff2a-4ff7-b532-f7c92232e7f1.png)

Extracts of the response:
```
{
	"api": 1,
	"id": "system.cpu_pressure",
	"name": "system.cpu_pressure",
	"view_update_every": 1,
	"first_entry": 1634787158,
	"last_entry": 1634901046,
	"after": 0,
	"before": 0,
	"min": 0,
	"max": 0,
	"dimension_names": [
		"some 10",
		"some 300",
		"some 60"
	],
	"dimension_ids": [
		"some 10",
		"some 300",
		"some 60"
	],
	"view_latest_values": [
		null,
		null,
		null
	],
	"dimensions": 3,
	"points": 0,
	"format": "json",
	"result": {
		"labels": [
			"time",
			"some 10",
			"some 300",
			"some 60"
		],
		"data": []
	},
	"nodes": [
		{
			"id": "25eb3db8-1afb-11e6-9db0-7cdd9077336a",
			"latency": "0s",
			"error": {
				"errorMsgKey": "ErrUnsupportedAgentVersion",
				"errorMessage": "unsupported agent version",
				"errorCode": "ekkrbJoXyf-6071229"
			},
			"chartIDs": []
		},
		{
			"id": "2f23d2ec-1afa-11e6-a1ad-d05099473bc7",
			"latency": "153.943966ms",
			"chartIDs": [
				"system.cpu_pressure"
			]
		},
		{
			"id": "44bbfb16-827f-11ea-bc9f-b827eb91870b",
			"latency": "239.77647ms",
			"error": {
				"errorMsgKey": "ErrContextNotFound",
				"errorMessage": "node doesn't have the requested context",
				"errorCode": "ekkrbJoXyf-6071229"
			},
			"chartIDs": []
		},
		{
			"id": "93bcabe6-8281-11ea-a175-b827ebd5a0a5",
			"latency": "0s",
			"error": {
				"errorMsgKey": "ErrUnsupportedAgentVersion",
				"errorMessage": "unsupported agent version",
				"errorCode": "ekkrbJoXyf-6071229"
			},
			"chartIDs": []
		},
		{
			"id": "b415e708-8e62-11ea-8db0-a7943ce28c42",
			"latency": "0s",
			"error": {
				"errorMsgKey": "ErrUnsupportedAgentVersion",
				"errorMessage": "unsupported agent version",
				"errorCode": "ekkrbJoXyf-6071229"
			},
			"chartIDs": []
		}
	],
	"keys": {
		"dimension": [
			"some 10",
			"some 300",
			"some 60"
		]
	},
	"labels": {}
}
```

**Comment by juacker** [comment]
fix deployed for new and old arch
