### ISSUE TITLE
Errors after automatic updates (bad version of files)

### ISSUE THREAD

**Issue by maxsot100** [netdata/netdata-cloud#168]
'''Since this night, we are experiecing errors in the startup of Netdata, after automatic updates. It looks like the binary downloaded are for ARM architecture, but we are on Intel X86_64. Moreover, if we reinstall the application via script, it throws an error with the checksum of the tarball. Can you please help us? Thanks '''

[root@vmsrv-21 ~]# uname -a; grep -Hv "^#" /etc/*release
Linux vmsrv-21.innovativegroup.eu 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.6.1810 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.6.1810 (Core)
/etc/system-release:CentOS Linux release 7.6.1810 (Core)

Provide output of `netdata -V`.

Netdata is not installed, there are errors during the installation because it tries to install the ARM package instead of the Intel x86_64

Installation method

Tried with on line, static binary one line, rpm package, but no one installed correctly

Component Name

Installers

Steps To Reproduce

bash <(curl -Ss https://my-netdata.io/kickstart.sh)

errors

[/tmp/netdata-kickstart-L5MqYRovhF]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-L5MqYRovhF/netdata-latest.tar.gz https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz  OK

ABORTED  Tarball checksum validation failed. Stopping Netdata Agent installation and leaving tarball in /tmp/netdata-kickstart-L5MqYRovhF.
Usually this is a result of an older copy of the file being cached somewhere upstream and can be resolved by retrying in an hour.

Expected behavior

It should install normally, but it does not actually.

**Comment by Ferroin** [comment]
This should be resolved now. @maxsot100 if you could re-test and vverify if you are still having issues, that would be appreciated.

**Comment by maxsot100** [comment]
Yes, I confirm that the issue was solved. Thanks and kind regards.
