### ISSUE TITLE
[BUG] Old alarms sometimes showing in the cloud

### ISSUE THREAD

**Issue by jurgenhaas** [netdata/netdata-cloud#17]
Sometimes, alarms don't reset in the cloud, even if we restart the agent. Here you can see the effect with the dashboard in cloud:

![Screenshot from 2020-11-23 08-38-56](https://user-images.githubusercontent.com/1475675/99938254-b4046380-2d67-11eb-9412-da51128c638a.png)

At the same time, the alarms grabbed through the CLI are empty, which is the correct situation:

![Screenshot from 2020-11-23 08-39-10](https://user-images.githubusercontent.com/1475675/99938296-c7173380-2d67-11eb-9072-dd29e84d142b.png)

Please not the age of the alarms displayed in the cloud, the seem to last forever.

**Comment by manos-saratsis** [comment]
@jurgenhaas thx for sharing but I close it as a duplicate with the https://github.com/netdata/netdata-cloud/issues/4
