### ISSUE TITLE
[BUG] Scrollbars on Firefox have the system specific look & feel

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#171]
**Describe the bug**	

Scrollbars don't have the expected look & feel, they have the systems look & feel

**To Reproduce**	
1. Enable Charts 2.0
2. Open Netdata on Firexo and go to, for example, apps.cpu chart
3. See that the scroll bar on the dimensions legend, if it applicable, isn't have the expected look & feel
4. The same happens on the navigation menu of the chart, vertical scrollbar

**Expected behavior**	

Have the same look & feel as chrome

**Screenshots**	
**Firefox**
![image](https://user-images.githubusercontent.com/82235632/139275236-140811bd-a576-43e0-86ac-13a5af85f6e7.png)

**Chrome**
![image](https://user-images.githubusercontent.com/82235632/139276030-6d9258dc-06cf-43b3-ae0c-d8a0eb1eb0c9.png)

**Error logs**	
N/A

**Desktop (please complete the following information):**	
 - OS: Windows 10
 - Browser: Firefox
 - Version: 93.0	

**Additional context**	
N/A

**Comment by cakrit** [comment]
Tested on Firefox on an Ubuntu and they look fine now.
