### ISSUE TITLE
[BUG] Save button sometimes appears when no changes were made

### ISSUE THREAD

**Issue by Jayto1** [netdata/netdata-cloud#176]
Save button sometimes appears when no changes were made.

![image](https://user-images.githubusercontent.com/79473923/139541779-dfd140f0-b8dc-49d1-b846-75825de73dac.png)

**Comment by manos-saratsis** [comment]
@Jayto1 thx for the feedback!

**Comment by dimko** [comment]
Fixed. Closing this.

**Comment by Jayto1** [comment]
@dimko @manos-saratsis seems to always be apparent now

**Comment by allelos** [comment]
@Jayto1 can you elaborate a bit more?

**Comment by Jayto1** [comment]
@allelos yes exactly thats the issue.

**Comment by allelos** [comment]
@Jayto1 thx, we pushed a fix for this yesterday!

**Comment by Jayto1** [comment]
@allelos I see it's fixed now, great work 👍
