### ISSUE TITLE
[BUG] Date time selection resets when switching tabs

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#178]
Steps to reproduce:

1. Sign in to Cloud
2. Enable Charts 2
3. Navigate to Single Node View (or Overview, the result is the same)
3. Edit date time selection and select a value different than the default one (e.g last 5 minutes)
4. Navigate to a different tab (if you were in Single node view, select Overview, dashboard, alerts, nodes tabs)
5. Date time selection resets to the the default one (last 15 minutes)

This happens only in Charts 2. Charts 1 works as expected and keeps user's selection

**Comment by dimko** [comment]
@manos-saratsis @hugovalente-pm this seems to be a regression from charts 2. I am not sure which team is responsible for it. Please change assignees and team if necessary

**Comment by hugovalente-pm** [comment]
@dimko checking with the guys, once I have more info will update assignees accordingly
