### ISSUE TITLE
[BUG] Received alert with negative time on go.d_job_last_collected_secs

### ISSUE THREAD

**Issue by cpipilas** [netdata/netdata-cloud#181]
I had a node installed in Ubuntu 20.04, received the following email alert:
<img width="705" alt="Screenshot 2021-10-28 at 11 25 22 AM" src="https://user-images.githubusercontent.com/30462769/139830511-98122bcf-ea5e-4ec9-871d-035ecc51b5c5.png">

and the specific chart:
<img width="888" alt="Screenshot 2021-10-28 at 6 27 59 PM" src="https://user-images.githubusercontent.com/30462769/139830619-8e68b91d-75d6-425c-ad57-460d15cf2194.png">

Installed the agent using kickstart script, default configuration.

**Comment by manos-saratsis** [comment]
@chrikar @car12o can you please check if this is from the agent collector or an issue with Cloud?

**Comment by car12o** [comment]
sure, is it possible to know in which env did it happen and the agent details?
a simple way to get agent detail is through this command:
```shell
/usr/sbin/netdatacli aclk-state 
```

**Comment by jparaskakis** [comment]
Is this agent claimed to the cloud? Is the email coming from netdata cloud or the agent?

**Comment by cpipilas** [comment]
Hey guys,

@car12o aclk ng used, cloud enabled, node claimed and working properly in cloud. 
@jparaskakis emails were coming from cloud

Unfortunately I've deleted the env, it was an AWS lightsail VM with limited resources (1 core/1 GB RAM), running Ubuntu 20.04 with standard kickstart installation, no special configuration. Could not reproduce the issue with other similar VMs that I have there.

**Comment by dimko** [comment]
@sashwathn I will close this until we have more info or manage to reproduce it again.
