### ISSUE TITLE
[BUG] Unable to remove war room or remove node from it

### ISSUE THREAD

**Issue by modem7** [netdata/netdata-cloud#182]
Hi guys, 

I have a war room that I wish to get rid of including all outdated nodes inside it. 

Unfortunately not able to do so. 

If I try to delete the out of date (and decommed) node i get:

![image](https://user-images.githubusercontent.com/4349962/140445889-eed3d14f-33e2-4b4d-8da7-2ef42edc7f00.png)

If I try to delete the war room, I get the following:

![image](https://user-images.githubusercontent.com/4349962/140446006-b2b0b792-4d03-4f8c-b0ca-290502ab46f2.png)

**Comment by chrikar** [comment]
Hi @modem7 !

Thank you very much for reporting this to us. 

Could you please clear your cookies and cache for the netdata site and try again?

**Comment by chrikar** [comment]
To elaborate a bit, please go to your browser's privacy settings, select to "See all cookies and site data", filter using "app.netdata.cloud" and delete the listing that shows up as shown here:
![Screenshot 2021-11-09 at 15 56 06](https://user-images.githubusercontent.com/2836342/140937547-34ba5dac-8873-42b4-9325-7c1ee9f3d903.png)

**Comment by modem7** [comment]
Heya, 

Sorry for the delay!

Unfortunately, still no go. Same error.

I even attempted it on another browser (edge) just to make sure.

**Comment by chrikar** [comment]
Thank you @modem7! 

We're going to need some user/room information to proceed with this. Could you please contact me on the [Netdata Discord](https://www.netdata.cloud/blog/netdata-is-launching-its-discord-server/) for that? You can find me as `christosk` with a "Netdata Team" tag.

**Comment by dimko** [comment]
@modem7 do you still have this issue? Can you share the information @chrikar asked for?

**Comment by modem7** [comment]
@dimko @chrikar info has been given in the discord channel. Georgia is currently investigating. 

Apologies for the *very* late reply.

**Comment by ravilushqa** [comment]
We have a quick call with Gergo and we are stuck in some confusing things that need to reinvestigate.
As I have some more prior things to be done, I'll not waste time on it right now until more prior things will be done

**Comment by ravilushqa** [comment]
We have a quick call with Gergo and we are stuck in some confusing things that need to reinvestigate.
As I have some more prior things to be done, I'll not waste time on it right now until more prior things will be done

**Comment by modem7** [comment]
> We have a quick call with Gergo and we are stuck in some confusing things that need to reinvestigate.
> As I have some more prior things to be done, I'll not waste time on it right now until more prior things will be done

No worries! Glad it's not my end!

I'll hold until you need something from me!

Thanks for looking at it!

**Comment by vkuznecovas** [comment]
hey @modem7, we've done a whole bunch of fixes related to node deletion, could you please check to see if your issue is resolved? 

Many thanks!

**Comment by modem7** [comment]
> hey @modem7, we've done a whole bunch of fixes related to node deletion, could you please check to see if your issue is resolved?
> 
> Many thanks!

Heya,

Unfortunately still getting:

![image](https://user-images.githubusercontent.com/4349962/157699659-8169b79a-dc5d-4feb-8fff-043a13470af7.png)

**Comment by bojdell** [comment]
Seems related to this thread, but I am unable to remove "dead" nodes from war rooms with this message. This is the default "General" room that is created automatically. I am a full admin.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/3486165/162497703-ebde87c7-532c-427e-bc53-8d3e9e47f0fc.png">

<img width="433" alt="image" src="https://user-images.githubusercontent.com/3486165/162497749-6dd9e2a5-f5f8-49b0-a9f6-6b44755362be.png">

**Comment by ravilushqa** [comment]
hey @bojdell.
Thank you for reporting.
It's expected behavior for now, as we changed some logic over General war room.
For now the General War Room is a centralized room with all nodes that belong in this Space, so you cannot remove nodes and users from it. We will improve your experience soon.

**Comment by bojdell** [comment]
@ravilushqa thanks for the quick reply. `with all nodes that belong in this Space` - I would like to remove nodes that no longer belong in the space. Do you have a rough timeline on the improvements? I see there is a related thread [here](https://community.netdata.cloud/t/deleting-a-node-from-the-ui/28/10) from 2020

**Comment by realEthanZou** [comment]
Observing similar behavior. Unable to claim new nodes / remove dead nodes / remove war space due to "untouchable room". Would appreciate timeframe for fix

**Comment by taylor5042** [comment]
I also have an unreachable node that cannot be removed due to the untouchable room message.

**Comment by dionysis-netdata** [comment]
Hi all, we understand the issue and we will work on adding the capability to mark nodes as obsolete. Essentially soft-delete them across the space. This is planned for this quarter and more likely towards the first part

**Comment by dimko** [comment]
related to https://github.com/netdata/netdata-cloud/issues/422

**Comment by dimko** [comment]
Hey all, the ability to remove **unreachable** nodes from every room should be available now.

**Comment by shyamvalsan** [comment]
As of now users, can obsolete offline nodes from the nodes tab, hovering on offline nodes will display a "trash" icon and clicking it will allow you to obsolete the node across the entire space.
