### ISSUE TITLE
[BUG] Unable to perform some actions on the sidebar navigation.

### ISSUE THREAD

**Issue by car12o** [netdata/netdata-cloud#183]
**Describe the bug**	
Unable to perform some actions on the sidebar navigation, clicking on the icons/dropdowns does not trigger any action.
- Unable to remove node by clicking on the trash bin icon;
- Unable to remove nodes by checking the desired ones and then clicking remove on the dropdown;
- Unable to remove users from a space;
- Unable to change user role from a space;

**To Reproduce**	
There're two ways to archive this state where clicking on the icons/dropdowns does not trigger any action.
1. Toggle Charts version (either on or off) on beta features.
2. Visit a space with v2 enabled by default when having v1 activated on beta features.

**Expected behavior**	
Expect to be able to perform the described actions.

**Desktop (please complete the following information):**	
 - OS: Arch Linux 5.14.16
 - Browser: Firefox & Chromium
 - Version: Firefox 94.0.1 (64-bit) | Chromium 95.0.4638.69

**Comment by novykh** [comment]
No need to fix this since toggle will be removed in the next days.
