### ISSUE TITLE
[BUG] Perth Timezone Incorrect

### ISSUE THREAD

**Issue by aashley** [netdata/netdata-cloud#187]
**Describe the bug**	
The timezone selector does not include Australian Western Standard Time (UTC+0800), it does include 'Perth' as an option but it appears that the small town Perth, Tasmania (UTC+1100) has been used instead of Perth, Western Australia (UTC+0800).

**To Reproduce**	
Login to netdata cloud

**Expected behavior**	
An entry for AWST

**Comment by burbuli8ra** [comment]
This fix was released on [v2.29.4](https://github.com/netdata/cloud-frontend/releases/tag/2.29.4)
