### ISSUE TITLE
[BUG] Error when install node on Agent because error package libbpf 

### ISSUE THREAD

**Issue by vuong-bse** [netdata/netdata-cloud#191]
I connect a new node by code rendered on cloud, and got error same is: https://github.com/libbpf/libbpf/issues/403
I found a solution by edit file in here.
https://github.com/libbpf/libbpf/commit/2ab26159262b61c7725c97a92beb46c5cfda068b

**Comment by cakrit** [comment]
Closing this, opened a report in the agent repo: https://github.com/netdata/netdata/issues/11796

**Comment by thiagoftsm** [comment]
Thank you very much @vuong-bse for your report, the PR will fix the issue.

Best regards,

Thiago
