### ISSUE TITLE
[BUG] Chart dimensions color in the legend and within the chart do not match

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#192]
**Describe the bug**	
The chart dimensions are ordered by value but the colors within the chart do not match

**To Reproduce**	
Go to a stacked chart, order dimensions and switch the chart type to line. More cases might exist

**Expected behavior**	

**Screenshots**	

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	

**Desktop (please complete the following information):**	

**Additional context**

**Comment by zeylos** [comment]
Was able to reproduce only by switching dimension sorting to one of the descending (no matter the vizualization style, area, line or stacked) :
![image](https://user-images.githubusercontent.com/24226163/143461964-2dec0b3e-1edf-4e13-b415-7f66e49d75d1.png)
![image](https://user-images.githubusercontent.com/24226163/143462008-7bbb400d-b066-4c40-8cbf-c330b475812c.png)

Not attaching the screenshot for value sorting but the same happens with Max→Min.
It seems that the color shown is the one of the last item in the list.

**Comment by Pingger** [comment]
Can confirm this to also be the case for Min -> Max (at least for Applications cpu graph, where all sortings except for default are broken)

**Comment by hugovalente-pm** [comment]
@zeylos and @Pingger this fix was released, if you still find anything not looking ok let us know
