### ISSUE TITLE
[BUG] Netdata Cloud doesn't show as much metrics as the node stores

### ISSUE THREAD

**Issue by zeylos** [netdata/netdata-cloud#193]
**Describe the bug**	
Netdata cloud only shows one or a few hours worth of metrics, even if the node stores more.

**To Reproduce**	
Increase `dbengine multihost disk space`, in my case here is my configuration :
```
        [global]
          memory mode = dbengine
          dbengine multihost disk space = 27455
          page cache size = 512
```
Wait for some time then try to show last hours on Netdata Cloud.

**Expected behavior**	
The same graph as the node's.

**Screenshots**	
Both screens are showing last 12 hours, first one from Netdata Cloud on a single node view, second one directly from the parent node's webserver.
![image](https://user-images.githubusercontent.com/24226163/142455646-8be92e0e-62e9-4973-9766-b52da4bc5dfb.png)
![image](https://user-images.githubusercontent.com/24226163/142455711-1e8b368e-6be3-4506-ba88-941131992fdf.png)

**Desktop (please complete the following information):**	
 - OS: Linux
 - Browser Firefox
 - Version 94.0

**Additional context**	
Netdata agent was installed on a kubernetes cluster with the helm chart, the only changes are the global config above and the database persistent volume's size.
We have 3 childs and one parent.
I spent the whole day reading the doc trying to figure out why but I couldn't find anything, sorry if this is documented somewhere.

Regards,
Zeylos

**Comment by manos-saratsis** [comment]
@zeylos thanks for raising this. If I understand well you would like to enjoy the increased retention of your parent. The Cloud currently does not support parent-child relationships but we are working on it and soon you will be able as we are in the final rounds of testing our redesigned BE services. 

My recommendation is either to wait or to help us testing the new architecture as a parent-child user. What do you think?

**Comment by zeylos** [comment]
@manos-saratsis hi, thanks for the answer. It appears the issue is a misunderstanding from my part then.
I would be glad to help you test the new architecture if you need people.

**Comment by zeylos** [comment]
Just a note in case someone encounters the same case before the next release, beta arch is compatible with netdata `1.31.0-497-nightly` and superior, I was using `1.31.0` (which is the default version of the helm chart right now).
Therefore, I had to change my childs and parent images tag to `latest` in order to fully enjoy beta architecture, I can now see more than one hour on cloud.

Thanks a lot to the netdata team to help me out with that one on Discord :)
