### ISSUE TITLE
[BUG] Truncated text and code snippets on Safari

### ISSUE THREAD

**Issue by georgiats** [netdata/netdata-cloud#194]
**Describe the bug**	
I use Safari 14.1 on macOS. The text and the snippets that are displayed on the onboarding screen are truncated and covered by the video. 

**Screenshots**	
![image](https://user-images.githubusercontent.com/4034214/142640968-e5030aa4-0d40-4d38-9f88-d008a09a7339.png)

**Desktop**	
Safari 14.1 on macOS (Catalina). Full details [here](https://whatismybrowser.com/w/PXECN4P)
MacBook Pro (13-inch, M1, 2020)

**Additional context**

**Comment by dimko** [comment]
@georgiats Can you please sync with @burbuli8ra to display the issue? We couldn't reproduce it.

**Comment by burbuli8ra** [comment]
The fix has been completed, development wise and will be included in the next release of cloud
