### ISSUE TITLE
[BUG] Chart type definitions aren't applied when loading the custom dashboard

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#199]
**Describe the bug**	

When a chart that is an `stacked` chart is added to a custom dashboard we see it on the preview with the correct look & feel and when we add it to the custom dashboard as well, but once we save and refresh the page it isn't rendered with the correct definition - we see from the BE response that it should be a `stacked` chart 

**To Reproduce**	
1. On a custom dashboard add a `stacked` chart, e.g. `disk_space._`
2. See on the preview and when it is added to the custom dashboard it stays as a `stacked` chart
3. Save the custom dashboard and refresh the page
4. The chart is displayed as a `line` chart

**Expected behavior**	

The information that is stored on the BE should be correctly rendered on the FE

**Screenshots**	
![yzyulpeMom](https://user-images.githubusercontent.com/82235632/143210766-75af5b58-673a-4a66-a6ed-d86d53e6a74c.gif)

**Error logs**	
N/A

**Desktop (please complete the following information):**	
 - OS: Windows 10
 - Browser: Chrome
 - Version:  96.0.4664.45 (Official Build) (64-bit)

**Additional context**	

Payload from the response of the custom dashboard definition

<details>

```json
{
	"id": "be5926bd-324c-4127-bf8b-e192da865b8f",
	"name": "Test",
	"slug": "test",
	"version": 4,
	"snapshot": {
		"slug": "test",
		"name": "Test",
		"uiState": [
			{
				"h": 9,
				"i": "39d40247-d196-4a75-ae8b-329003b82cad",
				"minH": 8,
				"minW": 6,
				"w": 6,
				"x": 0,
				"y": 0
			}
		],
		"items": [
			{
				"cardAttributes": {
					"chartType": "stacked",
					"id": "39d40247-d196-4a75-ae8b-329003b82cad"
				},
				"chartId": "disk_space._",
				"context": "disk.space",
				"id": "39d40247-d196-4a75-ae8b-329003b82cad",
				"nodeId": "242aab9e-c117-4037-8704-816a3503f0bc",
				"type": "chart"
			}
		],
		"updatedAt": "2021-11-24T09:18:01.71325Z",
		"createdAt": "2021-11-24T09:15:22.653441Z"
	},
	"createdAt": "2021-11-24T09:15:22.653Z",
	"updatedAt": "2021-11-24T09:18:01.713Z"
}
```

</details>

**Comment by njpau** [comment]
Has there been a fix for this? Curious as to why this was closed without a bugfix.

**Comment by njpau** [comment]
Ooh its fixed! Its fixed on my end atleast. Thanks :)

**Comment by hugovalente-pm** [comment]
Yes, it was fixed that's why it was closed was going to update a comment today :)

**Comment by walkertr0n** [comment]
I'm seeing this behavior (default `stacked` chart changes to `line` after reload) with `system.ram`, `system.swap`, and `apps.swap` charts -- but only ones I had added a day or two ago. Newly added `stacked` charts aren't exhibiting this (yet).

There seem to be two ways to get affected charts to render as `stacked` again:

**1. Manually set chart render type and save.** This fix persists upon reload and works when setting either `stacked` or `area`.
**2. Navigate to the Single Node dashboard of the same node, then back to the custom dash.** This fix _does not_ persist upon reload. Also, returning to the affected chart after navigating to the Single Node dashboard of a _different_ node has no effect on the chart - it's still `line`.

**Comment by hugovalente-pm** [comment]
@walkertr0n , I'm not sure this could a temporary glitch or side effect of a previous release. understanding that this isn't happening for new added charts we will not re-open this. 

please do let us know if you experience this again
