### ISSUE TITLE
[BUG] UI/UX: Composite charts for long named nodes having "UNKONW ERROR" get misaligned

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#204]
**Describe the bug**	

The pills for long named nodes with issues, e.g. `UNKNOW ERROR`, get misaligned.

**To Reproduce**	
1. Go to a War Room where you have long named nomes
2. Go to a composite chart where you nodes with some issues
3. Notice that the error pill and message are misaligned

**Expected behavior**	
The pill UI element should adapt when a node name occupies two lines

**Screenshots**	

![image](https://user-images.githubusercontent.com/82235632/144075627-bf1d80f1-ce35-409c-9ced-05982d649772.png)

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	

**Desktop (please complete the following information):**	

**Additional context**

**Comment by anastako** [comment]
Could we display the specific error? (if found?) 

I can not reproduce the error, thus It is impossible to calculate the size of the font. Can we lower the font size and display only  "Error" as a label? 

Is if fatal? If not (the data still are being displayed) can we replace the label with "Attention" ?

In all cases with tooltip to add explanatory text 

@hugovalente-pm

**Comment by anastako** [comment]
After checking with Backoffice, the issue is fixed. 

Despite that, the proposal is to change the message to "Attention" (it's informative error, confirmed) and provide context with a tooltip (on hover)

@hugovalente-pm

**Comment by hugovalente-pm** [comment]
These are the errors that exists on BE (for now):

Code - description:
* ErrInternal - "internal server error"
* ErrAgentTimeout - "timeout waiting agent response"
* ErrContextNotFound - "node doesn't have the requested context"
* ErrUnreachable - "node is unreachable"
* ErrNoData - "node doesn't have data for the requested period"

when we have an unknow error we could show a smaller message like `ATTENTION` and on hover show more details. 

atm we should be missing the mapping for:
* ErrInternal - "internal server error"
* ErrNoData - "node doesn't have data for the requested period"
