### ISSUE TITLE
[BUG] Incorrect reachability status

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#205]
When an agent goes offline, and there are still other connected NodeInstances for the same NodeID, we’re not correctly propagating the liveness(aka reachable) and queryable status. This only affects whitelisted spaces.

**Comment by dimko** [comment]
Fixed and deployed. Closing

**Comment by chrikar** [comment]
More information here: https://netdata-cloud.slack.com/archives/C022CNY12A3/p1638204850054100
