### ISSUE TITLE
[BUG] Alert has been raised but the unit is missing from within the chart on the right panel[BUG]

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#206]
**Describe the bug**	
Alert has been raised but the unit is missing from within the chart on the right panel

**Comment by burbuli8ra** [comment]
Regarding the required fix for this issue, the following have to be implemented:
* Add the missing unit to the label of the chart loaded in **Single load view** page
* Move the unit to the right of the value in the chart loaded in right panel alerts

**Comment by burbuli8ra** [comment]
@dimko the fix has been merged in `develop` branch at commit [(#66fdf6e) fix: units of chart labels](https://github.com/netdata/cloud-frontend/commit/66fdf6ef66d248c6c3b8640f032cb8271a16d211)
