### ISSUE TITLE
[BUG] Previous node instance not getting unreachable after agent reclaim

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#211]
Steps to reproduce:

1. Claim an agent to the cloud.
2. Re-claim agent according to the documentation https://learn.netdata.cloud/docs/agent/claim#remove-and-reconnect-a-node. Meaning delete claim.d directory on the agent's side and claim using -id=$(uuidgen)
3. 2 nodes with the same hostname appear on the cloud
4. The new one should be reachable, the old one unreachable.

The issue:
The old node still appears to be reachable after re-claiming, but its unqueryable. 

Setting the priority to low since the "sanitisation" script running every 15 minutes on cloud seems to fix the issue after a while.

**Comment by dimko** [comment]
@cpipilas assigning to you since this seems to be an issue agent side that after re-claiming we don't send a disconnect message to the cloud for the previous node.

Manolis can explain the issue agent side (cannot tag him for some reason)

**Comment by georgiats** [comment]
We also have a relevant bug report [in our Forums](https://community.netdata.cloud/t/removing-ghost-node/2352).

**Comment by cpipilas** [comment]
@MrZammler should we close this since https://github.com/netdata/netdata/pull/11924 has been merged?
