### ISSUE TITLE
[BUG] Invitations issue. invalid error_retry path after verify account request

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#212]
After a user with no account to Netdata Cloud follows an invitation link to join a space he has been invited to, BE sends invalid value for the **error_retry** param to the FE. 

What the BE sends for the error_retry is : `error_retry=/api/v1/spaces/751f374c-27d3-47cd-b3b4-94acfda724b3/join-callback?redirect_uri`

What it should send: `error_retry=/api/v1/spaces/751f374c-27d3-47cd-b3b4-94acfda724b3/join-callback?redirect_uri=https://staging.netdata.cloud/spaces/[invitation-space-id]/join-space`

**Comment by dimko** [comment]
@amalkov @manos-saratsis @chrikar Setting this as a high priority since it seems to be happening from time to time. FE has applied a workaround for this, but the important fix here is to remove the static localhost:8090 as the domain of the redirect and replace it with the origin of the request, staging/app/testing.

**Comment by burbuli8ra** [comment]
After (a lot of) investigation between backend and frontend, it turns out that this issue was FE related, so the fix is pending from our side! 😄

**Comment by chrikar** [comment]
Opened a new ticket for handling part (2): https://github.com/netdata/product/issues/2660

**Comment by dionysis-netdata** [comment]
Verified fix #1 , #2 will be dealt as separate ticket

**Comment by dimko** [comment]
Splitting this in 2 tickets so we can close the fixed part once released.

**Comment by dimko** [comment]
Released on https://github.com/netdata/cloud-frontend/releases/tag/2.14.9
