### ISSUE TITLE
[BUG] Metric Correlations - missing metrics for containers

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#218]
**Describe the bug**	

Upon running metric correlations after highlighting a k8s container related chart we got back things but nothing about the k8s container

![image](https://user-images.githubusercontent.com/82235632/145616231-fcf2bb21-15d7-4e08-9f4c-a979ed587d70.png)

![image](https://user-images.githubusercontent.com/82235632/145616254-72c00945-6817-45d1-a9a2-777350f3a231.png)

![image](https://user-images.githubusercontent.com/82235632/145616300-da229090-71b9-4901-9b42-a9869709ac50.png)

Reported by [link](https://netdata-cloud.slack.com/archives/CQY2AQZSP/p1638973837135800)

**To Reproduce**	

**Expected behavior**	

**Screenshots**	

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	

**Desktop (please complete the following information):**	

**Additional context**

**Comment by hugovalente-pm** [comment]
This is to replace the internal ticket https://github.com/netdata/product/issues/2626

**Comment by hugovalente-pm** [comment]
Comment from @TonyPath :

The response from `api/v2/nodes/199bd411-d0ec-4298-8765-5f0508a77e03/correlation` endpoint however includes the related metrics but are not depicted in FE. Please @netdata/cloud-fe can you take a look ?

```json
{
  "correlated_charts": {
    "anomaly_detection.anomaly_rate": {
      "anomaly_rate": 0.9948
    },
    ...
   
    "cgroup_k8s_cntr_mon_thanos_query_69658dfdcf_qdr8n_query.cpu": {
      "system": 0.3011,
      "user": 0.1106
    },
    "cgroup_k8s_cntr_mon_thanos_query_69658dfdcf_qdr8n_query.cpu_limit": {
      "used": 0.7313
    },
    "cgroup_k8s_cntr_mon_thanos_query_69658dfdcf_qdr8n_query.cpu_per_core": {
      "cpu0": 0.5298,
      "cpu1": 0.3393,
      "cpu10": 0.895,
      "cpu11": 0.9999,
      "cpu12": 0.9581,
      "cpu13": 0.3688,
      "cpu14": 0.1501,
      "cpu15": 0.9556,
      "cpu16": 0.0376,
      "cpu17": 0.1068,
      "cpu18": 0.017,
      "cpu19": 0.0482,
      "cpu2": 0.9998,
      "cpu20": 0.0792,
      "cpu21": 0.1652,
      "cpu22": 0.2754,
      "cpu23": 0.7542,
      "cpu24": 0.1015,
      "cpu25": 0.9974,
      "cpu26": 0.9989,
      "cpu27": 0.7313,
      "cpu28": 0.9944,
      "cpu29": 1,
      "cpu3": 0.9617,
      "cpu30": 0.2697,
      "cpu31": 0.8091,
      "cpu4": 0.975,
      "cpu5": 0.817,
      "cpu6": 0.9031,
      "cpu7": 0.9999,
      "cpu8": 0.771,
      "cpu9": 0.9306
    },
    "cgroup_k8s_cntr_mon_thanos_query_69658dfdcf_qdr8n_query.mem": {
      "rss": 0.0062,
      "rss_huge": 1
    },
    "cgroup_k8s_cntr_mon_thanos_query_69658dfdcf_qdr8n_query.mem_activity": {
      "in": 0.16,
      "out": 1
    },
    "cgroup_k8s_cntr_mon_thanos_query_69658dfdcf_qdr8n_query.mem_usage": {
      "ram": 0.0062,
      "swap": 1
    },
    "cgroup_k8s_cntr_mon_thanos_query_69658dfdcf_qdr8n_query.mem_usage_limit": {
      "available": 0.0062,
      "used": 0.0062
    },
    "cgroup_k8s_cntr_mon_thanos_query_69658dfdcf_qdr8n_query.mem_utilization": {
      "utilization": 0.026
    },
    "cgroup_k8s_cntr_mon_thanos_query_69658dfdcf_qdr8n_query.net_eth0": {
      "received": 0.5354,
      "sent": 0.7876
    },
    "cgroup_k8s_cntr_mon_thanos_query_69658dfdcf_qdr8n_query.net_packets_eth0": {
      "received": 0.8866,
      "sent": 0.9386
    },
    "cgroup_k8s_cntr_mon_thanos_query_69658dfdcf_qdr8n_query.pgfaults": {
      "pgfault": 0.1307
    },
    ...
    "users.vmem": {
      "1001": 0.7818,
      "netdata": 1,
      "root": 1
    }
  },
  "total_dimensions_count": 10022
}
```

**Comment by TonyPath** [comment]
Fixed by https://github.com/netdata/netdata/pull/11898

**Comment by andrewm4894** [comment]
can confirm that i am now seeing "k8s cntr..." stuff in results when i run MC on our prod room. Good stuff all!

will set myself a reminder to test again end of week some other rooms as look like the fix here depends on a nightly update.

(assuming we may have updated our prod nodes just by chance since fix was merged a few hours ago)
