### ISSUE TITLE
[BUG] Pacific Time & Mountain Time both UTC -7

### ISSUE THREAD

**Issue by ronniereid** [netdata/netdata-cloud#220]
Pacific Time should be UTC/GMT -8, not the same as Mountain time.

<img width="320" alt="Screen Shot 2021-12-11 at 8 12 32 AM" src="https://user-images.githubusercontent.com/2157697/145683632-df65e35a-c5b8-4121-808d-7b508d954763.png">

**Comment by burbuli8ra** [comment]
This fix was released on [v2.29.4](https://github.com/netdata/cloud-frontend/releases/tag/2.29.4)
