### ISSUE TITLE
[BUG] Settings temporarily turning themselves on after page reload

### ISSUE THREAD

**Issue by Jayto1** [netdata/netdata-cloud#222]
How I have been reproducing the bug:

Step 1: 
Click cog wheel to manage space settings (make sure both invitation settings disabled before clicking settings)

![image](https://user-images.githubusercontent.com/79473923/146083548-0326119f-90d5-4512-9aef-47da7393e840.png)

Step 2:
While the settings window is open reload the page
![image](https://user-images.githubusercontent.com/79473923/146084047-f2d3deb9-3267-4110-9283-da142211a813.png)
the invitation options should be temporarily enabled
![image](https://user-images.githubusercontent.com/79473923/146084116-f93dc272-8ebf-48ae-be01-c3e14dc7907d.png)

Step 3:
Close the settings page without saving, then re-enter, settings should appear as normal.

**Comment by dimko** [comment]
Fixed on release/2.14.11. Closing
