### ISSUE TITLE
[BUG] Selecting between pan, highlight etc. stops working after Alt-Tab

### ISSUE THREAD

**Issue by TimoKettunen** [netdata/netdata-cloud#223]
**Describe the bug**	
The graphs have small toolbar that allows selecting between pan, highlight, select and zoom etc.
This works OK when graph is first displayed. But if some other window is made top most and then netdata cloud again, the selection stops having any effect and the mouse operation is stick to highlight. Pressing F5 restores the functionality.

**To Reproduce**	
Show some graph. Click pan from the toolbar to activate panning with mouse. Press Alt-tab two times.  
The toolbar shows still panning mode but it is actually in highlight mode and selecting any mode from toolbar has no impact on mode.

**Expected behavior**	
The graph should still be in panning mode and selecting other modes should be possible 

**Desktop:**	
 - OS: Ubuntu 20.04	
 - Browser Chrome	
 - Version 96.0.4664.93 (Official Build) (64-bit)

**Additional context**	
--

**Comment by ktsaou** [comment]
I can reproduce this!

@hugovalente-pm @novykh this is a front-end bug that actually disables the first 3 selectors of the charts' toolbar after an ALT-TAB.

Tested on Manjaro Linux. Chrome Version 98.0.4758.80 (Official Build) (64-bit).

What I think is happening is this:

1. Select the panning tool (the first on the left)
2. Pan the chart (it works)
3. Press ALT and select something on the chart, with the panning tool selected - it highlights an area. This is great. So, we have a shortcut to highlight an area, even when panning is selected.
4. Release the ALT and pan the chart - it works
5. Now press ALT-TAB to switch windows
6. Press ALT-TAB to return back
7. Now, while panning is selected, you still highlight
8. Switching tools on the toolbar does not help
8. To solve this, press and release ALT
9. Now the toolbar works again

So, I think that during ALT-TAB and application sticks to "ALT is pressed" behavior.

Nasty bug.
