### ISSUE TITLE
[BUG] Wrong hostname in alert emails

### ISSUE THREAD

**Issue by IvMisticos** [netdata/netdata-cloud#225]
**Describe the bug**	
Alert emails are using the initial hostname of the node or something. I have changed the hostname in the system, in netdata configuration. In the UI it displays correctly. However in the emails it is still using a quite old one and I am unable to link it to a specific node in UI easily.

**Comment by dimko** [comment]
@IvMisticos Thanks for reporting this. Are we talking about emails coming from the cloud, or the agent?

**Comment by IvMisticos** [comment]
The cloud @dimko

**Comment by cakrit** [comment]
I believe we have no way of updating the cloud with a node's hostname, if it changes.
The hostname as netdata understands it, is configurable via `netdata.conf`, `[global]` section, `hostname` parameter. 
We probably have ways to update node info regularly, but may be neglecting to update the node name used in email notifications. Let's address that.

**Comment by hugovalente-pm** [comment]
@sashwathn could you please take this in on the Alerts team?

**Comment by sashwathn** [comment]
> @sashwathn could you please take this in on the Alerts team?

There are 2 scenarios I can think of:
- User updates the node name in netdata.conf and should be updated on the agent as well as the cloud. @MrZammler and @car12o - how are we handling this currently?
- User updates the hostname of the node but does not change the parameter on netdata.conf. Should there be an automated way for us to modify this without requiring user intervention? @cakrit and @ktsaou are we looking for this?

**Comment by cakrit** [comment]
The first definitely requires and agent restart.
I believe that the latter also requires an agent restart. Best case scenario we could do it also in health reload, but I wouldn't bother. The whole point is to ensure that whatever the agent knows while it is running has a way to make it to the cloud. Dunno anything about when/how the node info is updated.

**Comment by MrZammler** [comment]
I can confirm the problem. Assuming an agent is claimed and connected once in the cloud with the old hostname.

If there is no entry in `netdata.conf` for the hostname, the agent will pick up a change in hostname (with a restart).

The new hostname is then sent to the cloud via the `UpdateNodeInfo` message, and the new hostname appears ok in the node list, and in the list in the Alerts tab.

However, the notifications from the cloud will have the old one. Notifications from the agent have the new hostname after a change.

Similar with adding the `hostname` option in `netdata.conf`. It seems ok in the cloud as before, but still the notifications from the cloud carry the original hostname.

**Comment by sashwathn** [comment]
Thank you so much @MrZammler!
@car12o and @YaroslavDev : I am creating an issue for this to be handled on the backend.

cc: @amalkov

**Comment by sashwathn** [comment]
Issue handled in https://github.com/netdata/cloud-backend/issues/237.

**Comment by sashwathn** [comment]
Note: For existing users who have changed the node hostname in the past, there will be an exercise to update all the hostnames for all connected nodes in case there are any discrepancies. Until then, you may still receive notification emails with the previous hostname. We will update you once this is available!

**Comment by sashwathn** [comment]
The script has been successfully executed and all the notifications will now be received with the updated hostnames.

cc: @cakrit akriditis and @ktsaou
