### ISSUE TITLE
[BUG] Section on TOC gets an incorrect name (duplicates ending)

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#227]
**Describe the bug**	

The section names are incorrect and getting a strange duplication for an ending part.

**To Reproduce**	
1. Go to an Overview where you have Apache metrics or bind
2. Check the section names the are "Apache pache" "Bind ind"

**Expected behavior**	
The names shouldn't be duplicated

**Screenshots**	

![image](https://user-images.githubusercontent.com/82235632/148058202-e46db37f-98d1-457a-a434-6ad9f65dbb69.png)

**Error logs**	
N/A

**Desktop (please complete the following information):**	

**Additional context**

**Comment by cakrit** [comment]
This works now:

<img width="206" alt="image" src="https://user-images.githubusercontent.com/43294513/171429727-52304634-e1ac-4536-9a23-aee6944ddb67.png">

**Comment by ralphm** [comment]
Unfortunately, it seems this has regressed.

![image](https://user-images.githubusercontent.com/116741/180987926-414a65da-c526-416a-bfb1-f85e58be0abd.png)

**Comment by hugovalente-pm** [comment]
this seems to be fixed, so closing
![image](https://user-images.githubusercontent.com/82235632/191024468-296fca23-34bf-4685-88fa-ae22581addb4.png)
