### ISSUE TITLE
[BUG] Node is offline but states live

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#228]
**Describe the bug**	
On a production space on Cloud(7d8d5ba4-0d39-4ef7-aa9d-b39cceb9c3ff) a node is offline but shows as live 

**To Reproduce**	
Steps to reproduce the behavior:	- 

**Expected behavior**	
Live nodes should be live

**Screenshots**	
![Screen Shot 2022-01-04 at 2 44 56 PM](https://user-images.githubusercontent.com/19746055/148061099-56440499-0d5f-4e81-a91f-789a4fa01a4e.png)

**Comment by dionysis-netdata** [comment]
We fixed the main cause of this under #2674. Will close this ticket along #2674. And we will monitor and plan if further work is needed

**Comment by ktsaou** [comment]
@dionysis-netdata #2674 on which repo?

I also have a space that 3 nodes appear online, although they are not. This is a long standing issue.

**Comment by dionysis-netdata** [comment]
@ktsaou https://github.com/netdata/product/issues/2674

Can you jot them them here to investigate?

**Comment by ktsaou** [comment]
That is a closed ticket. I commented there, but I think that ticket refers to original cause that had this side effect. Probably the script that finds and fixes such discrepancies does not find my nodes for some reason.

**Comment by ktsaou** [comment]
Opened it here: https://github.com/netdata/netdata-cloud/issues/271

**Comment by vkuznecovas** [comment]
Just to clarify https://github.com/netdata/product/issues/2674 only fixed the major cause of this, however, it did not address the fix for a corrupted state that already exists. For this, we'll need to write a sanitization script. I've not worked on that yet, that's why this issue is still open. I'll get to it once we sort out the issues related to migration to new arch.

**Comment by vkuznecovas** [comment]
This has been fixed as part of https://github.com/netdata/product/issues/2803. 

I have checked - the node is now gone as it should have been a long time ago.
