### ISSUE TITLE
[BUG] [... More] button in sidepanel is clickable only on text

### ISSUE THREAD

**Issue by OdysLam** [netdata/netdata-cloud#23]
**Describe the bug**	

**To Reproduce**	

Login to app.netdata.cloud and click on more in the sidepanel

**Expected behavior**	

The button should be clickable either by clicking on the space at the right or on the text. The rest of the options function that way.

![image](https://user-images.githubusercontent.com/13405632/100761904-14487480-33fc-11eb-8c62-f16ecd1e1c12.png)

**Comment by cakrit** [comment]
I see it working fine. Can you check again @OdysLam and close if it's ok?
