### ISSUE TITLE
[BUG] No way to check full alert, chart and node name in Alerts tab

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#231]
Bug reported by SRE and BE team while investigating other issues.

In case of long alert, node or chart names we display `...` in the middle of the name string in the Alerts Tab
The full name is not visible in this page under any way. This is static and doesn't change based on screen resolution.

e.g Node names and Chart names

![image](https://user-images.githubusercontent.com/19268853/148544732-8fd481ab-30b3-4810-9ca9-376adc26154c.png)

Alert Name

![image](https://user-images.githubusercontent.com/19268853/148544774-693f27c3-1ca1-4d29-8696-3102937cc1d7.png)

**Comment by vinnygats** [comment]
Hi all! 
As a quick fix I would suggest to apply fixed widths to the following two columns to save space (as I see now they are all dynamically set to 16.6%).

1. Smaller width of Status Column (approx 80px)
2. Smaller width of Date & Time (approx 130px)

**Comment by christophidesp** [comment]
I think that this is currently partially solved by showing tooltips over chart name. We need to implement tooltips in the same fashion for the alert and node name.

**Comment by dimko** [comment]
@christophidesp @jacekkolasa We show a tooltip for the alert name, when hovering over chart and node name we don't show something. Does this only work only when name is too long, or should it work always?

**Comment by christophidesp** [comment]
@dimko @jacekkolasa Ideally, the tooltips should be shown only when the name is too long.

**Comment by dimko** [comment]
Nice one. Closing this as it has been fixed. After Jacek's fix, on hover we show a tooltip displaying the name of node, chart, alert
