### ISSUE TITLE
[BUG] Label issue with time measurements 

### ISSUE THREAD

**Issue by Jayto1** [netdata/netdata-cloud#232]
![image](https://user-images.githubusercontent.com/79473923/148632374-a84da0a8-ad81-483f-84a9-28aea9a963b9.png)

**Comment by hugovalente-pm** [comment]
@Jayto1 on this issue you're referring to the "cut" on the units where instead of `time` we just see `t´ (and something)
![image](https://user-images.githubusercontent.com/82235632/149149198-fc84aba8-155b-4dee-8197-a243f61543b3.png)

**Comment by Jayto1** [comment]
> @Jayto1 on this issue you're referring to the "cut" on the units where instead of `time` we just see `t´ (and something) ![image](https://user-images.githubusercontent.com/82235632/149149198-fc84aba8-155b-4dee-8197-a243f61543b3.png)

Ah I see, maybe we could expand it to fit times better?

**Comment by hugovalente-pm** [comment]
@Jayto1 I was just looking for confirmation, so you're really mentioning about the units being cut. is that right?

**Comment by Jayto1** [comment]
> @Jayto1 I was just looking for confirmation, so you're really mentioning about the units being cut. is that right?

Yup, been cute ever since charts 2.0
