### ISSUE TITLE
[BUG] Agent hostname change is not propagated to cloud

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#235]
Steps to reproduce:

1. Claim an agent to the cloud
2. Change the hostname of the agent from agent configuration
3. Restart the agent

What is expected:
Hostname of the node in cloud should change to match the newly changed name

What is happening:
Node name stays the same

**Comment by ivangergo3** [comment]
I have tested it just now, the node has to be restarted
But the name is changed in the cloud

https://learn.netdata.cloud/docs/configure/nodes
"After you make your changes, you need to [restart the Agent](https://learn.netdata.cloud/docs/configure/start-stop-restart) with sudo systemctl restart netdata or the appropriate method for your system."
