### ISSUE TITLE
In node view, entering a filter that returns no results hides the filter input box

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#236]
Steps to reproduce:
- Click on the nodes tab
- Enter in the filter a criterion that will return 0 nodes (e.g. node_name contains foobar)
- Press enter

You see an empty list as you should, but also the filter itself disappears. You need to go to another tab and then return to see the filter again.

**Comment by dimko** [comment]
Fixed on release/2.14.11. Closing
