### ISSUE TITLE
[BUG] Dead link

### ISSUE THREAD

**Issue by Jayto1** [netdata/netdata-cloud#237]
![image](https://user-images.githubusercontent.com/79473923/149170350-6d47026d-1ade-4521-9732-f579551d5d0e.png)
https://learn.netdata.cloud/docs/cloud/collaborate/#add-bookmarks-to-essential-resources

**Comment by dimko** [comment]
@manos-saratsis should we replace the link with something else, or check with documentation team why it is dead?

**Comment by dionysis-netdata** [comment]
@kickoke shared an updated link. https://learn.netdata.cloud/docs/cloud/get-started#add-bookmarks-to-essential-resources

let's replace it with that @burbuli8ra

**Comment by burbuli8ra** [comment]
Released on [v2.15.4](https://github.com/netdata/cloud-frontend/releases/tag/2.15.4)
