### ISSUE TITLE
[BUG] Cannot leave a space, the space remains in the list on the left bar

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#238]
**Describe the bug**	
I am trying to leave a space but I cannot. Space slug `cosmix`, user: manos@netdata.cloud

**To Reproduce**	
Steps to reproduce the behavior:	Left bar -> Leave space

**Expected behavior**	
I should be able to leave the space and not to see it again on the left bar

**Screenshots**

**Comment by dimko** [comment]
Closing this as it seems to affect a pretty old space which messed up data. Will re-open if we see similar issues.
