### ISSUE TITLE
[BUG] White screen appears temporarily when switching to notifications tab in Manage Space modal

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#240]
Steps to reproduce:

1. Open Manage Space Modal
2. Click to switch tabs to Notifications tab inside the modal

What happens:
Screen turns white temporarily, no console error is displayed.

Extra comments:
This happens only the 1st time you perform this actions. If you had previously loaded the Notifications tab, a full page reload is needed to reproduce it.

**Comment by AlexNti** [comment]
This is going to be solved by https://github.com/netdata/cloud-frontend/pull/3369.
