### ISSUE TITLE
Latency chart colors

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata-cloud#241]
I received a request from @manos-saratsis and @ktsaou to change the colors for latency charts:

![Screenshot_20220117_164846](https://user-images.githubusercontent.com/49162938/149809478-8ae098f8-499a-4940-951e-08c8fcccf937.png)

But, after talks  with design team and @jacekkolasa I was informed, that it is not only to change our NETDATA.colors vector, because we need different color scheme for `light` and `dark` themes. 

Our goal is to have the following vector in different order to display the 24 dimensions used with latency charts:

```sh
#fafec5,#fcfd6a,#fff704,#ffee0d,#ffe113,#ffd216,#ffc016,#ffae15,#ff9a12,#ff850e,#ff6d09,#ff5104,#ff2a00,#d84446,#b24f6b,#925082,#7a4996,#6441a4,#4b4683,#3f4656,#334138,#263e0f,#21350f,#18240d
```

**Comment by ktsaou** [comment]
@thiagoftsm @hugovalente-pm I think we can close this and implement the heatmap.

**Comment by hugovalente-pm** [comment]
@ktsaou you mean the heatmap a new type of chart like we discussed?
I don't think we have that ticket yet, but I can create it of course

**Comment by thiagoftsm** [comment]
@ktsaou I do not have any objection. As soon @hugovalente-pm make a new ticket we can close this for sure.

**Comment by hugovalente-pm** [comment]
@thiagoftsm if you want to close this you can I've opened this ticket netdata/netdata-cloud#265
