### ISSUE TITLE
[BUG] Alert cleared, but alert indication remains in room and node remains coloured 

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#242]
Steps to reproduce:

1. Navigate to Netdata Cloud
2. Claim an agent to a space
3. Trigger an alert for that agent (`sudo ./edit-config health.d/cpu.conf` and set an alert condition to True 

e.g`template: 10min_cpu_usage
      on: system.cpu
      os: linux
   hosts: *
  lookup: average -10m unaligned of user,system,softirq,irq,guest
   units: %
   every: 1m
    warn: $this == $this
    crit: $this > (($status == $CRITICAL) ? (85) : (95))
   delay: down 15m multiplier 1.5 max 1h
    info: average cpu utilization for the last 10 minutes (excluding iowait, nice and steal)
      to: sysadmin`
      
4. Trigger a full health reload on the agent /usr/sbin/netdatacli reload-health 
5. Alert appears in the cloud
6. Re-edit the alert configuration and set the condition to False 

e.g `template: 10min_cpu_usage
      on: system.cpu
      os: linux
   hosts: *
  lookup: average -10m unaligned of user,system,softirq,irq,guest
   units: %
   every: 1m
    warn: $this != $this
    crit: $this != $this
   delay: down 15m multiplier 1.5 max 1h
    info: average cpu utilization for the last 10 minutes (excluding iowait, nice and steal)
      to: sysadmin`
  7. Alert disappears from the cloud

What is expected:
Alert badge should be cleared from the Room list and affected node should change color to indicate there are no alerts on this node.

What happens:
![image](https://user-images.githubusercontent.com/19268853/149945145-a9b5c01f-2354-477b-97e3-1b45a31adaed.png)

**Comment by dimko** [comment]
@jacekkolasa could it be that something is not updated in the materialised views so it's a BE issue?

**Comment by dimko** [comment]
@AlexNti can we check if this a FE or a BE issue?

**Comment by dimko** [comment]
Un-assigning for now. Requires some investigation first. Added https://github.com/netdata/product/issues/2440 as blocker.

**Comment by dimko** [comment]
@car12o I remember you did some work that would fix this last week. I haven't verified yet if issue is gone. Have you tested it? Can you link the ticket you were working on on this one?

**Comment by car12o** [comment]
@dimko yes, I change the BE logic and it should be fixed by now :smile: 
These are the mentioned changes https://github.com/netdata/cloud-spaceroom-service/pull/263

**Comment by dimko** [comment]
This seems to be fixed. Closing
