### ISSUE TITLE
[BUG] Go to chart/Run correlations from inside alert's modal doesn't always scroll to affected chart

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#243]
Expected:
When **running correlations** or clicking **go to chart** for a specific alert from inside the alert's modal, after landing in the single node view, the affected chart should be marked with the alert and visible.

What happens:
The alert is highlighted in the chart, but the chart is not visible. The cursor stays at the top of the screen

![image](https://user-images.githubusercontent.com/19268853/149968063-6f2fd01c-44d7-43dd-b023-b83823caca04.png)

It doesn't always happen, it is a bit difficult to reproduce.

**Comment by dimko** [comment]
Lowering priority as it seems to be difficult to reproduce. Need to identify the cause.

**Comment by jjtsou** [comment]
`I think this got fixed around the time we moved to the alerts dedicated page and after a specific agent update.`

My thoughts exactly.

**Comment by cakrit** [comment]
Do me a favor and check the path from an email notification. Looks like it works from within the list in cloud, but I tried with a "load" alert that was cleared by the time I clicked on it. I saw the landing page, but from there it didn't scroll to the load chart, it went to the top.
