### ISSUE TITLE
[BUG] Spelling error

### ISSUE THREAD

**Issue by Jayto1** [netdata/netdata-cloud#244]
![image](https://user-images.githubusercontent.com/79473923/150023762-7438ad2d-882f-4b1d-90a1-c137d6a9d418.png)
Spelling error
![image](https://user-images.githubusercontent.com/79473923/150024342-dae9d4d0-b658-440e-a9fd-a2b943254e88.png)

**Comment by hugovalente-pm** [comment]
@Jayto1 this was recently closed, please check on your and let us know in case some issue still persists
once again thanks for opening this bug and helping us improve our product
