### ISSUE TITLE
[BUG] Alerts table titles bar not sticky 

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#246]
While on the Alerts tab, users can scroll up and down in the alerts list.

It is difficult to identify which field represents what data if you don't see the title of that field.

e.g While at the top of the screen, the row containing the titles of the represented data is visible
![image](https://user-images.githubusercontent.com/19268853/150498864-04a4510d-ba3f-4616-ab62-b5d94f7de9b1.png)

However when scrolling down, it's not and it is confusing.
![image](https://user-images.githubusercontent.com/19268853/150498947-05cd1b95-7067-427d-9e38-abd693efa6ff.png)

The bar should stay fixed when user scrolls inside the alerts table

![image](https://user-images.githubusercontent.com/19268853/150499043-215ae6ef-a95d-4e67-9a7f-e2ce229d119a.png)

**Comment by novykh** [comment]
<img width="579" alt="Screenshot 2022-02-17 at 6 19 01 PM" src="https://user-images.githubusercontent.com/601483/154524069-1d43e15e-1aeb-414b-8683-b52c7477e466.png">
@jacekkolasa should we open a new issue for this? Scrolling with a sticky header, you can see a couple of pixels of the row on the background above the header.

**Comment by jacekkolasa** [comment]
@novykh do you still see it? i couldn't recreate it

**Comment by novykh** [comment]
Havent seen it. Will reopen if needed
