### ISSUE TITLE
[BUG] Error 500 when we are clicking Kuberenetes filter labels at overview, before data has loaded completely.

### ISSUE THREAD

**Issue by AlexNti** [netdata/netdata-cloud#247]
Navigate to overview and find a kubernetes item. Before all the data has been loaded click the filter labels, a 500 error will pop up at screen.

This bug is only happening when the kuberentes data has not been completely loaded.
![Screenshot 2022-01-25 at 11.30.55 AM.png](https://images.zenhubusercontent.com/61b732586f96e01d83c35334/73cea9f9-a42e-46c9-b62e-a3c0c204ccfb)![Screenshot 2022-01-25 at 11.30.59 AM.png](https://images.zenhubusercontent.com/61b732586f96e01d83c35334/11ae41ac-49ac-42b6-8b74-eb6c03b28c48)

**Comment by dimko** [comment]
@AlexNti Can we close this one? I think it is released.

**Comment by dimko** [comment]
Released in release/2.14.13 of cloud-frontend. Closing
