### ISSUE TITLE
[BUG] URL of invitation to join Netdata Cloud is http

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#248]
When you send an invitation to another user, the url is something like  http://url9538.netdata.cloud/ls/click?upn=..... which is clearly http and not https. If you click on that it will open in the browser which immediately redirects you to an https URL, but that’s might be too late already.

**Comment by cakrit** [comment]
The following is the response from Sendgrid. We will discuss internally which of the two we want to do:

The reason the links are intermittently resulting in problems is because when we wrap a link for data reporting (link branding) it wraps it in http. You can set up your account for SSL Click Tracking which will wrap your links in https, and allow the click tracking data to take place, while maintaining your Link Branding. The potential downside here, is that all of your links will be wrapped in https. Also know that this process requires a third party and SendGrid support will not be able to assist through the portions of the setup that involve this third party for your certificate (changing the http to https).
 - [Setting up SSL](https://docs.sendgrid.com/ui/analytics-and-reporting/click-tracking-ssl)
 - [CDN Setup](https://docs.sendgrid.com/ui/sending-email/content-delivery-networks)

Also, you can turn off link branding, but leave on click tracking. This is a solution because the default SendGrid click tracking links (https://ct.sendgrid.net...etc.) are https encoded with a valid certificate.

**Comment by cakrit** [comment]
We're changing the sender in all emails to no-reply@app.netdata.cloud, which will result in not using link branding => all links will be https://...sendgrid.com/...

**Comment by jurgenhaas** [comment]
This is great!

**Comment by ravilushqa** [comment]
solved with a mentioned above issue
