### ISSUE TITLE
[BUG] Alert remains in cloud if chart disappears

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#252]
Not a very easy issue to reproduce, but the main issue is that if a node has an **active alert affecting chart X,** if **chart X disappears** from the agent for some reason, the **alert stays in cloud and is not cleared**

**Comment by MrZammler** [comment]
Hi @dimko !

This PR for the agent attempts to fix this issue: https://github.com/netdata/netdata/pull/12021 leaving it here for reference.

**Comment by dimko** [comment]
Thanks @MrZammler !

**Comment by dimko** [comment]
THis is fixed. closing
