### ISSUE TITLE
[BUG] Invalid pop up message after user successfully joins space

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#254]
Steps to reproduce:
1. User A invites new user B to join Space
2. User B accepts invitation by clicking Join Space button in his email
3. User B signs up in netdata cloud and clicks the Verify your email button inside the email

Expected: 
- User B joins space he was invited to
- **_Welcome! You successfully joined space_** is displayed 

Actual: 
- User B joins space he was invited to
- **Error! Email mismatch** or **Error! Invitation not found** pop up is displayed 

The error coming from the BE in such cases:

The location field in the response to **/join-callback** url is either

`https://staging.netdata.cloud/spaces/netdata-ownero-space-hyo1w6e/join-space#error_code=1FYezloCCc-8182213&error_message=space+invitation+not+found&error_msg_key=ErrInvitationNotFound`

or
`
https://staging.netdata.cloud/spaces/netdata-ownero-space-hyo1w6e/join-space#error_code=1FYezloCCc-8182213&error_message=space+invitation+email+mismatch&error_msg_key=ErrEmailMismatch`

This can be easily reproduced when the system is quite busy e.g when regression runs and creates a number of spaces and rooms

What the user sees 

![image](https://user-images.githubusercontent.com/19268853/152172132-c52b5645-7e8d-499d-87da-05cf0fe8cdb2.png)
or 

![image](https://user-images.githubusercontent.com/19268853/152172112-9dbf3e15-e16d-4e76-98f9-c7e15f4fcf2e.png)

**Comment by ivangergo3** [comment]
It is working as expected I get the following message
"""
Welcome!
Successfully joined space!
"""
