### ISSUE TITLE
User & Space notification settings not being honored (new arch)

### ISSUE THREAD

**Issue by car12o** [netdata/netdata-cloud#255]
User & Space notification settings are not being honored, even though they are disabled the user still receives an email.
Currently, we just take into consideration room settings.

Red - User Notification Settings - Not honored
Green - Room Notification Settings - honored
Blue - Space Notification Settings - Not honored

![Screenshot from 2022-02-03 16-24-44](https://user-images.githubusercontent.com/26550862/152384904-326f716e-eade-4675-b4cf-6566cf33642e.png)

![Screenshot from 2022-02-03 16-25-07](https://user-images.githubusercontent.com/26550862/152384950-1538acd8-647a-4438-a09f-d7796a09cf7c.png)

**Comment by gusarg81** [comment]
By the way, the weird thing is that there are some War Roms that this option is working just fine and others not (at least, in my case).

**Comment by car12o** [comment]
> By the way, the weird thing is that there are some War Roms that this option is working just fine and others not (at least, in my case).

Is this space migrated already? Maybe it works because it's connected through the legacy arch.

**Comment by gusarg81** [comment]
I don't know how to tell you that... All this just started to happen suddenly without any changes from my side.

**Comment by avimar** [comment]
Me too.  I got this email, then started getting notifications via cloud I'd previous disabled. I tried re-enabling, then disabling, but it didn't help.

>from: | The Netdata Team <info@netdata.cloud>
>date: | Feb 1, 2022, 12:53 AM
>subject: | We've got some exciting news... Agent v1.33.0 has arrived

**Comment by ktsaou** [comment]
@amalkov I think this should be high priority. We have to deal with it immediately.

**Comment by car12o** [comment]
@ktsaou I'm already working on it, a fixing patch will be released this week.

**Comment by car12o** [comment]
fixed deployed.

**Comment by dimko** [comment]
Fix is included in **cloud-alarm-notification-sender-service release/0.4.7**

**Comment by rowansc1** [comment]
Thank you everyone!

**Comment by ktsaou** [comment]
You rock guys!
