### ISSUE TITLE
[BUG] [FE] Unnamed nodes should not display as empty

### ISSUE THREAD

**Issue by burbuli8ra** [netdata/netdata-cloud#256]
**Bug Description**
Currently when a node has no name registered it appears with an empty space where the name is supposed to be.

**Expected behavior**
There should be a default name for unnamed nodes.

**Screenshots**	
![Screenshot_9.png](https://images.zenhubusercontent.com/619b813a6f772735c861ea19/ff89285c-3dae-461a-97c0-d051578fa7ef)
![Screenshot_8.png](https://images.zenhubusercontent.com/619b813a6f772735c861ea19/0ab20549-c61b-4fe2-93c3-b9135eba73f8)

**Comment by dionysis-netdata** [comment]
I image that is not something new. Correct? So all this time we have been displaying empty names?

**Comment by burbuli8ra** [comment]
@dionysis-netdata empty! 😄

**Comment by dionysis-netdata** [comment]
wow. open to proposals then. I am going to throw mine 

[Unnamed node]

**Comment by burbuli8ra** [comment]
Agree!

**Comment by vinnygats** [comment]
Unnamed sounds find. I'd consider [Untitled node] too. If possible, [Untitled node-*suffix*] \
e.g.
Untitled node-1
Untitled node-2

etc

As users are globally aware of this "lingo" from other software.

**Comment by libekonst** [comment]
Good point on the count suffix!

Maybe also something like [New Node], if that's the case for unnamed nodes?
It's shorter and also informative - the brackets and the generic word indicate a placeholder, so the node is unnamed, but the wording also explains why it is unnamed and potentially calls for action 🤔

**Comment by vinnygats** [comment]
The [New Node] though indicates that it is a new node actually and considering that for the moment we do not support renaming nodes, may not be so useful in the end in the future you have more nodes and one node named "New Node-2" that has been created 4-5 nodes prior to this.
Would make total sense in my opinion if we would support renaming nodes, but I think currently we don't.

**Comment by libekonst** [comment]
I see, Untitled or Unnamed sound very fitting then!

A side note, in the case of not being able to rename them maybe it'd be interesting to have random names around a theme, similar to what google docs do for unnamed users
e.g. teal-iron-dahlia, black-silver-tulip, etc.

Def. not a quickfix and no strong feelings on that, just a fun idea that might add some extra flavor 😄

**Comment by burbuli8ra** [comment]
@vinnygats and @libekonst to be honest, I am not sure about the indexing because it doesn't provide any info about the node.. it is just a random number, which also might defer in entities of nodes table and nodes dropdown, since I am not 100% sure that the grouping and sorting is the same in those 2!
I would go with either a simple `Unnamed node` or add in parenthesis maybe the `node id` or the info of `claimed at` , which we have available and also provide some identification info for the nodes).

Also, I am not quite sure how it is possible to have unnamed nodes!
I mean, since it is left like this, my guess is that the issue might only be visible on `staging` and not on `production` and that those nodes most likely are created for testing purposes and for some reason contain no name.
If that's the case, then maybe the `id` would be helpful, otherwise my guess is to use either `created at`, which might ring something in user's memory or just leave it `Unnamed nodes` in order to show something there.

**Comment by dionysis-netdata** [comment]
I agree with @burbuli8ra on this one. Please do a sanity check on production whether such nodes actually exist.

**Comment by burbuli8ra** [comment]
Hello guys, after confirmation from @chrikar , the issue also occurs on production, since at the moment we have 229 nodes with `null` and 20 nodes with `""` names.
So, since @libekonst has started with it, what do you think would be best as an alternative name?
My vote is at the simple `Untitled/Unnamed node`

**Comment by libekonst** [comment]
@burbuli8ra I understand the concerns about indexing and I agree that it's an overkill to do something more than a simple initialisation of the name to some default. Also thank you for checking on production and getting the empty name values!
We're definitely on the same side of not mutating the retrieved data, I'll build on top of that idea ✌️ 

So unless you have any concerns @dionysis-netdata ,  I'll be going with `Untitlted node`

**Comment by dionysis-netdata** [comment]
@libekonst is this closed/released?

**Comment by burbuli8ra** [comment]
Yes @dionysis-netdata !

**Comment by libekonst** [comment]
@dionysis-netdata Yeah, it is merged. Had this linked to another issue and forgot to update this one

**Comment by dionysis-netdata** [comment]
@libekonst I don't want to create a new ticket. I imagine it's trivial enough to update the name for unnamed nodes from [untitled node] to untitled node. Basically remove the brackets. It's just looks better

**Comment by libekonst** [comment]
@dionysis-netdata just saw this, still wanna do the change?

**Comment by dionysis-netdata** [comment]
yes please, if it's trivial to do. thanks
