### ISSUE TITLE
[BUG]Alarm info - Calculation/DB lookup sometimes missing

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#26]
**Describe the bug**	
Under alarm info sometimes the Calculation or the DB lookup sometimes is missing.
All active alarms should show either the Calculation or DB lookup.
It might well be that this happens because some alarms have DB lookup and not Calculation.

**To Reproduce**	
Steps to reproduce the behavior:	Go to an active alarm -> click on the 3-dot menu -> click on Alarm Info

**Expected behavior**	
All active alarms should show either the Calculation or DB lookup

**Screenshots**
In this img the Critical is missing as well but cannot confirm it is a bug, no access to the agent dashboard or configuration.
<img width="799" alt="Screen Shot 2020-12-03 at 4 16 03 PM" src="https://user-images.githubusercontent.com/19746055/101049472-d9714880-3583-11eb-85b4-b373884e88c9.png">

**Comment by dimko** [comment]
Fixed. CLosing it
