### ISSUE TITLE
Charts - Apply the same conversion of time in seconds on the pill as the one on the datetime legend

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#262]
## Goal

The same time conversion should be applied on the pill, which is inside the highlighted selection on the chart, as the one that is used on the datetime legend on the right-bottom corner of the chart.

### Screenshots

![image.png](https://images.zenhubusercontent.com/60b4ebb03f4163193ec31819/6be0f979-535a-406a-9658-ce1c493105b0)

![image.png](https://images.zenhubusercontent.com/60b4ebb03f4163193ec31819/150a9e64-0fc6-4c84-b470-7118c4a5c4b7)

**Comment by hugovalente-pm** [comment]
this is linked to netdata/product#2689

**Comment by jjtsou** [comment]
https://github.com/netdata/charts/pull/49

**Comment by hugovalente-pm** [comment]
@jjtsou was checking this on staging and I have one request, I know on the label we have `00m14s` but this on the pill takes a bit of space. could we omit the 00m?

![image](https://user-images.githubusercontent.com/82235632/153450789-565eb3e2-dfc2-42c7-801f-57d06941942b.png)

**Comment by jjtsou** [comment]
https://github.com/netdata/charts/pull/51

**Comment by ktsaou** [comment]
This should be tagged as a bug.

**Comment by hugovalente-pm** [comment]
@jjtsou I don't think has this deployed to production yet
![image](https://user-images.githubusercontent.com/82235632/154441527-140c7a37-ea80-4979-aa84-b663459382ea.png)

let's close this ticket when that happens
