### ISSUE TITLE
[BUG] Error in charts in custom dashboards when user does a fresh log-in

### ISSUE THREAD

**Issue by kaskavel** [netdata/netdata-cloud#264]
**Describe the bug**	

Originated from [community report](https://community.netdata.cloud/t/dashboard-charts-not-showing-data-before-visiting-node/2513). 
When a user logs in to netdata cloud and visits a custom dashboard containing charts from single node view, the relevant requests result in 404 from server: 

Request: 
GET  https://app.netdata.cloud/api/v2/nodes/{node_id}
Response: 
{"errorMsgKey":"ErrNodeInstanceNotFound","errorMessage":"could not find node instance","errorCode":"njvsYRMOlZ-347354315"}

However, the root cause of this seems to be in the _query request, returning empty results: 

Request: 

POST https://app.netdata.cloud/api/v2/spaces/31a2fba1-8ee2-4fa0-9fed-bb437e3fb75c/charts/_query 
Response: 
{"results":null}

**To Reproduce**	
Create a dashboard containing a chart from a single node view. In the particular example we are looking at, we are adding disk_space related charts to this dashboard.  
Log out. 
Log back-in and visit this dashboard. 

**Expected behavior**	
The charts within the dashboard to show data without the user having to visit the single node view of the contributing nodes. 
 
**Screenshots**	
Issue before visiting the single node view of one of the contributing nodes to the dashboard: 
![image](https://user-images.githubusercontent.com/31739664/153216566-ccf4738f-998f-4370-9864-eed5beeed65a.png)

View after visiting single node view: 

![image](https://user-images.githubusercontent.com/31739664/153216641-7b33de34-af42-41b3-ad88-4f012503f3f1.png)

**Desktop (please complete the following information):**	
 - OS: MacOS
 - Browser Chrome	
 - Version 97.0.4692.99

**Comment by hugovalente-pm** [comment]
thanks for looking into this @jjtsou I know @juacker and @kaskavel had looked into this in the past so probably they can help with some findings/guidelines from their side

**Comment by juacker** [comment]
I have taken a quick look and I cannot see the `context` field in the dashboards I created:

![Captura de pantalla de 2022-02-14 16-31-32](https://user-images.githubusercontent.com/2930882/153894203-3277d96c-1a31-4685-9021-6f85110a46fb.png)

I see the dashboard content is blindly stored in the cloud  on `PATCH` requests to `/api/v1/spaces/${spaceId}/rooms/${roomId}/dashboards/${id}`, and we just return the stored value on `GET` requests.

Any idea why the `context` is not sent in my tests @jjtsou? (I tried creating the dashboard before and after accessing the node, in both cases the `context` parameter was not sent)

**Comment by jjtsou** [comment]
@juacker The `chart` context was not sent because sometimes it was undefined in our previous approach. Opened a PR with a fix. Thanks for you inout on this one!
