### ISSUE TITLE
[BUG] When focus is lost charts are not update but time control is still showing Play 

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#267]
**Describe the bug**	

When my page loses focus the charts are no longer requesting /data for the chart but the icon on time control is still showing Play

**To Reproduce**	
1. Have your focus on Overview or Single Node view page and the time control as `Play` (mouse can't be on top of the charts)
2. Remove the focus from that (go to chrome devtools or some other)
3. See that charts are refreshed (no new requests to `/data` are made) but the `Play` button is still there

**Expected behavior**	

`Play` button should be moved to `Pause`

**Screenshots**	

![chrome_cqP9lylvpS](https://user-images.githubusercontent.com/82235632/153454717-55654d7b-6e53-40fe-b70d-79a6f1a153b8.gif)

**Error logs**	
N/A

**Desktop (please complete the following information):**	

**Additional context**

**Comment by hugovalente-pm** [comment]
This is linked to netdata/cloud-frontend#2886

**Comment by cakrit** [comment]
Moved it to prio low, as it's definitely annoying, but doesn't significantly impact the ability to troubleshoot.
