### ISSUE TITLE
[BUG] offline nodes appear as online

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#271]
I have 3 nodes in my space that they show as online, but they are not.

Space-id: f0bb93b8-670c-4c49-ad18-492ccc59ab74

1. https://app.netdata.cloud/spaces/tsaousis/rooms/general/nodes/25eb3db8-1afb-11e6-9db0-7cdd9077336a
2. https://app.netdata.cloud/spaces/tsaousis/rooms/general/nodes/93bcabe6-8281-11ea-a175-b827ebd5a0a5
3. https://app.netdata.cloud/spaces/tsaousis/rooms/general/nodes/b415e708-8e62-11ea-8db0-a7943ce28c42

This is a very long standing issue. They have been online for many months, although they are not online.

**Comment by ktsaou** [comment]
@papazach @vkuznecovas can we update the sanitization script to mark all these nodes as offline?

**Comment by ktsaou** [comment]
Do we know how many nodes are in this phantom state?

**Comment by vkuznecovas** [comment]
I'll take a look at this.

**Comment by vkuznecovas** [comment]
I've looked into it, there's some leftovers that have not been cleaned out. I'm planning on replaying some events to properly get rid of these Monday or Tuesday as the relevant code changes have been implemented. I'll come back to this once the issue is resolved.

More details for the cause & the fix: https://github.com/netdata/product/issues/2803

**Comment by ktsaou** [comment]
Thank you @vkuznecovas and @papazach for pushing forward to fix this issue! You rock!

**Comment by vkuznecovas** [comment]
Hey @ktsaou could you check if the problem is solved? These nodes should be gone now, as we've made the required fixes for this.

**Comment by dionysis-netdata** [comment]
@ktsaou this should be fixed by last weeks updates. let us know, so we can close this ticket

**Comment by ktsaou** [comment]
I see it fixed! You rock @vkuznecovas !
(Sorry for the delay to respond)
