### ISSUE TITLE
Right-hand bar component w/ filtering on Nodes

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#272]
## Goal

Provide on the right-hand bar component a filter section on **Overview tab** that allows filtering the data by selected Nodes.

This filtering when activated or changed will imply:
* Updating the TOC
* Updating the charts on the central main area
* Updating the data on the displayed charts

This filtering component should be the similar to to one used on the Alerts tab where we have:
* search box
* list of nodes
Note: on the Alerts tab this has a badge with the number of alerts on the node, which won't apply in this context

When this is introduced we need to remove the filter bar on top

**Comment by ktsaou** [comment]
@hugovalente-pm for some reason this ticket exists in 3 repos. I think this kind of duplication will kills us. We are going to lose our minds trying to keep track of everything and since we can discuss on all 3 about it, it is going to be confusing to find all the discussions. Let's discuss about this to find a solution.

**Comment by hugovalente-pm** [comment]
> Or we should drop that filtering bar. Do you have any stats on its usage?

@ktsaou we have stats that show some usage till end of Oct.21, will need to see if there is some issue with data after that period.

so from Jul.21 to Oct.21 we have over the filter box as a whole:
* Adoption rate of 4.02%
* Across the 4 months this has around 140 unique users using this per month

**Comment by ktsaou** [comment]
Just 140 users is way too low. Probably we need a more advanced filtering with search. So, I think we can kill it, provided that we add something more powerfull at the filters.

**Comment by hugovalente-pm** [comment]
ok, will update the ticket to mention to remove this when we add the filters on the right-hand bar

**Comment by hugovalente-pm** [comment]
This is a breakdown from #278, so this is to be followed on our internal repo netdata/cloud-frontend#2914.
closing this ticket
