### ISSUE TITLE
Metric correlations should be available on Overview page

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#273]
## Goal

The Metric Correlations button should be available on the Overview page

This button will only be available when:
* the War Room has one node
* any filtering applied has as a result data from a single node

This will be reviewed once Metric Correlations can be executed across multiple nodes

**Comment by ktsaou** [comment]
Metric Correlations today work like this:

1. UI is requesting metric correlations from a service in the cloud backend.
2. the metric correlations back end service, does multiple data queries to the agent.
3. the metric correlations calculates the `ks` score for all metrics and returns them back to the UI.

We have decided to implement metrics correlations calculation at the agent itself, to avoid transferring all the data of all the metrics from the agent to the cloud backend for this calculation. This will allow us to query a lot more data and actually provide a very efficient way for multi-node metric correlations, although it has some implications. @shyamvalsan do you have a ticket for it? Please link it here.

**Comment by hugovalente-pm** [comment]
This is a breakdown from #278, so this is to be followed on our internal repo netdata/cloud-frontend#2915.

@ktsaou @shyamvalsan closing this ticket and moving the above comment there
