### ISSUE TITLE
General as a war room for all space's nodes and users

### ISSUE THREAD

**Issue by ghost** [netdata/netdata-cloud#279]
**Story**
As Netdata,
We want the general War Room to become an space holistic War Room with all users and nodes,
so that users have a room that gives them complete visibility of the inventory 

**Acceptance Criteria for Nodes**
1. All existing nodes should appear in the `general` war room too, independently of the other war rooms they appear in.
2. Any newly added node will automatically be part of the `general` war room, even if the claim command does not state that.
3. Any attempt to remove a node from the `general` war room should fail.

**Acceptance Criteria for Users**
1. All existing users should be members in the `general` war room too, independently of the other war rooms they have access.
2. Any newly added user will automatically be part of the `general` war room.
3. Any attempt to remove a user from the `general` war room should fail.

In order not to messup with existing `general` rooms setup. We should create a copy that will behave as a standard room  (prior to adding all nodes in general)

**Comment by ktsaou** [comment]
This is great. With this change, the `general` war room becomes the absolute inventory for everything and everyone. People who don't need war room, will just work in the `general` war room, as the single source of truth for their infra. This takes away the need to explain war rooms to new comers, simplifies user onboarding process significantly and allow people to have clarity on their infrastructure.

Yes, we will eventually face scalability problems with this approach. What if the `general` war room gets 10k nodes. But this is a problem we have to solve for any war room. War rooms have to work efficiently even when there are 10k nodes in them. So, we should not see this scalability issue as a reason to prevent the `general` war room from becoming the inventory of the entire infra.

@amalkov @ralph please have a look at this. We just need a tech review currently. Then we can prioritize it.

**Comment by ktsaou** [comment]
> The first question is about Permission - for bigger organizations, not everyone should have access to everything.
> Every admin has access to all nodes, but users are assigned to individual rooms.

I agree. However, today users are all forced to be members of the General war room. Nodes are optional. But users are mandatory. Let's not change the way it is. We will deal with it later.

> However, for the `Overview` tab we would hit all nodes for the Space, as we start from the CPU chart to which all nodes contribute.
> Besides performance concerns, such composite charts may no longer convey any useful information.

I agree.

> We are suggesting having a different `Overview` tab, similar to what @hugovalente-pm suggested.
> The only difference is that we must display data available on the Cloud, to have control over the performance of this page. For example, Nodes topology, Alerts stats, Nodes Manager.

ok, let's see what information could be there.

> We are suggesting having an `Explore page` instead of the old `Overview` page with filtering functionality or slicing and dicing. It will allow displaying the subset of the data on the initial load

"Explore" is probably not the right name. Probably we need to rename "Overview", like this:

1. **Overview**
   A page that has high level stats about the war room, like you suggest.
   
2. **Nodes**
   The existing Nodes page, as we plan to improve it to become simpler and include node management functions.
   
3. **Metrics** or **Charts**
   The existing Overview, where all metrics and charts of the war room are listed.
   
4. **Dashboards**
   The existing Dashboards, where all custom dashboards are kept.
   
5. **Alerts**
   The existing Alerts, as we plan to improve it, to include all the configured alerts and the alerts log.

Ideally, the user should be able to pin any custom dashboard as the first page of a war room.

@hugovalente-pm @dionysis-netdata please let's discuss what the new "Overview" page can have, based on the available data.

**Comment by hugovalente-pm** [comment]
> @hugovalente-pm @dionysis-netdata please let's discuss what the new "Overview" page can have, based on the available data.

@ktsaou I would like to see if what is suggested from that past ideation is an interesting approach:
* Health summary
   * Alert badge/table - showing total number of active alerts and a breakdown on Critical and Warning
   * Anomaly information - initially this was done when Anomaly Events were a "first-class" citizen but now doesn't seem to make much sense, but we have other interesting stats probably like:
      * Top X anomalous nodes based on avg anomaly rate across their metric/dimensions
      * Top X anomalous nodes based on total number of anomalous metrics
   * Unreachable nodes counter
   
* War Room overview
   *  Number of clusters (if there are)
   *  Number of node
   *  Number of pods (if there are)   
   *  Number of containers (if there are) adding the technologis: k8s, docker, lxc, etc.
   * Apps/plugins active across all the nodes - goal to give a view of services being monitored
   * Total number of configured alerts across all the nodes

* Section with Top X offender over key metrics (CPU, Memory, Ram, Network)
  * Users could chose if they want to see these across: cluster, nodes, pods, containers
  
> 3. Metrics or Charts
> The existing Overview, where all metrics and charts of the war room are listed.
This one seems this ticket Evolution of dashboard engine towards powerful slice and dicing tool #2786

**Comment by ktsaou** [comment]
@hugovalente-pm please open a new ticket for ideating about the new overview dashboard, based on data that the cloud backend has.

**Comment by hugovalente-pm** [comment]
@ktsaou created this ticket netdata/product#2797

**Comment by ralphm** [comment]
> > The first question is about Permission - for bigger organizations, not everyone should have access to everything.
> > Every admin has access to all nodes, but users are assigned to individual rooms.
> 
> I agree. However, today users are all forced to be members of the General war room. Nodes are optional. But users are mandatory. Let's not change the way it is. We will deal with it later.

I didn't realize this. However, right now when nodes are claimed to Cloud, you can choose to not have them join the `General` room. With this, current users can compartmentalize users so they have access to specific sets of nodes by carefully assigning nodes and users to rooms. Repurposing the `General` room has the following result:

- It changes existing configuration of rooms.
- With that affects which users can see which nodes.
- By default we probably don't want the same behavior for the metrics view for this compared to _regular_ rooms.
- Node membership is dynamic and unmutable.

As such, maybe we should not repurpose, but instead convert the rooms named `General` to a regular room, and introduce a new _room_ called `All` or another name that conveys it is about all the things. We might have conflicts with existing rooms, but that probably is limited to a few spaces.

**Comment by ktsaou** [comment]
@ralphm @dionysis-netdata I like the idea of having a new room `all nodes`, but then we will have a discrepancy. All users in `general`, without any ability to change that and all nodes in `all nodes` without any ability to change that either.

The problem today is that there is no global inventory of the infra. Everything is scattered everywhere so that users get lost and they have to learn what "War Room" means and how to use them.

I think we are very early in our journey and we can still adapt a few things.

Can we take a data informed decision?

@cakrit @thanos-karachalios : How many of the currently connected nodes are not in the `general` war room?

Let's see how big the impact of this change will be...

**Comment by thanos-karachalios** [comment]
49% of connected nodes are under war-rooms named `general`. Remaining 61% in others

**Comment by ktsaou** [comment]
> 49% of connected nodes are under war-rooms named `general`. Remaining 61% in others

Wow! That's a lot! This can mean 2 things:

* Either the problem of distributed inventory is too widespread and people are lost
* or people really get how to use war rooms and they use them intentionally

It may help to exclude:
1. Spaces with <3 nodes connected (no practical need for war rooms)
2. Nodes in war rooms that are alone in there (when war room node count = 1, the war room is accidental, no practical need for it).

@thanos-karachalios could you please provide the same metric, over different space sizes. Like filling this table:

space connected nodes|% of nodes in general|% of nodes elsewhere
:---:|:---:|:---:
1-2|?|?
3-5|?|?
6-20|?|?
20-100|?|?
\>100|?|?

excluding spaces with node count < 3 and nodes that are alone in a war room.

**Comment by thanos-karachalios** [comment]
room_name | space_group | name_room_count_in_spacegroup | total_room_count_in_spacegroup | percentage
-- | -- | -- | -- | -- 
General | 4-10 | 1306 | 2640 | 49.0 
General | 11-20 | 199 | 744 | 27.0 
General | 21-100 | 107 | 679 | 16.0 
General | >100 | 13 | 159 | 8.0

**Comment by ktsaou** [comment]
@thanos-karachalios as we discussed, the above are "room counts".

What we need is (for every category / row):

1. Sum of number of unique nodes (not node instances) in space
2. Sum of number of unique nodes (not node instances) in space, that appear in `general` room

**Comment by thanos-karachalios** [comment]
Row | space_group | avg_unique_node_count_perSpace | avg_unique_node_count_perGeneralRoom
-- | -- | -- | --
1 | 4-10 | 6.0 | 4.0 |  
2 | 11-20 | 14.0 | 9.0 |  
3 | 21-100 | 38.0 | 16.0 |  
4 | >100 | 440.0 | 137.0

**Comment by ktsaou** [comment]
Thank you @thanos-karachalios !

So, the bigger the space, the less nodes appear in the general room.

I understand the `general` room will become too big for the users with a lot of nodes. 

Still:

1. we lack a centralized nodes management page, a page that users can see all their nodes.
2. new users get confused with war rooms - it is more suited for bigger setups.
3. all users are always in `general`, but nodes may not be.

I suggest the following:

1. all nodes will always join `general`, much like users, so the `general` war room will become the inventory and new comers will not have to learn the concept of war rooms.

2. to avoid to "Overview" page load when there are many nodes in the war room, the `general` war room will have as default page the "Nodes" tab.

We will release like this, to make the cloud more predictable for the new users and we will work to provide a new "Overview" page that will have the statistics of the war room https://github.com/netdata/product/issues/2797

@ralphm @amalkov what do you think?

**Comment by ralphm** [comment]
The biggest issue I have with the approach of having all users and all nodes in `general` is that you can no longer use rooms for controlling access. Having the ability for _admins_ to see the complete inventory makes sense to me, but I am not sure this extends to all users. Also, does this mean all users get alerts on all nodes by default?

**Comment by amalkov** [comment]
I'm sharing the same concerns as @ralphm mentioned. 
On top of it...

What we are trying to address? - Nodes should not be lost! 

This is why we need a Node management page without any dashboard overview capability but fast, clear, and manageable...
Where all nodes will be listed. 

Nodes that are not claimed into any warroom will be highlighted and filtered by default.

Another reason, Is what I as a user will gain from this huge general room?
More likely to be slow and limited as we need to display aggregated data... Probably more unhappy users, as some of my production nodes (displayed on the first page) will be queried by default all the time when any member of my team will go to Netdata cloud dashboard and land in a General warroom... 
The footprint for those unlucky nodes will be too high because of Netdata way of presenting dashboards.

I still believe that we are trying to address users' pain in a not optimal way.

Suggested Solution: 
1. do not change the General room
2. Introduce a simple Node management page
3. Add extra filters by warroom claim status

**Comment by ktsaou** [comment]
@ralphm @amalkov 

Based on our discussion we concluded that:

1. We will support a kind of dynamic war room membership for nodes.
   
2. New spaces created, will get this dynamic war room membership matching all nodes, at the `general` war room.
   
3. The Overview dashboard will be limited to 100 nodes for charts to appear. If any war room has more than 100 nodes, the Overview dashboard will present a message asking the users to filter nodes up to 100.
   
4. For existing spaces, if the `general` room has all the nodes, it will be automatically converted to dynamic, like in new spaces.
   
5. For existing spaces, if the `general` room does not have all the nodes:
   
   * copy `general` to `general-static` (nodes, users, dashboards)
   * modify `general` to have the dynamic membership with all nodes, like in new spaces
   * new users will join `general`, not `general-static`.

6. In all cases, the `general` war room has all the users.

In all cases, even for rooms with dynamic membership, the membership is recorded in the database. Membership may change based on various events, but it is always persisted in the database.

**Comment by amalkov** [comment]
Some questions were raised during the estimation process:
- Do we have limitations applied for the Nodes view as well?
- Nodes are not paginated now - performance concern
- Node deletion from `General` means delete from `Space`? (remove from other war rooms as well)
- How to see the rest of the nodes (above 100) to manage it?

**Comment by ktsaou** [comment]
> * Do we have limitations applied for the Nodes view as well?

No. Let's show them all. We are changing that page to make it more performant. Even if there are 30k nodes, the nodes tab should be ok.

> * Nodes are not paginated now - performance concern

There should not be any performance issues with this. Let's deal with it when it comes. It does not seem that hard.

> * Node deletion from `General` means delete from `Space`? (remove from other war rooms as well)

Node deletion from space is tricky. It can only happen on offline nodes and after all metadata we maintain have expired. Only then a node can be safely deleted without introducing data inconsistency. If for example we say that we will keep metadata (alarm log) for 1 year, we will need to maintain the node entry for 1 year too.

But offline nodes could be hidden somehow. We will discuss this in detail with node persistence and ephemerality.

Yes, I understand that a space that generates 2000 nodes per day can be a problem, but let's deal with this problem in a different way.

> * How to see the rest of the nodes (above 100) to manage it?

All active (online, stale, persistent offline) nodes will always be visible in the Nodes tab of the `general` war room.
We will have to deal with ephemeral offline in a special way (probably only search for them).

We will deal with ephemeral offline, when we will implement this.

**Comment by vkuznecovas** [comment]
So technical details for the implementation would be these:

Implement a script to migrate existing data
This script should do the following:
1) Iterate through spaces.
2) Check each spaces' general war room:
	a) If the general room does not have all the spaces' users assigned, assign permissions to the missing users to view general.
	b) If the general war room contains all nodes that belong to the space, all is well - continue.
	c) If the general war room does not contain all the nodes that belong to the space then do the following:
	* Make a copy of the existing general room and name it `general-static`. 
    * Add all missing nodes to the general room

Implement the following change to the spaceroom service:

When a `NodeCreated` arrives, automatically assign it to the general room as well as any rooms it would have been added to.

Both the script and the change should emit relevant events to let the other subscribers know of the changes.

AFAIK there's no need to change anything related to inviting, as by default users invited to the space will get invited to the general room.

**Comment by dionysis-netdata** [comment]
looks good @vkuznecovas 
`a` shouldn't happen as all users belong to general.

+ 1 more thing. block node removal from general war room. user removal is already not applicable

**Comment by ravilushqa** [comment]
> 2.a shouldn't trigger as all users belong to general. And if we create a copy war room, it should be made prior to any changes

@dionysis-netdata I didn't get it, can you please explain what do you mean

@vkuznecovas also `2.b` looks useless as all users are assigned to the general if I understand correctly

**Comment by dionysis-netdata** [comment]
> `2.a` shouldn't trigger as all users belong to general. And if we create a copy war room, it should be made prior to any changes

Forget my comment. Vik edited his previous comment.

I updated this ticket description to inlude the missing bit about the copy war room.

**Comment by ravilushqa** [comment]
@dionysis-netdata do we need to add acceptance criteria for dashboards?

**Comment by dionysis-netdata** [comment]
@amalkov I believe you said that we won't have any performance issues. Therefore, no need to implement logic of <100 nodes or change something.

**Comment by dionysis-netdata** [comment]
FYI, @thanos-karachalios

**Comment by dionysis-netdata** [comment]
@ravilushqa, @ivangergo3  I noticed it's not possible to delete the copied room general-static after migration. 

We should allow actions, like remove users, leave war room and delete war room for general static. It's the new general that won't allow such actions. So if we end up creating a copy room it will behave as a standard room

**Comment by ravilushqa** [comment]
> @ravilushqa, @ivangergo3 I noticed it's not possible to delete the copied room general-static after migration.
> 
> We should allow actions, like remove users, leave war room and delete war room for general static. It's the new general that won't allow such actions. So if we end up creating a copy room it will behave as a standard room
> 
> Not a blocker, but let's do it

it's bug, and it's probably fixed :)

**Comment by ivangergo3** [comment]
@dionysis-netdata For me, it makes sense to remove the general-static room, as it should not behave as general, but just as a simple room.
