### ISSUE TITLE
[BUG] When we get a lot of server errors, the UI becomes unusable

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#28]
We need to roll multiple events into a single notification, or just stop showing them until we find a solution.

![image](https://user-images.githubusercontent.com/43294513/101082929-1bd55e00-3561-11eb-8b5d-abf0e867d0ce.png)

**Comment by manos-saratsis** [comment]
In the Product team we need to find a better way to show errors.

**Comment by manos-saratsis** [comment]
After a discussion with @novykh we will do an exponential backoff. Next step is to have more detailed server errors from @netdata/cloud-be

**Comment by novykh** [comment]
Fixed
