### ISSUE TITLE
Join public and private war rooms (for admins) without an invitation

### ISSUE THREAD

**Issue by ghost** [netdata/netdata-cloud#280]
**Story**
As a Netdata Cloud user,
I want to join other war rooms,
So that I monitor services & infrastructure under those war rooms

**Acceptance Criteria**
* A simple/admin user can join other public war rooms, without requiring an invitation
* An admin can also join private war rooms under the same space, without requiring an invitation

**Comment by shyamvalsan** [comment]
@ktsaou @cakrit @amalkov what is the context behind this request? We will be fundamentally changing access workflow if we do this - especially for private war rooms. So I am trying to understand the rationale here.

**Comment by amalkov** [comment]
To be handled by https://github.com/netdata/product/issues/3019
