### ISSUE TITLE
Netdata Admins, Managers and Troubleshooters to have access to all war rooms in the space

### ISSUE THREAD

**Issue by ghost** [netdata/netdata-cloud#281]
**Story**
As a Netdata Cloud Admin / Manager / Troubleshooter
I want to be able to join any war rooms in my space,
So that I have visibility of all war rooms the space

**Acceptance Criteria**
* Admins and Managers will be able to fully manage all War Rooms in that space. 
* Troubleshooters will be able to have visibility on any War Rooms in that space.

**Comment by ravilushqa** [comment]
Do we know the exact cases that need to improve, or does it need investigating

**Comment by ravilushqa** [comment]
Ok, thanks

**Comment by hugovalente-pm** [comment]
released with paid plans
