### ISSUE TITLE
View all Active alerts in a user friendly format (table) from a mobile device.

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata-cloud#285]
##Issue
As a user of Netdata Cloud, I would like to view all active alerts in my Space/Room/Node on my mobile device.

##Use-case
On receiving a notification on the mobile, the user needs to be able to see the specific alert and also other active alerts on a mobile device.

**Comment by sashwathn** [comment]
@novykh, @jacekkolasa  and @libekonst : This is one of the topics that needs to be analysed and implemented.

**Comment by hugovalente-pm** [comment]
@sashwathn does the mobile app ticket replace this? https://github.com/netdata/product/issues/2868

**Comment by sashwathn** [comment]
@hugovalente-pm : This one is already completed and is related to the dedicated alert landing page which is mobile friendly.
