### ISSUE TITLE
Support Stale connection status for nodes

### ISSUE THREAD

**Issue by ghost** [netdata/netdata-cloud#289]
Currently Status only shows as `Live` or `Offline`. With introduction of new arch and parent/child functionality, we want to support a new `Stale` status for nodes.

`Stale` is a status where the metrics received for a node are historical as the node is currently not streaming any metrics

Places where we should display this
* Nodes Tab, on every node
* Single node tab
* On node inspector, connection status

**Comment by dionysis-netdata** [comment]
Remember to sync with FE on this https://github.com/netdata/cloud-frontend/issues/3217
