### ISSUE TITLE
Useability improvement: Duplicate node names lead to inability to manage a room

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#29]
We use the node name as the only identifier shown on multiple screens. Of especial importance is the room nodes list, which we would normally use to remove nodes we don't want in the room. 

If we continue to allow duplicate node names, we need to provide an additional identifier that allows users to distinguish between multiple entries with the same name, so they can at least remove from the room the ones that are problematic.

**Comment by manos-saratsis** [comment]
@franklinandrade let's discuss how we solve this

**Comment by vinnygats** [comment]
Hello! 
Discussed the issue with @dimko .
Considering the design changes that are being under implementation at the moment, there are a few changes that can be covered, such as displaying the node badges to the left side. 
Although, there are some cases in our design where user can see a full list of these replicas and they may have exactly the same name.

In this case, user can no longer identify which node is what, so we need to revisit and ideate on this scenario with the Product team to find a solution, maybe adding automatically a suffix etc.

cc: @manos-saratsis @Yannis-San

**Comment by ivangergo3** [comment]
Hi @vinnygats , do we know anything about this ticket? Will there be a change in design?

**Comment by cakrit** [comment]
I removed the BUG from the title and the labels. It's a useability problem and not one that I have seen other users mention. I expect that with node obsoletion the need to manually remove nodes will be resolved. Closing it.
