### ISSUE TITLE
[BUG] Immortal space refuses to go away

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#290]
I keep trying to leave the space in the URL below, I keep getting the message that it will be deleted and it keeps appearing again. Very stubborn little bugger.

https://app.netdata.cloud/spaces/github/rooms/general/overview#_f=

**Comment by novykh** [comment]
@cakrit could you verify if it works on prod?

**Comment by ivangergo3** [comment]
@cakrit can you please check it again? I have tried it and it was working for me

**Comment by cakrit** [comment]
Tried two more times. It just doesn't go away.

**Comment by cakrit** [comment]
I created and deleted tens of spaces today. Whatever happened then, it left that space in mongoDB and it won't go away unless I delete and recreate my account, which I won't do. Closing this one.
