### ISSUE TITLE
[BUG] Wrong right-side drawer content size

### ISSUE THREAD

**Issue by ivangergo3** [netdata/netdata-cloud#291]
**Describe the bug**	
On the right-side drawer, the content size is not the same as the drawer

**To Reproduce**	
1. Navigate to http://app.netdata.cloud
2. Login with google
3. Claim a node with the extra parameter "-h test"
4. Go to the Node tab
5. Open Nide Info, right-side drawer

**Actual behavior**
The drawer size and the content size is not the same

**Expected behavior**	
The drawer content size is the same as the drawer size

**Screenshots**	
Screenshot is attached
![question_ux](https://user-images.githubusercontent.com/5202868/154658992-bea2f840-2b9e-460b-a150-3a2d97ada38a.JPG)

**Desktop (please complete the following information):**	
 - OS: Windows 10 (although it is a problem on MacOS as well)	
 - Browser Chrome
 - Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by dionysis-netdata** [comment]
@ivangergo3 I think this is fixed.  Can you double check

**Comment by ivangergo3** [comment]
Seems like it has beed solved!
Closing the ticket
