### ISSUE TITLE
[BUG] Email not set message in Manage war room - Users tab

### ISSUE THREAD

**Issue by amalkov** [netdata/netdata-cloud#292]
**Describe the bug**	

The list of Users in the Manage War Room drawer is not displayed correctly

**To Reproduce**	

1. Select War room
2. Click the "War Room Users" icon in the top right corner
3. Check the list of Users under the "Users" tab

**Expected behavior**	

Every item should display 
FirstName LastName - EmailAddress

**Screenshots**	

![image](https://user-images.githubusercontent.com/423236/154715853-ef9712b9-8120-476f-b814-76da57ac4901.png)

**Comment by novykh** [comment]
Fixed and deployed on prod.
