### ISSUE TITLE
[BUG] Nodes shown as live even if they are not

### ISSUE THREAD

**Issue by ivangergo3** [netdata/netdata-cloud#297]
**Describe the bug**	
Node showed as live even if they are not

**To Reproduce**	
Check for instance gke-staging-streamnative-202103050938-299aaab9-1mtd node

**Expected behavior**	
It should be shown as not live

**Comment by dimko** [comment]
closing as duplicate to this one https://github.com/netdata/netdata-cloud/issues/271
