### ISSUE TITLE
[BUG] `list-node` shows wrong information for reachable nodes

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata-cloud#298]
**Describe the bug**	
I have a online host, and cloud is showing it, but when I access `list-nodes`, it is saying that my host is 32 days unreachable.

**To Reproduce**	

Connect a host and access `list-nodes`.

**Expected behavior**	

When my host connects with cloud, I wanna see the status that matches what I am seeing on dashboard.

**Screenshots**	

![Screenshot_20220222_190554](https://user-images.githubusercontent.com/49162938/155203521-c4585442-cf5e-4e8a-809b-f5c9ad816288.png)

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	

![Screenshot_20220222_192458](https://user-images.githubusercontent.com/49162938/155204297-07bee840-7749-4ebf-a935-e4a0e72deb7f.png)

**Desktop (please complete the following information):**	
 - OS:  Slackware Current
 - Browser: Firefox
 - Version: firefox-97.0.1

**Additional context**	
This war-room is already using the latest architecture.

**Comment by thiagoftsm** [comment]
Hello @ivangergo3 ,

I changed from `offline` to `unreachable`.

**Comment by cakrit** [comment]
I believe that the confusion here comes from the meaning of the Date field. Which Date is that? The date the node was first connected? The column name is meaningless as is, either change it or remove the column. @shyamvalsan I believe this is your decision now.

**Comment by shyamvalsan** [comment]
Also realized the documentation for this section is out of date https://learn.netdata.cloud/docs/cloud/war-rooms 

Was trying to figure out what "Services" is supposed to indicate? I see no info anywhere.

**Comment by thiagoftsm** [comment]
Hello @shyamvalsan ,

If we are talking about when it was `claimed`, to have only `Date` does not indicate what the field means as @cakrit well described.

We need to take care when we are naming the fields, `date` is so generic that I thought a completely different subject.

**Comment by shyamvalsan** [comment]
@thiagoftsm I completely agree - but having a `date claimed` doesn't really make sense in that view, which is why I would prefer to remove the column entirely.

**Comment by shyamvalsan** [comment]
https://github.com/netdata/learn/issues/1040 to make the docs better

**Comment by hugovalente-pm** [comment]
with the release of Centralized Admin Interface this is no longer applicable https://github.com/netdata/cloud-frontend/issues/3377
