### ISSUE TITLE
[BUG] Regular Unreachability and reachable alerts

### ISSUE THREAD

**Issue by LM1LC3N7** [netdata/netdata-cloud#30]
**Describe the bug**	
I receive a lot of emails because my node is unreachable and reachable again within minutes.

**To Reproduce**	
1. Start a netdata container
2. Change config to update every 3 seconds
3. Enrol the agent to Netdata Cloud

**Expected behavior**	
Node always reachable except when I stop the container.

**Screenshots**	
![image](https://user-images.githubusercontent.com/14235706/101362796-7c81d500-3898-11eb-9d53-0133fb78358a.png)

**Additional details**

`netdata.conf`

```bash
[global]
    update every = 3
    hostname = THOR
```

**Comment by manos-saratsis** [comment]
@LM1LC3N7 you saw these emails because we enabled early the email notification feature by mistake. Now we rolled back so no more emails. Within the next weeks we will ship the feature properly together with all controls to customize the notifications you will get. Closing this.
