### ISSUE TITLE
OS displayed on node inspector is incorrect

### ISSUE THREAD

**Issue by ghost** [netdata/netdata-cloud#304]
Currently, for displaying the operating system we use the `os` attribute from the nodes API to display the node's OS. But this is more like the kernel name. We should render `osName` and `osVersion`

In addition let's add `architecture`

And rename `Hard disk space` to `Hard disk size`

Notes
* https://github.com/netdata/netdata-cloud/issues/300

**Comment by dionysis-netdata** [comment]
@cpipilas , @stelfrag - similarly I assume we also need to get more data exposed about the OS for a node to present the correct information

**Comment by dionysis-netdata** [comment]
@novykh I suspect you may already have implemented this?

**Comment by novykh** [comment]
Yes will be deployed in tomorrow

**Comment by dionysis-netdata** [comment]
deployed in production. closing
