### ISSUE TITLE
[INTERNAL SUBMIT] War Room Naming

### ISSUE THREAD

**Issue by cboydstun** [netdata/netdata-cloud#306]
**Describe the bug**	
Cannot give new war room a name that includes spaces. For example, "War Room" is *not* valid, but "WarRoom" is valid. Trying to use spaces will reveal the error "There's an unexpected character in the War Rooms's name. Use only Unicode characters, and no spaces." Chris A witnessed this error and said it should be addressed.  

**To Reproduce**	
Log in to the Cloud and attempt to create a new war room. It will require no spaces.

**Expected behavior**	
I expected to be able to name a war room including spaces.

**Screenshots**	
![image](https://user-images.githubusercontent.com/52934303/155398998-6a5357a3-d894-4d38-ac6a-1716463c4e9b.png)

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	
![image](https://user-images.githubusercontent.com/52934303/155399108-40e13c28-42d3-4b5c-a7dc-7ea3b86a749a.png)
**Desktop (please complete the following information):**	
 - OS: [e.g. iOS] Ubuntu 20.04	
 - Browser [e.g. chrome, safari]: Chrome	
 - Version [e.g. 22]: 	22

**Additional context**

**Comment by shyamvalsan** [comment]
This limitation has been resolved as part of https://github.com/netdata/product/issues/2910

**Comment by ravilushqa** [comment]
This limitation has not been resolved, but we plan to do so. It's actually part of https://github.com/netdata/product/issues/2925

**Comment by shyamvalsan** [comment]
Closing now, since we have released https://github.com/netdata/product/issues/2925
