### ISSUE TITLE
[BUG] Mac install code doesn't work

### ISSUE THREAD

**Issue by gnuchu** [netdata/netdata-cloud#309]
**Describe the bug**	
First time user. Presented with the following code to install on a mac (copied from the new user screen):
`curl https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token <token> --claim-rooms <roomid> --claim-url https://app.netdata.cloud`

 Produces the error:
```
WARNING  Found an existing netdata install at /usr/local/netdata, but could not determine the install type.

 WARNING  Usually this means you installed Netdata through your distribution’s regular package repositories or some other unsupported method.

 ABORTED  We do not support trying to update or claim installations when we cannot determine the install type. You will need to uninstall the existing install using the same method you used to install it to proceed.

Password:
sudo: a password is required
 ERROR  Installer exited unexpectedly (2-0)
```

However this installation does not exist:

```
$ ls -l /usr/local/netdata
ls: /usr/local/netdata: No such file or directory
```

**Expected behavior**	
Installation proceeds

**Desktop (please complete the following information):**	
 - Mac OSX 10.15	
 - Brave

**Comment by cpipilas** [comment]
Thanks for the report! Is this the first time you try to install netdata on your mac? Maybe you've done this in the past through homebrew?

@Ferroin I think we should transfer this at netdata/netdata.

**Comment by gnuchu** [comment]
It was a firs time install. Have never used before or installed via brew.

**Comment by Ferroin** [comment]
@gnuchu Can you try again, we just merged a PR a couple of hours ago (https://github.com/netdata/netdata/pull/12199) that should fix this.

**Comment by gnuchu** [comment]
@Ferroin Confirmed - on MacOS 10.15 the installation proceeds as expected.
