### ISSUE TITLE
[BUG] Datetime picker doesn't display "last 1 day/24 hour"

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#310]
**Describe the bug**	
When I set the datetime picker for a period of 1 day/24 hours this information isn't displayed
![image](https://user-images.githubusercontent.com/82235632/155702877-862f32c9-79cb-42a2-906c-2453645904be.png)

**To Reproduce**	
1. Go to a War Room Overview or Single Node View
2. Select the datetime picker interval to 24 hours or 1 day
3. Notice that the information where it should say "last 1 day or 24 hours isn't there

**Expected behavior**	
Show that we are seeing "last 1 day" or "last 24 hours"

**Screenshots**	
![chrome_gUsxyEvirB](https://user-images.githubusercontent.com/82235632/155703448-ef40452d-4373-4765-8c03-a52f1da12180.gif)

**Error logs**	
N&A

**Desktop (please complete the following information):**	
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 98.0.4758.102 (Official Build) (64-bit)	

**Additional context**

**Comment by hugovalente-pm** [comment]
@dionysis-netdata @novykh opened this one on the datetime picker

**Comment by dionysis-netdata** [comment]
adding a screenshot of the issue.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/95340881/157437483-efe6b4fa-0fca-4b31-8330-48c98dc1264f.png">

**Comment by AlexNti** [comment]
@hugovalente-pm This is currently in staging.

**Comment by dionysis-netdata** [comment]
cant see it
<img width="446" alt="image" src="https://user-images.githubusercontent.com/95340881/158822106-220e0a82-6617-4586-a5ae-18475f81a200.png">

**Comment by AlexNti** [comment]
@dionysis-netdata You are right it is not yet on staging, i accidently deployed it at testing instead. It will be on staging in few minutes.

**Comment by AlexNti** [comment]
@dionysis-netdata  It is on staging now.

**Comment by dionysis-netdata** [comment]
confirmed. ship it :)
