### ISSUE TITLE
[BUG] composite charts are not reliable for the latest point of the chart in play mode

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#313]
Composite charts are not reliable for the latest point in play mode.

Related to https://github.com/netdata/cloud-frontend/issues/3003 (to see how it looks to users). Notice the discrepancy in legend and graph, also the jumping graph (there is another bug with the y-axis not rendered there, which is pure UI issue).

The data source is 4 nodes, each having the value 1 for the entire lifetime of the chart.

So here is what happens:

```json
{
	"api": 1,
	"id": "anomaly_detection.detector_events",
	"name": "anomaly_detection.detector_events",
	"view_update_every": 1,
	"first_entry": 1645900071,
	"last_entry": 1646044386,
	"after": 1646044087,
	"before": 1646044386,
	"min": 1,
	"max": 4,
	"dimension_names": ["reset_bit_counter"],
	"dimension_ids": ["reset_bit_counter"],
	"view_latest_values": [1],
	"dimensions": 1,
	"points": 300,
	"format": "json",
	"result": {
		"labels": ["time", "reset_bit_counter"],
		"data": [
			[1646044087000, 4],
			[1646044088000, 4],
			[1646044089000, 4],
			[1646044090000, 4],
			[1646044091000, 4],

                       ...

			[1646044381000, 4],
			[1646044382000, 4],
			[1646044383000, 4],
			[1646044384000, 4],
			[1646044385000, 4],
			[1646044386000, 1]
		]
	},
	"nodes": [{
		"id": "0195e4aa-1976-44dd-8e23-7a1294e49d92",
		"latency": "151.298093ms",
		"chartIDs": ["anomaly_detection.detector_events_007457b4-9731-11ec-91e8-dca632bea0cc"]
	}, {
		"id": "d0b23fd9-6536-4802-b978-c0a8a70c3149",
		"latency": "146.56041ms",
		"chartIDs": ["anomaly_detection.detector_events_ff0472d8-9730-11ec-82ea-dca632bea093"]
	}, {
		"id": "dcbaa83a-d446-4400-9213-6642a7590481",
		"latency": "146.327717ms",
		"chartIDs": ["anomaly_detection.detector_events_fdb94188-9730-11ec-aab7-dca632bb8656"]
	}, {
		"id": "ff6707ee-939b-44e9-8e06-54063d2132de",
		"latency": "152.792158ms",
		"chartIDs": ["anomaly_detection.detector_events_023f3d48-9731-11ec-9534-dca632bea090"]
	}],
	"keys": {
		"dimension": ["reset_bit_counter"]
	},
	"labels": {}
}
```

The last point should be 4, not 1. All 4 nodes have only ones all the time.

I understand this is a timing issue. All 4 nodes are asked for the same RELATIVE timeframe (i.e. last 15 minutes in 300 points), but based on the timing they receive the requests the RELATIVE timeframe may not be the same of all of them!

So, in our case, only 1 node managed to respond for timestamp 1646044386. The other 3 did not.

This is the immediately next response for the same chart:

```json
{
	"api": 1,
	"id": "anomaly_detection.detector_events",
	"name": "anomaly_detection.detector_events",
	"view_update_every": 1,
	"first_entry": 1645900071,
	"last_entry": 1646044387,
	"after": 1646044088,
	"before": 1646044387,
	"min": 1,
	"max": 4,
	"dimension_names": ["reset_bit_counter"],
	"dimension_ids": ["reset_bit_counter"],
	"view_latest_values": [1],
	"dimensions": 1,
	"points": 300,
	"format": "json",
	"result": {
		"labels": ["time", "reset_bit_counter"],
		"data": [
			[1646044088000, 4],
			[1646044089000, 4],
			[1646044090000, 4],
			[1646044091000, 4],

			...

			[1646044382000, 4],
			[1646044383000, 4],
			[1646044384000, 4],
			[1646044385000, 4],
			[1646044386000, 4],
			[1646044387000, 1]
		]
	},
	"nodes": [{
		"id": "0195e4aa-1976-44dd-8e23-7a1294e49d92",
		"latency": "153.531786ms",
		"chartIDs": ["anomaly_detection.detector_events_007457b4-9731-11ec-91e8-dca632bea0cc"]
	}, {
		"id": "d0b23fd9-6536-4802-b978-c0a8a70c3149",
		"latency": "145.438106ms",
		"chartIDs": ["anomaly_detection.detector_events_ff0472d8-9730-11ec-82ea-dca632bea093"]
	}, {
		"id": "dcbaa83a-d446-4400-9213-6642a7590481",
		"latency": "147.57774ms",
		"chartIDs": ["anomaly_detection.detector_events_fdb94188-9730-11ec-aab7-dca632bb8656"]
	}, {
		"id": "ff6707ee-939b-44e9-8e06-54063d2132de",
		"latency": "159.060964ms",
		"chartIDs": ["anomaly_detection.detector_events_023f3d48-9731-11ec-9534-dca632bea090"]
	}],
	"keys": {
		"dimension": ["reset_bit_counter"]
	},
	"labels": {}
}
```

Note than now timestamp 1646044386 is 4, because all 4 nodes managed to respond for it, but the latest timestamp 1646044387 is now problematic reporting the value 1.

It is random what the latest timestamp will be. It may be 1, 2, 3 or 4 purely based on the timing each node received the RELATIVE query and the data it had in its database.

This makes netdata composite charts very unreliable! In play mode, the value you see at the legends of the charts is totally random based on purely the time the requests were received by the nodes.

We should ensure data presented are consistent.

---

I can think of 2 ways for this to be solved:

1. composite charts should always send ABSOLUTE, not RELATIVE queries to the agents
   or
2. the composite charts aggregation function should ensure it has data from all nodes to aggregate the last point - otherwise it should just throw away the last point

---

To solve this properly, please take into account that under certain conditions different nodes pay report data with different data collection frequencies. I will open a new bug for this, as it is buggy too.

---

cc: @hugovalente-pm @novykh @papazach @vkuznecovas @amalkov @ralphm @dimko

**Comment by hugovalente-pm** [comment]
>1. composite charts should always send ABSOLUTE, not RELATIVE queries to the agents
or
>2. the composite charts aggregation function should ensure it has data from all nodes to aggregate the last point - otherwise it should just throw away the last point

Option 1. seems "simpler", but not sure what work would be needed and where. 
a) would FE send the same request as now (RELATIVE) and these are translated to ABSOLUTE on BE and then sent to the agents?
b) would FE need to already send the request as ABSOLUTE and BE would just pass it on to the agents?

Option 2. would probably be safer if, for some other reason, when aggregating the data from all the nodes we don't have data from all the agents. 
One doubt on this is what if a given Agent doesn't have a datapoint for the last point and won't have it (collectors stopped or something like that)?

**Comment by amalkov** [comment]
I would vote for Option 1 in this case, my worry is exactly the same as @hugovalente-pm mentioned...

**Comment by ktsaou** [comment]
> a) would FE send the same request as now (RELATIVE) and these are translated to ABSOLUTE on BE and then sent to the agents?
> b) would FE need to already send the request as ABSOLUTE and BE would just pass it on to the agents?

option a) would use web browser's computer clock. I would strongly avoid this.
To my understanding only option b) is acceptable.

When panning or using the datetime picker for a certain time period, the absolute timestamp is calculated by the browser, but this is completely different. In this case we don't care what is the time on the browser's computer clock. So, the personal computer's clock is totally irrelevant.

When requesting the last X mins/hours/etc, the computer that translates this into absolute timestamps has to have a synchronized clock. Otherwise, it can get very messy.

So, please do the translation of relative to absolute duration, at the back-end.

> Option 2. would probably be safer if, for some other reason, when aggregating the data from all the nodes we don't have data from all the agents.

Option 2 is tricky. It can only be applied for the last point.

Here is a scenario, where it shouldn't be applied:

1. composite query for 5 mins, from 2 nodes, having 2 container charts
2. on one of the nodes, the container stopped 30 seconds ago, so it has no data for the last 30 seconds
3. The system should return 4m30s of data from both nodes, and 30s of data from one node. It shouldn't stop at 4m30s.

In this case, an annotation would be ideal on the chart, at exactly 4m30s indicating that one node did not provide any data after this point. This will increase transparency and our users will always know that what they see is valid.

---

Generally, both options I gave at the original post as valid, but both are tricky to get them done right. This is a crucial part of our system and it needs very good automated testing to ensure we cover all cases.

**Comment by amalkov** [comment]
@ktsaou agree, your concern about web browser's computer clock is valid... 
looping: @papazach @underhood

**Comment by TonyPath** [comment]
Just to note that currently back-end already receives RELATIVE duration and transforms to ABSOLUTE before pass through to the agent. So does not seem to be the issue. We will keep investigating this and get back here with an update

**Comment by dimko** [comment]
Closing this one
