### ISSUE TITLE
[BUG] composite and single node charts are faulty when the agent has stopped collecting data (old chart data)

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#315]
Composite charts show this:

Custom dashboard showing above a composite chart and below a single node chart:

![image](https://user-images.githubusercontent.com/2662304/155986341-4149336d-6b81-4aa2-a147-1c5cc583248c.png)

---

## Composite charts

The composite  `/data` query fails with this (it was just one node):

```json
{
	"errorMsgKey": "ErrAllNodesFailed",
	"errorMessage": "ErrAllNodesFailed",
	"errorCode": "pKfCawNENU-430433295",
	"nodes": [{
		"id": "01702efd-af72-45b0-8e2f-33d806e5699f",
		"latency": "153.26024ms",
		"error": {
			"errorMsgKey": "ErrNoData",
			"errorMessage": "node doesn't have data for the requested period",
			"errorCode": "pKfCawNENU-430433295"
		},
		"chartIDs": []
	}]
}
```

The chart shows this:

![image](https://user-images.githubusercontent.com/2662304/155985844-01b22185-1672-4870-86aa-d0c365c4bae6.png)

It should say the chart has no data. Not present an error.

---

## Single node charts

Single node charts are more strange.

They show legend values, but the graph is not there:

![image](https://user-images.githubusercontent.com/2662304/155986080-45870192-e06a-4bda-8997-c949837c3b69.png)

It should also show that there are no data.

---

Both of these problems will become even more apparent when parents will have data for stale children. The current behavior is also problematic when monitoring containers that come and go all the time.

---

@hugovalente-pm @novykh @ralphm @amalkov

**Comment by ktsaou** [comment]
Found the issue:

The agent does not have latest data:

```sh
# curl 'http://localhost:19999/api/v1/data?chart=system.cpu_pressure&before=0&after=-60&points=200&options=jsonwrap'; date; date +%s
{
   "api": 1,
   "id": "system.cpu_pressure",
   "name": "system.cpu_pressure",
   "view_update_every": 2,
   "update_every": 2,
   "first_entry": 1645808654,
   "last_entry": 1645838660,
   "before": 1645838660,
   "after": 1645838602,
   "dimension_names": ["some 60", "some 300", "some 10"],
   "dimension_ids": ["some 60", "some 300", "some 10"],
   "latest_values": [null, null, null],
   "view_latest_values": [7.04, 5.79, 6.42],
   "dimensions": 3,
   "points": 30,
   "format": "json",
   "result": {
 "labels": ["time", "some 60", "some 300", "some 10"],
    "data":
 [
      [ 1645838660, 7.04, 5.79, 6.42],
      [ 1645838658, 7.14, 5.79, 6.86],
      [ 1645838656, 7.15, 5.79, 6.83],
      [ 1645838654, 7.15, 5.78, 6.79],
      [ 1645838652, 7.23, 5.78, 7.19],
      [ 1645838650, 7.267194, 5.78, 7.431762],
      [ 1645838648, 7.27, 5.78, 7.45],
      [ 1645838646, 7.31, 5.78, 7.77],
      [ 1645838644, 7.39, 5.79, 8.39],
      [ 1645838642, 7.4, 5.78, 8.69],
      [ 1645838640, 7.4, 5.75, 9.36],
      [ 1645838638, 7.31, 5.72, 9.21],
      [ 1645838636, 7.356486, 5.72, 9.879396],
      [ 1645838634, 7.36, 5.72, 9.93],
      [ 1645838632, 7.23, 5.68, 9.69],
      [ 1645838630, 7.15, 5.65, 10.3],
      [ 1645838628, 7.05, 5.62, 10.37],
      [ 1645838626, 7.02, 5.6, 10.89],
      [ 1645838624, 6.927034, 5.57211, 11.075933],
      [ 1645838622, 6.92, 5.57, 11.09],
      [ 1645838620, 6.67, 5.5, 11.46],
      [ 1645838618, 6.46, 5.45, 11.12],
      [ 1645838616, 6.283383, 5.403522, 10.943383],
      [ 1645838614, 6.27, 5.4, 10.93],
      [ 1645838612, 5.77, 5.29, 9.59],
      [ 1645838610, 5.574784, 5.24352, 9.097313],
      [ 1645838608, 5.56, 5.24, 9.06],
      [ 1645838606, 5.34, 5.2, 8.41],
      [ 1645838604, 4.78, 5.08, 5.89],
      [ 1645838602, 4.74, 5.08, 5.87]
  ]
},
 "min": 4.74,
 "max": 11.46
}
Mon Feb 28 02:54:39 PM EET 2022
1646052879
```

```
   "before": 1645838660,
``

Current timestamp: 1646052879

```sh
# date -d  @1645838660
Sat Feb 26 03:24:20 AM EET 2022
```

So the chart is 2 days old.

**Comment by papazach** [comment]
Thanks for posting this bug report @ktsaou 
We'll be revisiting our error handling strategy for composite /data requests and will address this accordingly.

Concerning the Single Node View _no data_ case, is  it still reproduceable?
Probably for this we should also coordinate with @novykh to see what logic is in place from the FE about error handling.

**Comment by jjtsou** [comment]
@hugovalente-pm We unfortunately cannot connect this 2 issues, because we have different error logs ( `failed data query` and` js promise error in console` )

**Comment by hugovalente-pm** [comment]
thanks for checking @jjtsou let's then keep them as separate issues then

**Comment by ktsaou** [comment]
@novykh this is not fixed.

I have created custom dashboard https://app.netdata.cloud/spaces/tsaousis/rooms/cgroup-rename/dashboards/netdata-cloud-315 having both charts (composite from 1 node and single node).

The issue is still the same.

**Comment by hugovalente-pm** [comment]
capturing highlights from slack discussion:

> yesterday this was tested for a custom dashboard, https://app.netdata.cloud/spaces/tsaousis/rooms/general/dashboards/hjvtst, were we get 5XX if we go way back in the past

![image](https://user-images.githubusercontent.com/82235632/159665779-17b210c8-4e5e-4646-b97c-f0cc5b9033e3.png)

> we can't see the response, this should work if you have charts already loaded on the page you change the time to a timeframe with no charts - we should show the "no data" message

> in the case we reload the page (initial rendering of charts) we would still show 500, since no charts exist when getting the initial charts to render the dashboard. here, maybe, we could the skeleton of the charts and show "no data" message or use the same approach being applied for the search box/filter nodes on [this figma](https://www.figma.com/file/rwF7kUv34rUQV0VzgJLS8b/Search-bar-on-the-table-of-contents?node-id=609%3A17748) would need just a tweak on the copy

last 30 days is ok
![image](https://user-images.githubusercontent.com/82235632/159665859-4e3ab650-27ba-4136-a1f3-615e9905e63d.png)

**Comment by hugovalente-pm** [comment]
> we could the skeleton of the charts and show "no data" message or use the same approach being applied for the search box/filter nodes on [this figma](https://www.figma.com/file/rwF7kUv34rUQV0VzgJLS8b/Search-bar-on-the-table-of-contents?node-id=609%3A17748) would need just a tweak on the copy

based on the update on the daily, I think we can go with not showing the skeleton but the actual chart with the "no data", since as you mentioned @novykh you have the charts list on the definition of the custom dashboard
