### ISSUE TITLE
[BUG] routing issue for /data queries

### ISSUE THREAD

**Issue by TonyPath** [netdata/netdata-cloud#316]
Full context comes from [#2637](https://github.com/netdata/netdata-cloud/issues/308)

Data requests go to the child instead of going to the parent. The issue is related with the way that retention is calculated. 
More info can be found [here](https://github.com/netdata/netdata-cloud/issues/308#issuecomment-1054160357)

Actual implementation detailed on Modify /data request node instance routing logic netdata/cloud-backend#37

**Comment by hugovalente-pm** [comment]
@TonyPath one clarification, this routing fix consists on what?
it isn't doing this Modify /data request node instance routing logic netdata/cloud-backend#37, right?

**Comment by TonyPath** [comment]
> @TonyPath one clarification, this routing fix consists on what? it isn't doing this Modify /data request node instance routing logic [netdata/cloud-backend#37](https://github.com/netdata/cloud-backend/issues/37), right?

@hugovalente-pm actually it does, we can consider this duplicate

**Comment by hugovalente-pm** [comment]
Closing since this was released to PROD

**Comment by hugovalente-pm** [comment]
@TonyPath just a check, the work here overrode this [be][cloud-charts-service] Route ADC data requests taking into account chart availability netdata/product#22717?

**Comment by TonyPath** [comment]
> @TonyPath just a check, the work here overrode this [be][cloud-charts-service] Route ADC data requests taking into account chart availability [netdata/product#2717](https://github.com/netdata/product/issues/2717)?

@hugovalente-pm  I would say that the work here improves/extends the https://github.com/netdata/product/issues/2717
