### ISSUE TITLE
[BUG] Agent claimed with capital uuid as agent claim id never becomes reachable

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#318]
Steps to reproduce:

Try and claim an agent in MacOS and add **-id=$(uuidgen)** or supply a valid uuid for the id field but in capital. e.g Id: A9ADFE67-334F-490B-AB84-5131F02458FB

Agent gets claimed but never becomes reachable as expected

**Comment by dimko** [comment]
Related to https://github.com/netdata/netdata/issues/12421#event-6250174806

**Comment by dimko** [comment]
Is handling of such cases required from cloud backend side as well to avoid such breaks in the future? @netdata/cloud-be @underhood @ilyam8

**Comment by vkuznecovas** [comment]
> Is handling of such cases also required from cloud backend side as well to avoid such breaks in the future? 

With the agent changes users should stop experiencing any issues, however we still want to fix this on the cloud backend side. I've opened up this for the full list of changes that are needed: https://github.com/netdata/cloud-backend/issues/73
