### ISSUE TITLE
[BUG] Chart names are including the room ID

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#319]
**Describe the bug**	
If you have a single node chart on a custom dashboard the chart name on the title is including the room ID

**To Reproduce**	

**Expected behavior**	
The title shouldn't include the room ID, should be the same as the on show on the Single Node view
![image](https://user-images.githubusercontent.com/82235632/156345270-0294a798-0f81-49a2-94d3-3f450e4d20eb.png)

**Screenshots**	
![image](https://user-images.githubusercontent.com/82235632/156345170-143d9c98-9fa4-4080-912a-cde19a04647b.png)

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	

**Desktop (please complete the following information):**	

**Additional context**

**Comment by ktsaou** [comment]
@hugovalente-pm how can i reproduce this?

**Comment by ktsaou** [comment]
Can you replicate it by creating a new custom dashboard?
Probably is the way we were creating custom dashboards at some point...

**Comment by hugovalente-pm** [comment]
@ktsaou , I've update my comment.
@jjtsou mentioned that he identified where the bug is and will release a quick fix

**Comment by hugovalente-pm** [comment]
@novykh @jjtsou I know this was released today and it solved the room id issue, but I see that for the chart that came from the Single Node page it doesn't show any name. If you go to Single Node view, for the same chart, you have it there. 

is there any limitation when we are on the custom dashboard?

**Custom dashboard**
![image.png](https://images.zenhubusercontent.com/60b4ebb03f4163193ec31819/eb1ad0fb-980e-4efe-8193-271a2d26fbe8)

**Single node view**
![image.png](https://images.zenhubusercontent.com/60b4ebb03f4163193ec31819/ffa752c9-5b2e-4282-923d-9075affc08df)

**Comment by novykh** [comment]
I guess we are not saving the chart name along with the dashboard, but we do save the context, hence the composite chart has something to show. We can add it, but the old ones won't have it.

**Comment by hugovalente-pm** [comment]
It is ok, let's add for the new ones

**Comment by hugovalente-pm** [comment]
@novykh just to confirm you'll open a task to do that on custom dashboard?

**Comment by novykh** [comment]
This ticket is already opened for @jjtsou https://github.com/netdata/cloud-frontend/projects/16#card-78473698

**Comment by jjtsou** [comment]
Seems that after our fix for the` room Id` issue, the issue regarding ` charts from the Single Node page  doesn't show any name` has been fixed too. Keep in mind, the fix regarding ` charts from the Single Node page  doesn't show any name` is applied for charts added in a custom dashboard after our fix reached production.
