### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by andrezaycev** [netdata/netdata-cloud#32]
**Describe the bug**	
I Have phantom Alarm in Netdata.Cloud. Alarm is absent on web:19999 
Reinstall agent not help. I think it is artifact on cloud side. Have not idea how clean it
Ready to help with additional info

**Screenshots**	
![image](https://user-images.githubusercontent.com/9984761/103093973-60738700-463f-11eb-8df2-5c738d9dbd8e.png)
![image](https://user-images.githubusercontent.com/9984761/103093992-73865700-463f-11eb-8cb7-5aad55c7f4a1.png)

**Comment by manos-saratsis** [comment]
https://github.com/netdata/netdata-cloud/issues/4
