### ISSUE TITLE
[BUG] The chart on the single alarm modal, is not the same as the chart on the dashboard, but it is fixed after the user sees the real dashboard chart

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#324]
On the alarm modal:

![image](https://user-images.githubusercontent.com/2662304/156825498-f598cb91-1310-4328-a737-dd358d2bf386.png)

On the dashboard:

![image](https://user-images.githubusercontent.com/2662304/156825395-54de7eab-3c3c-4574-84df-b96bd1b68259.png)

If I open the dashboard chart and then attempt to see the alert modal again, I see the right chart:

![image](https://user-images.githubusercontent.com/2662304/156825595-5050ec5c-a1c7-4a51-918a-28fdbd16491e.png)

So, the second time probably something is cached and it works properly. But the first time you see the alarm modal after a total refresh, the chart is wrong.

**Comment by cronlabspl** [comment]
@ktsaou You understand nothing...........

**Comment by ktsaou** [comment]
> @ktsaou You understand nothing...........

Probably you are right :)
But what do you mean exactly? About what?

**Comment by dimko** [comment]
@jacekkolasa does your fix for the new alert's page, fixes this one as well?

**Comment by jacekkolasa** [comment]
@dimko yes, that's exactly the same bug you discovered before, and it is fixed now
Closing then
