### ISSUE TITLE
[BUG]: agent and cloud have out of sync alarm log

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#330]
In case https://github.com/netdata/netdata-cloud/issues/323 we had an agent with a disk full situation.

Ticket https://github.com/netdata/netdata/issues/12324 opened to gracefully handle disk full / no disk situation at the agent.

The following issue remains:

The agent and the cloud didn't manage to re-sync properly after the disk full situation.
Currently all alerts are synced between agent and cloud, but for several hours they were not.

So, despite the fact that agent crashed (didn't shutdown properly) and didn't have all the data in sqlite, once it was restarted, the agent and the cloud were out of sync and cloud managed to get in sync after several hours (probably due to the snapshot).

**Comment by cronlabspl** [comment]
> no disk

What? How this could be even possible? Where would alarm be stored than?

**Comment by ktsaou** [comment]
> What? How this could be even possible? Where would alarm be stored than?

When netdata restarts, it should somehow figure this out (that it crashed and couldn't write to disk) and re-sync the alarm log with the cloud.

For example, today when netdata starts it creates a file (while the disk is there). It removes that file when it gracefully stops.
So, when it starts, if that file is there, netdata crashed. We should use this mechanism to trigger a proper re-sync with the cloud.

**Comment by ktsaou** [comment]
> @ktsaou Unix'es have `LOCKFILES`...... ND could be using these as well.....

Sure and we use lockfiles when they are useful.

However, a lockfile is not locked after the process holding the lock exits (crash?) or after the system reboots (no disk?).

So, locking the lockfile after such conditions will allow the lock to happen and we will not detect the issue. A simple file existance check is better in these cases.

**Comment by dimko** [comment]
@sashwathn @car12o @MrZammler just a follow up on this one. What are the actions required for this to close on agent and cloud side?

**Comment by car12o** [comment]
@dimko is there a way to reproduce? otherwise, it will be hard to investigate as this could happen for many reasons.
- setup (two alarm stream flows reporting different statuses)
- events being lost on the cloud
- events not being pushed to the cloud

**Comment by dimko** [comment]
@car12o Unfortunately,  I don't know of a flow to consistently reproduce this. The issue is too generic tbh. If we notice this again we should enrich this issue with more info.

The question is (both for cloud and agent), is there any pending or ongoing work to do a full sync in case we lose messages and the agent is not in shape to send a snapshot ?

**Comment by car12o** [comment]
@dimko agree, I think that's the only option we have :smile: 

AFAIK there's nothing ... currently, snapshots are the only way to re-sync alarms between agent & cloud.

**Comment by cakrit** [comment]
@stelfrag can you please help reproduce the condition? Could be via defining a mountpoint with very low storage capacity and installing netdata there, or using a usb drive for storage and unplugging it, or some more clever way you can think of. 

I also expect that we have several agents on the field that have fallen into the same predicament, all we'd need to do is monitor logs for failed synchronization I suppose.

**Comment by stelfrag** [comment]
> @stelfrag can you please help reproduce the condition? Could be via defining a mountpoint with very low storage capacity and installing netdata there, or using a usb drive for storage and unplugging it, or some more clever way you can think of.
> 
> I also expect that we have several agents on the field that have fallen into the same predicament, all we'd need to do is monitor logs for failed synchronization I suppose.

will do!

**Comment by sashwathn** [comment]
@stelfrag and @MrZammler : Please let us know when you have more information on this issue.

**Comment by sashwathn** [comment]
@stelfrag and @MrZammler : Any updates on this issue?

**Comment by hugovalente-pm** [comment]
this is related to this https://github.com/netdata/netdata-cloud/issues/330

**Comment by hugovalente-pm** [comment]
the new alert protocol has been released on the Agent, so this should not occur any longer
