### ISSUE TITLE
[BUG] 'internal submit' logo in app dimension need updated

### ISSUE THREAD

**Issue by jlbriston** [netdata/netdata-cloud#333]
**Describe the bug**	
The logo inside the app is incorrect dimensions. Accurate dimensions can be found here: https://www.figma.com/file/CvDzY945KJAzjNM1D90vbx/%E2%9A%99%EF%B8%8FPress-Kit-(WIP)?node-id=0%3A1

**To Reproduce**	

**Expected behavior**	
For extreme small scenarios we use a container of 24x24 containing the isotype. That container can be downsized to a minium size of 16x16

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	

**Desktop (please complete the following information):**	

**Additional context**

**Comment by cakrit** [comment]
This is what 24x24 looks like, which is much worse than the current size. We should leave it as is. 

<img width="40" alt="image" src="https://user-images.githubusercontent.com/43294513/171447285-3410bc0e-7dbd-4e4c-ae4b-1bdfe9f81775.png">

**Comment by cakrit** [comment]
These two show the difference better. 

Current:
<img width="252" alt="image" src="https://user-images.githubusercontent.com/43294513/171447614-06918693-707f-4cbd-ab4e-6d1b9db5aad2.png">

Proposed:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/43294513/171447543-73300284-bffc-477f-8b8e-88146f220f25.png">

The alignment with the other elements would be worse too.
