### ISSUE TITLE
[BUG] Virtualisation/Containerisation technology wrongly shown on Nodes table

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#34]
**Describe the bug**	
On Cloud'S Nodes table there is the wrong value ("Bare Metal") for an LXC container.
 
**To Reproduce**	
See https://community.netdata.cloud/t/best-way-to-setup-netdata-in-a-proxmox-host-with-some-lxc-containers/81

**Expected behavior**	
When a netdata agent it is installed on an LXC It should say LXC, not bare metal. 

**Screenshots**	
See https://community.netdata.cloud/t/best-way-to-setup-netdata-in-a-proxmox-host-with-some-lxc-containers/81

**Comment by cakrit** [comment]
This isn't a cloud issue. I'll comment on the community thread.
