### ISSUE TITLE
[be][cloud-spaceroom-service] cloud-spaceroom-service review

### ISSUE THREAD

**Issue by ravilushqa** [netdata/netdata-cloud#343]
As a part of stability improvement need to solve desynchronization problems in cloud-spaceroom-service.
Also this issue is part of the big one
https://github.com/netdata/product/issues/2051

Here is a plan for it:

## Needed changes

* use Pulsar retrier (it will decrease out-of-sync data, and give us some extra info about problem)
  * this also mean to monitor the logs in the following weeks to detect any `Critical consumer error`s since some of these could be bugs
* Review logic of producers and consumers
   * We should make sure that producers are idempotent otherwise we cannot trust the data in the broker.
   * Consumers should also be idempotent because the delivery semantics we try to guarantee in our cluster are at-least-once.
 * Move to PostgreSQL from cockroachdb
 * Remove Materialized views (mongo) usage

**Comment by vkuznecovas** [comment]
Released to prod.
