### ISSUE TITLE
[BUG] Multi-selection chart legend issue on Linux

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#344]
**Describe the bug**	

_This seems a specific issue for Linux OS_
On a chart, we chose 2 dimensions on the legend to show by clicking the Ctrl or Alt key, if a 3rd dimension is needed if I keep the finger pressing Ctrl or Alt this doesn't work, only the 3rd dimension is selected

If I release/re-push Ctrl or Alt between every click it works.

**To Reproduce**	
1. On a Linux OS go to a chart with at least 3 dimensions
2. Press and keep pressed Ctrl or Alt key and click 2 dimensions on the legend - all ok, the 2 are filtered on the chart
3. Without releasing Ctrl or Alt key click on a 3rd dimension
4. Previous 2 dimensions are "lost" and only the 3rd is selected

**Expected behavior**	
While pressing the Ctrl + Alt key we should keep "adding" to the list of already selected dimensions

**Screenshots**	

Example on firefox for the issue:
![image](https://user-images.githubusercontent.com/82235632/158222734-13af1939-f18e-43d2-8a6c-fd9a8ebfa9ff.png)

Example on firefox with release/re-push Ctrl + Alt between every click it works:
![image](https://user-images.githubusercontent.com/82235632/158222844-188b6a60-7452-401b-9877-54e05b487502.png)

**Error logs**	
N/A

**Desktop (please complete the following information):**	
 - OS: Ubuntu 20.04.3 LTS
 - Browser: Firefox
 - Version: 97.0 (64-bit)	

**Additional context**

**Comment by hugovalente-pm** [comment]
@novykh just to check if you did something that could have fixed this

**Comment by novykh** [comment]
yep
