### ISSUE TITLE
[BUG] overview dashboard with 2 versions of web_log plugin is confusing

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#347]
When on a single war room, there are some nodes with `web_log` from `python.d.plugin` and `web_log` from `go.d.plugin` the charts do not always match and the result is confusing.

![image](https://user-images.githubusercontent.com/2662304/158556686-aab1d510-a1bb-4137-adb7-df8b413d7131.png)

---

## The problem

`web_log` plugin exists in 2 versions. The old one written in python and a new one written in go.

When we re-write a plugin, we should make the most to have the same `chart_ids`, the same `dimensions`, the same `contexts` and the same `families`.

If this cannot be done for whatever reason (e.g. we need to improve the charts), then the cloud should create 2 separate sections in the menu:

* `web log (python.d.plugin)`
* `web log (go.d.plugin)`

And have separate sections for them.

---

The way they are merged now, it makes the dashboard very confusing.

**Comment by ktsaou** [comment]
cc: @ilyam8

**Comment by cakrit** [comment]
Is this for the cloud or for the agent? 
The suggestions are very open ended. What's the course of action?

**Comment by MrZammler** [comment]
Is this still valid since https://github.com/netdata/netdata/pull/12796 was merged?

**Comment by hugovalente-pm** [comment]
thanks for sharing this @MrZammler , with this release this will only happen for older agent versions.

the topic of older agent versions was discussed and it was agreed that supporting legacy and current versions can be a huge effort, we should ask our users to update their agent's version to the latest. for that we can leverage a UI component (that we already have) to flag that to get the best experience with Cloud users need to update their agents

<image src="https://user-images.githubusercontent.com/82235632/172131891-107a1c54-8c98-482f-895d-ef809be4835e.png" width="50%" height="50%"/>

@ktsaou @cakrit are you ok with this?

**Comment by cakrit** [comment]
I'm fine with this. Closing and it can be reopened if @ktsaou wants a different solution.
