### ISSUE TITLE
[BUG] Overview is not grouping all cgroups info

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata-cloud#348]
**Describe the bug**	
Right now when we access overview and we have a docker container on hosts with `CGROUP V.1` the overview is not grouping everything inside `cgroup`

It is also possible that this happens with `CGROUP v2`

**To Reproduce**	
1. Get latest netdata on hosts using `cgroup v1`
2. Enable integration between eBPF and [cgroup](https://learn.netdata.cloud/docs/agent/collectors/ebpf.plugin#integration-with-cgroupsplugin).
3. Start a docker container
4. Start netdata

**Expected behavior**	
When I access overview, I expect all charts related to cgroup in one unique submenu.

**Screenshots**	
![Screenshot_20220316_165657](https://user-images.githubusercontent.com/49162938/158645816-478ec363-6a06-476c-9417-1a6bc0370f6f.png)
![Screenshot_20220316_165648](https://user-images.githubusercontent.com/49162938/158645826-4885ccaa-df0c-472a-9334-0ca50043de84.png)

**Desktop (please complete the following information):**	
 - OS: Slackware Linux	
 - Browser: Google Chrome	
 - Version Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by cakrit** [comment]
@hugovalente-pm can you have a sit down with @thiagoftsm to investigate why this happens? It may be very relevant to the work currently being done to properly display and filter different instances based on family / instance.

**Comment by hugovalente-pm** [comment]
sure @cakrit , trying to follow-up on this today

**Comment by thiagoftsm** [comment]
Hello @cakrit and @hugovalente-pm ,

I tried to recreate the issue today, and I am observing that right now on my environment everything is correctly grouped, the charts that I see on `Overview` are the same I have locally for the host.

Best regards!
