### ISSUE TITLE
[BUG] Composite charts do not list all dimensions when the underlying charts have different dimensions

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#349]
This is a composite chart, from 2 nodes:

![image](https://user-images.githubusercontent.com/2662304/158647099-941cc425-8bdd-450b-b6ae-da13302bc7f7.png)

Node `box` is like this:

![image](https://user-images.githubusercontent.com/2662304/158647240-d345172c-74cc-45a8-88b0-b1cf458ebd84.png)

Node `freebsd` is like this:

![image](https://user-images.githubusercontent.com/2662304/158647347-763349a3-0344-4da2-a71f-05e13052a697.png)

So, the composite chart should mix the dimensions from both charts. So instead of having 7 dimensions listed, for the drop down selection it seems to use only the 4 `freebsd` ones. I guess this is random. It depends on which of the 2 charts it fetches first.

**Comment by ktsaou** [comment]
Moment later, it preferred the `box` ones:

![image](https://user-images.githubusercontent.com/2662304/158648350-887302b9-7353-4d9d-a826-60b08362f0d6.png)

**Comment by TonyPath** [comment]
The issue has been initially tackled but rolled back, more info at https://github.com/netdata/cloud-backend/issues/128

**Comment by TonyPath** [comment]
As first step I would suggest to move forward with the cache mechanism we are planning to introduce for the routing instance, expecting significant back pressure relief in DB. Then evaluate the gain performance and  re-apply the [fix](https://github.com/netdata/cloud-charts-service/pull/201) which has been rolled back.

cc: @hugovalente-pm @papazach @amalkov @ralphm @ktsaou

**Comment by hugovalente-pm** [comment]
@TonyPath afaik the caching mechanism has been released, probably @papazach can confirm for sure, so we could try to rollback in the fix and see how it performs.

**Comment by TonyPath** [comment]
> @TonyPath afaik the caching mechanism has been released, probably @papazach can confirm for sure, so we could try to rollback in the fix and see how it performs.

Yes @hugovalente-pm the caching is already in place, my bad. So @papazach wdyt for releasing again the fix you had made? would it make sense?

**Comment by hugovalente-pm** [comment]
This is parked since the work on https://github.com/netdata/cloud-backend/issues/142 will help delivering this

**Comment by hugovalente-pm** [comment]
@TonyPath @novykh  with the work on https://github.com/netdata/cloud-backend/issues/142 completed from BE perspective, is there anything needed to complete this one? not sure if anything changed on BE that we need to accommodate on FE

**Comment by cakrit** [comment]
There are issues with https://github.com/netdata/cloud-backend/issues/142, waiting for an update from @papazach

**Comment by hugovalente-pm** [comment]
As per discussed on the daily, this is fixed with the release of https://github.com/netdata/cloud-backend/issues/142 (this one is not closed since there is still work to do on k8s map to fully decommission the chart-details call)
