### ISSUE TITLE
[BUG] Undismissable empty alert, only on Netdata Cloud

### ISSUE THREAD

**Issue by TheCatLady** [netdata/netdata-cloud#35]
**Describe the bug**
I have an undismissable empty alert on my Netdata Cloud dashboard.  I believe it is from a collector I disabled (`powersupply_capacity.battery`).  It does not appear on the node's local dashboard.

**To Reproduce**	
-Set up a new Netdata agent
-Immediately disable a collector that will always trigger an alert
-Claim node in Netdata Cloud
-View Netdata Cloud dashboard

**Expected behavior**	
No (empty) alerts for disabled collectors

**Screenshots**	
![image](https://user-images.githubusercontent.com/52870424/104211729-6f5d8600-5402-11eb-9dae-ba2d4f42d9b1.png)

**Comment by manos-saratsis** [comment]
This is related to the agent team as the alarm should not be triggered in the first place considering that the collector is disabled.
@lvrach this is related to https://github.com/netdata/netdata-cloud/issues/4 so please consider this use case

**Comment by mfundul** [comment]
Does this involve streaming? If it is a child that disables the collector then the parent still will produce notifications for this chart. Maybe related to [this](https://github.com/netdata/netdata/issues/8751#issuecomment-615947033)?

**Comment by lvrach** [comment]
> @lvrach this is related to #4 so please consider this use case
Yes, it could be the case. If that is the case, an agent restart should fix the problem.

I am keen to believe that something else is going on here, maybe @mfundul suggestion.

We would try to reproduce it.

**Comment by stelfrag** [comment]
Thank you @TheCatLady

I have reproduced this and will plan a fix

**Comment by stelfrag** [comment]
PR that fixes this issue https://github.com/netdata/netdata/pull/10533

**Comment by cakrit** [comment]
The PR is merged so closing this one.
