### ISSUE TITLE
[BUG] Available memory chart does not show on Nodes tab for BSD

### ISSUE THREAD

**Issue by MikeJakubik** [netdata/netdata-cloud#352]
Hi,

As the subject states these values are not shown in Node view in the Cloud WebUI, however, the agent itself knows how much RAM is used and the OS type. See attached screenshots for more info.

Thanks.
![Screenshot 2022-03-16 165218](https://user-images.githubusercontent.com/73555475/158689340-f886e25c-0d7c-4652-b5ab-92b92a9d79ac.png)
![Screenshot 2022-03-16 165308](https://user-images.githubusercontent.com/73555475/158689343-e7431672-6289-40c7-b964-94b1b1a5812c.png)

**Comment by dionysis-netdata** [comment]
@burbuli8ra is this something that you have within your reach with the work you are doing?

basically the available mem chart on the nodes tab isn't showing.

**Comment by MikeJakubik** [comment]
The code is actually there in https://github.com/netdata/netdata/blob/master/daemon/system-info.sh on line 254 "CPU_MODEL="$(sysctl -n hw.model)"" guess it's just a matter of getting the cloud app to display this.

**Comment by cakrit** [comment]
I don't know what has changed since Mar 29th but I see both `system.ram` and the more useful `ram.available`

<img width="986" alt="image" src="https://user-images.githubusercontent.com/43294513/172217898-d02770d9-4bde-4962-bac3-ad0b7a95ced0.png">

"The difference between free memory vs. available memory in Linux is, free memory is not in use and sits there doing nothing. While available memory is used memory that includes but is not limited to caches and buffers, that can be freed without the performance penalty of using swap space" as mentioned [here](https://haydenjames.io/free-vs-available-memory-in-linux/#:~:text=The%20difference%20between%20free%20memory,penalty%20of%20using%20swap%20space.)

**Comment by cakrit** [comment]
@MikeJakubik please check if you're ok now.
As for the CPU type, I saw that we've made a lot of improvements since v1.33 to system-info.sh, so that should also be resolved.

**Comment by MikeJakubik** [comment]
Currently, the RAM metrics are not displayed at all, the space is blank. If I however add system.ram as a metric, it does show
![Screenshot 2022-06-06 151601](https://user-images.githubusercontent.com/73555475/172231549-bf72483a-f3ca-4777-94ba-f75469abd15f.png)
.

**Comment by cakrit** [comment]
The key seems to be `FreeBSD` here. Changing the title and we'll have someone check.

**Comment by cakrit** [comment]
Just to explain the previous comment a bit more, it's related to https://github.com/netdata/netdata-cloud/issues/351 and how for the same context we may have different dimensions based on the OS.

**Comment by hugovalente-pm** [comment]
>  the RAM metrics are not displayed at all, the space is blank. If I however add system.ram as a metric, it does show

@MikeJakubik to pick up on this, does the Single Node tab for the node in FreeBSD show data on `mem.available` - Available RAM for applications chart? (this is under Memory > system)

the payload/options we send on the `api/v2/nodes/[node-id]/data` request on the Nodes tab is this which I assume for your case is not returning results:
```
v2=&chart=mem.available&format=array&options=abs%7Cjsonwrap%7Cnonzero%7Cflip%7Cms&_=1654811681455&points=-9&group=average&gtime=0&after=-900&with_metadata=true
```

@MrZammler could you check on the Agent side if we have an issue here?

**Comment by MikeJakubik** [comment]
> > the RAM metrics are not displayed at all, the space is blank. If I however add system.ram as a metric, it does show
> 
> @MikeJakubik to pick up on this, does the Single Node tab for the node in FreeBSD show data on `mem.available` - Available RAM for applications chart? (this is under Memory > system)
> 

There is no metric named mem.available, I only see mem.commited and mem.pgfaults, both of which display info. There is also system.ram, which works as well.

**Comment by hugovalente-pm** [comment]
@MikeJakubik ok, so you are saying that you don't get this chart on the Single Node tab for the node in FreeBSD?

![image](https://user-images.githubusercontent.com/82235632/173390487-092999ff-110a-4845-ad79-636e42aca61c.png)

**Comment by MikeJakubik** [comment]
> @MikeJakubik ok, so you are saying that you don't get this chart on the Single Node tab for the node in FreeBSD?
> 

That is correct. Laos if I setup a custom dashboard the only mem. metrics available are committed and pgfaults.

**Comment by MrZammler** [comment]
@MikeJakubik Can you please check with an updated agent (either from next couple nightlies or next stable), the mem.available chart should be available for FreeBSD.

**Comment by MikeJakubik** [comment]
> @MikeJakubik Can you please check with an updated agent (either from next couple nightlies or next stable), the mem.available chart should be available for FreeBSD.

Hi, yes it is indeed available now. Although the metric itself is confusing to me, do you know how it is calculated?

![Screenshot 2022-06-16 160337](https://user-images.githubusercontent.com/73555475/174154666-0022f719-205b-4953-a0c4-c44e9913ead0.png)



```
[root@staging ~]# top
last pid: 92652;  load averages:  0.38,  1.31,  1.15                                                                                                             up 2+00:55:10  16:01:52
89 processes:  1 running, 87 sleeping, 1 zombie
CPU:  0.1% user,  0.0% nice,  0.1% system,  0.1% interrupt, 99.7% idle
Mem: 433M Active, 1706M Inact, 12G Wired, 104K Buf, 111G Free
ARC: 7822M Total, 4460M MFU, 1400M MRU, 160K Anon, 83M Header, 1863M Other
     5037M Compressed, 12G Uncompressed, 2.37:1 Ratio
Swap: 4096M Total, 4096M Free
```

**Comment by hugovalente-pm** [comment]
@MrZammler as discussed I've opened a new bug as a follow-up to @MikeJakubik question/report

@MikeJakubik can you please check this https://github.com/netdata/netdata/issues/13172 and add missing information there?
* Installation method (I put kickstart, please review)
* System info
* Netdata build info
