### ISSUE TITLE
[BUG] 500 error typo + auto refresh?

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#353]
**Describe the bug**	
The 500 error page needs a small language fix

"these error" --> "this error" OR "these errors"

**Screenshots**	
![image](https://user-images.githubusercontent.com/24860547/159079199-79284b11-29e2-459d-9648-82a08f885f13.png)

**Additional context**	
When such errors occur, and I've seen them on staging intermittently, a refresh usually fixes the problem. So why don't we do an auto refresh after X seconds so that users who aren't actively using Netdata at the time of error don't even need to land here. An auto refresh may have fixed the issue when the user returns and sees a working Netdata Cloud.

**Comment by hugovalente-pm** [comment]
thanks for raising this @shyamvalsan , we have some tickets in discussion that would sort most of the 5XX we are having.
I think we discussed the auto-refresh on the original ticket (netdata/product#2443) and the idea was not to constantly trigger requests that would fail and we would need to have some condition to stop trying

probably @novykh can also share his point

**Comment by jjtsou** [comment]
Typo fixed in this PR https://github.com/netdata/cloud-frontend/pull/3130 ,
[here](https://github.com/netdata/cloud-frontend/pull/3130/files#diff-5c486e0e3889075b4361004fbefe0806d1a7eaee8a9ee73c76c8177a490168b0)
