### ISSUE TITLE
[BUG] Typo on the 500 page - mean time should be one word (meantime)

### ISSUE THREAD

**Issue by Razique** [netdata/netdata-cloud#355]
**Describe the bug**	
The 500 page uses "mean time" instead of "meantime". See attached.
<img width="711" alt="Screenshot 2022-03-20 at 15 36 31" src="https://user-images.githubusercontent.com/1027278/159188988-7bab1c51-ac41-4784-b453-cf9d2f09e81d.png">

**To Reproduce**	

**Expected behavior**	

**Screenshots**	

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	

**Desktop (please complete the following information):**	

**Additional context**

**Comment by jjtsou** [comment]
Fixed in this PR https://github.com/netdata/cloud-frontend/pull/3130 ,
[here](https://github.com/netdata/cloud-frontend/pull/3130/files#diff-5c486e0e3889075b4361004fbefe0806d1a7eaee8a9ee73c76c8177a490168b0)
