### ISSUE TITLE
[BUG] dashboard with data from unreachable node, missing infos

### ISSUE THREAD

**Issue by dotob** [netdata/netdata-cloud#356]
**Describe the bug**	
In a dashboard where a chart of an unreachable node is shown one cannot know what metrics the charts was.

**To Reproduce**	
- create dashboard
- add chart
- node is unreachable
- chart show only node name und unreachable

**Expected behavior**	
show what metrics the chart was. in my case a had to reinstall the agent and reclaim the node and now i dont know which charts i once had.

**Screenshots**	
![CleanShot 2022-03-21 at 12 13 22](https://user-images.githubusercontent.com/16528/159250760-fcf4c90f-247d-4eb4-9bf9-77c6a2f9fdda.png)

**Error logs**	
-

**Desktop (please complete the following information):**	
 - OS: macos maverick
 - Browser chrome
 - Version 99

**Additional context**	
-

**Comment by hugovalente-pm** [comment]
thanks for opening this bug and bringing this to our attention.
we will find a away to improve the user experience here

**Comment by novykh** [comment]
Fixed on prod.
