### ISSUE TITLE
[BUG] anomaly advisor ml_info failing

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#357]
![image](https://user-images.githubusercontent.com/2662304/159263268-8f5f07f5-c3b3-4f4c-8507-ee2ffe6a5623.png)

![image](https://user-images.githubusercontent.com/2662304/159263466-bb2b5c74-e195-4390-b2a1-069b070c1c33.png)

3 issues:

1. ml_info are being cancelled. Why?
2. ml_info is failing on the backend. Why?
3. The status on the sidebar say "Loading..." while it has actually failed.

**Comment by juacker** [comment]
Issue nº2 (ml_info failing on the backend) has been fixed by https://github.com/netdata/cloud-charts-service/pull/184

**Comment by libekonst** [comment]
Issue 1 is now fixed.

Issue 3 is still open, we don't do any error handling there. Let's prioritize it and I can start it.

**Comment by shyamvalsan** [comment]
@libekonst So Issues 1 & 2 are fixed. 

Will Issue 3 even occur anymore? If the objective is purely error handling, then instead of "Loading..." we could replace with "Error" and tool tip can ask user to retry or reload.

**Comment by libekonst** [comment]
**no. 3** shouldn't occur anymore, we now show the error page that has the reload prompt when the initial data fail to load
