### ISSUE TITLE
Node - Cloud connectivity events feed

### ISSUE THREAD

**Issue by ghost** [netdata/netdata-cloud#360]
Before going into design and think about where the events will be display etc., we should capture all Cloud-Agent connectivity events that are useful for troubleshooting. 

The goal of this story is to let Cloud users understand what's is happening with nodes e.g. when they go offline or some other connection issues.

### Use case 1 - Node cannot connect be claimed (cannot connect 1st time)
A node may no be able to be claimed in Cloud due to various issues. These include authentication or network issues. These result in different error messages on Agent.

The feed may look like:
```
Unclaimed NodeA - node cannot be claimed, network error xxxx - 10:00 10 Mar 2022
Unclaimed NodeA - node cannot be claimed, unauthorised - 11:00 10 Mar 2022
```

### Use case 2 - Node claimed and then disconnected before connecting again 
After a node has been claimed in the Cloud, it may go offline for a number of reasons. 

The feed may look like:
```
NodeB - claimed - 10:00 10 Mar 2022
NodeB - connected - 10:00 10 Mar 2022
NodeB - disconnected - 11:00 10 Mar 2022
```

At the time of disconnection, it's not clear for Cloud, the reason the node disconnected. In order to get more clarity, the node needs to reconnect and fill the feed gaps.

E.g:
```
NodeB - claimed - 07:00 10 Mar 2022
NodeB - connected - 07:00 10 Mar 2022
NodeB - disconnected, connection dropped - 08:00 10 Mar 2022
NodeB - retry connection attempt failed, connection dropped - 9:00 10 Mar 2022
NodeB - retry connection attempt failed, connection dropped - 10:00 10 Mar 2022
NodeB - agent shutdown- 11:00 10 Mar 2022
NodeB - agent connected- 12:00 10 Mar 2022
```

Finally to add some more example of events

```
NodeC - claimed - 07:00 10 Mar 2022
NodeC - connected - 07:00 10 Mar 2022
NodeA - disconnected, corrupted data error 1000- 08:00 10 Mar 2022
NodeA - agent connected- 12:00 10 Mar 2022
```

All feed entries follow the convection of Node hostname - Event - Timestamp

**Comment by dionysis-netdata** [comment]
Sharing for review and feedback
@ktsaou , @underhood , @cpipilas , @amalkov

**Comment by underhood** [comment]
> All feed entries follow the convection of Node hostname - Event - Timestamp

we are talking about Agents (with ACLK) here, also it should be much safer to include `claim_id` as hostname can be same across agent installs

**Comment by underhood** [comment]
Additionally I would like to stress the initial source for connect and disconnect events must be cloud as agent might not reconnect and then we will be missing disconnect event (agent could never send it). So I think of it as cloud adds those events in and agent provides extra details if it can (upon next connection).

**Comment by dionysis-netdata** [comment]
> > All feed entries follow the convection of Node hostname - Event - Timestamp
> 
> we are talking about Agents (with ACLK) here.
> 
> Also it should be much safer to include `claim_id` as hostname can be same across agent installs. Additionally I would prefer not to define it as a strict string (as in log line) but as an structure with fields. Whoever is consumer can then display this date as it sees fit (instead of just lines of text as in logfile)

thanks @underhood. Yeye, I just put everything in a line, but as you said some data will be filled after the node reconnects so technically it makes sense that we use something other than log lines.

`claim_id` yes, plus other info we will need potentially. We could display both `hostname` and `claim_id`. Of course it will also depend on where we present the info. One option (like newrelic) is to display this on the context of individual nodes (instead of a central feed for all events, but we can discuss on that next)

**Comment by underhood** [comment]
Also big question is do we do a fallback HTTPS method for sending this information as was suggested in the past? IMHO this would be big overhead for small gain (as set of people whose agents suddenly cannot connect over MQTT/WSS but can connect with HTTPS will be small)

**Comment by amalkov** [comment]
I would suggest thinking about the display a bit later, agree with @underhood we would need to deal with an object.

The list of events we would like to capture in the feed is listed in the [Feed events](https://docs.google.com/spreadsheets/d/1p1Fd-U68dNccXA0_TDzxB-eSwFXhwqSJE5FqPLfKsN4/edit#gid=0) excel file (column `Node`).

**Comment by underhood** [comment]
@amalkov the Agent Unclaim event might be problematic as there is no such thing as unclaiming. You can claim agent again (basically giving it new identity) but you don't know if the previous "agent" will ever come back

**Comment by dionysis-netdata** [comment]
![Screenshot from 2022-05-16 12-09-12](https://user-images.githubusercontent.com/95340881/168575277-3b82d80c-264a-482e-95c7-321367c1ffb6.png)

events directory provided by @underhood

**Comment by vkuznecovas** [comment]
An MVP of a backend service for events(both ACLK based and Cloud-based) has been part of what we were prototyping last week.

Source available here https://github.com/netdata/cloud-feed-service but needs adjusting as we've approached it with a hackathon mentality.

**Comment by hugovalente-pm** [comment]
this is done
