### ISSUE TITLE
[BUG] Ask the community button link is broken

### ISSUE THREAD

**Issue by lupimiguel** [netdata/netdata-cloud#362]
**Describe the bug**	
After a change in the Forums categories, the button **Ask the community** in the "?" (help) section became outdated, therefore it's now sending users to a broken destination.

**Expected behavior**	
This button should now point to https://community.netdata.cloud/c/help/	

**Screenshots**		
![ask-the-community](https://user-images.githubusercontent.com/56279741/159522533-55abd064-9e09-4566-a3e0-dc503f3080c1.png)

Cheers

**Comment by cakrit** [comment]
We're defining something else in https://github.com/netdata/product/issues/2888
