### ISSUE TITLE
[BUG] data requests timeout at 3 seconds

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#364]
https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/nodes/1b48aa88-55c6-4a1a-9fc7-6e72e77abbd6

single node dashboard:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/2662304/159648703-5061c3fa-36bb-4e9f-9f91-cf30e7ac8479.png">

Request:

```
https://app.netdata.cloud/api/v2/nodes/1b48aa88-55c6-4a1a-9fc7-6e72e77abbd6/data?v2=&chart=system.cpu&format=array&options=absolute%7Cpercentage%7Cjsonwrap%7Cnonzero%7Cflip%7Cms&_=1648021465594&points=55&group=average&gtime=0&after=-600
```

Response:

```json
{
	"errorMsgKey": "ErrTimeout",
	"errorMessage": "timeout while waiting for agent response",
	"errorCode": "uohY73Xcw4-54929235"
}
```

**Comment by ktsaou** [comment]
I had the impression the timeout was set to 10s, which was already very low for supporting big queries.
3s is totally wrong, from any point of view.

**Comment by ktsaou** [comment]
@hugovalente-pm

**Comment by ktsaou** [comment]
Also, when a timeout happens, the UI shows "Error" on the chart. It should show "Timeout".

**Comment by papazach** [comment]
I see that netdata-parent's child instances are most of the time `live: false` and `queryable: false`  and when they get queryable and/or live - so we get to route data requests to them - then they time out.

Seems that they need more than 3sec. to return the responses whereas the child nodes themselves need no more than 300ms.

Pinged @stelfrag to take a look at the parent's state from the Agent side.

**Comment by hugovalente-pm** [comment]
@stelfrag let us know if you or someone from the agent team is or will be actively working on this.

**Comment by stelfrag** [comment]
> I see that netdata-parent's child instances are most of the time `live: false` and `queryable: false` and when they get queryable and/or live - so we get to route data requests to them - then they time out.

I am taking a look at this

**Comment by ktsaou** [comment]
> Seems that they need more than 3sec. to return the responses whereas the child nodes themselves need no more than 300ms.

@papazach does this mean that we do have a timeout at 3 seconds?

**Comment by hugovalente-pm** [comment]
@stelfrag just to check if this can be closed, I noticed now that this is on the `Done` status

**Comment by ktsaou** [comment]
Yes, this is done. The timeout is now 10s and the timeout is also propagated to the agent to abort the query there too.

**Comment by ralphm** [comment]
I don't understand what happened here. Did we revert the backend change to be 10 seconds again, instead of 3 seconds? Did we change something in the agent? Which tickets / PRs correspond to those changes and why are they not linked here?

FWIW I was the one suggesting to lower to 3 seconds, because I think it is not reasonable for the response to take even a second, and the UI will hang for a composite chart while maybe a single agent is taking its time.
