### ISSUE TITLE
Some collector icons and info not being displayed in cloud

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#37]
**Describe the bug**	

If i have alarms and anomlalies collector enabled, on cloud i dont see the icons or infor from dashboard_info.js

![image](https://user-images.githubusercontent.com/2178292/104601522-417e7880-5672-11eb-879e-ca6a9bff6a0a.png)

**To Reproduce**	

Look at any agent that has alarms collector on it in netdata cloud

**Expected behavior**	

THe icon and info should be displayed like it is in underlying agent dashboard

**Screenshots**	

Bad: 
![image](https://user-images.githubusercontent.com/2178292/104601634-5e1ab080-5672-11eb-8986-1fe122c346ee.png)

Good:
![image](https://user-images.githubusercontent.com/2178292/104601664-683caf00-5672-11eb-9428-87c5d4aa42ad.png)

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	

**Desktop (please complete the following information):**	

**Additional context**	

internal slack discussion: https://netdata-cloud.slack.com/archives/CHH8X9M5J/p1610627563003700

info from @jacekkolasa: We need to manually add dashboard_info.js to the Dashboard's bundle for the cloud. The icons are there, it's just a matter of that outdated file. Also the header info is missing, under the title.

**Comment by andrewm4894** [comment]
i dont seem to be able to add internal bug label for some reason

**Comment by hugovalente-pm** [comment]
Looking to our recent Anomaly Detection section would say this is fixed
