### ISSUE TITLE
[BUG] Inconsistency in databases

### ISSUE THREAD

**Issue by ivangergo3** [netdata/netdata-cloud#372]
**Describe the bug**	

I get different responses from different endpoints. One of them has a node, while another does not.

**To Reproduce**	

If you have a node, what is removed from one of the databases, but exists in another.
Let's say one request

/api/v1/spaces/4a920802-f67a-4f9f-a5bc-ecdd66749497/claimed-nodes

gives back "results": [] an empty array, at the same time

/api/v1/spaces/4a920802-f67a-4f9f-a5bc-ecdd66749497/rooms/2147de35-50e0-4e6f-a536-c07ce852ea55

response contains details of a node with id f5b9a873-e900-4a7d-aff7-db0ed198d78f
The above node and space Ids should be available in one of the databases in the testing environment.

**Expected behaviour**	

Consistent databases. So do not get 2 different responses from 2 different endpoints.

**Screenshots**	

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	

**Desktop (please complete the following information):**	

**Additional context**

**Comment by hugovalente-pm** [comment]
@vkuznecovas probably pinging you to see if we can link this to some on-going work or if this is something new

**Comment by vkuznecovas** [comment]
This is definitely caused by the general desync we have, https://github.com/netdata/cloud-backend/issues/91 will fix it. 

I've also applied a manual temporary data fix for staging and production for cases like this, but have not run it in the testing env as that was not seeing particular use at that time.

**Comment by hugovalente-pm** [comment]
@vkuznecovas with the work already completed, for this specific report, I think it can be closed, right?

```
/api/v1/spaces/4a920802-f67a-4f9f-a5bc-ecdd66749497/claimed-nodes

gives back "results": [] an empty array, at the same time

/api/v1/spaces/4a920802-f67a-4f9f-a5bc-ecdd66749497/rooms/2147de35-50e0-4e6f-a536-c07ce852ea55```

**Comment by vkuznecovas** [comment]
Yes, as long as we're using the v2 endpoints this is fixed.
