### ISSUE TITLE
[BUG] Composite charts with data from multiple nodes when filtering a specific node charts show wrong data and Error badge

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#374]
**Describe the bug**	
On Overview when you have composite charts with data from multiple nodes when filtering is applied and the visible charts don't have data for that node they show:
* data on charts in the viewport that is referent to the filtered out nodes
* `Error` charts when user scrolls and goes to a chart that doesn't contain data for the node selected on the filter

**To Reproduce**	
1. Overview without filters on `menu_bind` - https://app.netdata.cloud/spaces/ik-nu/rooms/general/overview#chartName=menu_bind
2. Single Node view for `mag.ik.nu` that **HAS** the `bind` charts - https://app.netdata.cloud/spaces/ik-nu/rooms/general/nodes/2e2ae08a-63bd-423e-8b90-ea253e58dea5#chartName=menu_bind_local&metrics_correlation=false&after=-900&before=0&utc=Europe%2FLisbon&offset=%2B1&timezoneName=Dublin%2C%20Lisbon&correlation=false
3. Single node view for `mag-vii` that **DOESN'T HAVE** `bind` charts - https://app.netdata.cloud/spaces/ik-nu/rooms/general/nodes/5ae0fb8d-d129-434f-93f7-7d6e7c73fc43#chartName=menu_system&metrics_correlation=false&after=-900&before=0&utc=Europe%2FLisbon&offset=%2B1&timezoneName=Dublin%2C%20Lisbon
4. Overview, go to `menu_bind` (same as step 1) and apply on the filter bar the node mag-vii
Charts still on the viewport show data but for the [mag.ik.nu](http://mag.ik.nu/) node and once you scroll down to the next chart it shows `Error` badge

**Expected behavior**	
After filtering, a re-fetch should be triggered on the visible charts on the user's viewport to update the visible data and when users scrolls if the charts don't have data for the filtered node they should show the "no data" message - not `Error`

**Screenshots**	
![image](https://user-images.githubusercontent.com/82235632/161232471-033d8208-3ff0-4e39-95db-bc3bbbb15276.png)

Chart with error badge
<image src="https://user-images.githubusercontent.com/82235632/161232526-2528c1a4-76da-4ccb-bfd0-d108f1031198.png" width="50%" height="50%"/>

**Error logs**	
N/A

**Desktop (please complete the following information):**	

**Additional context**	
For the charts that `Error` we don't see any `/data` request being triggered

**Comment by hugovalente-pm** [comment]
when a change in filters happens a new `/charts` request is fired and TOC will be updated based on that

**Comment by novykh** [comment]
there should be no new `/charts` request. We are doing the search on the frontend.

**Comment by hugovalente-pm** [comment]
I don't think I'm seeing things. @novykh please check this gif

1. last charts request: 05 Apr 2022 12:34:41 GMT
2. did the filtering, next charts request: 05 Apr 2022 12:34:50 GMT
3. sub-sequent charts request: 05 Apr 2022 12:34:51 GMT

![chrome_rK7l3HwdCB](https://user-images.githubusercontent.com/82235632/161754745-bb9ebbfa-bad4-49d1-a903-6107683d1844.gif)

**Comment by novykh** [comment]
My bad, I mean the table of contents search.
