### ISSUE TITLE
[BUG] k8s: how can I see all containers that are CPU throttled?

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#375]
There are 3 CPU utilization charts for cgroups:

1. cgroup.cpu_limit
2. cgroup.cpu
3. cgroup.cpu_per_core

## cgroup.cpu_limit

This chart is supposed to go 0-100% for all containers, within the CPU limits they have. So, if a container has 3 cores, it should be 100% when all 3 cores are used.

It does not happen.:

![image](https://user-images.githubusercontent.com/2662304/161248855-3f307b09-48f7-45c7-9688-c1992f0491f3.png)

## cgroup.cpu

This is supposed to give 100% for each core. So, if a container has 3 cores, the max should be 300%.

It seems ok.

## cgroup.cpu_per_core

Similar to the above.

The default view should be this:

![image](https://user-images.githubusercontent.com/2662304/161249430-0fadb05b-2bab-418f-a0f9-069976208948.png)

---

@ilyam8 @vlvkobal

**Comment by ilyam8** [comment]
We use the following files to calculate limits:

 - `cpuset.cpus` (cpuset controller)
   > specifies the CPUs that tasks in this cgroup are permitted to access. This is a comma-separated list, with dashes ("-") to represent ranges. 

 - `cpu.cfs_period_us` (cpu controller)
   > specifies a period of time in microseconds (µs, represented here as "us") for how regularly a cgroup's access to CPU resources should be reallocated.

 - `cpu.cfs_quota_us` (cpu controller)
   > specifies the total amount of time in microseconds (µs, represented here as "us") for which all tasks in a cgroup can run during one period (as defined by `cpu.cfs_period_us`). **Setting the value** in `cpu.cfs_quota_us` to **-1** **indicates that the cgroup does not adhere to any CPU time restrictions**. 

The calculations:

```go
if quota > 0 {
    quota = cpu_cfs_quota / cpu_cfs_period;
}
if quota < cpuset_cpus {
    limit = quota * 100
} else {
    limit = cpuset_cpus * 100
}
```

e.g. `--cpu-period=100000 --cpu-quota=15100` means: the tasks in the cgroup are allowed to access CPUs for 15100 us, this limit resets every 100000 us => 100% (`CPU Usage within the limits` chart) is 15.1% (`CPU Usage (100% = 1 core)` chart).


What we need to do is to collect more metrics that will tell us how many times the tasks got throttled (and probably the time duration for which tasks have been throttled). 

- `cpu.stat` (cpu controller)
  > reports CPU time statistics using the following values:
  - `nr_throttled`
    > number of period intervals (as specified in `cpu.cfs_period_us`) that have elapsed.
  - `nr_throttled`
    > number of times tasks in a cgroup have been throttled (that is, not allowed to run because they have exhausted all of the available time as specified by their quota).
  - `throttled_time`
    >  the total time duration (in nanoseconds) for which tasks in a cgroup have been throttled.

**Comment by ilyam8** [comment]
> This chart is supposed to go 0-100% for all containers

I think this info came frome me. In fact, it is not. But the value > 100 means it is above the quota.

Example (from the prev post):

limits:
 - `--cpu-period=100000`
 - `--cpu-quota=15100`
 - => limit is 15.1%

| Value      | cgroup.cpu_limit | cgroup.cpu|
| ----------- | ----------- | ----------- |
| 7.5%      | 7.5%       | 50%       |
| 15%      | 15%       | 100%       |
| 30%      | 30%       | 200%       |
