### ISSUE TITLE
[BUG] missing data are not shown on composite charts

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#376]
In group by node, there are missing data:

![image](https://user-images.githubusercontent.com/2662304/161315067-bccaa878-e1c2-4a39-aa1f-5fb1661ab2a9.png)

But in group by dimension, data are not missing:

![image](https://user-images.githubusercontent.com/2662304/161315175-540ff1d8-07ab-45c0-90c7-a07e7aa9e8cb.png)

When all the values reported by the agents are `null`, now the backend just skips them. It should present `null` values too, so that it is obvious for the user that data are missing for that period.

**Comment by ktsaou** [comment]
@papazach

**Comment by hugovalente-pm** [comment]
@ktsaou isn't this the same as #377 ?

**Comment by hugovalente-pm** [comment]
@ktsaou @TonyPath was working on https://github.com/netdata/netdata-cloud/issues/377 and these seem to be related, so if we interpolate and add annotations to _gaps_ we won't be showing these as `null`

can we close this ticket this #377 is to apply the interpolation?

**Comment by hugovalente-pm** [comment]
closed since #377 was closed
