### ISSUE TITLE
[BUG] partially missing data should show be interpolated and annotations on composite charts

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#377]
Example source data partially missing (in group by node):

![image](https://user-images.githubusercontent.com/2662304/161315580-8ee61f19-1e11-4d00-827f-5637ac4c8563.png)

What we present on group by dimension:

![image](https://user-images.githubusercontent.com/2662304/161315686-75294dd9-2fa6-4228-a118-005ebe25a187.png)

The backend is just skipping the `null` values reported by the agents and averages the remaining, which leads to such totally wrong data presented.

## Proposed solution

When we have partial data (some - but not all - source data have `null` values in them), the backend should:

1. Interpolate the data based on the 2 values available (before and after the gap) and use the intepolated value in the calculation.
   Example source data:
   
   t1 -> 10
   t2 -> null
   t3 -> null
   t4 -> 40
   
   The interpolated values for `t2 = 20` and `t3 = 30` (assume a straight line between t1 and t4).

3. Add another object in the response to annotate the region, like:
   
```json
"annotations": [
   {
      "from": "t1",
      "to": "t2",
      "type": "missing-data",
      "message": "node X reports missing data on dimensions A, B, C"
   }
]
```

**Comment by hugovalente-pm** [comment]
since annotations is a new feature we should track it in a separate ticket, we have this one around the topic and we can spin out smaller tasks out of it https://github.com/netdata/product/issues/1792

**Comment by hugovalente-pm** [comment]
I think that is the general assumption, logic that can be pushed to the edge should be done there.
let's see if @amalkov and @ralphm confirm this

**Comment by hugovalente-pm** [comment]
@TonyPath as discussed let's push forward the work on Cloud.
@MrZammler please take a look and a chat with @TonyPath to see the work needed to do this on Agent side
