### ISSUE TITLE
Phantom alarm[BUG]

### ISSUE THREAD

**Issue by maxsot100** [netdata/netdata-cloud#38]
**Describe the bug**	
I see an alarm on netdata but when I try to click on it from the numbered link in the war room list of nodes the browser returns a blank page. When I access it from the active alarms list, only the node and raise date are reported (no other information) and if I view alarm info they are empty. On the agent console no alarm is reported. It seems the synch between agent and cloud information is "broken".

**To Reproduce**	
I have no idea on how this issue occurred.

**Expected behavior**	
I would expect either detailed alarm info or no alarm and the same info in cloud and agent.	

**Screenshots**	
Link to screenshots: https://www.dropbox.com/s/iykalzaf63ec70v/Screenshot%202021-01-15%20181914.zip?dl=0 

**Error logs**	
Access to XMLHttpRequest at 'https://www.google-analytics.com/j/collect?v=1&_v=j87&a=1067901606&t=pageview&_s=1&dl=https%3A%2F%2Fapp.netdata.cloud%2Fspaces%2Figroup%2Frooms%2Fseregno%2Fnodes&ul=en-gb&de=UTF-8&dt=Netdata%20Cloud&sd=24-bit&sr=1920x1080&vp=1920x970&je=0&_u=QACAAEABAAAAAC~&jid=284583430&gjid=2177631&cid=1399776216.1604608692&tid=UA-64295674-3&_gid=1574353512.1610433909&_r=1&gtm=2wg161N6CBMJD&z=995482689' from origin 'https://app.netdata.cloud' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Desktop (please complete the following information):**	
 - OS: Windows10
 - Browser Edge 
 - Version 87.0.664.75 (Official build) (64-bit)

**Additional context**

**Comment by cakrit** [comment]
Changes have been made to cleanup such issues for a large majority of cases, but there are still cases where they persist and we're still investigating additional causes.

**Comment by maxsot100** [comment]
Thanks, this is a very good news! We already see improvements and we will let you know if other cases will occur. Kind regards.

**Comment by cakrit** [comment]
The fix was in 1.29.2. We use 1.29.3 in our prod infra, but I see two of those "phantom alarms" there right now:

![image](https://user-images.githubusercontent.com/43294513/109845484-0f18e280-7c02-11eb-8f62-6da16878613f.png)

**Comment by maxsot100** [comment]
I confirm that there are really many still.... it seems many alarms never close.

**Comment by harrisbz** [comment]
Hi @maxsot100,

Thanks for the feedback! 
We are aware of this issue and we are working as we speak to mitigate it.

**Comment by dimko** [comment]
Fixed in the new architecture for alerts. We should no longer see phantom alerts. Closing it for now.
