### ISSUE TITLE
[Bug]: Unreachable nodes not removable from General room

### ISSUE THREAD

**Issue by zeylos** [netdata/netdata-cloud#392]
### Bug description

Hi there,

After the implementation of #279 I have 131 unreachable nodes that I can't remove from the General room.
![image](https://user-images.githubusercontent.com/24226163/162966323-7413c5b6-d009-4814-950a-d4e51c8def71.png)
The following error message appears when I try to remove one.
![image](https://user-images.githubusercontent.com/24226163/162966452-402dc7e4-7c5d-4ed8-b846-db2a8b11b1d5.png)

### Expected behavior

Could we make an exception for unreachable nodes on the General room modification restriction ?

### Steps to reproduce

1. Delete a node on General room

### Additional context

I tried with Firefox 99.0 & Chromium 100.0, cleared cache and stuff.

**Comment by dionysis-netdata** [comment]
Hi @zeylos .

We are already working on this https://github.com/netdata/product/issues/2821
which will let you soft-delete nodes from your space.

By soft-deleting obsolete nodes, all views that bring nodes will not contain such nodes

**Comment by dimko** [comment]
Nodes deletion from every room is live for Unreachable nodes. @zeylos  can you please try it? Please keep in mind that stale != offline and they can't be removed.

**Comment by zeylos** [comment]
Hi @dimko, yep I tried yesterday but forgot about this issue :sweat_smile:.
The remove button works well, thanks.

If we could have something to bulk remove that would be awesome (using Kubernetes with AWS instances, nodes are very volatile so there is a lot of Stale and Offline nodes).

About Stale nodes, do they become Offline automatically after there is no more data from them in history ?

**Comment by dimko** [comment]
Thanks @zeylos Bulk deletion will be added in the future.
Pinging someone from the backend team to clarify about stale nodes @vkuznecovas @ravilushqa can you help on this one?

@zeylos if you're ok with it, can we close this issue?

**Comment by zeylos** [comment]
@dimko yes the issue can be closed.

Thanks for the work !

**Comment by vkuznecovas** [comment]
Stale nodes represent a case where there is data for the node and that data can be fetched but the agent itself is offline - i.e. the parent still has data for the child and this can be shown in the charts but the child itself is currently offline. The child would be marked as stale in this case.

**Comment by SR-G** [comment]
Better now, indeed, thanks !

One (i hope) last point : how do we clear the "visited nodes" (on the menu on the left) - indeed, in that area, i still have several deleted nodes.
