### ISSUE TITLE
[Feat]: A notifier for recent breaking commits

### ISSUE THREAD

**Issue by realEthanZou** [netdata/netdata-cloud#393]
### Problem

Recently there are two breaking changes that makes netdata cloud very difficult to work with for me.
1. unable to remove unreachable nodes or obsolete war rooms
2. a "General static" room appeared out of no where. The notification policy set for that room is all alerts. I got ~100 emails flooding my inbox today.

### Description

Please, a proper way to inform users the breaking changes.

### Importance

nice to have

### Value proposition

1. So you don't have to say some breaking changes (and bugs introduced) are actually expected behaviors in bug reports

**Comment by hugovalente-pm** [comment]
thanks for the feedback, it is totally to the point
> 1. unable to remove unreachable nodes or obsolete war rooms

this has been addressed

> 2. a "General static" room appeared out of no where. The notification policy set for that room is all alerts. I got ~100 emails flooding my inbox today.

we are sorry this change has caused this flood of e-mails, we are improving our communication process and will for sure try to give prior notifications when some breaking change is to be released

closing this ticket.
