### ISSUE TITLE
[Bug]: Alert configuration is not updated if change doesn't contain status or name change

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#394]
### Bug description

Cloud doesn't update alert configurations even though agent sends the updated configuration, when the modification doesn't trigger an alert name or alert status change.

### Expected behavior

Since alert hash for configurations is calculated based on the whole conf file, even the slightest change should trigger an event in cloud to update the config and all affected alerts.

### Steps to reproduce

1. Create an alert in agent in /etc/netdata/health.d/alert.conf e.g 

> template: alert1
> on: system.cpu
> hosts: *
> lookup: average -15s unaligned of user,system,softirq,irq,guest
> units: %
> every: 1s
> crit: $this == $this
> delay: up 0s down 0s multiplier 1.0 max 1h
> info: test alert 1

2.` /usr/sbin/netdatacli reload-health` to trigger the alert
3. Alert appears in cloud 
4. Edit the alert.conf lookup from -15s to -30s (or any other change, e.g delay, every etc) to the following:

> template: alert1
> on: system.cpu
> hosts: *
> lookup: average -30s unaligned of user,system,softirq,irq,guest
> units: %
> every: 1s
> crit: $this == $this
> delay: up 0s down 0s multiplier 1.0 max 1h
> info: test alert 1
5.` /usr/sbin/netdatacli reload-health` to trigger the alert
6. Alert remains in cloud with the previous configuration. Even though config has changed agent side

**Comment by dimko** [comment]
Assigning to me for re-testing.

**Comment by car12o** [comment]
@dimko we need to update the FE request to use the new endpoint. I think this will be addressed on the drawer refactoring.
cc: @jacekkolasa

**Comment by dimko** [comment]
This seems to be fixed after the update in the alert's drawer. closing
