### ISSUE TITLE
[Bug]: Alert pop-up covers chart

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#395]
### Bug description

After a user clicks to view the alert affected chart either from the email or the alert's details modal (they both redirect to the new alert's dedicated page) the alert pop-up covers part of the chart 

### Expected behavior

The chart should be visible and popup should be displayed a bit higher

### Steps to reproduce

1. Trigger an alert on a node claimed to cloud
2. Click the View Alert CTA from inside the alert's email
3. After landing in the Alert's dedicated page click the Go To Chart button
4. User is re-directed to single node view, the affected chart is highlighted and a pop up is displayed with alert's name and date raised

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/163405492-77fe143a-6bb7-421b-b629-5e0272e060d2.png)

### Desktop

OS: MacOs
Browser chrome
Browser Version latest

**Comment by jacekkolasa** [comment]
fix is on production
