### ISSUE TITLE
[Bug]: Unable to remove old, unreachable node

### ISSUE THREAD

**Issue by Mic-Pod** [netdata/netdata-cloud#396]
### Bug description

Hi,
I can't remove old, unreachable nodes from War Room.
![image](https://user-images.githubusercontent.com/57563877/163442043-9000fa30-3dee-4014-91ac-bfface0af790.png)
Last time I checked Netdata Cloud, I have had only nodes that are alive. Now I see also old ones (cloned VMs with same ID).
![image](https://user-images.githubusercontent.com/57563877/163442717-f8511f7b-3e53-45a8-9369-c5e14b16a567.png)

How can I remove those old nodes?

### Expected behavior

I should be able to remove old nodes.

### Steps to reproduce

1.
2.
3.
...

### Desktop

Windows 10, Chrome 100

**Comment by Mic-Pod** [comment]
As a workaround, I have created new Space, deleted the old one and claimed all nodes to the new new Space. All is working fine now - no old nodes.

**Comment by hugovalente-pm** [comment]
Hi @Mic-Pod , thanks for raising this issue.

This seems to be duplicated with this one netdata/netdata-cloud#392, so if you agree you can track the other one and close this one

**Comment by Mic-Pod** [comment]
@hugovalente-pm, ok, thanks. I'll close this one.
