### ISSUE TITLE
[Bug]: Error 500 when accessing cloud

### ISSUE THREAD

**Issue by mrleongalaxyum** [netdata/netdata-cloud#397]
### Bug description

I was trying to remove a node from war room general and move it to a custom room, but now I cant add it to any room anymore

contact:
wisefox3599@gmail.com

### Expected behavior

open the cloud and show selected node data

### Steps to reproduce

1.Install docker container netdata
2.connect to cloud
3.remove docker container
4. connect to cloud with new token
5. remove container
6. create new container and assign it to a new war room
...

### Screenshots

![image](https://user-images.githubusercontent.com/51249624/163507440-c7a344da-179a-4b4a-8cff-6b481bf346e4.png)

### Error Logs

[app.netdata.cloud.har.csv](https://github.com/netdata/netdata-cloud/files/8493431/app.netdata.cloud.har.csv)

github does not allow .har upload so i added .csv suffix. remove .csv and you will get .har

### Desktop

OS:win11	
Browser chrome	
Browser Version  100.0.4896.75 (Official Build) (64-bit)

**Comment by hugovalente-pm** [comment]
Hi @mrleongalaxyum , thanks for raising this bug.
we will take a look and come back with any finding

**Comment by dionysis-netdata** [comment]
Hi @mrleongalaxyum , can you see the node under the Nodes tab?

**Comment by mrleongalaxyum** [comment]
> Hi @mrleongalaxyum , can you see the node under the Nodes tab?

hello, yes now it is showing up and working, but I can't delete 4 of the old nodes.
