### ISSUE TITLE
[Bug]: Can't delete stale node from a  war room

### ISSUE THREAD

**Issue by weastur** [netdata/netdata-cloud#399]
### Bug description

There is no delete button along with node name. 

### Expected behavior

Successful deletion

### Steps to reproduce

1. Add node

### Screenshots

<img width="626" alt="Screenshot 2022-04-17 at 13 07 21" src="https://user-images.githubusercontent.com/10865586/163710017-40deedad-eb2a-4ae2-9036-35bbc319d747.png">

### Additional context

I'm the only admin of the space. Nothing has been changed recently.

**Comment by hugovalente-pm** [comment]
Hi @weastur , thanks for reporting this bug.

There was a change done on the General War Room, General as a war room for all space's nodes and users netdata/netdata-cloud#279 that removed the possibility to delete nodes from this room specific.

Nevertheless, there is work in progress to allow the soft-delete of nodes from a space please see this comment on this other bug https://github.com/netdata/netdata-cloud/issues/392#issuecomment-1096701304

If you agree you could track the bug I mentioned above and close this one

**Comment by dimko** [comment]
Nodes deletion from every room is live for Unreachable nodes. @weastur can you please try it and let us know? Please keep in mind that stale != offline and they can't be removed.

**Comment by weastur** [comment]
https://user-images.githubusercontent.com/10865586/172810642-f1a80c06-956d-43b8-8602-43b37d6a6c2f.mov

Seems still not working.

**Comment by burbuli8ra** [comment]
Hello @weastur we have released a hotfix that should solve the issue you are experiencing!
Can you please verify that when you click the button to delete a node you can see the confirmation modal?

**Comment by weastur** [comment]
@burbuli8ra Yes, now everything is working exactly as your say: I see the confirmation, click on it, and a node disappears. Thanks.

**Comment by burbuli8ra** [comment]
Thank you @weastur for getting back to us!
We are glad we could help! 🙌
