### ISSUE TITLE
[BUG] Node View not loading due to Javascript errors

### ISSUE THREAD

**Issue by mbigatti** [netdata/netdata-cloud#40]
**Describe the bug**	
Node page not loading

**To Reproduce**	
Click on a node detail like https://app.netdata.cloud/spaces/production-iqdkpt4/rooms/general/nodes/483ee1be-3cbb-47a0-a913-7d00facd5c96

**Expected behavior**	
Page should render

**Error logs**	
[Error] TypeError: undefined is not an object (evaluating 'Object(o.a)(r,n)')
hasOwnProperty
(funzione anonima) — main-344126e7afd18628ea00.js:199:1483564
(funzione anonima) — main-344126e7afd18628ea00.js:236:1708661
(funzione anonima) — main-344126e7afd18628ea00.js:199:1454311
(funzione anonima) — main-344126e7afd18628ea00.js:236:1708668
(funzione anonima) — common~main~netdata_dashboard.e5eb42184e81835fbe6b.js:1:13762
v — common~main~netdata_dashboard.e5eb42184e81835fbe6b.js:1:11769
(funzione anonima) — main-344126e7afd18628ea00.js:199:1619585
(funzione anonima) — main-344126e7afd18628ea00.js:199:1612626
f — main-344126e7afd18628ea00.js:199:1610279
y — main-344126e7afd18628ea00.js:199:1610468
p — main-344126e7afd18628ea00.js:199:1610328
(funzione anonima) — main-344126e7afd18628ea00.js:199:1612581
(funzione anonima) — main-344126e7afd18628ea00.js:199:1617305
m — main-344126e7afd18628ea00.js:199:1618263
p — main-344126e7afd18628ea00.js:199:1617774
c — main-344126e7afd18628ea00.js:199:1618046
promiseReactionJob

	(funzione anonima) (main-344126e7afd18628ea00.js:408:3552814)
	y (main-344126e7afd18628ea00.js:2:233276)
	y (main-344126e7afd18628ea00.js:199:1616469)
	i (main-344126e7afd18628ea00.js:199:1615983)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1616070)
	p (main-344126e7afd18628ea00.js:199:1617838)
	c (main-344126e7afd18628ea00.js:199:1618046)
	n (main-344126e7afd18628ea00.js:2:233931)
	c (main-344126e7afd18628ea00.js:199:1618046)
	y (main-344126e7afd18628ea00.js:199:1616568)
	i (main-344126e7afd18628ea00.js:199:1615983)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1616070)
	y (main-344126e7afd18628ea00.js:199:1616568)
	i (main-344126e7afd18628ea00.js:199:1615983)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1616070)
	y (main-344126e7afd18628ea00.js:199:1616568)
	i (main-344126e7afd18628ea00.js:199:1615983)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1616070)
	p (main-344126e7afd18628ea00.js:199:1617838)
	c (main-344126e7afd18628ea00.js:199:1618046)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1612652)
	f (main-344126e7afd18628ea00.js:199:1610279)
	y (main-344126e7afd18628ea00.js:199:1610468)
	p (main-344126e7afd18628ea00.js:199:1610328)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1612581)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1617305)
	m (main-344126e7afd18628ea00.js:199:1618263)
	p (main-344126e7afd18628ea00.js:199:1617774)
	c (main-344126e7afd18628ea00.js:199:1618046)
	promiseReactionJob

[Error] TypeError: undefined is not an object (evaluating 'Object(o.a)(r,n)')
	(funzione anonima) (main-344126e7afd18628ea00.js:408:3552814)
	y (main-344126e7afd18628ea00.js:2:233276)
	y (main-344126e7afd18628ea00.js:199:1616469)
	i (main-344126e7afd18628ea00.js:199:1615983)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1616070)
	p (main-344126e7afd18628ea00.js:199:1617838)
	c (main-344126e7afd18628ea00.js:199:1618046)
	n (main-344126e7afd18628ea00.js:2:233931)
	c (main-344126e7afd18628ea00.js:199:1618046)
	y (main-344126e7afd18628ea00.js:199:1616568)
	i (main-344126e7afd18628ea00.js:199:1615983)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1616070)
	y (main-344126e7afd18628ea00.js:199:1616568)
	i (main-344126e7afd18628ea00.js:199:1615983)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1616070)
	y (main-344126e7afd18628ea00.js:199:1616568)
	i (main-344126e7afd18628ea00.js:199:1615983)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1616070)
	p (main-344126e7afd18628ea00.js:199:1617838)
	c (main-344126e7afd18628ea00.js:199:1618046)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1612652)
	f (main-344126e7afd18628ea00.js:199:1610279)
	y (main-344126e7afd18628ea00.js:199:1610468)
	p (main-344126e7afd18628ea00.js:199:1610328)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1612581)
	(funzione anonima) (main-344126e7afd18628ea00.js:199:1617305)
	m (main-344126e7afd18628ea00.js:199:1618263)
	p (main-344126e7afd18628ea00.js:199:1617774)
	c (main-344126e7afd18628ea00.js:199:1618046)
	promiseReactionJob

**Desktop (please complete the following information):**	
 - OS: Mac OS Big Sur
 - Browser Safari
 - Version latest

**Comment by manos-saratsis** [comment]
@mbigatti this should be fixed by now. Closing, if you face issue please comment here.
