### ISSUE TITLE
[Bug]: Unable to remove live node from non-General room

### ISSUE THREAD

**Issue by bojdell** [netdata/netdata-cloud#402]
### Bug description

I understand there are known issues (ex https://github.com/netdata/netdata-cloud/issues/182#issuecomment-1093152078 ) with deleting unreachable nodes and also from modifying the "untouchable" General room. However, I am also unable to delete live nodes from a new room (non-General). I attempted this room as a workaround for the other issues but ran into this additional issue.

![image](https://user-images.githubusercontent.com/3486165/163892867-1b691511-0394-41f5-acfd-77a6ad7362fc.png)

I have tried deleting this node from my new room but am unable to do so. I click "Yes, remove", the node disappears, but upon a page refresh it is back again.

### Expected behavior

I expect the removed node to remain removed from the war room even after page refresh.

### Steps to reproduce

1. Create a new war room with at least 1 node in it
2. Attempt to remove the node from the room
3. Refresh the page and see the node is still there
...

### Screenshots

See above

### Desktop

OS: Mac OSX 12.2
Browser firefox
Browser Version 99.0

**Comment by bojdell** [comment]
Hmm, now the node appears to be removed. I believe I attempted ~3 removal attempts over the course of a few hours, so perhaps some of the removal requests failed and/or there was some latency for the delete to propagate fully in the system. The last removal request used the bulk delete dropdown in the screenshot above, the others likely used the inline trash bin icon.

Feel free to close this issue if it's no longer helpful

**Comment by hugovalente-pm** [comment]
Hi @bojdell thanks for raising this, glad that it got sorted out but we still should take a look before closing.
My guess it is that it will be related to this netdata/netdata-cloud#372

@vkuznecovas probably you could help to confirm this

**Comment by vkuznecovas** [comment]
Due to the async nature of our implementation, there's some expected delay between the action being taken and the action taking effect. However, it should not take that long.

I'm confident that https://github.com/netdata/cloud-backend/issues/91 will tackle this case as well.

I'm closing this as we're already aware of situations like this.
