### ISSUE TITLE
[Bug]: Unable to start topic on netdata forums

### ISSUE THREAD

**Issue by bojdell** [netdata/netdata-cloud#403]
### Bug description

I am unable to create a new topic to submit questions/feedback on the Netdata Cloud forums. I would leave this feedback there, but due to the nature of the issue I am unable to...

### Expected behavior

I am able to create a new topic.

### Steps to reproduce

1. Create account on netdata forums
2. Try to create a new topic, taking care to fill out the post template + add tags

I disabled ad blockers

### Screenshots

<img width="647" alt="image" src="https://user-images.githubusercontent.com/3486165/164057035-4c356dac-9450-4316-8d87-4cdfacda1538.png">

### Error Logs

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3486165/164056968-7ebc5455-7dcd-4506-94dd-b23af69b8cc4.png">

### Desktop

OS:  Mac osx
Browser FF
Browser Version 99.0

**Comment by tkatsoulas** [comment]
Hello @bojdell

1. What's the method you used to sign up in our forums? 
2. In which category you tried to create your new topic?
3. Could you share with me your user name?

**Comment by bojdell** [comment]
1. I believe it was email+pw
2. Category "Feature Requests" with tag "cloud"
3. `@bo-d`

Thanks

**Comment by tkatsoulas** [comment]
Issue resolved, thanks for reporting it.

**Comment by dimko** [comment]
Closing this.
