### ISSUE TITLE
Enhance the Alerts drawer / modal in the Active alerts and Alerts Configuration Page

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata-cloud#406]
### Problem

The current Alerts drawer / modal does not display the details of node instances where this alert has been raised and how it has been aggregated at the node level.

### Description

The alert drawer is currently being used in the Active Alerts tab and will need to be used also in the "Alerts Configuration" / "Manage Alerts" tab. The drawer / model needs to be enhanced to provide more clear information on the alert itself:

- The Chart relevant to the alert (already available)
- Details of the alert event as a vertical bar with value (already available for Warning and Critical) also for the Clear state.
- Table with Node instances where the alert was raised (with criticality)
- Alert configurations in a more easily readable and understandable way for each node instance
- CTA to view the alert configuration at the node level (on a dedicated page?)

This can possibly be extended to also show historical logs relevant to the specific alert within the drawer.

cc: @ktsaou @amalkov @vinnygats @car12o @YaroslavDev @novykh @jacekkolasa 

### Importance

must have

### Value proposition

1. The current alert drawer does not convey a clear description of the alert
2. The user will need to see details at the node instance level
3. Possible future extension to also show the historical logs relevant to the alert
...

**Comment by sashwathn** [comment]
- 1 Phase: Prettify the configuration
- 2 Phase: Allow modifying only the values
- 3 Phase: Allow changing the functions and the frequency of the lookup etc..

The following aspects need to be shown and improved on the drawer:

1. Value shown on active alert
2. What is the vertical line on the chart in the drawer? Is this the current value or when raised?
3. Why hostname and not node name?
4. Show within the chart lines for Warning and Critical
5. Capture the current value and value at raised within the threshold
6. Check with backend how the alert values are fetched and if it is lost when the alert state changes?
7. Try to replicate some stuff from the agent
8. Put the manual configuration change information at the bottom with lower importance
9. Time series of the output? With the history?
10. Values reported at the node instances? And who reported it?
11. The drawer needs to be rendered also for Cleared alerts (on the display configured alerts tab)

cc: @amalkov @ralphm @vinnygats @ktsaou

**Comment by YaroslavDev** [comment]
@jacekkolasa @car12o @sashwathn This is the payload that we will return from backend to render this drawer. 
```json
{
	"info": "info",
	"class": "class",
	"type": "type",
	"component": "component",
	"family": "family",
	"calculation_expr": "calc expr",
	"warning_expr": "warn expr",
	"critical_expr": "crit expr",
	"update_every": 42,
	"units": "%",
	"delay": "1min up",
	"lookup_dimensions": "dims",
	"lookup_method": "method",
	"lookup_options": "opts",
	"lookup_after": 1,
	"lookup_before": -3,
	"status": "CRITICAL",
	"node_instances":{
		"889e7bd3-ba2f-4ff5-a4ee-dc888aca9936": {
			"status":"WARNING",
			"value": 1.2,
			"units": "units",
			"transition_at":"2010-01-01T15:15:20Z"
		},
		"528033ed-39b8-488f-92c3-22f8b1a2c7eb": {
			"status":"CRITICAL",
			"value": 2,
			"units": "percentage",
			"transition_at":"2010-01-01T15:15:21Z"
		}
	}
}
```
If there is smth. missing or some fields that are not needed, please let me know

**Comment by jacekkolasa** [comment]
I don't have hard opinion regarding the naming, if you find more explicit names more suitable, please change them. Easy to change it on FE. `calculation` seems clear to me, but `warning` and `critical` could be changed (or not). Personally i don't like abbreviations so `critical_expression` or `critical_when` suits me better :)

Regarding casing, if you'll change it to snake_case, we'll `normalizeIt` anyway on FE

I'm missing `chartID` and `name`. Can we include it? I know they are encoded into the `id`, but maybe we shouldn't rely on that encoding to parse those values.

Also I see we have `units` for every `node_instance`, is it something that can differ between instances?

**Comment by YaroslavDev** [comment]
@jacekkolasa I would assume normally, units should NOT change across instances, but our current data model permits this :) because technically, each node instance can have its own config, and every config may have its own `units` 😄

**Comment by YaroslavDev** [comment]
I suggest snake_case because in 3 "configured alerts" endpoints and "room active alarms count" endpoint we're already using snake_case. If we decide to switch to camelCase, it means we need to change all alarm-processor endpoints to camelCase

**Comment by jacekkolasa** [comment]
> @jacekkolasa I would assume normally, units should NOT change across instances, but our current data model permits this :) because technically, each node instance can have its own config, and every config may have its own units 😄

@YaroslavDev Then maybe we should remove `units` from general part of the payload? (And leave only units per instance)

**Comment by car12o** [comment]
I guess we have more endpoints returning in `camelCase` rather than in `snake_case` but I will raise this question in the next BE chapter.

**Comment by YaroslavDev** [comment]
if we have majority of endpoints using `camelCase`, then lets stick to that. I agree that we need to discuss this on BE chapter and agree on format. Its better for all services to use same format.

**Comment by jacekkolasa** [comment]
@YaroslavDev makes sense, all good, thanks!
