### ISSUE TITLE
[Bug]: No notification displayed for last space deletion forbidden action

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#407]
### Bug description

When a user tries to delete his last space a console error is displayed in browser console and no popup is displayed notifying the user that action cannot be performed

### Expected behavior

User should see a message like "This is your last space and cannot be deleted"

### Steps to reproduce

1. Login to an account with a single space
2. Manage Space -> Delete account
...

### Error Logs

```
Uncaught (in promise) TypeError: Cannot destructure property 'slug' of '(c && (intermediate value))' as it is undefined.
    at app.94a190d87ae1e24d05d9.chunk.js:440:99280
```

### Desktop

OS: MacOS
Browser: chrome
Browser Version: doesn't matter

**Comment by AlexNti** [comment]
This is related with. https://sentry.io/organizations/netdata-inc/issues/2485832520/?query=is%3Aunresolved&statsPeriod=14d

**Comment by AlexNti** [comment]
fixed
