### ISSUE TITLE
[Bug]: Can't access notification settings for some spaces from the Profile tab

### ISSUE THREAD

**Issue by Ancairon** [netdata/netdata-cloud#408]
### Bug description

When I am in a space, and I go to the bottom left -> profile -> notifications, the dropdowns don't show info, except the first one, which is the space I am in, and one other space, in which I am an admin.

### Expected behavior

Be able to manage notifications for all spaces through this tab.

### Steps to reproduce

1. Press the profile pic on the bottom left
2. Click "profile"
3. Go to the "Notifications" tab
4. Open all the tabs, not all of them expand with the info, but the arrows animate

### Screenshots

![image](https://user-images.githubusercontent.com/70198089/164444911-4f63233d-dbac-4a62-9fbe-26c5dfd2cb47.png)

### Desktop

Browser: Google Chrome

**Comment by ivangergo3** [comment]
I have just tested. Seems ok, will close the ticket when it has been released

**Comment by burbuli8ra** [comment]
This was released on [v2.29.4](https://github.com/netdata/cloud-frontend/releases/tag/2.29.4)
