### ISSUE TITLE
Cannot save cpu.cpu0-7 charts in dashboard

### ISSUE THREAD

**Issue by ironbelly** [netdata/netdata-cloud#41]
1) Make Dash Board - Result = Pass
2) Try to add any chart - Result = Fail(Add chart button does nothing)
3) Add Text - Result - Pass
4) Add Bandwidth Chart - Result = Pass
5) Click Save - Result = Pass
6) Add cpu.cpu1 Chart - Result = Pass
7) Click Save - Result = Fail (Dashboard clears cpu.cpu1 chart leaving text and bandwidth chart)

Does not matter if I add cpu chart before bandwidth chart, cpu.cpu# charts will always be wiped when save button has been hit
Have deleted Dashboard and recreated multiple times

**Comment by cakrit** [comment]
Verified. When trying to save the dashboard, we get the following exception:
![image](https://user-images.githubusercontent.com/43294513/106512521-93067000-6486-11eb-8c1f-b2ffa68d80be.png)

**Comment by jacekkolasa** [comment]
Duplicate of https://github.com/netdata/netdata-cloud/issues/42, it'll be released tomorrow
