### ISSUE TITLE
[Bug]: Mass removal of unreachable nodes from War Room doesn't work

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#410]
### Bug description

On `Manage Nodes` under `Manage War Room / <War Room Name>` if you select multiple nodes to be removed this doesn't work.
The nodes aren't removed even after multiple tries. 

### Expected behavior

The selected nodes should be removed from the War Room

### Steps to reproduce

1. Go to a War Room, other than the General
2. Go to `Manage Nodes` under `Manage War Room / <War Room Name>` 
3. Select multiple nodes to be removed and remove them
4. Notice that these aren't removed (even if you try multiple times)

### Screenshots

Nodes to be removed
<image src='https://user-images.githubusercontent.com/82235632/164912848-782bb907-c6a1-4dbf-8d5b-c269950a2199.png' width="50%" height="50%"/>

Mass removal of 11 nodes out of 25
<image src='https://user-images.githubusercontent.com/82235632/164912867-bae6f00f-bd1b-4774-b15b-4c85cb5ac895.png' width="50%" height="50%"/>

Confirmation
<image src='https://user-images.githubusercontent.com/82235632/164912877-cdc9fb93-bd65-418a-8cc2-a89db86f64a6.png' width="50%" height="50%"/>

After removal we see 14 nodes
<image src='https://user-images.githubusercontent.com/82235632/164912908-9e5c3708-083c-4c8c-b2d8-f8b801c5f7cc.png' width="50%" height="50%"/>

After refresh we see again the 25 nodes
<image src='https://user-images.githubusercontent.com/82235632/164912928-f7c74a2a-7623-4d0a-8632-ee2925b87a29.png' width="50%" height="50%"/>

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@ralphm @dionysis-netdata @vkuznecovas  this is an issue @ktsaou mentioned to me about and, in opposition to this one https://github.com/netdata/netdata-cloud/issues/402#issuecomment-1102578930, it is not a matter of a "delay" the nodes are never deleted even after multiple retries

I've placed this under P&S scope

**Comment by vkuznecovas** [comment]
There seems to be some delay/caching going on. The delete seems to have gone through, i.e. I'm seeing only the 14 nodes, so the 11 have been deleted. Could you try deleting your local DB and try a refresh @hugovalente-pm ?

<img width="716" alt="Screenshot 2022-04-25 at 10 25 10" src="https://user-images.githubusercontent.com/18392269/165040291-27abab7c-dab0-4132-ae07-e858f572736e.png">

I've also checked the logs there seem to be no indications of failed deletes on the back end. 

Both the SoT and Matview databases report 14 nodes correctly. 

I've also tested this scenario on my personal space and a bulk deletion of nodes has gone through without an issue - they disappeared and did not re-appear after a refresh.

Could someone @netdata/cloud-fe also take a peek as to what might be causing this?

**Comment by LordMike** [comment]
Just chiming in - I couldn't find how to remove nodes, but this thread helped a bit (it was tricky.. :P)

I _did_ experience this issue, my 4 nodes remained after a refresh of the page.. A force-refresh removed them, however.. So maybe a timing or local state issue.

**Comment by solracsf** [comment]
Option (checbox+delete) doesn't seem available anymore, impossible to delete any node on my WebUI.

![image](https://user-images.githubusercontent.com/12234510/167015295-ee178943-e71f-42af-85e4-8bca3d3ea9aa.png)

**Comment by LordMike** [comment]
You're in the wrong place (I made this mistake 20 times so far).. It's tricky to find, but right now it's here:

![image](https://user-images.githubusercontent.com/1027111/167016021-5fcf531a-bf36-4e9e-a652-b8a4c2122eb5.png)

**Comment by solracsf** [comment]
@LordMike this is exactly where i'm clicking before getting that screen.
![image](https://user-images.githubusercontent.com/12234510/167016816-33ffda72-d991-41b8-91cf-d4bee4d08145.png)
and on click
![image](https://user-images.githubusercontent.com/12234510/167016876-77c8e728-49c6-49b8-a483-983258f2f575.png)

**Comment by LordMike** [comment]
Huh, maybe General is different here also. I created new War rooms as I found that I couldn't do certain things with General in other parts of Netdata Cloud (like deleting it). So I figured if I invited 10 colleagues to General, I could never undo it. I just checked, and even after a force refresh, my other war rooms still have checkbox+remove.

**Comment by vkuznecovas** [comment]
@solracsf General has been changed recently and you won't be able to remove nodes from it at the moment. See https://github.com/netdata/netdata-cloud/issues/399 for more details.

We're working on a better flow for this.

**Comment by solracsf** [comment]
Thanks @vkuznecovas deleting nodes is **a real mess** on Netdata 😭
Global UX is great, but this option really needs improvements...

**Comment by hugovalente-pm** [comment]
thanks for the feedback @solracsf and @LordMike , @dionysis-netdata please consider this if it isn't already under the radar for the delete nodes work

@novykh could you check this feedback from @vkuznecovas 
https://github.com/netdata/netdata-cloud/issues/410#issuecomment-1108179090

**Comment by burbuli8ra** [comment]
Hello @hugovalente-pm !
There is a known issue about the FE and BE databases sync, which is random!
In short, in FE we receive the data from BE from an initial call made to receive the nodes and we update the local cache with the next response received from the same call to this endpoint (either from polling or by a new call if the user refreshes).
For same reason, BE not always responds with the updated nodes list, but with `null`, which means that no update has been made!
As part of the nodes obsoletion feature, we have made some updates in FE that hides this BE issue, but we have applied the fix only on this functionality! When we go live, I will inform @dionysis-netdata that I will take a look at this issue, to maybe apply the same fix in the nodes removal functionality too!

**Comment by hugovalente-pm** [comment]
thanks for the update @burbuli8ra and for picking this up 💪

**Comment by cakrit** [comment]
@burbuli8ra please do look into getting the fix in node deletion, we've had this bug for far too long and node deletion is a constant complaint of our users.

**Comment by burbuli8ra** [comment]
Released on [v2.34.0](https://github.com/netdata/cloud-frontend/releases/tag/2.34.0)
