### ISSUE TITLE
[Bug]: Alert re-direct to Cloud from Agent Email reports Alert doesn't exist anymore even though it does

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#413]
### Bug description

When a user follows an alert email for a claimed node, coming from the **Agent**, to view the alert in cloud we always display the message that alert doesn't exist in the node anymore even though it does.

### Expected behavior

The alert and its info should be displayed as normal, since the alert is active.
If user from the dedicated alert page clicks to run correlations or go to chart the alert is displayed as expected in the single node view

### Steps to reproduce

1. Claim a node to cloud
2. Enable agent alert notifications
3. Trigger an alert
4. Visit user's email inbox and click the go to chart CTA inside the email
5. User lands in Alert's dedicated page in Cloud

### Screenshots

![Uploading image.png…]()

### Desktop

OS: Docker
Browser: Chrome
Browser Version: 101

### Additional context

The alert email on the agent side still says Go To Chart instead of View Alert. We should handle this in a separate ticket.

**Comment by jacekkolasa** [comment]
fix is on production
