### ISSUE TITLE
[Bug]: Adding chart to dashboard from single node view or overview doesn't work

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#414]
### Bug description

Adding charts or creating dashboards from views other than the dashboard tab doesn't work

### Expected behavior

- Chart should be added to selected dashboard when clicking the Add Chart button either from overview or single node view
- User should be able to create dashboards from the side modal when no dashboards exist and clicks the Add Chart button either from overview or single node view

### Steps to reproduce

1. Claim a node
2. Go to single node view (or overview)
3. Click to add a chart to an existing dashboard
...

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/166709702-4f575329-a7d9-4f31-8209-24489d65652c.png)

### Error Logs

- No error log displayed in Dev Tools console
- No request issued to add chart to dashboard

**Comment by novykh** [comment]
Will be on prod on next release

**Comment by cakrit** [comment]
Please don't close bugs until the fix is deployed and tested in production.

**Comment by dimko** [comment]
Closing this, it's on production
