### ISSUE TITLE
[Bug]: Invalid popup after user opens alert details from node info

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#415]
### Bug description

The alert popup incorrectly appears after user visits the alert details from the alerts list inside node's info sidebar 

### Expected behavior

The popup shouldn't appear

### Steps to reproduce

1. Claim a node
2. Trigger an alert to that node
3. Click the (i) icon next to node's name in Nodes List view
4. Switch to the alert's tab in the Nodes Info sidebar
5. CLick the triggered alert from the list of active alerts

### Screenshots

Click alert as displayed in the screenshot below:

![image](https://user-images.githubusercontent.com/19268853/166975921-8db18e08-f2e8-4f37-ad72-332e62e16180.png)

The popup shouldn't appear
![image](https://user-images.githubusercontent.com/19268853/166975978-0c7333b6-5a96-48b5-8a5e-908b4f1fccc6.png)

**Comment by dimko** [comment]
@jacekkolasa @christophidesp Guys, is this an expected behaviour? Should we close this one?

**Comment by christophidesp** [comment]
I also don't see a reason for this pop up to be triggered, not sure if there is something else here we should consider @jacekkolasa

**Comment by jacekkolasa** [comment]
@dimko @christophidesp thx for asking, but It's just a bug, i'll close it as soon as fix will be in prod
