### ISSUE TITLE
[Bug]: Service value is null for all nodes

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#416]
### Bug description

Service discovery doesn't seem to work as expected. Group By service always groups the available nodes as No Service.

### Expected behavior

Well... the nodes be grouped per Service and services returned as expected from the BE

### Steps to reproduce

1. Claim 1 or more nodes in a room
2. Visit the nodes table
3. Check the /claimed-nodes request in the Dev tools network
4. Service shouldn't be null for every node

### Error Logs

Response payload for `https://app.netdata.cloud/api/v1/spaces/3c4128b9-a2cd-4930-8a92-509bbc5f3330/claimed-nodes` request

> results: [,…]
0: {nodeID: "fd6f3f0d-b627-40e0-bef5-aa1986950cf8", name: "ubuntunetdata20-VirtualBox", services: null,…}
claimedAt: "2022-03-24T13:47:31.411Z"
name: "ubuntunetdata20-VirtualBox"
nodeID: "fd6f3f0d-b627-40e0-bef5-aa1986950cf8"
os: "linux"
services: null
state: "current"
1: {nodeID: "93d7f48f-b874-49b9-bf5f-c505c34d5132", name: "65608fa2fa98", services: null, os: "linux",…}
claimedAt: "2022-03-24T14:25:09.701Z"
name: "65608fa2fa98"
nodeID: "93d7f48f-b874-49b9-bf5f-c505c34d5132"
os: "linux"
services: null
state: "current"

**Comment by vkuznecovas** [comment]
It seems that the field is not arriving with the `UpdateNodeInfo` message from the agent.

@MrZammler pointed that it's always NULL on the agent side as well:
https://github.com/netdata/netdata/blob/0b3ee50c76dcc3b8dcdd13cec0e432394d3c6964/database/sqlite/sqlite_aclk_node.c#L55

**Comment by vkuznecovas** [comment]
Right so it seems that way back when in the JSON days of agent <-> cloud interaction, the AMC would receive a message that would contain an array of collectors. These collectors would then get transformed to services on the cloud and passed on as "services".

This mechanism seems to have been lost in translation. 

Solution would be:

1) Agent starts sending the cloud a list of collectors in the `UpdateNodeInfo` message.
2) Cloud takes in the collectors, re-maps them to services.
3) Cloud saves the services in the database for easy future lookups.
4) Cloud passes the services in the `NodeInfoUpdated` message.

**Comment by vkuznecovas** [comment]
Agent ticket: https://github.com/netdata/netdata/issues/12876

**Comment by dimko** [comment]
Re-openning this one as it was incorrectly close. The services icons have been removed from the UI, but grouping by services is still present and doesn't work.

**Comment by dimko** [comment]
Service icons missing related issue in cloud-frontend: https://github.com/netdata/cloud-frontend/issues/2997

**Comment by vkuznecovas** [comment]
Implementing https://github.com/netdata/cloud-frontend/issues/3594 will make the services be visible again once the agent starts sending the collector info.

**Comment by hugovalente-pm** [comment]
this has been fixed, we can even group by Service again on nodes tab

![image](https://user-images.githubusercontent.com/82235632/181803115-033e62f2-cd5c-40f1-93e6-933d9d736c0f.png)
