### ISSUE TITLE
[Bug]:  Grouping headers are difficult to distinguish 

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#417]
### Bug description

When a user **groups by** in nodes table, the headers for each grouping section isn't very visible.

### Expected behavior

Headers for each category should be much more distinguishable

### Steps to reproduce

1. Navigate to Nodes Table view
2. Have a large number of nodes claimed, ideally with different alerts and reachability startes
3. Group by Alert Status

### Screenshots

Group By Alert:

![image](https://user-images.githubusercontent.com/19268853/167003742-ed22509a-d097-45d3-ab81-1d8a7bbd5a05.png)

Group by Service
![image](https://user-images.githubusercontent.com/19268853/167003771-6eb74166-71f0-46d4-8ded-2e17d85a0569.png)

### Desktop

OS:  Linux
Browser Chrome
Browser Version: 100

**Comment by cakrit** [comment]
The grouping functionality has been removed for now.
