### ISSUE TITLE
[Bug]:  Go to chart from a chart with error in custom dashboards loads forever

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#419]
### Bug description

After a user visits the custom dashboards tab and sees a chart with error, if he tries to access the chart in the single node view by clicking the three bullets and go to chart for the errored chart, the single node view loads forever

### Expected behavior

The go to chart option be disabled, or gone, or the single node view loads and shows the affected chart and maybe a reason why it failed.

### Steps to reproduce

1. Claim a node
2. Create a custom dashboard
3. Add a chart in the custom dashboard that has errors
4. Click the three bullets in Chart's header
5. Click the Go To Chart button

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/167138362-3762d773-ca59-489a-8d45-45911c83a71d.png)

![image](https://user-images.githubusercontent.com/19268853/167138416-72a5d882-35ea-4ecb-8b19-0af7326fb6fa.png)

![image](https://user-images.githubusercontent.com/19268853/167138535-9843086a-4c79-4ae9-8ce1-6fbfdb525a8f.png)

### Error Logs

No error logs

### Desktop

OS: Linux
Browser Chrome
Browser 101

**Comment by novykh** [comment]
Same happens for a node tab that's open, but we delete the node, and then try to navigate to that tab.
Maybe we should throw a 404 on such cases, since the node doesn't exist anymore, I believe is the same case with the one on this issue. @hugovalente-pm thoughts?

**Comment by hugovalente-pm** [comment]
@novykh I think so since the node doesn't exist, but this is a different case than this https://github.com/netdata/product/issues/2554#issuecomment-1135460381, right?

can we distinguish between both and have different messages to the user? e.g. saying the node doesn't exist in the War Room

@dionysis-netdata as fyi

**Comment by hugovalente-pm** [comment]
closing this has been released

**Comment by hugovalente-pm** [comment]
this actually isn't fixed

**Comment by hugovalente-pm** [comment]
this is fixed
