### ISSUE TITLE
[BUG] Cannot save charts provided by 3rd party collectors

### ISSUE THREAD

**Issue by jamezrin** [netdata/netdata-cloud#42]
**Describe the bug**	
I cannot save dashboards that have charts provided by 3rd party collectors.

**To Reproduce**	
- Add a chart provided by a 3rd party collector to a netdata's cloud dashboard
- Saving

**Expected behavior**	
I expected it to save and persist between reloads.

**Screenshots**	
As well as the screenshot attached below for the error that is thrown, I also recorded and uploaded this video reproducing the issue.
https://www.youtube.com/watch?v=u1t57t8tg-Q&feature=youtu.be

**Error logs**	
![image](https://user-images.githubusercontent.com/5949554/106189242-4da52280-61a8-11eb-89ad-1e818f06049d.png)

**Desktop (please complete the following information):**	
 - OS: Windows and Linux
 - Browser: Chrome
 - Version: 88

**Additional context**	
It has worked well for around 8-9 days until yesterday, I haven't done anything to netdata in that time.
I tried restarting the netdata service to see if that fixed the issue but no.
This happens in all War Rooms and dashboards, creating a new one doesn't fix the issue.
I tried on an incognito window (without extensions) and the issue still happens.

**Comment by jacekkolasa** [comment]
@jamezrin your discovery about `3rd party collector` helped us a lot, thanks! The fix has been deployed.

**Comment by jamezrin** [comment]
@jacekkolasa Thanks for fixing this issue! I'm glad I helped. 

However, I have been experiencing other issues with netdata cloud since yesterday, I'm now completely unable to see any charts or perform any dashboard operations, the API is returning a lot of timeouts and fetch errors. 

I have tried in multiple browsers, no cache, no extensions that could interfere, etc. Do I need to do something on my nodes for this new deployment of netdata cloud?

Are these problems already known to the netdata team or should I open an issue with more info? 
Thanks in advance.

**Comment by jacekkolasa** [comment]
@jamezrin we have some issues with stability, which are very high priority for us. Your nodes are probably OK, no extra action is needed from your side. :)
When you had problems in Dashboards, have you experienced the same problems in single node-view and Overview? I want to make sure it's a general problem, not only Dashboard - related.

**Comment by jamezrin** [comment]
@jacekkolasa Are you referring to the 3rd party collector chart problems of the issue or the other problems? 

For the first: I could look at charts provided by 3rd party collectors perfectly fine, both in the overview and a dashboard (but couldn't save the dashboard)

For the second: Yesterday I was able to view charts in the overview and the single node view, but I couldn't see any charts in my dashboards or even list the contexts to add a new one (it kept on loading, a bunch of errors in the console). 
As of today, I can see some charts here and there but most of the time I cannot see any charts.

I appreciate the support, if there is anything I can help with let me know :)
