### ISSUE TITLE
[Feat]: Dispel common misconceptions about Netdata limitations by adding static content to the cloud

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#420]
### Problem

Users are commonly asking questions about:
 - [Alert configuration](https://learn.netdata.cloud/docs/configure/common-changes#modify-alarms-and-notifications) (silencing, disabling etc).
 - [Notification methods other than emails](https://learn.netdata.cloud/docs/monitor/enable-notifications#netdata-agent)
 - Additional integrations (mainly [collectors](https://learn.netdata.cloud/docs/agent/collectors/))
 - [Increasing data retention](https://learn.netdata.cloud/docs/configure/common-changes#increase-the-long-term-metrics-retention-period)
 - [Privacy/Where is data stored](https://learn.netdata.cloud/docs/cloud/data-privacy)

Users are also completely unaware of our most advanced features such as
 - [Exporting to other time series DBs](https://learn.netdata.cloud/docs/export/external-databases)
 - [Streaming and Replication](https://learn.netdata.cloud/docs/metrics-storage-management/how-streaming-works)

### Description

In addition to the in-app guides we are already building, we should add in appropriate places in Netdata cloud CTAs that will inform users about these capabilities of the Netdata agent. 

### Importance

must have

### Value proposition

Users with no previous exposure to the agent will discover how powerful it is. 

### Proposed implementation

Suggested links for the various CTAs are in the Problem statement. Here are suggestions as to where to put what:

Purely static content:
 - [ ] Wherever appropriate for every alert, but especially somewhere in Alerts/Alert Configurations add CTAs to configure the alerts that appear on the cloud (change limits, disable). 
 - [x] Under Manage Space/Notifications: CTA to Notification methods available on the agent. There was also suggestion to list all notification methods available via the agent, but that would take more time.
 - [x] Add an "Add more charts" CTA that leads to the collectors page right under the "Sections and Charts" search, below the info "Showing X of total Y" charts. 
<img width="215" alt="image" src="https://user-images.githubusercontent.com/43294513/167885356-76ee9951-6e4a-46b6-a442-1051c5782794.png">

 - [ ] Bring back to the Netdata cloud charts the CTA below to replace the "No data for this period". Add to it a link to the Privacy/Where data is stored, so there can be no misunderstandings. The "history" CTA is obsolete by now, almost everyone is probably using dbengine. Perhaps try to also pass the message here that for very long retention, people should export metrics to another timeseries DB and link to that doc page.  Sample new CTA in the next bullet.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/43294513/167887092-64edf2a9-4047-4562-bdf9-149f0465d6e1.png">

  - [ ] Perhaps: In the datetimepicker predefined periods, add a similar CTA (probably after the "Last 7 Days" Option) as the one described above. Summary of suggested CTA:

Want to extend your history of real-time metrics? If clicked, expands or pops up the following:
[We don't store metric data on the cloud](https://learn.netdata.cloud/docs/cloud/data-privacy), so you will need to configure the Netdata Agent to [change how long Netdata stores metrics](https://learn.netdata.cloud/docs/store/change-metrics-storage). If you are concerned about performance in production nodes, set up [streaming/replication](https://learn.netdata.cloud/docs/metrics-storage-management/how-streaming-works). For months or years of retention, [export metrics to external time-series databases](https://learn.netdata.cloud/docs/export/external-databases).

This text is too long, so it may need to be expandable, based on a click to the question. 

More dynamic content:
- [x] ~~The "Search charts" could be extended to also search inside the collectors documentation, or at least in an index of all collectors. So e.g. I'm searching for "oracle", there's nothing currently collected, but I get back results that will tell me how to configure the agent to access my oracle db. ~~ Team decided not to do this.
- [x] Streaming/replication CTAs were already planned to be added next to the "replication factor" information, which is currently not visible.

**Comment by hugovalente-pm** [comment]
> Bring back to the Netdata cloud charts the CTA below to replace the "No data for this period". Add to it a link to the Privacy/Where data is stored, so there can be no misunderstandings. The "history" CTA is obsolete by now, almost everyone is probably using dbengine. Perhaps try to also pass the message here that for very long retention, people should export metrics to another timeseries DB and link to that doc page. Sample new CTA in the next bullet.

@ktsaou @cakrit on this there is this ticket under discussion about bringing back that message and trying to review which CTAs we want https://github.com/netdata/product/issues/2390 it was agreed to keep the previous design (less intrusive than what was proposed, sample below) but we wanted to have one CTA so not sure we can put here:
* link to Privacy/Where data is stored
* increasing retention - we can use an existing page, but we had a discussion were we would need rework on docs https://github.com/netdata/product/issues/2390#issuecomment-1043272367
* pass the message here that for very long retention, people should export metrics to another timeseries DB - this last one U think we should not put it on the charts, since it won't make the chart's history longer

![image](https://user-images.githubusercontent.com/82235632/168870112-d30c38bc-c6c8-482d-8aeb-04344723c557.png)

> Perhaps: In the datetimepicker predefined periods, add a similar CTA (probably after the "Last 7 Days" Option) as the one described above. Summary of suggested CTA:
Want to extend your history of real-time metrics? If clicked, expands or pops up the following:
[We don't store metric data on the cloud](https://learn.netdata.cloud/docs/cloud/data-privacy), so you will need to configure the Netdata Agent to [change how long Netdata stores metrics](https://learn.netdata.cloud/docs/store/change-metrics-storage). If you are concerned about performance in production nodes, set up [streaming/replication](https://learn.netdata.cloud/docs/metrics-storage-management/how-streaming-works). For months or years of retention, [export metrics to external time-series databases](https://learn.netdata.cloud/docs/export/external-databases).

For this one we may be have more space, but not sure how this would look like on the datetime picker.
@christophidesp @vinnygats @dionysis-netdata what do you think?

**Comment by hugovalente-pm** [comment]
> More dynamic content:
> - The "Search charts" could be extended to also search inside the collectors documentation, or at least in an index of all collectors. So e.g. I'm searching for "oracle", there's nothing currently collected, but I get back results that will tell me how to configure the agent to access my oracle db.

@cakrit not sure this is the best approach, I think I remember on a brainstorming session @novykh suggesting an "overall" search engine across all Netdata Cloud where it would make more sense to include our docs (example given was this https://stripe.com/docs/api)

what do you think @novykh ?

**Comment by dionysis-netdata** [comment]
> Perhaps: In the datetimepicker predefined periods, add a similar CTA (probably after the "Last 7 Days" Option) as the one described above. Summary of suggested CTA:
> Want to extend your history of real-time metrics? If clicked, expands or pops up the following:
> [We don't store metric data on the cloud](https://learn.netdata.cloud/docs/cloud/data-privacy), so you will need to configure the Netdata Agent to [change how long Netdata stores metrics](https://learn.netdata.cloud/docs/store/change-metrics-storage). If you are concerned about performance in production nodes, set up [streaming/replication](https://learn.netdata.cloud/docs/metrics-storage-management/how-streaming-works). For months or years of retention, [export metrics to external time-series databases](https://learn.netdata.cloud/docs/export/external-databases).
> 
> For this one we may be have more space, but not sure how this would look like on the datetime picker.
> @christophidesp @vinnygats @dionysis-netdata what do you think?

Sure, if guys can come up with a clean design

**Comment by cakrit** [comment]
> @cakrit not sure this is the best approach, I think I remember on a brainstorming session @novykh suggesting an "overall" search engine across all Netdata Cloud where it would make more sense to include our docs (example given was this https://stripe.com/docs/api)

@hugovalente-pm We have the overall search in the KC Bot. This doesn't cover the specific need. We want a way for users to know that even though the metric they are looking for isn't there, they may be able to add it very easily, by configuring the relevant collector. An alternative is that if the search doesn't return results, we point them to https://learn.netdata.cloud/docs/agent/collectors/

i.e. use the following to promote the hundreds of collectors we have available:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/43294513/169549452-6ca566db-90d2-4df0-a8e3-7e74cfaa5119.png">

**Comment by cakrit** [comment]
> > Perhaps: In the datetimepicker predefined periods, add a similar CTA (probably after the "Last 7 Days" Option) as the one described above. Summary of suggested CTA:
> > Want to extend your history of real-time metrics? If clicked, expands or pops up the following:
> > [We don't store metric data on the cloud](https://learn.netdata.cloud/docs/cloud/data-privacy), so you will need to configure the Netdata Agent to [change how long Netdata stores metrics](https://learn.netdata.cloud/docs/store/change-metrics-storage). If you are concerned about performance in production nodes, set up [streaming/replication](https://learn.netdata.cloud/docs/metrics-storage-management/how-streaming-works). For months or years of retention, [export metrics to external time-series databases](https://learn.netdata.cloud/docs/export/external-databases).
> > For this one we may be have more space, but not sure how this would look like on the datetime picker.
> > @christophidesp @vinnygats @dionysis-netdata what do you think?
> 
> Sure, if guys can come up with a clean design

@hugovalente-pm and @dionysis-netdata in https://github.com/netdata/product/issues/2390 I added a suggestion for the docs that will help minimize the CTA to a single link. Just need an approval from ktsaou, I will ping him in Slack too.

**Comment by hugovalente-pm** [comment]
>@hugovalente-pm We have the overall search in the KC Bot. This doesn't cover the specific need. We want a way for users to know that even though the metric they are looking for isn't there, they may be able to add it very easily, by configuring the relevant collector. An alternative is that if the search doesn't return results, we point them to https://learn.netdata.cloud/docs/agent/collectors/

yes @cakrit it was clear and it is really helpful, just not sure of the effort of the search _spilling over_ to our learn page. I'll try to check with @novykh this

the alternative we are already doing, adding the CTA to the bottom of the search bar, probably we could also review text where it says `No results were found` but would probably not add a link to the collectors page, because we would have the same CTA very close by

see what we have on staging, ready to be released on Mon.

![image](https://user-images.githubusercontent.com/82235632/169561269-7e82e648-148a-4183-bd90-c30422e6f35e.png)

If we added another CTA on the message it would be very close
![image](https://user-images.githubusercontent.com/82235632/169561319-62b3b921-b212-4c6a-a1db-742f4515450b.png)

**Comment by cakrit** [comment]
yes @hugovalente-pm I would add to the main screen under the try again with different conditions also a marketing message, with an additional way to avoid the page being a dead end, more room there. The CTA is essentially the same, but we have room to tell them something more than just "Add more charts", which they may not notice with all the clutter in the UI.

**Comment by cakrit** [comment]
There was one more idea, from @ralphm or @amalkov (don't remember), to poke people to add a second node as soon as possible. Where we see that they only have one node (probably Nodes tab and Overview screen), ask them to claim a 2nd node to get the full benefits. 

I'm telling them to do so in the in-app engagement for the overview tab and kind of point them to that in the last step of the quick tour.

**Comment by hugovalente-pm** [comment]
@cakrit added the follow-up ticket for that here Add CTA also on central message when no charts are available netdata/cloud-frontend#3432

**Comment by hugovalente-pm** [comment]
> Streaming/replication CTAs were already planned to be added next to the "replication factor" information, which is currently not visible.

@cakrit for this one we have a link to docs and we have added the tooltip, where you thinking about anything else?

<image src="https://user-images.githubusercontent.com/82235632/171144916-e781c9d2-fa98-44c0-a5bc-c3dcc41adefd.png" width="50%" height="50%"/>

**Comment by cakrit** [comment]
@hugovalente-pm looks good

**Comment by amalkov** [comment]
> There was one more idea, from @ralphm or @amalkov (don't remember), to poke people to add a second node as soon as possible. Where we see that they only have one node (probably Nodes tab and Overview screen), ask them to claim a 2nd node to get the full benefits.
> 
> I'm telling them to do so in the in-app engagement for the overview tab and kind of point them to that in the last step of the quick tour.
Yes, we discussed this, basically, the idea is on the Nodes tab to display a notification "Please add at least two nodes" in case the War room has only one node available (active + stale), offline nodes needs to be ignored.

Having such information inside in-app engagement is really good, however, users can not see this message all the time and can forget about it.

**Comment by hugovalente-pm** [comment]
most of the things were done, there is no action on more hints/insights
