### ISSUE TITLE
[Bug]: No way to delete node

### ISSUE THREAD

**Issue by tiliarou** [netdata/netdata-cloud#422]
### Bug description

There is absolutely no way to delete a node from netdata cloud

### Expected behavior

Ability to delete node (super basic)

### Steps to reproduce

1. Go to war room
2. Nothing, you can't delete a node...

### Desktop

Browser Version [e.g. 22]

**Comment by ivangergo3** [comment]
Hi @tiliarou , 
Are you referring to removing nodes from the General room?
If so, we are working on it to make it happen

**Comment by tiliarou** [comment]
> Hi @tiliarou , Are you referring to removing nodes from the General room? If so, we are working on it to make it happen

Yes I am, it's like super basic that I still don't believe that it's not implemented yet...

**Comment by ivangergo3** [comment]
We are working on removing the nodes from the General room, but General is a special room so you can remove nodes from other rooms, but General should have all your nodes.
The remove functionality to remove nodes from General is getting ready. We will test it this week

**Comment by realEthanZou** [comment]
@ivangergo3 Now that there are live/stale/offline categories for nodes, is there a way to remove a node or label them as stale?

**Comment by dimko** [comment]
Nodes deletion from every room is live for **Unreachable** nodes. @tiliarou @realEthanZou can you please try it? Please keep in mind that stale != offline and they can't be removed.

**Comment by RoggerFabri** [comment]
> Nodes deletion from every room is live for Unreachable nodes. @tiliarou @realEthanZou can you please try it? Please keep in mind that stale != offline and they can't be removed.

Hey @dimko, that works for me, thanks :)

**Comment by tiliarou** [comment]
> Nodes deletion from every room is live for **Unreachable** nodes. @tiliarou @realEthanZou can you please try it? Please keep in mind that stale != offline and they can't be removed.

works well ! thanks
