### ISSUE TITLE
[Bug]: Critical filter is always selected after switching tabs 

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#423]
### Bug description

Only critical alerts are displayed after user switches between the alerts tab and any other tab and no alert filters are selected at all in the 1st place.

### Expected behavior

The previous filter selection should be remembered and displayed

### Steps to reproduce

1. Claim a node
2. Navigate to Alerts page for that room the node lives into
3. Select NO filters from the alert filtering sidebar
4. Switch to Overview screen tab
5. Switch back to Alerts tab
6. Critical alerts checkbox is selected even though it shouldn't

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/168264562-8dadf0eb-a840-4fc1-ab0a-a0459e5fc083.png)

### Desktop

OS: MacOS
Browser: chrome
Browser Version:  101

**Comment by dimko** [comment]
Well... this seems to be a feature and not a bug 😛 When you click the tab **critical** is next to the tab name so you filter by critical when you click it... 🤯 

We'll probably remove this functionality, so leaving it open for this reason.

**Comment by car12o** [comment]
I looked to it as a bug for months, and only found it was a feature a couple of weeks back :smile:

**Comment by cakrit** [comment]
When I repeatedly click on the amber "6" below...

<img width="108" alt="image" src="https://user-images.githubusercontent.com/43294513/172223351-661b25a7-441f-4057-bca6-64ceefdab394.png">

I shouldn't be seeing the filter change constantly to include or exclude warnings, but it does. It doesn't look like much of a feature to me. Can't we just remember the previous filter? 

Alternatively, if this behavior remains, then the icon in the tab should indicate that we have changed something (e.g. make the warnings a different shade of amber when they are hidden).

**Comment by car12o** [comment]
@cakrit I don't see it as a feature either and I remember we all agreed during a daily that we will remove this functionality (include or exclude alarm status when clicking on these badges). Most likely this is not done yet due to the workload we currently have on the alarms FE team.
cc: @sashwathn @amalkov @jacekkolasa

**Comment by amalkov** [comment]
@cakrit confirming, we agreed to remove "pre-filter" capability from the tab, going to be completed by @jacekkolasa

**Comment by sashwathn** [comment]
@jacekkolasa : Will be working on this shortly to get this filtering disabled.

**Comment by jacekkolasa** [comment]
fixed
