### ISSUE TITLE
[Bug]: Node works in overview but not in single node dashboard

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#424]
### Bug description

On single node dashboards I get this response to data queries:

```
{ "errorMsgKey": "ErrNoQueryableNodeInstanceFound", "errorMessage": "no queryable node instance for chart or context", "errorCode": "uohY73Xcw4-417159821" }
```

On the overview dashboard, everything works.

### Expected behavior

The node instance is online and queriable, since the overview dashboard works.
It should work for single node dashboards too.

### Steps to reproduce

I am not sure.
I know that there is a parent, which is offline.
The same behavior happens, even when the parent is online and has the node connected to it.

In the single node dashboard, I see the `/charts` call being sent to the node. However, no `/data` queries reach the node.

### Desktop

Browser Version [e.g. 22]

**Comment by ktsaou** [comment]
@papazach @vkuznecovas please check this.

**Comment by 1ohnny** [comment]
Same problem here. I've created 2 new nodes (debian 11) - no data in charts. Also upgraded existing node (which stopped working after change of netdata.cloud architecture, but had no time to solve it before), also no data appearing for it.
All 3 nodes are "online" and works ok.
All 3 nodes are assigned to war room.
I have also custom dashboards with multiple graphs from multiple nodes (cpu + ram for all 3 nodes), where also can't see any data.
I can see many 404 requests in browser for every chart with error as posted by @ktsaou
