### ISSUE TITLE
[Bug]: Composite chart display name is wrong when we have multiple chart instances per node

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#426]
### Bug description

When we have multiple chart id/names for the same context in a single node, we can't use any of the display names for any of the charts, as they contain information identifying the instance. We should find a way to show a display name at the context level. @ilyam8 should be able to help.

### Expected behavior

Don't show instance information in the composite chart's display name, when it includes multiple instances. Better to not show a display name at all, until we can show a proper one.

### Steps to reproduce

1. Scroll down to any chart with multiple instances per node (usually disks, mountpoints, network interfaces).
2. Note the display name to the left of the context and units.

### Screenshots

![image](https://user-images.githubusercontent.com/43294513/168654594-f0caf889-9bfc-4a4e-a76c-93e4619e72e3.png)

### Desktop

Browser Version [e.g. 22]

**Comment by ilyam8** [comment]
@cakrit I think we just shouldn't show a chart id on composite charts. Why do we need it?

**Comment by cakrit** [comment]
Of course we shouldn't show chart id. What I don't know is if there's a simple rule (e.g. remove everything within paretheses) that will fix the display name. I think I have seen display names that also contain an instance identifier, but I may be wrong. Definitely the quickest win is to just strip out " \(.*\)"

**Comment by ilyam8** [comment]
Probably I am missing something:
 - A chart id must be globally unique (within a Netdata instance).
 - It means that usually, ids have some instance-specific data (disk, mount point, network interface).
 - The value in `()` on the overview page is, I guess, the first chart id from the aggregated group.
 - It never makes sense to show `()` (using the same pattern, the value is a chart id) on the overview page.

> Definitely the quickest win is to just strip out " (.*)"

Yes.

**Comment by hugovalente-pm** [comment]
this is linked to https://github.com/netdata/netdata-cloud/issues/253 and https://github.com/netdata/product/issues/2052

@ilyam8 's suggestion works for most of the cases, but we have the isuse of fping that wouldn't be sorted by that.
@papazach these chart titles are provided by Cloud BE to FE, right?

**Comment by ilyam8** [comment]
> but we have the isuse of fping that wouldn't be sorted by that

I read the linked issue but didn't understand what exactly you mean @hugovalente-pm. Can you explain?

The fping chart titles (e.g. "Fping Latency for X" => "Fping Latency") issue fix is https://github.com/schweikert/fping/pull/253

**Comment by hugovalente-pm** [comment]
ok, didn't know the hostname is to be removed from fping charts titles. that for sure solves the issue on the title of these

there is a further issue with fping then on section names, because sections are also showing a hostname and on Cloud Overview page this is "generic", the hostname specific charts can be seen if you change "Group by" to `instance`
![image](https://user-images.githubusercontent.com/82235632/169025010-51a54149-bd9c-4c55-832e-369101013210.png)

**Comment by hugovalente-pm** [comment]
@TonyPath @juacker @papazach this needs to be tackled from BE, because it is BE that provides these to FE
can we try to do something like @ilyam8 was suggesting [here](https://github.com/netdata/netdata-cloud/issues/426#issuecomment-1129110605)? 

Another option could probably be doing something similar to the mutations we do for disks, network interfaces, mount points families, but this would be a step back on what we want to achieve - Expose more details on Disks, Mount Points, Network Interfaces and other sections where we group under all #Expose more details on Disks, Mount Points, Network Interfaces and other sections where we group under all #275

**Comment by cakrit** [comment]
> > but we have the isuse of fping that wouldn't be sorted by that
> 
> I read the linked issue but didn't understand what exactly you mean @hugovalente-pm. Can you explain?
> 
> The fping chart titles (e.g. "Fping Latency for X" => "Fping Latency") issue fix is [schweikert/fping#253](https://github.com/schweikert/fping/pull/253)

No, we can't wait for the source code to be fixed and the new version of `fping` to be deployed to the entire world for the title to be fixed. Please strip it with a regular expression or something, we need to problem corrected ASAP.

**Comment by ilyam8** [comment]
I don't know how to do it, we just [exec fping](https://github.com/netdata/netdata/blob/044d4c9d916fbc94a5a00324ab377d56b4937a29/collectors/fping.plugin/fping.plugin.in#L199). @netdata/agent-sre can you help us? Asking you because you are much more experienced with bash.

**Comment by cakrit** [comment]
To get back to how to handle this issue though, the point is to not go through the rabbit hole of the issues linked to #253 
I'm not talking about making the Overview more useful/useable, but ONLY about removing the completely wrong names linked to each context, by taking out what's in the parentheses and then also going through the contexts where multiple instances appear as different sections (e.g. httpcheck, fping, apache, bind etc.) to ensure that nothing else contains weird identifiers in the title. 

If it's a matter of a couple of weeks to completely resolve the issue and have a brand new version where all the cases are handled well and the filtering is available, I suppose we can wait. If not, we should provide a patch ASAP.

**Comment by hugovalente-pm** [comment]
@juacker was trying to find this also on our PROD space but seems it was fixed already

**Comment by cakrit** [comment]
Here you go:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/43294513/171870817-25d9c3fa-9da8-4b28-b604-09c0f2675762.png">

**Comment by cakrit** [comment]
Checking the others, it looks like httpcheck does NOT have this issue, as the chart titles don't have the name
So it's really just `fping` that we have an issue with. Closing this one, @ilyam8 let's continue in https://github.com/netdata/netdata-cloud/issues/253
