### ISSUE TITLE
[Bug]: Dimensions can appear with the same color

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#427]
### Bug description

Not sure how it happened, but in the screenshot below you can see two dimensions in a single chart with the same exact color: `background-color: rgb(102, 170, 0);`

### Expected behavior

It should be completely impossible to show the same exact color for the dimensions shown in a chart. 

### Steps to reproduce

No idea how to reproduce. Went back to the same exact chart in the same room and the colors were back to normal (green and red). We should just add some kind of failsafe in the FE to ensure it can't happen. 

### Screenshots

![image](https://user-images.githubusercontent.com/43294513/168655195-e6243ca9-18c8-4db2-b0ec-83673b54f824.png)

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
> just add some kind of failsafe in the FE to ensure it can't happen.

@cakrit not sure what you mean with the failsafe.
@novykh do you think there is something we can do?

**Comment by novykh** [comment]
Let's see it after the migration. It should be fixed, no? I mean did you see this happening after the latest releases?

**Comment by hugovalente-pm** [comment]
no @novykh, I didn't see it happen again but let's confirm as you say after the migration

on the part if there is anything we can do, I was trying to refer to the "failsafe" measure. is there a way we could prevent this from happening? the case where two dimensions got the same colour was because of how the dimensions were sent to FE by BE/Agent or something else?

**Comment by hugovalente-pm** [comment]
@novykh I actually see a current case where this is happening now in our, even the dials on top  [PROD War Room](https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/overview#chartName=menu_net&appliedFilteredIds=&reachableNodesIds=&staleNodesIds=&unreachableNodesIds=&filteredNodesSearchParams=&metrics_correlation=false&after=-900&before=0&utc=Europe%2FBucharest&offset=%2B3&timezoneName=E.%20Europe)

![image](https://user-images.githubusercontent.com/82235632/175093194-3bb03acc-1424-40c5-b68b-9bf55f32a8a3.png)
