### ISSUE TITLE
[Bug]: Plots in overview stay hanged in "Loading"

### ISSUE THREAD

**Issue by pcm32** [netdata/netdata-cloud#429]
### Bug description

While all tabs seem to see nodes correctly, the plots in overview and dashboards are stuck in loading and no data is displayed. This was working well yesterday up a until 14:00 UK time if not mistaken, maybe a side effect of the fix done for the syncing issue?

### Expected behavior

That the plots in overview and dashboard show some content.

### Steps to reproduce

1. Go to the overview tab in any of my war rooms (which contains both clients running on VMs directly and on k8s)

### Screenshots

![image](https://user-images.githubusercontent.com/368478/168759647-f5bab13a-40df-48cc-8a97-820e150449df.png)

### Desktop

OS: macOS
Browser: Chrome
Browser Version: 100.0.4896.127

**Comment by dimko** [comment]
The initial issue that made the cloud unusable has been resolved, however we still have cases where charts aren't received from the agent and take a long time to sync to cloud. Will close this and you can track the status of the aforementioned issue [here](https://github.com/netdata/netdata-cloud/issues/430)
