### ISSUE TITLE
Alarm without any way to turn it off

### ISSUE THREAD

**Issue by therealgilles** [netdata/netdata-cloud#43]
I have an alarm on my dashboard but I don't see any way to address it or turn it off.

Here is a screenshot:
<img width="640" alt="Screen Shot 2021-01-28 at 4 11 12 PM" src="https://user-images.githubusercontent.com/18076992/106214485-b62dd880-6183-11eb-92e2-8dc4e202fd2f.png">

The alarm does not even say what it's about. How am supposed to handle it? Thanks for any insight/advice.

**Comment by cakrit** [comment]
This should definitely not be happening. When you click on the three dots to "View alarm info", what does it show?
Also, please give us the first part of the URL, that shows the space and room, so we can investigate further and clean it up manually. e.g. `https://app.netdata.cloud/spaces/netdata-cloud/rooms/general`.

**Comment by therealgilles** [comment]
It shows this:
<img width="639" alt="Screen Shot 2021-02-01 at 10 01 48 AM" src="https://user-images.githubusercontent.com/18076992/106498814-a3adea80-6474-11eb-9b7a-2ea7466cdb22.png">

Here is the url:
`https://app.netdata.cloud/spaces/svsd-llc/rooms/general/`

**Comment by cakrit** [comment]
@nicolasparada/@harrizbs plz check and clean up. This is garbage. Let's see if we can find similar cases across all workspaces/rooms as well.

**Comment by nicolasparada** [comment]
May be the same as this https://github.com/netdata/netdata-cloud/issues/35

**Comment by nicolasparada** [comment]
Hi. We recently did an automatic fix for all nodes with these kind of problems. Can you confirm if you are still seeing this issue?

**Comment by therealgilles** [comment]
I confirm the error notification is gone. Thank you!

**Comment by nicolasparada** [comment]
Great 😀
Thank you for your help 😉
