### ISSUE TITLE
[Feat]: Structure the composite chart bar in a way as if it was being explained in written English

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#432]
### Problem

The way we present the composite chart bar and its configuration options makes it difficult to understand and interact with to make the chart provide the data we need.

Examples:

![image](https://user-images.githubusercontent.com/82235632/169318760-34afc806-ad4e-4ebb-b357-7aafbdff34fb.png)

![image](https://user-images.githubusercontent.com/82235632/169318884-71942b86-88be-41e9-be30-f9bf94ac24af.png)

![image](https://user-images.githubusercontent.com/82235632/169319080-50269893-7f75-485c-aaca-57d250d51216.png)

![image](https://user-images.githubusercontent.com/82235632/169319368-93676a7a-8de0-4712-9eb3-afabaeac7907.png)

### Description

**The way it currently is presented its showing:**
1. The aggregation function to be applied over the data sources (instances)
1. The dimensions available on the data sources (where user can also filter which ones to show)
1. The data sources (where the data is retrieved from, the instances from the contributing nodes)
1. The nodes that contribute with data for the chart
1. Group by option for the chart: dimensions, nodes, instances, k8s chart labels

**The way it should be presented to make it easier to read:**
1. Group by option for the chart: dimensions, nodes, instances, k8s chart labels
1. The aggregation function to be applied over the data sources (instances)
1. The data sources (where the data is retrieved from, the instances from the contributing nodes)
1. The nodes that contribute with data for the chart
1. The dimensions available on the data sources (where user can also filter which ones to show)
1. The aggregation function over time, for each of the metrics contributing to this query
   * This is needed when `update_every` and `view_update_every` are not the same, meaning that sometime aggregation is applied by the agent
   * for now we apply by default the `average`
   * for all options available on the agent check [Queries - Grouping methods](https://github.com/netdata/netdata/tree/master/web/api/queries#grouping-methods)

### Importance

must have

### Value proposition

Users better understand what data they have is being displayed on a composite chart and change its conifugrations as required in an easier way

### Proposed implementation

Some examples of expected outcomes:

| Group by | Aggregate function over data sources | Contributing nodes | Dimensions available from data sources | Time Aggregation (when applicable |
| -- | -- | -- | -- | -- |
| Group by {node [v]} | the AVERAGE [v] of {2 instances [v]} | from {2 nodes [v]} | sum {2 dimensions [v]} | each as AVERAGE [v] every {5m,10s, etc.} |
| Group by {dimension [v]} | the AVERAGE [v] of {2 instances [v]} | from {2 nodes [v]} | select {2 dimensions [v]} | each as AVERAGE [v] every {5m,10s, etc.}
| Group by {instance [v]} | {2 instances [v]} | from {2 nodes [v]} | sum {2 dimensions [v]} | each as AVERAGE [v] every {5m,10s, etc.} |
| Group by {\<whatever\> [v]} | {1 instance [v]} | from {2 nodes [v]} | sum {2 dimensions [v]} | each as AVERAGE [v] every {5m,10s, etc.} |
| Group by {k8s labels [v]} | {the AVERAGE [v] of {2 instances [v]} | from {2 nodes [v]} | sum {2 dimensions [v]} | each as AVERAGE [v] every {5m,10s, etc.} |

**Comment by burbuli8ra** [comment]
Released on [v2.34.0](https://github.com/netdata/cloud-frontend/releases/tag/2.34.0)
