### ISSUE TITLE
[Feat]: Allow the definition of the aggregation function over time on composite charts bar

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#433]
### Problem

Currently, there is no way for a user to define what type of aggregation function over time he wants to have applied when a Node is providing data for a composite chart, this when `update_every` and `view_update_every` are not the same (for a point in the chart some aggregation had to be applied).

This is a limitation because we are, by default, applying the `average` aggregation function and if a user wants to, for example, get the `max` value of a data series he can't.

### Description

Allow the user to specify aggregation function over time, for each of the metrics contributing to a composite chart.

From the agent API on [Queries - Grouping methods](https://github.com/netdata/netdata/tree/master/web/api/queries#grouping-methods) we have the following options:
![image](https://user-images.githubusercontent.com/82235632/169499852-11ae401c-2b7e-4a21-80c6-37a63f635394.png)

Note: This is only needed when `update_every` and `view_update_every` are not the same

### Importance

really want

### Value proposition

By adding this feature we will allow users to tweak what aggregations to be applied and better control what data they want to see on the charts.

### Proposed implementation

This ticket needs to be tackled after [Feat]: Structure the composite chart bar in a way as if it was being explained in written English #432 .

We want to have a dropdown menu on the `Time Aggregation` component where we specify something like `each as AVERAGE [v] every {5m,10s, etc.}`

The default option to be selected is `average`

**Comment by hugovalente-pm** [comment]
@ktsaou on a previous ticket about this the options to be available had been restricted to `min`, `max` and `average` https://github.com/netdata/product/issues/1995.
do you see any reason why we should just limit to those?

**Comment by hugovalente-pm** [comment]
it is noticed that we have work to do on the tooltip since because of the default we had `View point: average 47s`

![image](https://user-images.githubusercontent.com/82235632/173770638-5c94abe3-c3c7-4cef-9839-736d3a70502a.png)

Our aggregation function passed to the agent was by default average, but we now introduced more

![image](https://user-images.githubusercontent.com/82235632/173770713-4b90adc6-8a6e-475f-a4f5-bcba676144b7.png)

the part of  `average` will need to be updated based on the time aggregation function selected

**Comment by jjtsou** [comment]
https://github.com/netdata/charts/pull/105 tooltip update

**Comment by hugovalente-pm** [comment]
released
