### ISSUE TITLE
[Bug]: Docker instructions to connect node may get cut

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#435]
### Bug description

Can't see all the instructions, or the copy button.

### Expected behavior

Need to be able to scroll to see all the instructions

### Steps to reproduce

Go to a room with no nodes and select Docker.

### Screenshots

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/43294513/169565989-b3f6a849-429d-4bdb-a9bf-a140463d6ae3.png">

### Desktop

Browser Version [e.g. 22]

**Comment by burbuli8ra** [comment]
Released on [v2.30.2](https://github.com/netdata/cloud-frontend/releases/tag/2.30.2)
