### ISSUE TITLE
[Bug]: Adding a chart to custom dashboard when no reachable nodes available crashes

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#436]
### Bug description

500 error screen is displayed without any console error in the Frontend  when user tries to add a chart in a custom dashboard and no reachable nodes exist in this room.

### Expected behavior

The 500 page shouldn't be displayed. The nodes selection dropdown should have all values greyed out and disabled, or the option to add a chart should be disabled in the 1st place.

### Steps to reproduce

1. Claim a node in a Space/Room
2. Kill the node so it becomes unreachable
3. Add a custom dashboard
4. Add a chart to the newly created custom dashboard

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/169783577-5b014306-3e18-4032-b962-35559560b057.png)

### Error Logs

No error logs

### Desktop

OS: MacOs
Browser: Chrome
Browser Version: 101

**Comment by hugovalente-pm** [comment]
@jjtsou as discussed when all the nodes are unreachable we should display a different message and block the add chart buttons, let's use the same graphics as when there aren't charts but a different message

>You don't have any available node to retrieve charts from. Please verify your nodes' state and/or connect a new node to Netdata Cloud

also let's add the dashboard title and hamburguer menu here (the three dots)

<image src="https://user-images.githubusercontent.com/82235632/170230900-15f3083b-2ffd-406a-bfea-b84de09149d6.png" width="50%" height="50%"/>

**Comment by jjtsou** [comment]
https://github.com/netdata/cloud-frontend/pull/3446

**Comment by dimko** [comment]
@jjtsou this doesn't seem to work as expected. When there are no reachable nodes in the room when trying to add dashboards it's stuck in a never ending loading page.

**Comment by dimko** [comment]
It's strange. It doesn't happen with all Unreachable nodes 🤔 The node I tried to add reports as unreachable but we try to query charts for it, so I guess this loading in dashboards happen due to the invalid state of the node, probably the sanitization script hasn't run yet to clear it.

I will accept and close this as the functionality itself seems to be fixed and the issue described above is a side effect of a bigger malfunction. Will re-open it if extra things are needed to enhance the check applied here.

**Comment by dimko** [comment]
fixed on **release/2.30.5** of cloud-frontend
