### ISSUE TITLE
[Bug]: Missing charts on Netdata Cloud

### ISSUE THREAD

**Issue by tkatsoulas** [netdata/netdata-cloud#437]
### Bug description

This is a follow up issue from this https://community.netdata.cloud/t/apache-configuration-no-work-threads-information-available/2912 ticket. 

The Netdata Agent collect all the metrics about Apache (apache module from go.d.plugin) and you can query the actual data from the Agent's API. Some of the charts though are not available in Netdata Cloud (to be more specific the charts about apache_local.workers).

### Expected behavior

Netdata Cloud to present all the charts for the Apache.

### Steps to reproduce

1.
2.
3.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@tkatsoulas this seems a similar issue to this one https://github.com/netdata/netdata-cloud/issues/430

**Comment by dimko** [comment]
Closing this as duplicate. We can track it through https://github.com/netdata/netdata-cloud/issues/430
