### ISSUE TITLE
[Bug]: Incorrect list of dimensions shown on mouseover of sparkline in Nodes view

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#439]
### Bug description

The little info that appears when you hover over a sparkline chart on the Nodes view shows Context, Dimensions and Aggregate Funtion. 

The content of Dimensions is wrong, as it always lists every dimension, regardless of whether the chart is based on All Dimensions or on a subset of them. 

### Expected behavior

On hover we should be seeing the dimensions really included in the chart

### Steps to reproduce

1. Add two charts of system.cpu, one only with dimension `idle` and one for `All` dimensions
2. Hover over the two charts and look at the text after the "Dimensions"

**Comment by hugovalente-pm** [comment]
@shyamvalsan moving this to Mgmnt & Navigation, the revamp of the Nodes tab was/is being tackled inside this team's scope

**Comment by burbuli8ra** [comment]
Released on [v2.35.4](https://github.com/netdata/cloud-frontend/releases/tag/v2.35.4)
