### ISSUE TITLE
[BUG] Critical Alert is being reported as Warning

### ISSUE THREAD

**Issue by Slind14** [netdata/netdata-cloud#44]
Critical is reported as Warning

![image](https://user-images.githubusercontent.com/3914677/107160660-de91b000-6997-11eb-95f4-46d8c1643be6.png)

**Comment by jacekkolasa** [comment]
@Slind14 Thanks for submitting the issue. Did the value reached `98`? If not, then it's expected to see it as `warning` in this case. Reference: https://learn.netdata.cloud/docs/agent/health/reference#special-use-of-the-conditional-operator

**Comment by Slind14** [comment]
ahh I thought it should start at 90.
