### ISSUE TITLE
[Bug]: Invalid re-direct after refreshing page following custom dashboard creation

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#441]
### Bug description

If user refreshes page immediately after creating a custom dashboard he is re-directed to Dashboards tab and sees an invalid link for dashboard error message.

### Expected behavior

After user refreshes the page he should land on the page he previously was on

### Steps to reproduce

1. Login to netdata cloud
2. claim an agent
3. create a custom dashboard
5. save custom dashboard
6. refresh the page

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/171020183-d452813f-cc96-438a-9fe2-cfd2cf68a7ae.png)

### Desktop

OS: MacOs
Browser chrome
Browser Version 101

**Comment by hugovalente-pm** [comment]
@dimko is this somehow related to the custom dashboard issue you mentioned on yesterday's daily?

**Comment by dimko** [comment]
@hugovalente-pm no, the issue mentioned yesterday and fixed was about auto-closing the dashboard renaming modal after user saves the changes
