### ISSUE TITLE
[Bug]: Go to chart from a custom dashboard seldom works

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#443]
### Bug description

I played a lot adding charts to a custom dashboard and clicking on the "go to chart" from them:
<img width="126" alt="image" src="https://user-images.githubusercontent.com/43294513/171427960-a660384b-32c2-4579-aba9-cd7d1ced11e0.png">

It has worked only for a couple of charts. The rest of them are taking me all over the place. The interesting thing is that it's not even necessarily the same place every time. The `tc.qos_dropped` chart initially took me to the `Firewall` section, but then started taking me to `Memory`. Something is very finnicky there.

### Expected behavior

I should always be going to the correct chart.

### Steps to reproduce

1. Add charts from various sections of the Overview dashboard to a custom dashboard. 
2. Click on three dots and Go to chart for each of them
3. See where on the overview screen you are taken

### Desktop

Browser Version [e.g. 22]

**Comment by dimko** [comment]
To add more info on this one. It seems to re-direct you to the last chart you've visited in the respective tab.

e.g if dashboard is for **All Nodes** and you last visited **System Overview** submenu it will re-direct you to that section. It doesn't get you to the chart that corresponds to the dashboard

**Comment by novykh** [comment]
@AlexNti this has to do with the page object right?
