### ISSUE TITLE
[Bug]: Home should have date time picker and time control disabled like Alerts tab

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#445]
### Bug description

When you are on the Home tab the date time picker and time controls aren't applicable, so these should be disabled like on the Alerts tab

### Expected behavior

See above

### Steps to reproduce

1. Go to Home tab and see that date time picker and time control aren't disabled

### Screenshots

**Home tab**
<image src="https://user-images.githubusercontent.com/82235632/171578290-8502f15e-de81-4fb1-92bb-6c9b49b012d0.png" width="50%" height="50%"/>

**Alerts tab**
<image src="https://user-images.githubusercontent.com/82235632/171578423-3f8a0cec-4dc6-491a-92b7-a59a7a545735.png" width="50%" height="50%"/>

### Desktop

Browser Version [e.g. 22]

**Comment by jjtsou** [comment]
https://github.com/netdata/cloud-frontend/pull/3495

**Comment by hugovalente-pm** [comment]
closing this has been released
