### ISSUE TITLE
[Bug]: Home tab redirects doesn't respect existing filters

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#446]
### Bug description

When filtering Nodes using the Global filter if user clicks on a card to be redirected to the Nodes tab existing filters are overriden

### Expected behavior

When there is a filter applied and user clicks to be redirected to the Nodes tab the existing filter should be respected.
One exceptional case is when we have a value of `0` (zero) here probably the redirect shouldn't happen

### Steps to reproduce

1. Go to home tab and ensure you have more than 1 Live Node
2. On Global Node filter filter for just one Node
3. Click on the Nodes by Status card on Live nodes link
4. See that you get all the Lives nodes - expectation is to get only the filtered node

### Screenshots

![chrome_b7GmWOTaR6](https://user-images.githubusercontent.com/82235632/171579497-458387e4-accd-4204-b0c9-266f7c6c1468.gif)

### Desktop

Browser Version [e.g. 22]

**Comment by jjtsou** [comment]
https://github.com/netdata/cloud-frontend/pull/3493

**Comment by hugovalente-pm** [comment]
closing this has been released
