### ISSUE TITLE
[feat]: Cannot filter Kubernetes in Overview tab

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#447]
### Feat description

Typing Kubernetes in the charts filter while in the Overview screen doesn't bring back the kubernetes section.

### Expected behavior

It should show me all the kubernetes related sections in the sidebar

### Steps to reproduce

1. Login to Netdata Cloud
2. Claim a kubernetes cluster
3. Navigate to Overview Screen
4. Type _Kubernetes_ in the input field under **Sections and Charts** and **ENTER**

### Screenshots

The kubernetes section is there when no filtering 

![image](https://user-images.githubusercontent.com/19268853/171579195-273e9369-aa64-4a22-ab8e-0366edb95b91.png)

But not when typing the full word _kubernetes_

![image](https://user-images.githubusercontent.com/19268853/171579337-52421c2a-45ba-4833-b732-098a0ac0b841.png)

nor when typing half of it _ku_

![image](https://user-images.githubusercontent.com/19268853/171579933-ccc91918-1cec-4b6c-9de5-a0c4076df8a0.png)

### Error Logs

No error logs

### Desktop

OS: Ubuntu
Browser Chrome
Browser Version 101

### Additional context

This behaviour makes it  really difficult to navigate through all the available sections and find the kubernetes one.

**Comment by hugovalente-pm** [comment]
changing to feature request

**Comment by hugovalente-pm** [comment]
we currently have the k8s tab, we can look at improving the TOC search bar later
