### ISSUE TITLE
[Bug]: applied filter on nodes should be visible on home tab (like on other tabs)

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#448]
### Bug description

If there are node filters applied these should be displayed on Home tab like they are on other tabs

### Expected behavior

Show applied node filters on top

### Steps to reproduce

1. On Home tab go to Global node filter and filter by 1 node
2. See that no info is shown on top

### Screenshots

**Home tab**
<image src="https://user-images.githubusercontent.com/82235632/171580041-b34bb557-7ea4-4f81-af13-b9809328e6df.png" width="50%" height="50%"/>

**Overview tab**
<image src="https://user-images.githubusercontent.com/82235632/171580080-bb999385-7d8b-4b73-8170-456625e7e7ca.png" width="50%" height="50%"/>

### Desktop

Browser Version [e.g. 22]

**Comment by jjtsou** [comment]
https://github.com/netdata/cloud-frontend/pull/3494

**Comment by hugovalente-pm** [comment]
closing this has been released
