### ISSUE TITLE
[Bug]: Alerts tab Last updated at entry has no value

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#451]
### Bug description

Last updated entry at the bottom of the alerts table in Active alerts tab has no value

### Expected behavior

It should display the date time the alarms were last updated at.

### Steps to reproduce

1. Login to Netdata Cloud
2. Claim a node
3. Trigger one or more alerts
4. Navigate to Alerts tab
5. Select the Active Alerts section

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/172351291-bd8ae05f-fe80-48e2-b378-057d0f508caf.png)

### Error Logs

No error logs

### Desktop

OS: MacOs
Browser chrome
Browser Version 101

**Comment by thiagoftsm** [comment]
While I was testing a PR at `netdata/netdata`  I also observed this issue when I used either `Chrome  102.0.5005.61 (Official Build) (64-bit)` or `Mozilla Firefox 101`.

**Comment by jacekkolasa** [comment]
@dimko added a `activeAlerts-updatedAt` testid for this string, if it's needed (we don't have a way to test it yet, in FE integration tests)

**Comment by sashwathn** [comment]
@jacekkolasa : Are we doing anything about this?

**Comment by jacekkolasa** [comment]
@sashwathn fix is merged, will be released today

**Comment by dimko** [comment]
closing this one. it's fixed
