### ISSUE TITLE
[Bug]: PLAY/PAUSE breaks for the whole app after user hovers over chart in alert's dedicated page or switches to a different tab

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#452]
### Bug description

Play/pause button inside the date-time picker becomes unresponsive (user can't pause charts) for the whole application after a user hovers over the alert affected chart displayed in the alert's dedicated tab.

If a user hovers over the chart, the chart pauses again after a while, on its own, without any user interaction.

### Expected behavior

 If datetime picker is always set to PAUSE in the alert's dedicated page the latest value we display for the alert isn't the real latest value.

Since we display alert's latest value, datetime picker should be PLAYING and user can pause/play and interact with the date time picker, both in alert's dedicated view and inside alert's details modal.

### Steps to reproduce

1. Claim a node in netdata cloud
2. Trigger an alert for that node
3. Navigate to Alerts tab
4. Click on the triggered alert
5. Click on View alert's dedicated page
6. Hover over the chart in the page

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/172365187-d9d04c31-fcd8-4bb6-ab97-8dd3a221c48d.png)

### Error Logs

No error logs

### Desktop

OS: MacOs
Browser chrome
Browser Version 101

**Comment by shyamvalsan** [comment]
Yes - this doesn't seem to be specific to alerts - any time the user navigates to a different tab outside of netdata or does an alt tab and comes back, the PLAY/PAUSE breaks. The user has to interact with a chart for the PLAY/PAUSE to start working again. 

See example of this behavior

https://user-images.githubusercontent.com/24860547/172839517-2fc82167-4905-4c52-98eb-86b882c17dd0.mp4

cc: @dimko @AlexNti @hugovalente-pm

**Comment by hugovalente-pm** [comment]
@shyamvalsan updated the label to `mgmt-navigation-team`

**Comment by AlexNti** [comment]
This has been fixed by @novykh.
