### ISSUE TITLE
[Feat]: netdata dashboard node delete

### ISSUE THREAD

**Issue by marliyev** [netdata/netdata-cloud#459]
### Problem

Hi  there,

How to remove unreachable node from netdata dashboard General room? seems from general room nothing can be deleted

### Description

general room

### Importance

really want

### Value proposition

1.
2.
3.
...
Annoying to see unreachable nodes ;)

**Comment by dimko** [comment]
Hey @marliyev **Unreachable (offline)** nodes can now be removed from any room by going to the Nodes list tab. There is a little trash icon when you hover over an unreachable node. Bulk deletion is a feature to be introduced later on.

![image](https://user-images.githubusercontent.com/19268853/172806303-897576e0-f0f2-49cb-b616-52783673e21a.png)


Please try it and if you face any issues we'd be happy to assist you.

**Comment by marliyev** [comment]
ah cool, got it, thanks ;)

**Comment by marliyev** [comment]
ahm, sorry Man, every after 2 deleted node need to refresh page coz showing: 500 Oops, something unexpected happened!

Also how can i delete stale nodes?

thanks

**Comment by dimko** [comment]
Let me try to reproduce and will get back to you, can you also please share some more info about this 500 error? Any console error, any failed network requests?

Unfortunately there is no way currently to remove stale Nodes :/ This is a functionality that will probably be added in the future, along with bulk node deletion.
Any ideas why these nodes became stale? What happens if you try restarting them?

**Comment by marliyev** [comment]
![Screenshot from 2022-06-09 13-47-38](https://user-images.githubusercontent.com/63017170/172829789-679d15bc-2f73-4a34-b45b-cbc966bdeeff.png)

**Comment by marliyev** [comment]
ahm, looks like fixed, i am not getting 500 error anymore, thanks

**Comment by marliyev** [comment]
ah no, now getting every 4 nodes :D

**Comment by marliyev** [comment]
after 8 nodes deleting didnt get so far ;)

**Comment by dimko** [comment]
@marliyev can you please give me your space id? also, when you see the 500 can you check if you had a console error in your browser's dev tools? 

You can get space id by clicking the Cog icon on the bottom left corner

![image](https://user-images.githubusercontent.com/19268853/172832142-f6d8d69f-443e-452d-b1e9-d3aeac35786f.png)


I am not sure I understand your last question 🤔 Could you please elaborate? 
You can check each node's version by clicking on the (i) icon on the node

![image](https://user-images.githubusercontent.com/19268853/172831908-e4df1a70-05e1-44d4-a57e-74c80ad45b13.png)

**Comment by marliyev** [comment]
3e35831a-ec26-4fb2-80c7-41745af16ced

i have more than 300 nodes, i cant see which nodes running which version and i cant check them one by one, i see only total count and total version for nodes

**Comment by dimko** [comment]
Ah I got it. So you need a way to list the versions for all of your nodes. Will create a feature request for this. Thanks for bringing this up.

**Comment by marliyev** [comment]
one more thing, in process of rebuilding my mail server, netdata got from me many MAiLER-DAEMON, now i am restored my email but cant receive email or login to my account, i created account on another email, how can i restore my old account?

Thanks

**Comment by dimko** [comment]
If you're using the same email address in google or github which you were using to receive the Netdata Cloud signin emails, you can always login to your account using Google or Github signin methods.
