### ISSUE TITLE
[Bug]: Clicking on a room doesn't close the rooms dropdown

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#461]
### Bug description

Pretty minor. After a user opens the Rooms selector dropdown and clicks one of the rooms the dropdown remains open. It's a bit annoying as user has to click a 2nd time to an empty space of the screen so he can close the dropdown, as it covers part of the screen.

### Expected behavior

After clicking an option the dropdown should close.

### Steps to reproduce

1. Login to Netdata Cloud
2. Navigate to a space with 1+ rooms
3. Open the Rooms dropdown by clicking the name of the room at the top (next to the gear icon)
4. Select one of the rooms you wish to navigate to.
...

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/172804758-d5ffd8a6-3bd1-471f-81dc-bdfc04ce4b8a.png)

![image](https://user-images.githubusercontent.com/19268853/172805336-74cd7092-74ac-4dd1-b866-0ee416e3ce63.png)

### Error Logs

-

### Desktop

OS: MacOS
Browser Chrome
Browser Version 101

**Comment by AlexNti** [comment]
Closing as it going to be fixed by https://github.com/netdata/cloud-frontend/pull/3550/files
