### ISSUE TITLE
[Bug]: No Tooltips for minimized tabs

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#462]
### Bug description

When having too many tabs opened it's a bit difficult to understand which tab is which one (from the ones that are sticky and cannot be closed, meaning: Home tab, Overview, Nodes table, Dashboards, Alerts, Anomaly) as we don't display any tooltip when user hovers over them.

Tooltips are displayed when tabs are shown in their full view.

### Expected behavior

Show a tooltip when user hovers over a tab that is minimized and name of it isn't displayed. 

### Steps to reproduce

1. Navigate to Netdata Cloud
2. Open several Nodes in their single node view until the other tabs are minimized and their names are hidden
3. Hover over Overview tab or Nodes tab for example

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/172807997-7bad49ec-4b9e-4d4a-a6c6-c3e21bd7314a.png)

### Error Logs

- 

### Desktop

OS: MacOS
Browser Chrome
Browser Version 101

**Comment by AlexNti** [comment]
Closing this, it will be fixed on the next release.
