### ISSUE TITLE
[Feat]: Give users the ability to list all available nodes versions

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#463]
Feedback coming from user.

Users need the ability to check all available nodes versions in bulk and identify which one needs an update.

> i have more than 300 nodes, i cant see which nodes running which version and i cant check them one by one, i see only total count and total version for nodes

_Originally posted by @marliyev in https://github.com/netdata/netdata-cloud/issues/459#issuecomment-1150983297_

**Comment by hugovalente-pm** [comment]
probably version should be a criteria to allow filtering of nodes, that way we could have a redirect to the Nodes tab having the filter applied on agent version

what do you think @shyamvalsan ?

p.s.: just referencing the Universal filter for nodes netdata/product#2836 in case it is additional criteria to place

**Comment by hugovalente-pm** [comment]
this is now available on Centralized Admin Interface and user can order by it and use the search box
![image](https://user-images.githubusercontent.com/82235632/197846096-98d6c887-d89a-40b4-80e0-c766a297625b.png)
