### ISSUE TITLE
[Bug]: Selecting a chart submenu with a single entry selects the direct below

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#465]
### Bug description

When in **Overview** tab, once I select a specific section from the sidebar that only has **1 subsection**, I am not directed to the chart I clicked on, but instead the directly below section is selected.

e.g I click on the **test** section but the **Netdata monitoring** section is highlighted and displayed.

### Expected behavior

I should be directed to the section I clicked on and the chart for that section should be displayed.

### Steps to reproduce

1. Navigate to Netdata Cloud -> Overview Tab
2. Click on **Firewall (netfilter)** section
3. The Application section is selected and the name of the chart selected is cut off the screen

### Screenshots

**Test** section
![image](https://user-images.githubusercontent.com/19268853/173561655-42adfd84-2481-4184-ac53-7d16f0568b0a.png)

**Firewall** Section
![image](https://user-images.githubusercontent.com/19268853/173561095-f0808feb-155b-46ee-bd4f-84355221ae0d.png)

![image](https://user-images.githubusercontent.com/19268853/173561095-f0808feb-155b-46ee-bd4f-84355221ae0d.png)

### Error Logs

- 

### Desktop

OS: MacOS
Browser: Chrome
Browser Version: 101

### Additional context

It probably depends on the size of the screen and used resolution. This is something however that randomly breaks the regression tests.

**Comment by hugovalente-pm** [comment]
@dimko is this still happening? I was trying to reproduce and I can't
![chrome_4ahEwVEAlm](https://user-images.githubusercontent.com/82235632/174159470-c095f11a-8863-4004-b7c3-dc04751dc9ed.gif)

**Comment by dimko** [comment]
Indeed, it isn't happening anymore. Closing and will re-open if I see it again. This seems to break very easily from time to time.

**Comment by dimko** [comment]
@hugovalente-pm just re-produced it and also regression failed due to it. So re-opening.

**Comment by hugovalente-pm** [comment]
ok, just added to our board @dimko

**Comment by jacekkolasa** [comment]
I couldn't recreate it, let's sync after vacations

**Comment by hugovalente-pm** [comment]
as per the discussion on today's daily on an update by @dimko this has been raised in priority - moving to `high´

**Comment by dimko** [comment]
@hugovalente-pm reducing prio on this one again as I managed to overcome the block in regression tests. It's not a very obvious issue to the user and can be easily bypassed by scrolling a bit. When FE team has more availability we can try and fix it.

**Comment by hugovalente-pm** [comment]
@dimko I was trying to reproduce it and couldn't, could you also check tomorrow so we can close it if it isn't happening any more?

**Comment by dimko** [comment]
@hugovalente-pm will try and reproduce today and will ping FE guys so we can address it. This seems to be happening more and more often lately, again breaking the regression. Also there was a mention in slack about a similar issue.

**Comment by hugovalente-pm** [comment]
what happens now is that navigation starts to work ok, but afte
![chrome_L4NPLvjA7a](https://user-images.githubusercontent.com/82235632/191243493-aa3f7476-9d1f-452e-a035-4f8623f9904e.gif)
r a while things get messed like clicking on a menu item takes you to a total different place

**Comment by dimko** [comment]
So the initial issue has been fixed. There is side effect to all these when a new chart is added to the list of existing charts in the ToC sidebar making some menus unclickable. Closing this and opening a new one to track it.
