### ISSUE TITLE
[Bug]: Alert description showing $family

### ISSUE THREAD

**Issue by MrZammler** [netdata/netdata-cloud#466]
### Bug description

On the alert page, (dedicated or drawer), the alert description shows the $family variable:

`average percentage of time $family disk was busy over the last 10 minutes`

The $family is actually a placeholder which should have been replaced by the "item" that the alert refers to (i.e. in this case a disk, such as `sdc` or similar).

If the alert description is taken by the alert configuration, then it will contain the $family variable. I believe we also carry the alert description (with replaced $family value) in the alert event, and we should print it from there.

### Expected behavior

Display the family value instead of $family.

### Steps to reproduce

1. In production cloud click on an alert that it's configuration contains a $family entry in description.
2. Check the alert configuration string.

### Screenshots

![image](https://user-images.githubusercontent.com/1905463/173576866-9f5a852b-2ace-4fb6-8d9b-a7e7954b35ba.png)

### Desktop

OS: Linux
Browser Firefox
Browser Version 91.9

**Comment by car12o** [comment]
fix deployed to prod!
