### ISSUE TITLE
[Feat]: Improve the interpolation work and show to users that data was interpolated

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#468]
### Problem

With the work done on [BUG] partially missing data should show be interpolated and annotations on composite charts #377 we are doing some "blindly" interpolation and masking out existing gaps on data.

We need to put some more logic to the interpolation as well as show to the users on charts where the interpolation occurred.

### Description

The first rule is that interpolation should only happen when data exists for some data series and not on other(s), meaning that if no data exists across the data series at a given point in time it can't be interpolated - we can't mask the existing gap.

Considering this example:
* highlighted red area can't have any interpolation applied since all data series on that time period are null
* dashed yellow lines for each data series is where the interpolation should be applied since, at least, there is a data series with data for that period
![image](https://user-images.githubusercontent.com/82235632/173795622-4674d5b8-f717-45cb-bafd-2bdf90a41a40.png)

In order to correctly apply the above, the interpolation can only happen when the grouping logic is being applied since the check of nulls across data series needs to take into consideration the grouping option. 

For an example, let's assume we have 2 nodes, 2 instances (charts) and 3 dimensions if we consider the grouping options we can have:
* `Grouping by node` - in this case we will have **2 data series** where we have one for each node. interpolation will only happen if on these 2 data series across the time periods we have data for one and not the other - interpolation happens on the one without data
* `Grouping by dimension` - in this case we will have **3 data series** where we have one for each dimension. interpolation will only happen if on these 3 data series across the time periods we have data for, at least, one and not other(s) - interpolation happens on the one(s) without data
* `Grouping by instance` - in this case we will have **2 data series** where we have one for each instance. interpolation will only happen if on these 2 data series across the time periods we have data for one and not the other - interpolation happens on the one without data

On the UI we will need to have a way to show the interpolated sections on each data series with, possibly, one of these ways:
1. represent a dashed line for the places where the interpolation occurred
2. show an overlay icon/symbol to present where the interpolation occurred, possible adding a tooltip with details from it

The chart info should also be enhanced to show the summary of all the interpolations that happened

### Importance

must have

### Value proposition

1. We avoid showing wrong data presented and hiding gaps
2. We clearly show to users where interpolations occurred

**Comment by ralphm** [comment]
I think we should do no interpolation at all. Gaps are better than fake data points and suggestive (but unknowable) trends. Instead:

- If the chart has two points with a gap in between, and there is a desire to connect it with a line, then don't show data points there when hovering. Maybe use a dashed line, but in the same color as the metric. I prefer to have an explicit gap, though.
- Have the modal show a marker for missing data. Maybe with a yellow warning triangle.
- Have explicit counters shown for the number of data points for this time **and/or** the number of dimensions, chart instances, and hosts included in the aggregation. This is useful in all cases, but explicitly also when there are more than fit the modal.

**Comment by hugovalente-pm** [comment]
we don't do interpolation and now show gaps or some visual indicator when no data was available for all nodes or partially
