### ISSUE TITLE
[BUG] Strange DateTime picker behaviour in new rooms

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#47]
**Describe the bug**	

If i create a new room and then select a date time range that goes back in time covering before the room was created i see strange date axis behaviour. 	

**To Reproduce**	

Create a new room, go into the room, press last 12 hours. You should see a longer time frame on the data axis than 12 hours. 

**Expected behavior**	

I expect to see last 12 hours

**Screenshots**	

i just created a new room called "Redis" that has all the gke-production-redis nodes in it. Then i pressed last 12 hours and for some reason it's showing charts in some strange way but not the last 12 hours. It's like its trying to go much further back in time for some reason.

![image](https://user-images.githubusercontent.com/2178292/107802655-8a9d1780-6d59-11eb-8407-6b853798b2a1.png)

if i go to the General room it looks ok

![image](https://user-images.githubusercontent.com/2178292/107802687-94bf1600-6d59-11eb-8e5e-123c2777f8dc.png)

But any of the 3 new rooms i made seem to have this issue:

![image](https://user-images.githubusercontent.com/2178292/107802720-9f79ab00-6d59-11eb-80af-fc0d4ff31fde.png)

So its almost like its just for new rooms for some reason the datetime picker does strange stuff.

e.g. last 30 minutes seems ok on the load chart but not on the cpu chart

![image](https://user-images.githubusercontent.com/2178292/107802776-b0c2b780-6d59-11eb-810b-da3badd04558.png)

its like its doing the math wrong and looking back further or something

last 2 hours:

![image](https://user-images.githubusercontent.com/2178292/107802831-c0420080-6d59-11eb-90d5-06e1ffb1a7ed.png)

its like the blank space outside what i'm asking for is growing with the size of the window from the datetime picker

its almost like if i request a time range that goes to before the room was created then i get this issue.

**Comment by andrewm4894** [comment]
i dont seem to be able to add some additional labels

**Comment by cakrit** [comment]
This may be something we're already discussing in the channel, I didn't spend time to see if it's a separate issue.

**Comment by chrikar** [comment]
Hi @andrewm4894!

I just tried to the same on `production` with an existing agent I have and it looks to be working as expected. These agents were already claimed you just put them in a new room, right?

**Comment by andrewm4894** [comment]
Yep. There is a lot lot of unreachable nodes in the room too so was wondering if that might be having an effect. I can invite you to the room if you'd like.

**Comment by chrikar** [comment]
Sure. Let's also check with the FE people to take a look in case it's a known issue.

**Comment by andrewm4894** [comment]
I had a little look and i can still see this and recreate it in the non general rooms here: 

![image](https://user-images.githubusercontent.com/2178292/107965906-063dd500-6fa3-11eb-86df-03d636ac0c76.png)

I have not tried to recreate it in a different space - i will try that next just to see.

**Comment by andrewm4894** [comment]
It seems to work ok in a different space where i have just 5 nodes. I made a room with just one node and one with 4 nodes and was not able to recreate the issue. So it seems to be specific to the room above.

**Comment by cakrit** [comment]
I just did a similar thing on another room. Went from looking at the real time (15 min) to select to see a whole day. The request done from the FE to the BE requests very few points, which is what causes the strange experience:

Reasonable request:
https://app.netdata.cloud/api/v1/nodes/813de04f-6d10-4a07-b569-db2952dba762/data?chart=cgroup_k8s_cntr_cert-manager_cert-manager-787bcdcf89-7fzns_cert-manager.mem_activity&_=1613501963019&format=json&points=251&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-3600

Problematic request (only 10 points requested):
https://app.netdata.cloud/api/v1/nodes/813de04f-6d10-4a07-b569-db2952dba762/data?chart=cgroup_k8s_cntr_cert-manager_cert-manager-787bcdcf89-7fzns_cert-manager.mem_usage_limit&_=1613501966581&format=json&points=10&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-86400

**Comment by jacekkolasa** [comment]
@cakrit the `10 points` requested is probably valid. I've added an additional layer that lowers the nr of points needed, when the history is not big enough. For example, if there's only history for 1/10th of the selected timeframe, we ask for 10 times less points. That's because Agents in that case respond with 10 times bigger frequency. (they return the same nr of points than requested even for much smaller time-frame).

That behaviour was working in old dashboard which was always changing visible time-frame when we asked beyond `first_entry`. But now we want to show empty space on the left instead of automatic pan-and-zoom on available data.

That can be fixed when we'll be able to force nr of points on Agents.

**Comment by jacekkolasa** [comment]
I see that `first_entry` returned by `data` calls can be much bigger than first entries (either `after` or first timestamps in `result.data`). That can result in buggy behaviour. @netdata/cloud-be do you this can be a bug? I recreated it in prod, NC/Overview, by setting timeframe to `last 5 days`. `first_entry` is from 4 hours ago and first data timestamps are from few days ago.

**Comment by cakrit** [comment]
We had a very short retention period, which caused this.
