### ISSUE TITLE
[Bug]: Newly claimed nodes can remain unreachable without any explanation on the UI

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#471]
### Bug description

We have at least three ways for a claimed node to never connect to the cloud:
- Agent requires a restart (see https://github.com/netdata/netdata/issues/13164)
- Network or other temporary issue connecting to the cloud 
- Claiming was executed on an agent with an old version, that was deprecated with the new architecture.

In these cases, users see their nodes as unreachable and have no idea that they need to debug by looking for `aclk` messages in Netdata's `error.log`. 

Note that the 3rd reason did not exist before we shut down the old architecture, which is why this has become a real problem now.

### Expected behavior

We should present some information on the home page and/or the node tab to let users know about recently claimed nodes that never connected successfully to the cloud and explain the possible reasons and resolution of the issue. 

### Steps to reproduce

Scenario 1: Claim a node without starting Netdata and see the UI
Scenario 2: Claim a node with an old Netdata version 

### Desktop

Browser Version [e.g. 22]

**Comment by shyamvalsan** [comment]
Breaking this task in to smaller pieces per team: 

BE: Confirm that this information (newly claimed nodes that are visible but never connected to cloud) is available and can be exposed to FE, if it is not currently available then we should implement this.

FE: Decide how to represent this in the cloud UI in a way that is useful to users, link to the right doc page.

Doc: Have a dedicated doc page that provides all the info required to solve this problem.

**Comment by cakrit** [comment]
This shows the % of newly claimed nodes that didn't connect to the cloud per day. You can see clearly that the primary reason is the migration to the new architecture on May 11th, i.e. old agent versions:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/43294513/176680872-729aadb8-1b1b-4dcb-83e5-792fed50f8be.png">

**Comment by hugovalente-pm** [comment]
the FE task has been completed:

* Nodes table on Centralized Admin interface include the `Connection to Cloud` status
![image](https://user-images.githubusercontent.com/82235632/187248669-5e732577-9134-4772-9464-9c8462eca5aa.png)


* Node inspector has also been revisited to include this
![image](https://user-images.githubusercontent.com/82235632/187248763-e80029cb-ca15-46f2-b30f-255874a6d2e1.png)

and with link to https://learn.netdata.cloud/guides/troubleshoot/troubleshooting-agent-with-cloud-connection

closing the bug
