### ISSUE TITLE
[Bug]: Deleting a room results in misleading error "Not a room member"

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#472]
### Bug description

<img width="450" alt="image" src="https://user-images.githubusercontent.com/43294513/174132800-2f7d5be5-b784-41c4-af3a-21e472fd14e1.png">

### Expected behavior

No error should appear.

### Steps to reproduce

1. Create a room
2. Delete a room

### Desktop

Browser Version [e.g. 22]

**Comment by dimko** [comment]
Just a comment on this one. The room deletion is executed as expected. Room is deleted. 
The 403 response is related to fetching available **dashboards** for the room

![image](https://user-images.githubusercontent.com/19268853/174573520-ab4ef02b-14fb-4962-a8d2-1d4120486d77.png)

**Comment by hugovalente-pm** [comment]
@cakrit just tried this and was able to delete the room having the correct notification and not getting the server error.
I still saw the `403` error on the dashboards call, but probably best to close this one and open one for the dashboard call failure - https://github.com/netdata/netdata-cloud/issues/529
