### ISSUE TITLE
[BUG] cpufreq and cpuidle should go under the CPU

### ISSUE THREAD

**Issue by apostolidhs** [netdata/netdata-cloud#48]
**Describe the bug**	
In the response of the `/charts` endpoint in the room overview screen there are 2 keys `cpufreq.cpufre` `cpuidle.cpuidle` that are getting display in the sidebar as primary menu options.

**To Reproduce**	
Most of the production spaces in the room overview page contain this response.

**Expected behavior**	
Should be prefixed by the `cpu.` key, so they are grouped under the cpu primary menu.
Something like `cpu.freq`

**Screenshots**	

<img width="193" alt="Screenshot 2021-02-16 at 3 55 58 PM" src="https://user-images.githubusercontent.com/2164902/108078489-6cdff300-7076-11eb-83f4-f66c2f15ba98.png">

**Error logs**	

Part of the `/charts` response

<img width="341" alt="Screenshot 2021-02-16 at 4 47 06 PM" src="https://user-images.githubusercontent.com/2164902/108078698-a87abd00-7076-11eb-8bfb-e7c45b5c569c.png">

**Comment by chrikar** [comment]
This might originate from the agent, so we need to check that. In the meanwhile we can get a quick-fix to address this.

**Comment by apostolidhs** [comment]
Added handling special handling in the frontend (`release/2.1.3`).
We are expecting the actual fix on the agent as @chrikar mentioned.
