### ISSUE TITLE
[Bug]: Chart pop-over changes highlighted metric before new metric is introduced

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata-cloud#480]
### Bug description

When viewing a chart that has multiple metrics (e.g. dimensions) and a new one of them is not present for the whole time range, this distorts the highlighted metric in the hover modal. In the screenshots below I was pointing at the top metric _before_ and _after_ the introduction of the orange metric, but before the introduction, the selected metric for the modal changes to the bottom one. Having checked this with various combinations of enabled metrics, the even if the orange metric is not the bottom one, it still affects the highlight.

### Expected behavior

The point-at metric should be highlighted and in view of the modal.

### Steps to reproduce

1. Have a chart with multiple metrics
2.One of the metrics should only exist for part of the time range
3.Hover over the chart to point at desired highlighted metric

### Screenshots

Correct highlight:
![image](https://user-images.githubusercontent.com/116741/175308879-bf6dd181-b114-4298-8714-2387e3c2f339.png)

Unexpected highlight:
![image](https://user-images.githubusercontent.com/116741/175308605-68d07c7a-3a9b-447c-ac4c-aba2543cb571.png)

Unexpected highlight with a _lower_ chart also selected
![image](https://user-images.githubusercontent.com/116741/175310814-70d828bd-02b7-401d-ad8e-34f50e64228e.png)

### Desktop

OS: Ubuntu
Browser: Firefox	
Browser Version: 102.0b7

**Comment by hugovalente-pm** [comment]
sorry for only following on this now @ralphm, it went under my radar for some reason.
was checking this bug and seems to be the same as reported here https://github.com/netdata/netdata-cloud/issues/481, right?

would it be ok to keep only the #481 ?

**Comment by ralphm** [comment]
480 < 481 😀

**Comment by ralphm** [comment]
Closing in favor of #481.
