### ISSUE TITLE
[Bug]: Chart tooltip dimension highlight position not working correctly

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#481]
### Bug description

On a chart with multiple dimensions when you navigate with our mouse over an outlier dimension the tooltip dimension highlight isn't highlighting the dimension being _navigated_

### Expected behavior

The dimension closer to the mouse pointer should be the one highlighted 

### Steps to reproduce

1. Go to to [this chart](https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/overview#correlation=true&after=-32400&before=0&utc=Europe%2FAthens&offset=%2B3&timezoneName=E.%20Europe&metrics_correlation=true&chartName=menu_prometheus_traefik_submenu_traefik_entrypoint&appliedFilteredIds=0fc6e555-1f75-49d9-bd35-70321f6dd2e6%2Cab334255-6e26-4457-969e-cebd58699c7c&reachableNodesIds=&staleNodesIds=&unreachableNodesIds=&filteredNodesSearchParams=)
2. Navigate with your mouse across time the dimension of `traefik_entrypoint_open_connections|entrypoint=web,method=GET,protocol=http`, which is the outlier one
3. Notice that the tooltip highlight isn't always highlighting the dimension where mouse is over (or closer to)

### Screenshots

![image](https://user-images.githubusercontent.com/82235632/175326355-cb5ad165-0b19-4c22-be24-55b85fbab41c.png)

If you select that one dimension it is ok, if you select two dimensions it is ok for some but for others not:
* **OK** example - `traefik_entrypoint_open_connections|entrypoint=web,method=GET,protocol=http` and `traefik_entrypoint_open_connections|entrypoint=web,method=HEAD,protocol=http` selected
![image](https://user-images.githubusercontent.com/82235632/175326834-6e62a192-21a0-4683-a83f-f9f8431a8954.png)
 
 * **NOK** example - `traefik_entrypoint_open_connections|entrypoint=web,method=GET,protocol=http` and `traefik_entrypoint_open_connections|entrypoint=web,method=GET,protocol=websocket` selected
![image](https://user-images.githubusercontent.com/82235632/175326973-8644b0fc-dc87-4a0b-a850-e1de6e2156c5.png)

### Desktop

Browser Version [e.g. 22]

### Additional context

The array of dims

```
	"dimension_ids": [
		"traefik_entrypoint_open_connections|entrypoint=traefik,method=GET,protocol=http",
		"traefik_entrypoint_open_connections|entrypoint=web,method=DELETE,protocol=http",
		"traefik_entrypoint_open_connections|entrypoint=web,method=GET,protocol=http",
		"traefik_entrypoint_open_connections|entrypoint=web,method=GET,protocol=websocket",
		"traefik_entrypoint_open_connections|entrypoint=web,method=HEAD,protocol=http",
		"traefik_entrypoint_open_connections|entrypoint=web,method=OPTIONS,protocol=http",
		"traefik_entrypoint_open_connections|entrypoint=web,method=PATCH,protocol=http",
		"traefik_entrypoint_open_connections|entrypoint=web,method=POST,protocol=http",
		"traefik_entrypoint_open_connections|entrypoint=web,method=PUT,protocol=http"
	]
```

The timestamp being checked
```
	[
		1655978400000,
		1,
		0,
		72.375,
		null,
		0,
		null,
		0,
		0.375,
		0
	],
```

The *NOK* behaviour also happens to the `traefik_entrypoint_open_connections|entrypoint=web,method=OPTIONS,protocol=http`, both of these have `null` value. So when there is a dimension with `null` value the highlighted is put on those

**Comment by hugovalente-pm** [comment]
@dimko @jjtsou for visibility, adding to our board

**Comment by ralphm** [comment]
Marked #480 as duplicate

**Comment by novykh** [comment]
The issue for this and #480 mentioned above seems to happen when at least one dimension comes back on the specific point as `null` it's more clear on the #480 issue. It should be an easy fix.

**Comment by hugovalente-pm** [comment]
this still seems to be happening 
![image](https://user-images.githubusercontent.com/82235632/193037898-35c5aae1-ef73-4dbe-b123-d50fb505c16c.png)

https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/overview#chartName=menu_prometheus_traefik_submenu_traefik_service&after=1664396039000&before=1664439238000&utc=Europe%2FAthens&offset=%2B3&timezoneName=E.%20Europe&metrics_correlation=true&appliedFilteredIds=&correlation=true&reachableNodesIds=&staleNodesIds=&unreachableNodesIds=&filteredNodesSearchParams=

**Comment by hugovalente-pm** [comment]
this is fixed
