### ISSUE TITLE
[Bug]: System overview gauges missing from single node view

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#484]
### Bug description

System overview gauges missing from single node view

you can see it on the overview: 

![image](https://user-images.githubusercontent.com/2178292/175769592-8af6a41b-0955-4520-b51e-4ef55a85a8a1.png)

But not on the single node view: 

![Uploading image.png…]()

### Expected behavior

THe gauges should be there as usual

### Steps to reproduce

1. go to any single node view

### Desktop

Browser Version [e.g. 22]

### Additional context

first reported by user on discord here: https://discord.com/channels/847502280503590932/851461027229073428/990022165044809728

some slack discussion here: https://netdata-cloud.slack.com/archives/CNLAM2B19/p1656145137792259

**Comment by dimko** [comment]
A workaround for this issue:
**Go to overview tab. The Gauges at visible there. Click the global filter on the top right section and select the desired node.**

**Even though user is on Overview screen, all charts and gauges will be displayed only for the filtered node.**

**Comment by AlexNti** [comment]
Closing this as fix is already in Production.
