### ISSUE TITLE
[Bug]: New Caledonia Timezone Incorrect

### ISSUE THREAD

**Issue by ebzao** [netdata/netdata-cloud#485]
### Bug description

The timezone selector include New Caledonia with the label : "Solomon Is., New Caledonia UTC +10".

### Expected behavior

The New Caledonia Timezone (NCT) is always UTC +11, without daylight saving time.

### Steps to reproduce

1. Search for "New Caledonia" in Timezone selector, and select "Solomin Is., New Caledonia UTC +10".
2. Time is wrong, one our offset because of UTC+10 instead of UTC+11

### Desktop

OS: Windows, Linux Debian, Linux Ubuntu
Browser Chrome, Firefox

**Comment by hugovalente-pm** [comment]
thanks @ebzao for reporting this, we acknowledge the bug and will get it in to be sorted out

**Comment by hugovalente-pm** [comment]
reviewed priority since this seems to be very specific to this timezone, was confirming that for other timezones not affected by daylight saving time it is working ok

**Comment by AlexNti** [comment]
Closing this, it will fixed on the next release
