### ISSUE TITLE
[Bug]: Dashboard chart type does not persist when saved

### ISSUE THREAD

**Issue by nethershaw** [netdata/netdata-cloud#486]
### Bug description

Chart rendering types (line, stacked, area) are not persisted when returning to a previously saved dashboard where those types have been altered.

### Expected behavior

On returning to a saved dashboard, charts where I have changed the rendering type (e.g., from 'stacked' to 'line') should remember  the type they had when I saved them.

### Steps to reproduce

1. I create a new dashboard.
2. I add a chart to the dashboard representing one metric (e.g., `chrony.stratum`) over all nodes grouped by node.
3. I change the chart display mode from 'stacked' to 'line'.
4. I save the dashboard.
5. I leave the dashboard (i.e., I switch to any other tab in the Netdata app) and return to it.

### Screenshots

![Peek 2022-06-26 15-37](https://user-images.githubusercontent.com/3607458/175831045-7fd605e8-e9d2-4184-9385-5c1c58119af5.gif)

### Desktop

OS: Linux 5.10.123-gentoo-dist
Browser: Google Chrome
Browser Version: 102.0.5005.115 (Official Build) (64-bit)

**Comment by hugovalente-pm** [comment]
@nethershaw thanks for raising this to our awareness, I was able to reproduce this behaviour once as well.
we will take a look and work on a fix for it.

**Comment by hugovalente-pm** [comment]
data seems to have been saved correctly but on FE the `line` value isn't being correctly retrieved:
![image](https://user-images.githubusercontent.com/82235632/175924192-8f67fbb2-a88d-48cc-bf8a-e8b274c1c233.png)

**Comment by moson-mo** [comment]
Can confirm it.
Next to the chart type it also affects other options.
For example the dimension selection. See demo video:

https://user-images.githubusercontent.com/13588013/177002448-7086f763-a021-4a47-bb44-694fd813581b.mp4

**Comment by moson-mo** [comment]
> `line` value isn't being correctly retrieved:

There is this piece of code which seems to force a stacked view when group by is not "dimension".

![image](https://user-images.githubusercontent.com/13588013/177004812-51f84f53-84c2-45ff-b8f9-617e8bdc77c8.png)

**Comment by jjtsou** [comment]
https://github.com/netdata/charts/pull/111

**Comment by hugovalente-pm** [comment]
@nethershaw @moson-mo a fix for this was released today so closing this issue. do let us know in case you still face any problem

**Comment by hugovalente-pm** [comment]
thanks for the quick feedback @jmakov and @moson-mo , we will look into #495
