### ISSUE TITLE
[Bug]: New generic error page for non-5xx HTTP errors

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#487]
### Bug description

The image used for the error page shows a large 500 behind a crane. This suggests that there was a network error (HTTP 5xx response code). In practice, though, there was no request with a 5xx response, but rather a Javascript error.

### Expected behavior

We should show something different here. Maybe a version of drawing without the 500.

### Steps to reproduce

N/A

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
bug on implementation of the 500 error page, original work here https://github.com/netdata/cloud-frontend/issues/3264 --> point 2. has keep the current 500 page in case of any REAL 500 error from the BE

**Comment by hugovalente-pm** [comment]
based on the conversation on today's daily the priority for this has been raised to `medium` and item has been raised on the backlog

**Comment by AlexNti** [comment]
This is paused for now, waiting for @novykh to be back as we need to discuss possible strategies.

**Comment by hugovalente-pm** [comment]
@AlexNti as discussed on the daily let's proceed with removing the big graphics of "500" from the current page while in parelel we will discuss what and how to better distinguish the error scenarios we want to show (HTTP errors and other generic errors)

**Comment by hugovalente-pm** [comment]
the removing of the 500 graphic solved this for now.
the plan is to review the overall notifications displayed as across the together with errors, closing this bug
