### ISSUE TITLE
[BUG] chart families not showing properly in overview screen

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#49]
**Describe the bug**	

I have a room with one node. This node about 20 anomalies collector jobs running on it and so has lots of anomalies contexts in the menu on the right. 

When i am in the node itself i see correct menus:

![image](https://user-images.githubusercontent.com/2178292/108206526-69a04200-711e-11eb-8456-11158a752684.png)

But for some reason when i go to the overview for the room i lose those menu's and it has for some reason sort of flattened out all the "System Overview" sections into their own menus for some reason. 

![image](https://user-images.githubusercontent.com/2178292/108206709-a9672980-711e-11eb-8443-0bd3ace96b9b.png)
	

**To Reproduce**	

Create a agent with a lot of non standard collectors and/or multiple jobs per collector. Chanage the priority of those jobs to be 80-90 and so appear at top of menu list. 

Create a space and room with just that node. Look at the differences between the overview and the node view of the dashboard itself. 

**Expected behavior**	
I could see all the menu sections in the overview screen just like i do on the node screen.

**Screenshots**	
As above	

**Additional context**	
I'm happy to invite anyone to my room if easier to debug that way as might be a tricky one to recreate.

**Comment by papazach** [comment]
Hey @andrewm4894 could you please invite me to the room to take a look?

**Comment by andrewm4894** [comment]
just sent invite there - let me know if you don't see it and i can resend.

**Comment by hugovalente-pm** [comment]
@andrewm4894 do you know if this still happens?

**Comment by papazach** [comment]
Is this still relevant or we should close it?

**Comment by andrewm4894** [comment]
@papazach feel free to close this one. It may have been fairly specific to the anomalies python collector which will be less relevant once we have the anomaly advisor in prod.
