### ISSUE TITLE
[Bug]: Dashboard - Chart settings not saved

### ISSUE THREAD

**Issue by moson-mo** [netdata/netdata-cloud#495]
### Bug description

Some chart settings are not saved.

### Expected behavior

Changes to charts should be saved.

### Steps to reproduce

1. Create Dashboard
2. Add "net.net" chart for all nodes
3. Change "for" setting to "All dimensions"
4. Click "Save"
5. Navigate to another tab
6. Navigate back to Dashboard

### Screenshots

https://user-images.githubusercontent.com/13588013/177002108-b4598eb7-410d-49ff-9262-bf6557c8b384.mp4

### Desktop

OS: Archlinux
Browser Firefox 102 / Chromium 03.0.5060.53

### Additional context

When you choose "All dimension", it saves it with an empty array

![image](https://user-images.githubusercontent.com/13588013/177833860-80cf51e9-56d7-4076-b7d7-759164a66696.png)

Now it seems that during loading of the chart settings, it is interpreted as "not defined" and it falls back to the default setting (in this case it is "received"...)

That being said, I modified the data in the PATCH request (when saving the dashboard) like this:

"dimensions":["received","sent"]

Bingo. That did the trick:
(this selection is impossible to make in UI, it'll automatically select "All dimensions" if you select more than one entry)

![image](https://user-images.githubusercontent.com/13588013/177833947-1b6e8970-e245-4d77-a6cd-ad48512351ec.png)

So to fix this, the array should probably contain all possible options rather than being empty when "All dimensions" is selected...

**Comment by moson-mo** [comment]
Same as #486 it seems -> Closing this issue.

Additionally to what has been reported in #486, also some other options than the type are not saved.

**Comment by moson-mo** [comment]
https://github.com/netdata/charts/pull/111 fixes https://github.com/netdata/netdata-cloud/issues/486#issuecomment-1177949167

But not the other problem with "All dimensions" selection.
Reopening...

**Comment by jmakov** [comment]
Would just like to add that sorting by dimensions also isn't saved. Also can someone help me understand how this isn't a super high priority bug (am I using netdata wrong - doesn't everybody have multiple custom graphs :) )?

**Comment by cakrit** [comment]
I agree, this should have been a high prio bug. 

Not everyone creates custom dashboards @jmakov, many people just work with the default views.

**Comment by jjtsou** [comment]
https://github.com/netdata/charts/pull/114

**Comment by hugovalente-pm** [comment]
@moson-mo @jmakov an initial fix has been released for this and we've opened a follow-up bug to deal with a very specific scenario on chart type.

please try it and let us know if you still find any issue.
