### ISSUE TITLE
[Bug]: Cannot delete agent from cloud dashboard

### ISSUE THREAD

**Issue by luisj1983** [netdata/netdata-cloud#496]
### Bug description

I can't seem to delete a number of offline clients.

I coulddn't upgrade some nodes and so had to uninstall-reinstall. This lead to duplicates in the cloud dashboard, which I've had before; however, this time when I deleted the 'old' nodes from the dashboard's "nodes" view I got an internal server error.
andrewm4894 passed the info on to the backend team and soon I could delete without any errors.
However, after a few seconds the deleted node reappears.

I've tried deleting the cache via the developer tools and then doing a hard refresh (ctrl + F5) as well as a different browser.
Note that the agents are showing as Unreachable, not as stale etc.

Let me know what you need :)

### Expected behavior

Nodes should be deleted.

### Steps to reproduce

1.
https://app.netdata.cloud/spaces/home-office-space/rooms/all-nodes/nodes
2. Click delete/trash icon for node.
3. 3. Also happens via the node tab under the settings for the room.

### Error Logs

Dev tools console shows two errors:

with "the server responded with a status of 499". Attached
[app.netdata.cloud-1656953801417.log](https://github.com/netdata/netdata-cloud/files/9041179/app.netdata.cloud-1656953801417.log)
[app.netdata.cloud-1656953793862.log](https://github.com/netdata/netdata-cloud/files/9041181/app.netdata.cloud-1656953793862.log)

### Desktop

OS: Windows 10 and 11
Browser: Edge	and Chrome 
Browser Version: 103.0.1264.44 and 103.0.5060.66

### Additional context

These clients had been intermittently on and off over a few months and had been failing to auto-update.
When I tried to update them via the kick-start script (which is how they were installed in the first place) it kept failing complaining that it could not establish the type of the existing installation.
So I uninstalled completely using the uninstall script and did fresh installs.

**Comment by hugovalente-pm** [comment]
@luisj1983 we've made a release yesterday that we hope to have solved this. could you please try it?

fyi, now you can even delete offline nodes from the “All Nodes”. If you access the space settings and go to Nodes, you see the following table that allows you to filter all offline nodes, mass select them and bulk delete them.

![image](https://user-images.githubusercontent.com/82235632/181790176-0cd73ef8-4668-4853-b345-627a1c3a4da8.png)

**Comment by luisj1983** [comment]
@hugovalente-pm Thanks to the team for working on this, however, the issue still persists with agent version: v1.35.0-240-nightly.

**Comment by hugovalente-pm** [comment]
@luisj1983 could you potentially record a short video/gif of this? is the agent being reported as Offline on Netdata Cloud? 

the agent version shouldn't be relevant here, since this actions is managed on Netdata Cloud.

**Comment by luisj1983** [comment]
Sure thing:

https://youtu.be/wJeMDrUcTJ4

**Comment by hugovalente-pm** [comment]
thanks @luisj1983 , will pass this internally to further check on things

**Comment by hugovalente-pm** [comment]
@luisj1983 to help us clear some doubts, could you either:
1. do this action by logging in using a private window
1. do this on your normal browser window but having cleared cache+data for `app.netdata.cloud`

**Comment by hugovalente-pm** [comment]
the fix as been deployed, please try it again @luisj1983

**Comment by luisj1983** [comment]
haha, I didn't see your edit and so was really confused when I tested just now and it worked! Thought I'd done something stupid the first time around :-)
It looks to be working perfectly now.
Thank you very much to you and the team for your work on this!

**Comment by hugovalente-pm** [comment]
sorry for that, glad that it is now sorted out
will now close this ticket
