### ISSUE TITLE
[Bug]: Alert tab counters are not updated when global filter is applied

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#497]
### Bug description

Alert tab counters are not updated when global filter is applied

### Expected behavior

Alert tab counters should be updated when global filter is applied, otherwise it is misleading to the user

### Steps to reproduce

1. Go to prod room
2. Filter on a node in global filter
3. See that alert counters do not change
4. Visit alert tab and see empty page even if counters show active alerts

### Screenshots

https://user-images.githubusercontent.com/24860547/177331188-35fcc988-6eb9-4841-8ec9-bd1fd95990a5.mp4

### Desktop

OS: Windows
Browser: Chrome
Browser Version: 103.0.5060.66 (64 bit)

**Comment by jjtsou** [comment]
https://github.com/netdata/cloud-frontend/pull/3620

**Comment by jjtsou** [comment]
released
