### ISSUE TITLE
[Bug]: Chart in alert details modal and alert dedicated view "plays"

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#498]
### Bug description

Date time picker in alerts tab and alert's dedicated view is disabled.
When a user opens the modal by clicking the alert name, or visits the alert dedicated page the chart displayed is supposed to be a snapshot of the chart view around the time the alert was triggered and it shouldn't get updated.

### Expected behavior

Chart in alert details modal and dedicated view should not update after every /alarms-values update.

### Steps to reproduce

1. Navigate to Netdata Cloud
2. Claim an agent
3. Trigger an alert to that agent
4. Open the alert's details modal by navigating to Alerts tab and clicking the desired alert name
5. Monitor the chart displayed and wait for a new /alarms-values request to be issued

### Screenshots

When first opening the alert details modal

![image](https://user-images.githubusercontent.com/19268853/177542091-e776af70-6c03-4cc2-b637-f224e8a636d4.png)

After waiting for a while 
![image](https://user-images.githubusercontent.com/19268853/177542275-71cca158-e2be-4801-aa2b-d6cc41a8b41d.png)

### Error Logs

- 

### Desktop

OS: MacOS
Browser: CHrome
Browser Version: 103

**Comment by dimko** [comment]
@jacekkolasa as discussed, assigning it to you.

**Comment by hugovalente-pm** [comment]
@dimko I was trying to validate if this was still happening and I couldn't reproduce it, could you validate as well?

**Comment by novykh** [comment]
This is not the issue here, it's discussed multiple times in the past that the value we are receiving is the latest value of the alert, but not the value that triggered the alert, hence it's forever changing. We need the actual value when the alert got triggered inside the active alerts or somewhere else and use that instead. Hope it's clear.

**Comment by hugovalente-pm** [comment]
the issue that @dimko reported was about the chart being in "play" mode, right @dimko?

@novykh if you check screenshot 1 and screenshot 2 there is a chance in the graph that the alert triggered value actually didn't change. probably you are speaking about a different bug

let's probably discuss this after the daily today

**Comment by dimko** [comment]
Yes. The problem is that the chart plays even though it is paused and dateyimepicker is disabled. This was the case when I opened it at least. We can check tomorrow, when I'll be back.

**Comment by hugovalente-pm** [comment]
yes, let's discuss tomorrow

**Comment by novykh** [comment]
@dimko @hugovalente-pm let's jump on a meet?
