### ISSUE TITLE
[BUG] first_entry is different when accessing node through Cloud

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata-cloud#50]
**Describe the bug**	
When accessing the same node through Cloud or directly from Agent's Dashboard ,`first_entry` is different. The difference varies - sometimes it's just 1 second, sometimes more than 2 hours.
I'm not sure if this bug is not only valid for our test infrastructure.

**Expected behavior**	
We should see the same data/metadata from Agent Dashboard and Cloud's Node-view

**Screenshots**	

https://staging.netdata.cloud/api/v1/nodes/226fdb02-d510-43e0-82b7-ba0a00440252/data?chart=system.io&_=1613650295832&format=json&points=90&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-900
![image](https://user-images.githubusercontent.com/5786722/108388210-b2372880-720e-11eb-9d9c-462dc7793f63.png)

https://netdata.corp.staging.netdata.cloud/host/gke-staging-main-3dce75e9-8ou7/api/v1/data?chart=system.io&_=1613650295832&format=json&points=90&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-900
![image](https://user-images.githubusercontent.com/5786722/108388187-a8adc080-720e-11eb-9966-008e8e7a3edb.png)

Notice that `latest_values` match, so it looks like it's the same node. All query params in the urls are the same.

Are we sure those are the same nodes?
![image](https://user-images.githubusercontent.com/5786722/108388473-f75b5a80-720e-11eb-8faf-3a36eda05e01.png)
![image](https://user-images.githubusercontent.com/5786722/108388502-ffb39580-720e-11eb-94ee-4b28c00c61ee.png)

The `version`/`history`/`memory_mode` are different, but the `hostname` matches.

Also, i've noticed that `id`s of those nodes are changing in the Cloud - after some time, it seems to have restarted: The same `hostname` now has new id, history is cleared, and the first_entry is matching or the difference is just 1 second. After some time (an hour) it desynchronises again.

Related to https://github.com/netdata/netdata-cloud/issues/47

**Comment by chrikar** [comment]
To provide some background on this, the netdata children are configured to stream their data to the parent, which is configured with a dbengine and a big retention period. So if we go to the parent's netdata page we can see all this information that the children have sent by accessing the parent's db. However, from the cloud we are now still contacting the children directly to request the data, and the children were configured to have really small history of `60` in their stream.conf.

We have now increased this to `3600`, so we should have at least 1 hour of data in the children, until we are able to get the data we want from the cloud directly from the children.
