### ISSUE TITLE
[Bug]: chart family is not correctly rendered in notification

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata-cloud#506]
### Bug description

E-mail notifications don't properly render the string with alert details. E.g.:

> Details: disk **$family** space utilization

### Expected behavior

`$family` should be expanded, in this case to `/var`.

### Steps to reproduce

1. Observe disk space alerts notification e-mails.

### Screenshots

![image](https://user-images.githubusercontent.com/116741/178294714-082a466d-b5f7-4056-bced-c23bad9896af.png)

### Additional context

Possibly, the chart family should also be rendered in the title.

**Comment by dimko** [comment]
I see the following issue as fixed https://github.com/netdata/netdata-cloud/issues/466

is this a new email @ralphm ?

**Comment by dimko** [comment]
@car12o this is similar to https://github.com/netdata/netdata-cloud/issues/466 but for alert emails do you think it's easy to fix?

**Comment by car12o** [comment]
@dimko indeed, we fixed on the UI but seems like we also need to fix it on the email :sweat_smile:

**Comment by car12o** [comment]
Fix deployed to prod!
