### ISSUE TITLE
[Bug]: Postgres DB instances are displayed incorrectly 

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#507]
### Bug description

If you have multiple Postgres DB instances, they currently show up as different sections on the TOC menu but in each chart data from all instances are present. This is confusing and incorrect. 

In the below example I have two Postgres dbs, one called "example" and another called "postgres". But in the chart for "example" shown here you can see two instances listed one for "example" and another for "postgres". 

![image](https://user-images.githubusercontent.com/24860547/178298443-73be3976-a557-47e4-b00e-eef307fdfcdb.png)

### Expected behavior

Expected behavior is to be similar to how "Mount Points" and "Disks" are treated where there is an "all" option which covers all the instances. See example below:

![image](https://user-images.githubusercontent.com/24860547/178298866-44484d85-3691-412b-9f4e-379ebe97a4f0.png)

### Steps to reproduce

Have a working PostgreSQL database and enable Netdata PostgreSQL collector

### Desktop

N/A

**Comment by hugovalente-pm** [comment]
this isn't actually a bug it is a feature to be deal with https://github.com/netdata/netdata-cloud/issues/295, so closing the bug as discussed with you

**Comment by shyamvalsan** [comment]
Re-opening this, as there seems to be an actual defect here - specific to cloud representation of this data - as well. 

For an example see the Postgres section of the [agent dashboard](https://netdata.corp.app.netdata.cloud/host/netdata-parent-5d7769ddc7-x428z/#menu_postgres_vernemq_submenu_db_postgres;after=0;before=0;theme=slate;utc=Europe/Kiev ) for production



Now see the Postgres section in the cloud[ K8s war room](https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/overview#chartName=menu_postgres&appliedFilteredIds=&reachableNodesIds=&staleNodesIds=&unreachableNodesIds=&filteredNodesSearchParams=&metrics_correlation=false&after=-900&before=0&utc=Europe%2FHelsinki&offset=%2B3&timezoneName=Helsinki%2C%20Kyiv%2C%20Riga%2C%20Sofia%2C%20Tallinn%2C%20Vilnius)

**Comment by novykh** [comment]
This is backend @juacker (sorry for mentioning you always, I believe you are the only one back from holiday for viz team.)

**Comment by shyamvalsan** [comment]
We also have the problem (not sure if it is the same, related or different) where if you have the same DB name Eg: postgres across different instances then they all get clubbed together in the chart showing a weird aggregate-inflated meaningless number instead of showing them separately.

**Comment by novykh** [comment]
The grouping is happening by context, not sure how the example you mentioned can be handled. Someone from the backend please help? :)

**Comment by juacker** [comment]
Let me take a lookk, no problem for mentioning me @novykh, its ok!.
@shyamvalsan your links above are not working for me , can you invite me to an space with multiple pg databases, please?

**Comment by shyamvalsan** [comment]
@juacker with the new Go collector for postgres, we no longer have this issue since we don't have separate charts per DB, rather it is composite charts across all DBs. 

But the problem I mentioned in my comment earlier still exists - you can see this on the Netdata production space, there are multiple databases called postgress across different instances but no way for us to differentiate them in our charts

cc: @sashwathn @ralphm

**Comment by juacker** [comment]
I think I understand what you mean. For example here we can see 19 charts contributing to the composite chart, There are 4 pg instances, and in total 15 different database names. The DB name `postgres` exists on all pg instances, so if you group by database, the values for that db are aggregated:

![image](https://user-images.githubusercontent.com/2930882/185619335-452da9f6-5f9a-4e25-acee-b814191fae1a.png)

If you group by instance and filter by `postgres` database you can see the individual postgres values:

![image](https://user-images.githubusercontent.com/2930882/185619976-f74f3913-5c39-4430-a9ac-df7ebeb03fa3.png)


Could this be an option?

**Comment by sashwathn** [comment]
@juacker you are absolutely right and currently there is no way to filter / group by the postgres instance.

And even if we do, there should be some way in our database filtering to differentiate the 4 postgres instances.

**Comment by sashwathn** [comment]
@juacker and @shyamvalsan : Just to point out that the instance is not referring to the Postgres instance but the chart instance / context? And although we are able to see the postgres db per instance with the **group by instance + filter by database name**, I think we need to add the "Postgres instance" label and enable it for filtering for a better visualisation and understanding.

cc: @ralphm @ktsaou @amalkov

**Comment by hugovalente-pm** [comment]
@shyamvalsan @sashwathn I'm not sure this is a bug atm, with the work done to have the charts based on context and the new collector we don't have the chart titles issues

![image](https://user-images.githubusercontent.com/82235632/185960067-32ab773e-415f-4510-b14c-fbed881941d7.png)

I'm aware that there is limited capability to easily filter the data, but we have ways to change the grouping of the charts to `database` select the `dimensions` to see on the chart, etc.

we may have work as feature enhancements, but not as a a bug fix.
wdyt?

**Comment by shyamvalsan** [comment]
@hugovalente-pm I agree the original bug no longer exists with the new Go collector.

maybe we need a separate ticket to track all dbs with the same name being clubbed together.

**Comment by hugovalente-pm** [comment]
thanks for confirming @shyamvalsan, I believe this ticket already captures the need to be able to display dbs as not clubbed together - https://github.com/netdata/netdata-cloud/issues/550. if you don't agree I can open a new one.

closing this one based on the above.
