### ISSUE TITLE
[Bug]: Group by node triggering anomaly rate call when it shouldn't

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#508]
### Bug description

I'm switching overview charts to group `by node` on a personal space with two nodes and on Netdata Cloud room `k8s-prd-parent`. Whenever I do that switch on `system.cpu` and a lot of other charts I see a failed `data` call with a 400 response and many following `data` calls with every single point returning as 0. Switching back to `by dimension` fixes it. 

### Expected behavior

Get proper data back

### Steps to reproduce

1. Switch to by node and see the results. 

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@cakrit was trying this out today and it seemed a glitch since today I can't reproduce it.
@dimko were you able to see this happening?

**Comment by dimko** [comment]
@hugovalente-pm I've tried, but can't reproduce it.
@cakrit could you please post the `/data` requests?

**Comment by cakrit** [comment]
Repeated it now.

List of requests when switching to by node:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/43294513/178496006-f928160f-6148-4b79-8f31-d10974b5806b.png">

1st request
```Request URL: https://app.netdata.cloud/api/v2/spaces/31a2fba1-8ee2-4fa0-9fed-bb437e3fb75c/rooms/edc22286-b5ee-4c1f-bc28-eea6cc02a84c/data
Request Method: POST
Status Code: 400 
Remote Address: 54.198.178.11:443
Referrer Policy: strict-origin-when-cross-origin
content-length: 653
content-type: application/json; charset=utf-8
date: Tue, 12 Jul 2022 12:59:44 GMT
netdata-request-id: IWGf28ESw4-1853072
vary: Accept-Encoding
:authority: app.netdata.cloud
:method: POST
:path: /api/v2/spaces/31a2fba1-8ee2-4fa0-9fed-bb437e3fb75c/rooms/edc22286-b5ee-4c1f-bc28-eea6cc02a84c/data
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,el;q=0.8
cache-control: no-cache
content-length: 374
content-type: text/plain;charset=UTF-8
cookie: _gcl_au=1.1.971011366.1657217117; _ga=GA1.2.1167182375.1657217118; _gaexp=GAX1.2.6qDACkKtQ3G6NnGb_xNbcg.19251.4; _fbp=fb.1.1657217117834.711219208; SL_C_23361dd035530_DOMAIN=true; hubspotutk=a6d35f0642d2ce81ce71e9c2a2af4366; __hssrc=1; __hs_initial_opt_in=true; __hs_opt_out=no; SL_C_23361dd035530_KEY=7fffcc8bd531e0e404ae570ed2894af66c2f5dd2; SL_C_23361dd035530_VID=4cN9qe-Mib; s_i=09KK5BUVM9HOK; s_v_09KK5BUVM9HOK=eyJhbGciOiJIUzI1NiIsImtpZCI6ImRlZmF1bHQiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiIzOGY1ZTE3NS1mNmEyLTQ3ZWItYjJmNy00YjEzY2NhNTZhYWYiLCJleHAiOjE2NjUwNjA5MjUsImlhdCI6MTY1NzI4NDkyNSwiZW1haWwiOiJjaHJpc0BuZXRkYXRhLmNsb3VkIiwib19hdXRoX3VzZXIiOnsiSUQiOiIiLCJFbWFpbCI6IiIsIk5hbWUiOiIiLCJBdmF0YXJVUkwiOiIifX0.plKvJ6wxqIE6SWUrBG53eDdnid2BtxH5WXddahEp7Sc; apt.uid=AP-WA6UGT2X7KII-2-1657284925327-79479678.0.2.a9d5baa0-c380-484e-850c-5b038149b66a; _gid=GA1.2.627769829.1657537059; _gat_UA-64295674-3=1; apt.sid=AP-WA6UGT2X7KII-2-1657630730097-98295969; __hstc=3319087.a6d35f0642d2ce81ce71e9c2a2af4366.1657217118569.1657555354234.1657630731132.11; __hssc=3319087.1.1657630731132; SL_C_23361dd035530_SID=eI8_WXM4s3; ph_phc_hnhlqe6D2Q4IcQNrFItaqdXJAxQ8RcHkPAFAp74pubv_posthog=%7B%22distinct_id%22%3A%2238f5e175-f6a2-47eb-b2f7-4b13cca56aaf%22%2C%22%24device_id%22%3A%2217c4af2dce13d-0ce6e44fb36846-b7a1b38-384000-17c4af2dce2113e%22%2C%22%24initial_referrer%22%3A%22%24direct%22%2C%22%24initial_referring_domain%22%3A%22%24direct%22%2C%22%24referrer%22%3A%22https%3A%2F%2Fwww.google.com%2F%22%2C%22%24referring_domain%22%3A%22www.google.com%22%2C%22%24session_recording_enabled%22%3Afalse%2C%22%24active_feature_flags%22%3A%5B%5D%2C%22%24search_engine%22%3A%22google%22%2C%22event_source%22%3A%22cloud%22%2C%22posthog_first_seen_at%22%3A%222021-10-11T12%3A04%3A00.765Z%22%2C%22posthog_first_distinct_id%22%3A%2217c4af2dce13d-0ce6e44fb36846-b7a1b38-384000-17c4af2dce2113e%22%2C%22%24user_id%22%3A%2238f5e175-f6a2-47eb-b2f7-4b13cca56aaf%22%2C%22netdata_cloud_account_id%22%3A%2238f5e175-f6a2-47eb-b2f7-4b13cca56aaf%22%2C%22netdata_cloud_account_email%22%3A%22chris%40netdata.cloud%22%2C%22netdata_cloud_signed_in_at%22%3A%222021-10-11T12%3A04%3A04.864Z%22%2C%22utm_source%22%3A%22hs_email%22%2C%22utm_content%22%3A%22125436410%22%2C%22%24enabled_feature_flags%22%3A%7B%7D%2C%22%24sesid%22%3A%5B1657630782670%2C%22181f27da466397-02be0121ec8dca-26021a51-384000-181f27da467605%22%2C1657630729318%5D%2C%22utm_medium%22%3A%22email%22%2C%22%24session_recording_enabled_server_side%22%3Afalse%2C%22utm_campaign%22%3A%22Cloud%20Onboarding%22%7D
origin: https://app.netdata.cloud
pragma: no-cache
referer: https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd-parent/overview
sec-ch-ua: ".Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
```

1st request payload:
```
{"filter":{"nodeIDs":["8fc23294-3d9c-4681-8bb4-448deed086e6","4110549d-9601-4989-9bc5-7607ccc14426"],"context":"system.cpu"},"aggregations":[{"method":"sum","groupBy":["chart","node"]},{"method":"avg","groupBy":["node"]}],"agent_options":["anomaly-bit","jsonwrap","flip","ms","abs"],"points":-47,"format":"json","group":"average","gtime":0,"after":-900,"with_metadata":true}
```

1st response
```
{
    "errorMsgKey": "ErrAllNodesFailed",
    "errorMessage": "ErrAllNodesFailed",
    "errorCode": "IWGf28ESw4-1853072",
    "nodes": [
        {
            "id": "4110549d-9601-4989-9bc5-7607ccc14426",
            "routing_latency": "0s",
            "adc_latency": "0s",
            "error": {
                "errorMsgKey": "IgnoreNoDataAvailable",
                "errorMessage": "IgnoreNoDataAvailable",
                "errorCode": "IWGf28ESw4-1853072"
            },
            "chartIDs": [],
            "hops": 0,
            "coverage": 0,
            "db_points_per_tier": null
        },
        {
            "id": "8fc23294-3d9c-4681-8bb4-448deed086e6",
            "routing_latency": "0s",
            "adc_latency": "0s",
            "error": {
                "errorMsgKey": "IgnoreNoDataAvailable",
                "errorMessage": "IgnoreNoDataAvailable",
                "errorCode": "IWGf28ESw4-1853072"
            },
            "chartIDs": [],
            "hops": 0,
            "coverage": 0,
            "db_points_per_tier": null
        }
    ]
}
```

2nd request
```
Request URL: https://app.netdata.cloud/api/v2/spaces/31a2fba1-8ee2-4fa0-9fed-bb437e3fb75c/rooms/edc22286-b5ee-4c1f-bc28-eea6cc02a84c/data
Request Method: POST
Status Code: 200 
Remote Address: 54.198.178.11:443
Referrer Policy: strict-origin-when-cross-origin
content-encoding: gzip
content-length: 1860
content-type: application/json; charset=utf-8
date: Tue, 12 Jul 2022 12:59:44 GMT
netdata-request-id: IWGf28ESw4-1853075
vary: Accept-Encoding
:authority: app.netdata.cloud
:method: POST
:path: /api/v2/spaces/31a2fba1-8ee2-4fa0-9fed-bb437e3fb75c/rooms/edc22286-b5ee-4c1f-bc28-eea6cc02a84c/data
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,el;q=0.8
cache-control: no-cache
content-length: 383
content-type: text/plain;charset=UTF-8
cookie: _gcl_au=1.1.971011366.1657217117; _ga=GA1.2.1167182375.1657217118; _gaexp=GAX1.2.6qDACkKtQ3G6NnGb_xNbcg.19251.4; _fbp=fb.1.1657217117834.711219208; SL_C_23361dd035530_DOMAIN=true; hubspotutk=a6d35f0642d2ce81ce71e9c2a2af4366; __hssrc=1; __hs_initial_opt_in=true; __hs_opt_out=no; SL_C_23361dd035530_KEY=7fffcc8bd531e0e404ae570ed2894af66c2f5dd2; SL_C_23361dd035530_VID=4cN9qe-Mib; s_i=09KK5BUVM9HOK; s_v_09KK5BUVM9HOK=eyJhbGciOiJIUzI1NiIsImtpZCI6ImRlZmF1bHQiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiIzOGY1ZTE3NS1mNmEyLTQ3ZWItYjJmNy00YjEzY2NhNTZhYWYiLCJleHAiOjE2NjUwNjA5MjUsImlhdCI6MTY1NzI4NDkyNSwiZW1haWwiOiJjaHJpc0BuZXRkYXRhLmNsb3VkIiwib19hdXRoX3VzZXIiOnsiSUQiOiIiLCJFbWFpbCI6IiIsIk5hbWUiOiIiLCJBdmF0YXJVUkwiOiIifX0.plKvJ6wxqIE6SWUrBG53eDdnid2BtxH5WXddahEp7Sc; apt.uid=AP-WA6UGT2X7KII-2-1657284925327-79479678.0.2.a9d5baa0-c380-484e-850c-5b038149b66a; _gid=GA1.2.627769829.1657537059; _gat_UA-64295674-3=1; apt.sid=AP-WA6UGT2X7KII-2-1657630730097-98295969; __hstc=3319087.a6d35f0642d2ce81ce71e9c2a2af4366.1657217118569.1657555354234.1657630731132.11; __hssc=3319087.1.1657630731132; SL_C_23361dd035530_SID=eI8_WXM4s3; ph_phc_hnhlqe6D2Q4IcQNrFItaqdXJAxQ8RcHkPAFAp74pubv_posthog=%7B%22distinct_id%22%3A%2238f5e175-f6a2-47eb-b2f7-4b13cca56aaf%22%2C%22%24device_id%22%3A%2217c4af2dce13d-0ce6e44fb36846-b7a1b38-384000-17c4af2dce2113e%22%2C%22%24initial_referrer%22%3A%22%24direct%22%2C%22%24initial_referring_domain%22%3A%22%24direct%22%2C%22%24referrer%22%3A%22https%3A%2F%2Fwww.google.com%2F%22%2C%22%24referring_domain%22%3A%22www.google.com%22%2C%22%24session_recording_enabled%22%3Afalse%2C%22%24active_feature_flags%22%3A%5B%5D%2C%22%24search_engine%22%3A%22google%22%2C%22event_source%22%3A%22cloud%22%2C%22posthog_first_seen_at%22%3A%222021-10-11T12%3A04%3A00.765Z%22%2C%22posthog_first_distinct_id%22%3A%2217c4af2dce13d-0ce6e44fb36846-b7a1b38-384000-17c4af2dce2113e%22%2C%22%24user_id%22%3A%2238f5e175-f6a2-47eb-b2f7-4b13cca56aaf%22%2C%22netdata_cloud_account_id%22%3A%2238f5e175-f6a2-47eb-b2f7-4b13cca56aaf%22%2C%22netdata_cloud_account_email%22%3A%22chris%40netdata.cloud%22%2C%22netdata_cloud_signed_in_at%22%3A%222021-10-11T12%3A04%3A04.864Z%22%2C%22utm_source%22%3A%22hs_email%22%2C%22utm_content%22%3A%22125436410%22%2C%22%24enabled_feature_flags%22%3A%7B%7D%2C%22%24sesid%22%3A%5B1657630782670%2C%22181f27da466397-02be0121ec8dca-26021a51-384000-181f27da467605%22%2C1657630729318%5D%2C%22utm_medium%22%3A%22email%22%2C%22%24session_recording_enabled_server_side%22%3Afalse%2C%22utm_campaign%22%3A%22Cloud%20Onboarding%22%7D
origin: https://app.netdata.cloud
pragma: no-cache
referer: https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd-parent/overview
sec-ch-ua: ".Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
```

2nd request payload
```
{"filter":{"nodeIDs":["8fc23294-3d9c-4681-8bb4-448deed086e6","4110549d-9601-4989-9bc5-7607ccc14426"],"context":"system.cpu","dimensions":["guest"]},"aggregations":[{"method":"sum","groupBy":["chart","node"]},{"method":"avg","groupBy":["node"]}],"agent_options":["jsonwrap","flip","ms","abs"],"points":535,"format":"json","group":"average","gtime":0,"after":-900,"with_metadata":true}
```

2nd request response
{
    "api": 1,
    "id": "system.cpu",
    "name": "system.cpu",
    "view_update_every": 2,
    "first_entry": 1656579280,
    "last_entry": 1657630783,
    "after": 1657629715,
    "before": 1657630784,
    "min": 0,
    "max": 0,
    "dimension_names": [
        "aws-parent-1",
        "aws-parent-0"
    ],
    "dimension_ids": [
        "4110549d-9601-4989-9bc5-7607ccc14426",
        "8fc23294-3d9c-4681-8bb4-448deed086e6"
    ],
    "view_latest_values": [
        0,
        0
    ],
    "dimensions": 2,
    "points": 535,
    "format": "json",
    "result": {
        "labels": [
            "time",
            "4110549d-9601-4989-9bc5-7607ccc14426",
            "8fc23294-3d9c-4681-8bb4-448deed086e6"
        ],
        "data": [
            [
                1657629716000,
                0,
                0
            ],
....
            [
                1657630784000,
                0,
                0
            ]
        ]
    },
    "nodes": [
        {
            "id": "4110549d-9601-4989-9bc5-7607ccc14426",
            "routing_latency": "515.679µs",
            "adc_latency": "8.855371ms",
            "chartIDs": [
                "system.cpu"
            ],
            "hops": 0,
            "coverage": 1,
            "db_points_per_tier": [
                1070,
                0,
                0
            ]
        },
        {
            "id": "8fc23294-3d9c-4681-8bb4-448deed086e6",
            "routing_latency": "516.699µs",
            "adc_latency": "6.510849ms",
            "chartIDs": [
                "system.cpu"
            ],
            "hops": 1,
            "coverage": 1,
            "db_points_per_tier": [
                1070,
                0,
                0
            ]
        }
    ],
    "keys": {
        "node": [
            "4110549d-9601-4989-9bc5-7607ccc14426",
            "8fc23294-3d9c-4681-8bb4-448deed086e6"
        ]
    },
    "labels": {},
    "all_dimensions": {
        "guest": {
            "id": "guest",
            "name": "guest"
        },
        "guest_nice": {
            "id": "guest_nice",
            "name": "guest_nice"
        },
        "idle": {
            "id": "idle",
            "name": "idle"
        },
        "iowait": {
            "id": "iowait",
            "name": "iowait"
        },
        "irq": {
            "id": "irq",
            "name": "irq"
        },
        "nice": {
            "id": "nice",
            "name": "nice"
        },
        "softirq": {
            "id": "softirq",
            "name": "softirq"
        },
        "steal": {
            "id": "steal",
            "name": "steal"
        },
        "system": {
            "id": "system",
            "name": "system"
        },
        "user": {
            "id": "user",
            "name": "user"
        }
    }
}
```

**Comment by dimko** [comment]
Thanks @cakrit . In the first request that gets the Bad Request status, I see that points asked is a negative number `"points":-47,`

I am pretty sure this is the issue.

Can someone from @netdata/cloud-fe explain how are those points defined and requested? How is it possible to request for negative points?

**Comment by hugovalente-pm** [comment]
with the pinpointing of the potential cause, seeing that this isn't something happening all the time (seems related to viewport size) and looking that we don't have an high rate of  400 errors on the `/data` requests for the composite chart ([link](https://grafana.corp.app.netdata.cloud/d/qiI8zr5nk/overview-flow?orgId=1&viewPanel=12&from=now-7d&to=now&refresh=30s) was thinking of reducing this to a `priority/medium`

all ok?

**Comment by hugovalente-pm** [comment]
thanks @burbuli8ra for the taking the time to investigate this and sharing the detailed summary of your findings

I'll open a separate ticket for the negative value on `points`, with low priority, and add link it here just for tracking.

for the `4xx` error we are also getting a help from @BillKalaitzis since we saw a pattern coming up from 8:40 UTC today with a constant stream of these type of responses. hopefully it will help us track where/what is causing these

**Comment by BillKalaitzis** [comment]
Hello everyone,
I've had a look at the issue and I think that we're actually talking about two different problems.

### HTTP 400 
The recent HTTP 400 increase ever since 13/07 8.40UTC seem to be originating from a single space.
We can group the HTTP 400 errors via the following Loki query:
```
sum(rate({app="cloud-charts-service"} | json | code=~"4[0-9]*" [30m])) by (url,code)
```
The problematic `/data` request looks like this:
```
{"time":"2022-07-13T18:45:56.289794363Z","level":"info","severity":"INFO","message":"request","svc":"cloud-charts-service-0-59d4cfbbf8-tcz66","request_id":"oCpc0ryQHf-3754013","method":"POST","host":"app.netdata.cloud","url":"/api/v2/spaces/8928b747-bcb5-4262-bdc1-f24bef52d141/rooms/26e6d0a8-95aa-4493-9359-dcfb430c06bb/data","code":400,"status":"Bad Request","duration":10.008954442}
```
![Screenshot 2022-07-13 at 8 58 50 PM](https://user-images.githubusercontent.com/11575975/178937916-1bf9fef4-1fe5-4d3a-99e7-e36a121ec179.png)

As we can see, the request and error is similar to what @cakrit has already reported, but this specific space is generating a few orders of magnitude more HTTP 400 errors than any other space.
The HTTP 400 is something we should definitely investigate, but since the main source of failed requests originate just from a single space, makes me believe that the actual root cause might not be on our side.
@cakrit , is the HTTP400 on the `/data` endpoint something you can consistency reproduce?  I gave it a few tries but couldn't get a 400 response.

### Zero data points for system.cpu
It seems that after switching the grouping to `by node`, our UI will select only the first available dimension.
For the case of `system.cpu`, it selects `for=guest`, which would explain why @cakrit sees only data points with 0 value - I wouldn't expect to see any non-zero values for `system.cpu.guest`, unless an HV is running on the node.
@cakrit, can you please verify that everything looks good if you switch the dimension selection to `All dimensions`?
If that's the case, I think we should revisit the default dimension selection for `node` and `instance` grouping on our UI.

**Comment by cakrit** [comment]
@BillKalaitzis you nailed it with the automated selection of `guest`. The moment I switch to `by node` only the `guest` dimension is selected.

I cleared all site data and reloaded the FE, but the issue is still there. So it looks like an FE bug to me. 

I have my VMs down now, but I'm still getting the same behavior on the k8s-prd-parent room

**Comment by cakrit** [comment]
I added you and Bill.

**Comment by hugovalente-pm** [comment]
was checking this one and I saw the `400` s and it is alway one call for `/data` that fails and the next one works, the one that fails is triggering the request for the anomaly-rate, e.g. below, which I don't think should have been triggered on Group by change since the icon is not available on the chart

![image](https://user-images.githubusercontent.com/82235632/180455321-68c2d7ee-222a-4a3c-a84f-65dd2216d91c.png)


```json
{
	"filter": {
		"nodeIDs": [
			"8fc23294-3d9c-4681-8bb4-448deed086e6",
			"4110549d-9601-4989-9bc5-7607ccc14426"
		],
		"context": "system.cpu"
	},
	"aggregations": [
		{
			"method": "avg",
			"groupBy": [
				"dimension"
			]
		}
	],
	"agent_options": [
		"anomaly-bit",
		"jsonwrap",
		"flip",
		"ms"
	],
	"points": -47,
	"format": "json",
	"group": "average",
	"gtime": 0,
	"after": -43200,
	"with_metadata": true
}
```

**Comment by hugovalente-pm** [comment]
@cakrit decreasing the priority to medium, since the issue with the default dimension selection has been fixed and these 400's seem to be exaplained by ☝️

**Comment by jjtsou** [comment]
https://github.com/netdata/cloud-frontend/pull/3728

**Comment by hugovalente-pm** [comment]
this was fixed
