### ISSUE TITLE
[BUG] Unable to pick custom timerange on cloud dashboard

### ISSUE THREAD

**Issue by chrikar** [netdata/netdata-cloud#51]
**Describe the bug**	
Changing the time period to using the timestamp and not the "Show X latest minutes/hours etc" appears to have no actual effect. The time reverts to it's original values when clicking on anything else.

**To Reproduce**	
Check video.

**Expected behavior**	
Accepting a custom time period for getting chart data.

**Screenshots**	
Video attached.
https://user-images.githubusercontent.com/2836342/108420984-31435580-723d-11eb-8a3c-fef486ab229c.mp4

**Error logs**	
`API is not enabled in project settings` in dev console

**Desktop (please complete the following information):**	
 - OS: Ubuntu 20.10
 - Browser: Google Chrome 
 - Version: 88

**Comment by cakrit** [comment]
@jacekkolasa I believe that this has been fixed for a while. Please close if that's the case.

**Comment by manos-saratsis** [comment]
Fixed and I am closing this
