### ISSUE TITLE
[Bug]: Dashboard Chart doesnt show

### ISSUE THREAD

**Issue by jonknud** [netdata/netdata-cloud#510]
### Bug description

Some of the charts only show part of the graph. But I can see the data in mouse over.

![image](https://user-images.githubusercontent.com/28842347/178685847-868c41ad-7525-49e8-8997-a67dc414a8ea.png)

### Expected behavior

I can see the complete graph.

### Steps to reproduce

1. creat a dashboard
2. add some nodes
3. logout / login
4. select long time span

### Desktop

OS: Windows
Browser Vivaldi
Browser Version: latest

**Comment by dimko** [comment]
@jonknud hey, once again thanks for the report 😄 Netdata Cloud is currently under a scheduled maintenance https://status.netdata.cloud/?utm_source=embed so this could be the reason for those missing data. Could you please re-try  once maintenance is done? I'll help identify the issue if it persists.

**Comment by hugovalente-pm** [comment]
@jonknud did you experience this issue again?

**Comment by jonknud** [comment]
Sorry for the long answer delay

![image](https://user-images.githubusercontent.com/28842347/180477813-bd8b7d72-a8b6-4528-b41e-5adf8d1dbb34.png)

Unfortunaly it is not related to the maintainance.

I have the problem now for a couple of month and always hoped that it will be fixed one day, because I dont now how I could help you with fixing it.

**Comment by jonknud** [comment]
please reopen

**Comment by hugovalente-pm** [comment]
sure @jonknud we will re-open it, me and @dimko will try to see how we can help you to helps us troubleshoot this.

as a starter, could you:
* confirm what agent version you're running on your nodes?
* if you open the Single Node view, for any of the nodes on that composite chart, do you see the same issue?
* could you check if you open the dev-tools console on your browser if you see any errors?

**Comment by hugovalente-pm** [comment]
sure @jonknud we will re-open it, me and @dimko will try to see how we can help you to helps us troubleshoot this.

as a starter, could you:
* confirm what agent version you're running on your nodes?
* if you open the Single Node view, for any of the nodes on that composite chart, do you see the same issue?
* could you check if you open the dev-tools console on your browser if you see any errors?

**Comment by jonknud** [comment]
Hello.

> confirm what agent version you're running on your nodes?

I thought all node are up to date but:

![image](https://user-images.githubusercontent.com/28842347/180936828-442cc554-9c99-487e-ac5b-b1e6fc925dcd.png)

Is there a way in netdata cloud to find the version of the agent for every node?

> if you open the Single Node view, for any of the nodes on that composite chart, do you see the same issue?

I dont have problems in sigle node charts.

> could you check if you open the dev-tools console on your browser if you see any errors?

I cant see any problem in the dev tools.

**Idea:**

Maybe the problem only exist if I select 18h.

If I select 12h it seams fine

![image](https://user-images.githubusercontent.com/28842347/180937462-6e7e379a-b2d6-4a36-b4d1-f23ccc92fae7.png)


24h also doesnt work.

**Comment by hugovalente-pm** [comment]
> Is there a way in netdata cloud to find the version of the agent for every node?

unfortunately atm this isn't possible but we want to make it available soon, the only alternative is to go through the nodes on the `Nodes tab` and click the info icon on each
![image](https://user-images.githubusercontent.com/82235632/181222603-21dbbbcb-5528-4b9d-b599-edf4ec64769b.png)

do you think you could get the 3 nodes on `v1.34.1` updated to `v1.35.1` to see if the issue is sorted out?

**Comment by jonknud** [comment]
I updated all nodes. I did not help.

**Comment by hugovalente-pm** [comment]
thanks for trying that, I think next we need to dig into a specific example. 

on this chart that you shared previously could you open the dev-tools and on the network console get us the request payload and response you got? (you can email them to me if you prefer to hugo at netdata dot cloud )

![image](https://user-images.githubusercontent.com/82235632/182640922-6fbb366a-6fe1-43f1-a956-eb3bfa7169a9.png)

**Comment by jonknud** [comment]
This can be closed. It is working now.
