### ISSUE TITLE
[Bug]: netdata cloud shows 500 code. 

### ISSUE THREAD

**Issue by ALEXSANPEDRO** [netdata/netdata-cloud#511]
### Bug description

try to check app.netdata.cloud and see 500 error code

### Expected behavior

Nothing

### Steps to reproduce

??

### Error Logs

nothing

### Desktop

OS: [win10]	
Browser [firefox]	
Browser Version [102.0.1]

**Comment by dimko** [comment]
This is due a scheduled maintenance https://status.netdata.cloud/?utm_source=embed

**Comment by dimko** [comment]
System back to normal. Maintenance completed
