### ISSUE TITLE
[Bug]: Status discrepancy on offline nodes, can't delete them

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#513]
### Bug description

In the picture below, notice how the home page shows 2 offline nodes, but the filter shows them as stale. 

![image](https://user-images.githubusercontent.com/43294513/178997798-cb3c1681-c7a6-4da2-8afb-e8db974e9667.png)

This could be just an unrelated bug to the more serious issue, that I can't delete nodes that really are offline, because they are incorrectly marked as stale. Stale nodes are supposed to have some data on a parent that's live, but this is certainly not the case (I've clicked on the two "stale" nodes, expanded the time window to be as large as possible and there's just no data there). 

So it looks like a glitch in updating the state. I have the same exact report from a user. The common pattern is that we unclaimed and reclaimed on the same machine. The user reinstalled Netdata there. I've personally done many reclaims and did at some point have a parent too, so it can get complicated to trace. I will provide the other user's details offline.

We saw the behavior with @amalkov on my room, he is invited and can assist with the investigation too.

### Expected behavior

Offline nodes should be offline, not stale. 

### Steps to reproduce

No idea, possibly a missing message because of a sudden shutdown. 

### Desktop

Browser Version [e.g. 22]

**Comment by burbuli8ra** [comment]
This issue has been fixed with implementation of [Cloud Frontend #3672](https://github.com/netdata/cloud-frontend/issues/3672).

**Comment by hugovalente-pm** [comment]
this have been confirmed in PROD

**Comment by cakrit** [comment]
It works great, good job!

**Comment by burbuli8ra** [comment]
Released on [v2.36.0](https://github.com/netdata/cloud-frontend/releases/tag/2.36.0)
