### ISSUE TITLE
[Bug]: After deleting nodes, counters are not updated

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata-cloud#516]
### Bug description

When deleting (obsoleting) nodes, counters in Manage-Space/War-Rooms table do not update.

### Expected behavior

After deleting nodes, table in "Manage Space" / "War Rooms" tab, should have updated counter in Nodes column

![image](https://user-images.githubusercontent.com/5786722/179559025-75cf87a9-ee7b-4161-bfe4-97163cef864d.png)

**Comment by hugovalente-pm** [comment]
@jacekkolasa do you think this is an easy fix or something more complex/lengthily?

**Comment by jacekkolasa** [comment]
We fixed it with @AlexNti in new Centralized Admin Panel
I'll close it then
