### ISSUE TITLE
[BUG] Claim command for user onboarding does not work as expected. 

### ISSUE THREAD

**Issue by kaskavel** [netdata/netdata-cloud#52]
**Describe the bug**	

During user onboarding, after creating the first space and room the user is guided to a "Claim your first nodes in _room_ " tab.

There are currently two issues with this tab: 

a) The claim command should include two rooms (General and the one the user has just created) 
b) The user should be able to remove General room from the Rooms tab, but currently cannot remove it (even if the claim command gets updated, the UI still show the General room in the bar). 

 
**To Reproduce**	

Follow onboarding for a new user in cloud. 

**Expected behavior**	

The user should be able to remove general room from the bar & see two rooms in the claim command shown initially.
 
**Screenshots**	

![Screen Shot 2021-02-19 at 1 24 17 PM](https://user-images.githubusercontent.com/31739664/108501798-7e194180-72ba-11eb-98b9-28420f9fe97e.png)

**Desktop (please complete the following information):**	
 - Browser [chrome Version 88.0.4324.150]	

**Additional context**

**Comment by allelos** [comment]
Are we sure we want room `General` to be deletable?

**Comment by kaskavel** [comment]
> Are we sure we want room `General` to be deletable?
> 
> Some of our implementations depend on `General` being always there.

@allelos I guess @manos-saratsis can comment on that. So you mean that even if the user want to add the node only to the newly created room (and not in General) we should still show the General there?

**Comment by allelos** [comment]
@kaskavel Oh my misunderstanding, I thought you were talking about removing `General` completely not just from the list. From what I've seen nodes can be present in one room and not in another. @manos-saratsis ?

**Comment by kaskavel** [comment]
No, not removing General overall just from the list, yes.
