### ISSUE TITLE
[Bug]: Invalid `node removed` notifications

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#520]
### Bug description

Apparently the backend returns nodes that haven't changed to the `nodes` request, causing repeated notifications for removed nodes. This has been observed in our production space "Netdata Cloud", following node deletions from a specific room yesterday (not clear if the two are related).

Details were added in an internal dogfooding channel, but it looks like requests to `/nodes?last_updated=...` may return nodes that in fact haven't been updated since that timestamp (or maybe something happens that keeps switching the state, that is invisible via the FE). 

### Expected behavior

Only receive notifications for removed nodes once. 

### Steps to reproduce

Access our Netdata Cloud space and wait for a while, you should start receiving invalid notifications. 

### Desktop

Browser Version [e.g. 22]

**Comment by ralphm** [comment]
I believe this might have to do with a change in the node service, removing the dependency on MongoDB. There was an intricate system to provide diffs and FE relies on this being a diff. In the new situation, the service doesn't keep track of deletes anymore, so it has to send the whole thing. Apparently, FE cannot tell the difference.

@cc @vkuznecovas

**Comment by ralphm** [comment]
Related https://github.com/netdata/netdata-cloud/issues/513

**Comment by vkuznecovas** [comment]
> I believe this might have to do with a change in the node service, removing the dependency on MongoDB. There was an intricate system to provide diffs and FE relies on this being a diff. In the new situation, the service doesn't keep track of deletes anymore, so it has to send the whole thing. Apparently, FE cannot tell the difference.

That's not the case. The front end is still using the v1 endpoint, which has not been changed and is still in tact.

The v2 endpoint is separate and it's the one that is using the SoT directly.

**Comment by ralphm** [comment]
Had a chat with @vkuznecovas and @hugovalente-pm on this. Vik says that due to the complex nature of the materialized view implementation, it is likely to be inconsistent. We concluded that the work that he mentioned above will fix this, and should be completed soon.

**Comment by cakrit** [comment]
Can someone manually clean up our space somehow? It's really annoying.

**Comment by hugovalente-pm** [comment]
the release of the above didn't fix this, so we need to take a look at it by itself

**Comment by burbuli8ra** [comment]
We need to re-open this issue and revisit the fix's implementation, without changing `useSubscribe`, since this way we produced a more important bug, which is that the `/api/v2/spaces/{spaceId}/charts/_query` call is not triggered anymore on **Nodes** view.

**Comment by hugovalente-pm** [comment]
we may "fix" it in some other way, with the work @jacekkolasa  is doing on this https://github.com/netdata/cloud-frontend/issues/3623 we will remove the need for the call to `/charts/_query`, I think it is only used on Nodes tab but probably worth to check. if it is just that, the previous fix could be deployed then maybe

**Comment by jacekkolasa** [comment]
I think that change to v2 fixed most cases, but as @AlexNti pointed out, there could be situations when `last_updated`, cached on FE since user used v1, could cause unwanted notifications.
Fixed in [pr](https://github.com/netdata/cloud-frontend/pull/3712).

Btw. right now notifications related to migrated to v2 endpoints are not working (because we don't get the diffs from BE anymore). There is a way to fix notifications using the cached results, [created a ticket for it ](https://github.com/netdata/cloud-frontend/issues/3713)
