### ISSUE TITLE
[Bug]: Occasionally getting 400s with ErrAgentInvalidResponse from all nodes

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#522]
### Bug description

I've noticed since last week that sometimes some charts seem to be receiving no data. Today I did a few more experiments on a space I have with two test VMs. `data` calls seem to be getting the following with no explanation. I don't see the same on the single node view.

It looks like the `data` requests that receive this are random and reloading may fix it and show the chart. 

I should note that especially today I occasionally have very long latencies, but the following isn't about timeouts.

```
{
    "errorMsgKey": "ErrAllNodesFailed",
    "errorMessage": "ErrAllNodesFailed",
    "errorCode": "8bysCdqiLO-36740699",
    "nodes": [
        {
            "id": "3b3d712b-e3f6-478a-976e-c339ee206e83",
            "routing_latency": "2.267373ms",
            "adc_latency": "155.025136ms",
            "error": {
                "errorMsgKey": "ErrAgentInvalidResponse",
                "errorMessage": "agent's response is invalid",
                "errorCode": "8bysCdqiLO-36740699"
            },
            "chartIDs": [],
            "hops": 0,
            "coverage": 1,
            "db_points_per_tier": null
        },
        {
            "id": "b0da7e2c-4f13-46c0-bde7-cf8bef5d88ad",
            "routing_latency": "2.265973ms",
            "adc_latency": "162.159993ms",
            "error": {
                "errorMsgKey": "ErrAgentInvalidResponse",
                "errorMessage": "agent's response is invalid",
                "errorCode": "8bysCdqiLO-36740699"
            },
            "chartIDs": [],
            "hops": 0,
            "coverage": 1,
            "db_points_per_tier": null
        }
    ]
}
```

### Expected behavior

Show the chart.

### Steps to reproduce

1. Work on the overview of any room until at least some nodes inexplicably fail to return data.

Agent versions:
v1.35.0-211-nightly

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@netdata/cloud-be the error seems to be on an invalid Agent response, do we log these somewhere so we could see what the Agent sent?

**Comment by hugovalente-pm** [comment]
@cakrit do you still face these 400s? @papazach and me were trying to trigger them but we only get successful 200 responses
what I've noticed is that your nodes have updated to the following nightly version when we checked... not sure something could have been fixed

**Comment by cakrit** [comment]
I don't see it now.
