### ISSUE TITLE
[Bug]: Misleading charts when gaps in the data are not sent as null or 0 by the agent

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#523]
### Bug description

I'm not sure if we had a recent change to save space in the agent response, but in cases where we have gaps in the data, we can now see responses like the one shown below to a `data` call. The result is charts that look horrible, like the following:

![image (7)](https://user-images.githubusercontent.com/43294513/180837111-83c23a32-e75e-43fd-b1ae-a7ca80b19fae.png)

I have broken the response into two parts, to identify exactly where the gap is, but it was really a single response to a request that was for hundreds of points. The FE can't handle this and draws a line, where it should be showing a gap.

```
       "data": [
            [
                1658306336000,
                5.4783761
            ],
            [
                1658306500000,
                22.6290166
            ],
            [
                1658306664000,
                1.4558333
            ],
            [
                1658306828000,
                2.053102
            ],
            [
                1658306992000,
                8.79
            ],
            [
                1658307156000,
                4.7404167
            ],
            [
                1658307320000,
                20.9784034
            ],
            [
                1658307484000,
                2.1475171
            ],
            [
                1658307648000,
                2.3149128
            ],
            [
                1658307812000,
                2.0053359
            ],
            [
                1658307976000,
                2.6858333
            ],
            [
                1658308140000,
                1.1733333
            ],
            [
                1658308304000,
                20.655
            ],
```

Huge gap here, with no nulls or zeroes.

```
            [
                1658391288000,
                7.0559965
            ],
            [
                1658391452000,
                2.0862524
            ],
            [
                1658391616000,
                12.8333333
            ],
            [
                1658391780000,
                1.4511299
            ],
            [
                1658391944000,
                5.3448211
            ],
            [
                1658392108000,
                5.5964218
            ],
            [
                1658392272000,
                1.3368644
            ],
            [
                1658392436000,
                9.109887
            ],
            [
                1658392600000,
                1.6090395
            ],
            [
                1658392764000,
                11.943597
            ],
            [
                1658392928000,
                1.6580038
            ],
            [
                1658393092000,
                1.2814972
            ],
            [
                1658393256000,
                5.0833333
            ]
        ]
    },
```

### Expected behavior

Show a gap instead.

### Steps to reproduce

1. Stop an agent for a few seconds or minutes, start it again and look at a chart that has this gap.

### Desktop

Browser Version [e.g. 22]

**Comment by juacker** [comment]
Thanks for rising this @cakrit, I've taken a look and it seems that the cloud is filtering out `null` values received from the agent, so the FE will not have them and no _gap_ will appear on the chart. 

This only happens on composite data requests aggregating data from a single node instance. And the reason seems to be a cloud limitation related with data aggregation. We need to filter out `null` values for aggregating data, but then, if we're aggregating data from one node instance, we will also lose the filtered timestamps. (It's a bit tricky, I try to show it in the video attached).

https://user-images.githubusercontent.com/2930882/181011849-3d9c8f67-99fc-4019-bf67-6c42605cf5f3.mp4

we're investigating possible solutions to this.

**Comment by juacker** [comment]
fix deployed, now null values are properly represented on composite charts.

![image](https://user-images.githubusercontent.com/2930882/182902207-5904d62d-59c1-4f8f-a810-1ca811f95858.png)

**Comment by hugovalente-pm** [comment]
thanks @juacker , closing this now
