### ISSUE TITLE
[BUG] Charts list for containers in overview screen doesn't handle long container names well

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#53]
![image](https://user-images.githubusercontent.com/43294513/108701962-7b3a6e80-74bd-11eb-9c0e-d04cdab99c87.png)

**Comment by hugovalente-pm** [comment]
The **ellipsis** have been applied to accommodate this together with full name on tooltip.
Probably there is still room for improvement here, but no longer an issue.

![image.png](https://images.zenhubusercontent.com/60b4ebb03f4163193ec31819/611dad25-8150-4bf6-99bb-f199313dc94b)
