### ISSUE TITLE
[Bug]: Home page shows the wrong node count

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#531]
### Bug description

See https://community.netdata.cloud/t/can-i-automatically-remove-unreachable-nodes-from-netdata-cloud/1066/7 and notice the count of nodes in the home page, vs the nodes view and admin info. 

### Expected behavior

List of nodes and count of nodes should always match.

### Steps to reproduce

Not sure. If we use mongoDB as a cache of these counters, I'll bet that's where it's from. If not, it's probably the FE. 

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@iorvd started to look into this one, to try to understand if it somehow is related with the migration work done on the service that provides those stats

**Comment by iorvd** [comment]
Fixed in https://github.com/netdata/cloud-spaceroom-service/pull/323

**Comment by andrewm4894** [comment]
can confirm this looks fixed to me on a test i just did
