### ISSUE TITLE
[Bug]: Abbreviation on Total points card on home tab causes confusion

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#532]
### Bug description

The abbreviation used on the Total points card is causing confusion when number displayed in on billions (diplayed as `G`) 

![image](https://user-images.githubusercontent.com/82235632/182582769-ae07620f-37b1-49e5-abfd-536b4fe075a8.png)

### Expected behavior

Let's instead show the full words for the numbers, the cards has space to accommodate it

### Steps to reproduce

1.

### Screenshots

Above

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
as caught-up on some internal conversations and discussions, let's revisit this abbreviation

cc/ @amalkov @papazach @shyamvalsan

**Comment by jjtsou** [comment]
@hugovalente-pm @shyamvalsan @papazach @amalkov 

For this case, should we map the symbol with the english word and show the word instead ? ( By `english word` I mean thousand, million, billion etc )

thousand - kilo - k
Million - mega - M
billion - giga - G
trillion - tera - T
quadrillion - peta - P
quintillion - exa - E

**Comment by shyamvalsan** [comment]
@jjtsou Yes, I believe that is the intent here.

**Comment by jjtsou** [comment]
https://github.com/netdata/cloud-frontend/pull/3726

<img width="1454" alt="Screenshot 2022-08-17 at 1 50 25 PM" src="https://user-images.githubusercontent.com/17753005/185105691-bbb2e2f3-5bd9-469f-8951-6eba8eb30430.png">

**Comment by hugovalente-pm** [comment]
@jjtsou yes that was the intent, but the Total metrics collected card doesn't look to good, should we do a word-wrap if a given margin isn't respected? probably you could check this with @christophidesp

**Comment by christophidesp** [comment]
@jjtsou @hugovalente-pm I think it would be valid to use K (thousand), M (million) and B (billion) instead of G, since we are talking about absolute numbers I think that B is pretty common for billion. 
I have updated the layout so it can host bigger text 

![Screenshot 2022-08-22 at 12 26 31](https://user-images.githubusercontent.com/96468003/185888898-ec9b943f-43e5-4e73-8e0c-1519bde0e222.png)

but my personal preference would be to use the above abbreviations.

**Comment by ralphm** [comment]
Just want to note that _billion_ means something different between US English (10<sup>9</sup>) and UK English (10<sup>12</sup>). Probably ok to explicitly use US English, though.

**Comment by hugovalente-pm** [comment]
yes, I think US English is ok.
the main doubt is should we go with:
a) explicit _words_
b) abbreviations of K (thousand), M (million) and B (billion)

UI-wise I prefer the abbreviations, but having the explicit _words_ doesn't shock me.

**Comment by jjtsou** [comment]
https://github.com/netdata/cloud-frontend/pull/3753

**Comment by hugovalente-pm** [comment]
above has been merged so closing this
