### ISSUE TITLE
[Bug]: Host labels section on the Node inspector doesn't expand for some nodes

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#534]
### Bug description

When trying to see the `Host labels` section on the Node inspector we aren't able to expand it for some nodes.

### Expected behavior

Host labels section should be expanded like on other nodes that work

### Steps to reproduce

1. Go to Netdata PROD Space
2. Open Nodes tab
3. Check node inspector for `aws-parent-0`
4. Try to expand host labels section

### Screenshots

![chrome_r5eYcIjpdQ](https://user-images.githubusercontent.com/82235632/182661387-e5de2e01-da94-4f78-b8f3-9429deeed09c.gif)

### Desktop

Browser Version [e.g. 22]

### Additional context

Host labels from JSON payload for node with issue

```
  "hostLabels": {
    "_aclk_impl": "Next Generation",
    "_aclk_legacy_available": "false",
    "_aclk_ng_available": "true",
    "_aclk_ng_new_cloud_protocol": "true",
    "_aclk_proxy": "none",
    "_architecture": "x86_64",
    "_cloud_instance_region": "us-east-1",
    "_cloud_instance_type": "m5a.2xlarge",
    "_cloud_provider_type": "AWS",
    "_container": "unknown",
    "_container_detection": "systemd-detect-virt",
    "_install_type": "custom",
    "_is_k8s_node": "false",
    "_is_parent": "true",
    "_kernel_version": "5.15.0-1015-aws",
    "_mqtt_version": "5",
    "_os_name": "Ubuntu",
    "_os_version": "22.04 LTS (Jammy Jellyfish)",
    "_streams_to": "dummy-value-to-mask",
    "_system_cores": "8",
    "_system_cpu_freq": "2199000000",
    "_system_disk_space": "214748364800",
    "_system_ram_total": "33005219840",
    "_virt_detection": "systemd-detect-virt",
    "_virtualization": "amazon"
  },```

**Comment by hugovalente-pm** [comment]
this is set to medium since as a workaround user can get the full JSON payload which has the host labels.

**Comment by jacekkolasa** [comment]
The host labels is expected to be empty, because we don't show host labels which start with `underscore`.

We deliberately show the empty group as visible, as written [here](https://github.com/netdata/cloud-frontend/issues/3091)

My guess is we should disable clicking on empty group, with a tooltip. I'll create a PR for that.
