### ISSUE TITLE
[Bug]: Server Error No spaces found

### ISSUE THREAD

**Issue by tbouquet** [netdata/netdata-cloud#539]
### Bug description

Hi,

I'm getting the error in screenshot when I go to the webpage https://app.netdata.cloud/

Thanks

### Expected behavior

At least a working page

### Steps to reproduce

1. Going to https://app.netdata.cloud/

### Screenshots

![image](https://user-images.githubusercontent.com/14275200/183256166-2067a6f1-75c3-4cd5-ad30-0bf43d9f8f26.png)
![image](https://user-images.githubusercontent.com/14275200/183256185-bfbb4f00-791f-42a4-b9b8-8d1eb358214d.png)

### Error Logs

HAR file in a zip below

[app.netdata.cloud.zip](https://github.com/netdata/netdata-cloud/files/9275370/app.netdata.cloud.zip)

### Desktop

OS: Ubuntu 20.04.4 LTS
Browser Chrome	
Browser v104.0.5112.79

**Comment by hugovalente-pm** [comment]
@tbouquet thanks for raising this and sorry for taking so long to come back to you.
I think the team is aware of this issue, trying to check where we are on this and will come back with an update

**Comment by hugovalente-pm** [comment]
seems this was fixed already @tbouquet 
can you confirm you don't have any issues signing in?

**Comment by tbouquet** [comment]
Hi,

Thanks for your answer

I confirm it's working now

That's great
