### ISSUE TITLE
[Bug]: Multi select on label filtering does not work

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#540]
### Bug description

Multi selecting in the new label filtering chart option does not work. Chart is only filtered by first item in multi select the user selected, even if all items are subsequently selected.

See video for more details.

### Expected behavior

Multi select should work.

### Steps to reproduce

1. Click on filter by conditions
2. Select first item of multi select, filtering by that item works fine
3. Select second item of multi select, chart is NOT updated
4. Select any subsequent item of multi select (or all items in multi select), chart is NOT updated

### Screenshots

https://user-images.githubusercontent.com/24860547/183852501-aae1156f-3668-4d16-84d7-c76599441f04.mp4

### Desktop

Browser Version [e.g. 22]

**Comment by shyamvalsan** [comment]
The filters seem to be present in the data request, but chart does not get updated

![image](https://user-images.githubusercontent.com/24860547/183857520-67b0a9f9-1dc7-4ca9-8a64-4f7c18c5c171.png)

**Comment by shyamvalsan** [comment]
cc: @amalkov @sashwathn @jacekkolasa

**Comment by jacekkolasa** [comment]
fixed by @papazach , deployed to production
