### ISSUE TITLE
[Bug]: X Nodes are below recommend agent version v1.34.1.

### ISSUE THREAD

**Issue by ced1check** [netdata/netdata-cloud#542]
### Bug description

All servers are using netdata 1.35 or 1.36, however the cloud dashboard keeps reporting those are below remcommended version!?

### Expected behavior

Cloud dashboard should not report such issue when it's not the case.

### Steps to reproduce

1.

### Screenshots

![banner](https://user-images.githubusercontent.com/104206200/184077066-97bee090-1232-4fa0-9c5c-a322ce8bc592.png)
![versions](https://user-images.githubusercontent.com/104206200/184077070-22095a65-d614-40f4-ad49-f7fbb0401f06.png)

### Desktop

Browser Version [e.g. 22]

**Comment by ced1check** [comment]
Issue has disappeared.

**Comment by MrZammler** [comment]
Thanks for the followup!
