### ISSUE TITLE
[Feat]: Anomaly Rate and Alert Widgets that can be added to in section summary dashboard

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#546]
### Problem

When users navigate to a section, they do not immediately receive context on whether everything is OK or NOT OK in that particular section. This leads to users having to scroll for a significant amount of time to actually uncover problems.

### Description

It would be very useful for users to have a per section summary of:
- Current anomaly rate across all metrics in that section (and how it compares to a 24 hour average)
- Current active alerts (split by critical vs warning)

### Importance

really want

### Value proposition

1. It would be valuable to show this for every per section summary dashboard. As it will give users guidance on whether they need to spend time going through the subsequent charts or not - if everything is normal and expected they can carry on with their life, if anything is anomalous or alerts are active they can dive deeper to investigate further.

### Proposed implementation

A rough mock up of how this could look

![image](https://user-images.githubusercontent.com/24860547/184098997-562b1b71-8240-488c-aba9-d90d289549b3.png)

Clicking on alerts widget should take user to alerts tab filtered by these metrics. (Don't think we can currently do this for anomaly rate as well, but eventually we should be able to do something similar)

**Comment by shyamvalsan** [comment]
cc: @cakrit @sashwathn @amalkov @hugovalente-pm

**Comment by shyamvalsan** [comment]
![image](https://user-images.githubusercontent.com/24860547/184126077-0406f21f-9a67-4ab1-ae67-0e4a71e8e703.png)

**Comment by shyamvalsan** [comment]
@sashwathn @amalkov Good idea, I think the alerts badge would serve the purpose. 

Regarding anomaly rate, not sure if it will be intuitive to users without accompanying text. Also some context for the raw number is useful (which is why I included the average rate over last 24 hours). 

But in general I agree @sashwathn if we can get these two in without eating up too much screen real estate that would be great.

**Comment by hugovalente-pm** [comment]
@shyamvalsan @sashwathn should we try this one out first after the PostegreSQL work is released? kind of a follow-up

After we validate it we can, at least, add to the section that have already some sort of summary, for those that don't have I'm concerned it could be just to badges "hanging" there. probably @christophidesp can also share some thoughts

> Regarding anomaly rate, not sure if it will be intuitive to users without accompanying text. Also some context for the raw number is useful (which is why I included the average rate over last 24 hours).

On this one maybe just some label that would give some context and the additional info on a tooltip.

**Comment by christophidesp** [comment]
I think I also prefer the badges, we could experiment a little bit with position and different cases to see where is the best place to show them.

**Comment by amalkov** [comment]
Can it be more visible if we would have a little indication in TOC for each first level item

**Comment by hugovalente-pm** [comment]
I think this can be closed since we are exploring this idea to be incorporated on the TOC, wdyt @shyamvalsan ?

**Comment by shyamvalsan** [comment]
@hugovalente-pm yes, agree. If we can do this on TOC i would prefer to avoid overloading summary panels.
