### ISSUE TITLE
[Bug]: Node count in centralized admin interface does not match true node count

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#547]
### Bug description

Node count in centralized admin interface does not match true node count. 

See attached video for more details.

### Expected behavior

Node counts should match

### Steps to reproduce

1. Go to a space (Eg: production) and observe number of nodes (in home tab, nodes tab etc.)
2. Go to admin interface, war rooms panel and observe number of nodes reported per room
3. The two values do not match

### Screenshots

https://user-images.githubusercontent.com/24860547/184301070-e23a7e22-e33d-4eed-80ee-e28576bb094f.mp4

### Error Logs

N/A

### Desktop

N/A

**Comment by novykh** [comment]
<img width="1213" alt="Screenshot 2022-08-17 at 1 26 15 PM" src="https://user-images.githubusercontent.com/601483/185096809-b1fd7261-0a1e-4573-a066-f8204911c9a9.png">
The node count is coming from the backend in this screen. @juacker is this the wrong attribute? Should we check for something else? (the attribute node_count is highlighted on the right of the attached pic.)

**Comment by hugovalente-pm** [comment]
@juacker has the PR been merged?

**Comment by juacker** [comment]
has just been deployed @hugovalente-pm

**Comment by hugovalente-pm** [comment]
closed since this is fixed
