### ISSUE TITLE
[Bug]: wrong summary bandwidth 

### ISSUE THREAD

**Issue by cheluskin** [netdata/netdata-cloud#548]
### Bug description

wrong summary bandwidth 

### Expected behavior

Right gigabit per second

### Steps to reproduce

1.
Add multiple nodes to netdata cloud

### Screenshots

<img width="247" alt="Снимок экрана 2022-08-16 в 11 03 35" src="https://user-images.githubusercontent.com/80083/184830717-dcacd999-66c8-4721-aff7-9233414241dd.png">

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@cheluskin thanks for raising this bug, could you please provide some more details?
could you check the detailed chat on network section `system.net`

I was trying to check this in our environment and the conversion was happening ok - just need to get a check why one is showing with `gb/s` and the other as `mb/s`

![image](https://user-images.githubusercontent.com/82235632/185872814-f1f7eb17-2f0e-4582-8b18-69189a96bb0e.png)

the detailed chart on network `system.net`
![image](https://user-images.githubusercontent.com/82235632/185872928-6e3b307c-0b30-4b54-9bca-292544704288.png)

**Comment by Obmenrich** [comment]
Thanks, it fixed itself in a couple of days

**Comment by hugovalente-pm** [comment]
cool, then closing this
