### ISSUE TITLE
Dashboards - selection of dimensions is forgotten if the chart card is out of the view

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#55]
**Describe the bug**	
In Cloud dashboards, if you select some dimensions in a chart card and you bring it out of view it forgets the setting

**To Reproduce**	
Go to Cloud dashboard -> add chart card ->select a dimension -> bring it out of view and back in

**Expected behavior**	
The dimension selection is as set unless the user reloads the page

**Comment by hugovalente-pm** [comment]
@manos-saratsis to confirm on this one, when you meant "bring it out of view and back in" is just out of the viewport? like scrolling down and then up?

**Comment by manos-saratsis** [comment]
@hugovalente-pm yes, out of the viewport

**Comment by hugovalente-pm** [comment]
Closing this ticket since this is not longer applicable
