### ISSUE TITLE
[Bug]: Overlap of update notifications - leftover from new architecture relrease

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#552]
### Bug description

We have potentially have a situation on the Node Inspector where we show two update node notifications.
The old one from the new architecture is to be discontinued - removed

![image](https://user-images.githubusercontent.com/82235632/186119627-a69fb845-49a2-4c38-a233-a901b5769124.png)

### Expected behavior

Just have on update node notification

### Steps to reproduce

1.

### Desktop

Browser Version [e.g. 22]

**Comment by AlexNti** [comment]
Goind to be fixed by https://github.com/netdata/cloud-frontend/pull/3737
