### ISSUE TITLE
[Bug]: Alert might remains set forever even long after the corresponding process is gone

### ISSUE THREAD

**Issue by mulder999** [netdata/netdata-cloud#555]
### Bug description

I am running the official docker container with netdata v1.36.0-40-nightly running in a docker swarm. My monitoring is done using netdata-cloud.
Since 4d, I have a memory alert that remains triggered as critical for the netdata_agent process despite the fact that the process no longer exists (possibly OOM killed just after the critical alert was raised).

I have restarted the agent service, reinitialized the swarm, rebooted the host, the manager but the alerts seems to remain set forever.

### Expected behavior

Alerts for charts gets cleared out once the corresponding process no longer exists.

### Steps to reproduce

This happen for me after a disaster...
As you can guess the post mortem for this side issue is now quite difficult to reconstruct exactly.

But you might try this:
- Setup a bunch of various docker stack.
- For the netdata agent define a cgroup memory at 360m. For the `cgroup_ram_in_use` defines:
```yaml
     warn: $this > (($status >= $WARNING)  ? (92) : (96))
     crit: $this > (($status == $CRITICAL) ? (96) : (98))
```
- Reinitialize your whole cluster with a script to generate some quick load through huge number of container start
- Make sure to abuse of command `docker swarm --force-new-cluster ` on the manager and regenerate the whole stack with the script a couple time within a few minutes
- Wait until netdata agent memory pass the critical margin and with some help of Mr. Murphy you might eventually get it as well

### Screenshots

REM: The chart would actually never load

![NetDataStaleAlertBug](https://user-images.githubusercontent.com/1905023/186272742-d89cc376-d7ca-465b-b6cd-60eaeeb38efb.JPG)

### Desktop

Browser: Opera 89.0.4447.101

**Comment by dimko** [comment]
Hey @mulder999 thanks for the report. It seems like the chart affected by the alert was removed, but alert linked to it wasn't cleared.

Is it possible to check if alert still exists on the agent side? Also, is the chart still present in Cloud and Agent?

Lastly, could you please share your space ID so the team can investigate? You can see the ID of the affected space by clicking the gear icon over the profile icon at the bottom left corner

**Comment by mulder999** [comment]
Hi @dimko, thanks for replying.

There is no alert in the web console of the agent itself, the alert is only visible on the cloud.

I studied the netdata logs around and after the alert. Was wrong in my earlier description. The netdata process who reported the error about himself at 15h08, runned in fact until 18h01. Then I have a hole until 18h55 during which we were probably busy rebuilding the cluster/node and had no log collection in place. A new netdata agent processed runned on that node from 18h55 and started sending it's first alerts at 18h58.

**Comment by MrZammler** [comment]
Hi @mulder999 thanks for this.

Can you please also send the logs during that time (would like both the `access.log` and `error.log`) to manolis@netdata.cloud ?

When you say a `new netdata agent process` could I assume that this process did not share the same data as the old one? Most importantly the contents of our local sqlite db in /var/cache/netdata ? (But still somehow shared the machine guid and cloud ids of the old one ?)

Thanks!

**Comment by mulder999** [comment]
Hi @MrZammler,

Oups sorry, I used "process" as a shortcut of "process wrapped in a container service instance", this is later visualized as a unique "container" element in the right column of netdata cloud/web console.

The cache and config volumes of the container service were preserved and reused by the different container service instances all the time so should the netdata identities.

Will try to export you that tomorrow.

**Comment by mulder999** [comment]
@MrZammler info sent per email. Hope it helps finding and solving the issue. Best regards

**Comment by mulder999** [comment]
Closing ticket as issue has been fixed by netdata cloud team.
