### ISSUE TITLE
[Feat]: Allow metric descriptions and guidance text to be minimized and make them available everywhere

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#558]
### Problem

- Metric descriptions and guidance text is always present without a way for users to minimize them. 
- Metric descriptions and guidance text only live on overview tab (and single node view) with no way to persist them to other tabs such as (but not limited to) alerts, anomalies, custom dashboards, use-case dashboards.

Example: 

![image](https://user-images.githubusercontent.com/24860547/187144992-e8384444-ff4f-4a2a-b272-209a84b25104.png)

- No way to minimize above explainer text. 
- No way to view this explainer text in alerts/anomalies/custom dashboards/use-case dashboards.

### Description

The info section containing the metric description and guidance text should be a chart property that can be:
 - ~hidden by the user if they wish to do so~
 - ~viewable as a popup when clicking on help on chart so that it can be useful in other tabs such as alerts, anomalies, custom dashboards, use-case dashboards.~
 - be available as info of the chart

### Importance

really want

### Value proposition

1. Netdata is not just about showing metric values but helping users understand the "so what" associated to the chart they are viewing. So any context info we provide must be available universally across Netdata and not be limited to overview on single node view.

2. Giving users the option to minimize text clutter if they already know and understand the context for a particular chart will improve usability, especially for power users.

### Proposed implementation

The suggested approach is to add it to the info section of the chart and this should include (when available either):
* chart related info - positioned right below the chart title
* Section related info - positioned right below the section title, where the chart is located
![image](https://user-images.githubusercontent.com/82235632/193259672-6a8323bf-0ee3-4e20-9bed-44681a17a97c.png)

**Comment by shyamvalsan** [comment]
cc: @hugovalente-pm @novykh @jacekkolasa @sashwathn @cakrit @amalkov

**Comment by amalkov** [comment]
Fully agree, I believe this CTA should be located next to the title, might be as an "i" icon before the title for consistency (to avoid misalignment due to different lengths of the title)

**Comment by hugovalente-pm** [comment]
agree on both and the default behaviour of expanding or collapsing the explainer text could be a user preference

> Netdata is not just about showing metric values but helping users understand the "so what" associated to the chart they are viewing. So any context info we provide must be available universally across Netdata and not be limited to overview on single node view.

on this one, while this is kept in dashboard source code we could try to play this one below (it was created for custom dashboards but being a chart option it could be made available in more places):

https://github.com/netdata/product/issues/2322

@novykh not sure if what your refactoring and/or the approach we take are related

**Comment by hugovalente-pm** [comment]
after a meeting with @amalkov and @novykh it was agreed to speed this and iterate fast these should be moved to the info section of the chart

![image](https://user-images.githubusercontent.com/82235632/193259358-22307437-4484-4e8b-b579-d448629a5266.png)

@cakrit maybe we will need to prepare an engagement for existing users to let them know this is to be changed and for new users where they can find more details on the chart - maybe add a step to the Guided tours
wdyt?

**Comment by hugovalente-pm** [comment]
@shyamvalsan @amalkov were discussing this on the daily and the descriptions exist at 3 levels:
1. Main section: examples System Overview, Disks, PostgreSQL
2. Sub-section: examples System Overview > cpu, Disks > all, PostgreSQL > connections
3. Chart

![image](https://user-images.githubusercontent.com/82235632/194832817-c1ed0324-9a8d-45d4-9bad-cf337fe1bdfc.png)

2. and 3. can be moved to chart info without issues, 1. work as an intro in most cases to the main section in most cases, so I propose to not move it.

do you agree?

cc/ @MichaelGamel @novykh

**Comment by shyamvalsan** [comment]
@hugovalente-pm I think this makes sense. The main intro section is usually just a sentence anyway so it makes sense to keep it always visible. If there was a way to associate the intro description to an entire section (family?) it might make sense to keep it associated to that particular context in case we need to reference it elsewhere (outside of overview tab).

**Comment by hugovalente-pm** [comment]
great, thanks for confirming

> If there was a way to associate the intro description to an entire section (family?) it might make sense to keep it associated to that particular context in case we need to reference it elsewhere (outside of overview tab).

This is already kinda like that, we have the main section intro description here https://github.com/netdata/cloud-frontend/blob/ce13bad23d3216c49c9b060aba724583b35d2355/src/domains/charts/toc/menus.js and the reference currently is to the first part of the context name, example

```
  postgres: {
    title: "PostgreSQL",
    icon: '<i class="fas fa-database"></i>',
    info:
      "Performance metrics for <b>PostgreSQL</b>, the open source object-relational database management system (ORDBMS).",
  },
```

**Comment by hugovalente-pm** [comment]
@cakrit the other engagement we had spoken about was this about moving the chart and sub-section descriptions inside the chart info

**Before**
![image](https://user-images.githubusercontent.com/82235632/199508847-d42f57e0-abef-444b-a65e-72a7dca58ec0.png)

**After**
![image](https://user-images.githubusercontent.com/82235632/199508963-fb142cab-801f-4f31-850c-8146f55457e4.png)

can we also have one for existing users for a start?

**Comment by cakrit** [comment]
Sorry, I never told you, but it was done on Oct 20

I put this hotspot on the charts...

<img width="446" alt="image" src="https://user-images.githubusercontent.com/43294513/199533695-5095bcb0-e70c-4641-b290-b18df1d38494.png">

and when people click on it they see this

<img width="461" alt="image" src="https://user-images.githubusercontent.com/43294513/199533864-3d2b1755-8ed0-4170-875c-6030bff87f37.png">

But, out of 1600 who saw the hotspot, only 30 clicked on it.
<img width="832" alt="image" src="https://user-images.githubusercontent.com/43294513/199534410-dc31047b-9451-4972-9ebf-2ff3c19adf75.png">

So I'll just cancel this one and do an unconditional one that just displays the info.

**Comment by cakrit** [comment]
Done, it will automatically show up to the older users who haven't already clicked on the hotspot.

**Comment by hugovalente-pm** [comment]
this has been released
