### ISSUE TITLE
[BUG] Removing too many nodes from a room results in incorrect error message

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#56]
I tried to remove the 476 (! yes, I know) unreachable nodes from room "K8s", by selecting every node in the room and deselecting each reachable one. We probably didn't expect to have such a large request for removals (though I did see the popup asking for confirmation). The problem is that the error that comes back says that "There's no internet connection" or something like that, so we're using the wrong error code somewhere. Perhaps we can do something more graceful there.

**Comment by manos-saratsis** [comment]
@cakrit me and @franklinandrade will work on this as part of the changes planned in the management screens

**Comment by manos-saratsis** [comment]
We will plan in Q3 2021 improvements on making nodes obsolete

**Comment by cakrit** [comment]
Duplicate of https://github.com/netdata/netdata-cloud/issues/410
