### ISSUE TITLE
[Feat]: Allow inviting users to a Room that aren't yet invited to the Space

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#561]
### Problem

When we are inviting a user to a Room we are restricted to only the users that are already invited to the Space. This restrictions makes the process of inviting a user to a Room a two-step process where I need to:
1. Invite the user to the Space
2. Add the user to the Room

Besides the above, if we want to manage the user level of permissions (role) we need to go to yet another screen to do it.

### Description

We need to make the process of inviting a user to a Room simpler and faster we need to do something similar to what we do for adding nodes to a Room, where we:
* allow the users to claim and add a new Node to the Space and Room, or
* allow the user to add already claimed nodes, existing already on the Space

**Need for paid features** is to have a way to exclude inviting the user to the All Nodes for paid plans

### Importance

must have

### Value proposition

1. This will make the task completion of inviting a user to a Room simpler and faster
2. It will also allow to assign a role immediately and not need to go to another screen

### Proposed implementation

We should merge on `Add users to room <room-name>` screen the section that would allow to invite a user that is not on the Space and make available a dropdown box to define the role

Screen for inviting user to Space

<img src="https://user-images.githubusercontent.com/82235632/187636534-94ee94e8-88b4-40d7-a495-b830f28dbe3d.png" height="65%" width="65%"/>

Screen for adding user to Room
<img src="https://user-images.githubusercontent.com/82235632/187636720-2d44450c-db33-4a63-b6aa-240b25d4f3d9.png" height="65%" width="65%"/>

Screen for adding nodes to Room
<img src="https://user-images.githubusercontent.com/82235632/187636833-490a7e10-ef1a-4176-839b-0d84d1134734.png" height="65%" width="65%"/>

**Comment by hugovalente-pm** [comment]
@christophidesp @AlexNti an example based on what we have spoken, changing the order of what we show first,

in terms of text changes I would suggest:
* "Send invitations to your team" --> "Invite an external user to the Space and this War Room" adding a note somewhere the by default user will be added to the `All Nodes`

Points to steal deal with:
* Send button and CTA/button to confirm the action on adding users already on the space
* Invitations awaiting response section

![image](https://user-images.githubusercontent.com/82235632/187891424-6b5e4a3b-6aa9-40bb-8e9e-940fb6e0dcfd.png)

**Comment by hugovalente-pm** [comment]
Potential key need for paid features by defining the role of the user and will also need to have a way to exclude inviting the user to the `All Nodes` also for paid plans (TBC)

**Comment by hugovalente-pm** [comment]
on call with @iorvd clarify the things needed for this ticket that is trying to tackle two things:
* on the invitation to Space allow pre-defining a role to the user being invited
* streamline the process of inviting to a Room a user that is not yet on the Space by allowing to define a user email and trigger the invitation to the Space from there

**for BE work** this seems to only fall into allowing on the invitation to the Space to get the role we want to assign to the user, like we do for Rooms
nothing else seems to be needed because of the FE work mentioned below

**on FE work** we will need to:
* change the invitation to Space screen to allow specifying the role
* change the invitation to Room screen to:
   * allow adding users by email (since they aren't o the Space) and specify their role
   * trigger the request to invite to the Space for the above-mentioned users --> @jacekkolasa  please confirm this is ok from FE pov

we will need to discuss a UX point that is for both screens related to defining the role, if we are adding multiple e-mail addresses and want to define different roles to them the current component doesn't work since, like we have for Rooms now, if we add just a dropdown it will be the same role to all users - it isn't an impossible task if you want to add users with different roles (and we could also say Rooms) but you would need to do in batches

@jacekkolasa @christophidesp  I know this isn't in the top tasks to work on, compared to the other ones, but we will need to discuss on the approach to follow

**Comment by amalkov** [comment]
@iorvd please allow adding multiple roles, similar to rooms

**Comment by hugovalente-pm** [comment]
this is released
