### ISSUE TITLE
[Feat]: increase dashboard name limit from 20 characters

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#563]
### Problem

20 character limit on dashboard names seems very very small - no?

### Description

![image](https://user-images.githubusercontent.com/2178292/187686115-ed7e6265-a2b7-47d3-8c03-5b9333b1b310.png)

### Importance

nice to have

### Value proposition

1. better naming of custom dashboards

**Comment by hugovalente-pm** [comment]
@jacekkolasa @vkalintiris since you quickly jumped to the bookmarks' name, can we check if this one is also easy to push forward?

**Comment by jacekkolasa** [comment]
@netdata/cloud-be we need to increase the limit on BE first. 

|From FE side, i think we will need optional ellipsis with tooltip on Dashboard Tab names, since we display the full name currently

**Comment by vkuznecovas** [comment]
PR is open, I'll let you know once this is rolled out.

**Comment by vkuznecovas** [comment]
Change is now live across all envs.

**Comment by hugovalente-pm** [comment]
this is completed
