### ISSUE TITLE
[Bug]:  Invalid error message after new cloud user successfully joins invited space

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#564]
### Bug description

This is a regression caused by 213 as explained here https://github.com/netdata/netdata-cloud/issues/213#issuecomment-1173625177

 After a **new user** successfully joins and invited space, he doesn't see the correct popup that he successfully joined the space (even though he does), but he sees an error popup that invitation to join failed, **Invitation not found**

### Expected behavior

User should see a Join space successfully popup green message instead of an error, as he successfully joined space

### Steps to reproduce

1. Admin User A invites non netdata cloud user Β
2. User B clicks the Join Space CTA in the received email
3. User B doesn't yet have an account in Netdata Cloud -> after following the above link lands in the signin screen of cloud
4. User B inputs email and submits
5. User B clicks the Verify email CTA in the signup email
6. Accepts terms and conditions
7. Successfully joins space but sees an error

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/188105854-b1b6df85-624b-4e5d-a69b-45aaa08c93b4.png)

### Desktop

OS: MacOS
Browser Chrome
Browser Version 103

**Comment by vkuznecovas** [comment]
Backend part addressed in https://github.com/netdata/cloud-spaceroom-service/pull/353, released to prod

**Comment by burbuli8ra** [comment]
Released on [v2.36.16](https://github.com/netdata/cloud-frontend/releases/tag/2.36.16)
