### ISSUE TITLE
[Bug]: Latency histogram chart legends should be sorted numerically not alphabetically

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#571]
### Bug description

Latency histogram chart legends should be sorted numerically not alphabetically

![image](https://user-images.githubusercontent.com/24860547/188945522-8cd984f0-aaac-4abc-9856-c30769967d91.png)

In this example the actual sort order should be:

0.100, 0.500, 1.000, 2.500, 5.000, 10.000, +Inf

as defined in the collector.

But cloud is re-sorting them based on alphabetically order leading to a weird mix.

### Expected behavior

Use numeric sort order as defined in collector.

### Steps to reproduce

1. Always visible for newly added metrics for queries and transactions histogram (postgreSQL)

### Screenshots

![image](https://user-images.githubusercontent.com/24860547/188945522-8cd984f0-aaac-4abc-9856-c30769967d91.png)

### Error Logs

N/A

### Desktop

N/A

**Comment by shyamvalsan** [comment]
cc: @hugovalente-pm @novykh @ilyam8

**Comment by thiagoftsm** [comment]
Hello @shyamvalsan only to clarify, this chart is ordered according ASCII [table](https://www.asciitable.com/), what you want is to move text (this means exclude `+` from `+Inf`) to the end, is this correct?

**Comment by shyamvalsan** [comment]
@thiagoftsm It's not only +Inf

it is currently showing 1, 10, 2.5, 5 instead of 1, 2.5, 5, 10

**Comment by hugovalente-pm** [comment]
@novykh I don't have access to the example @shyamvalsan mentioned (this isn't live yet) but you can find some latency charts here on `Kubernetes kubeproxy` section having the same issue - https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/overview#chartName=menu_system&appliedFilteredIds=&liveNodeIds=&staleNodeIds=&offlineNodeIds=&filteredNodesSearchParams=

![image](https://user-images.githubusercontent.com/82235632/189154929-9a63d5cf-c51c-480b-9880-d29c85a3ce8e.png)

**Comment by novykh** [comment]
For the legend we are using the `dimension_ids` attribute in `/data` payload, which is the sorting we are showing as default. Can we fix that being consistent with the sorting needed?

**Comment by shyamvalsan** [comment]
@hugovalente-pm @novykh is this ^ something the BE decides or does it come all the way from agent?

**Comment by novykh** [comment]
I'd say from agent..
The inconsistency is on those attributes (`dimension_ids`, `dimension_names`) and on the `/charts` payload on a single node view, where we get the dimensions as an `object`. I'd suggest to fix all of those for future reference.

**Comment by shyamvalsan** [comment]
Over to you @ilyam8

**Comment by novykh** [comment]
Also, another possible issue, is that we are getting all the dimensions on the overview, whereas on the single node we are getting only the dimensions with value.

**Comment by novykh** [comment]
@ilyam8 inconsistency with the sorting we mean. `all_dimensions` and `result.labels` have different sorting from `dimension_ids/names`.

**Comment by hugovalente-pm** [comment]
@ilyam8 @papazach @juacker is this something that needs to be fixed from the Agent or needs to be from Cloud BE?

**Comment by hugovalente-pm** [comment]
this is fixed
![image](https://github.com/netdata/netdata-cloud/assets/82235632/e8dc4486-26aa-47af-afca-cd8f0a9bc0df)
