### ISSUE TITLE
[Feat]: Allow chart defaults to be selected per metric

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#572]
### Problem

Certain charts are more useful (or only make sense) when the chart options are set to values other than the default that is used for all charts and metrics. Currently all charts use common defaults (Eg: group by dimension) unless specifically hardcoded otherwise - this is not a very extendable or flexible state of affairs. 

For example, database charts should be **"grouped by database"** and NOT **"grouped by dimension"** by default. 

Similarly other charts may require to be **"grouped by table"** or other labels.

This is also applicable to other chart options besides **"group by"** - for example the aggregation function and the interpolation function.

### Description

There should be a mechanism in dashboard_info.js (or an equivalent) to define these options per metric. 

The following options should be supported:
 - Group by <>
 - Aggregation function (SUM|MIN|MAX|AVG)
 - Interpolation function (MIN|MAX|SUM|etc...)
 - Filtered by <>
 - Chart type (Area|Stacked|Line|Other supported chart types)

![image](https://user-images.githubusercontent.com/24860547/188947220-004a134a-975c-4b67-b806-a6154fcf0e41.png)

### Importance

really want

### Value proposition

1. Make charts more useful and intuitive for end users
2. Flexibility to quickly change the representation of a particular chart from the cloud without having to change or upgrade the agent

**Comment by shyamvalsan** [comment]
cc: @amalkov @ralphm @sashwathn @hugovalente-pm @cakrit @ktsaou

**Comment by hugovalente-pm** [comment]
I believe we already have mechanisms for most of them:
* groupBy - https://github.com/netdata/charts/blob/main/src/sdk/filters/getGroupBy.js
* chartType - from collector and some other rules https://github.com/netdata/charts/blob/main/src/sdk/filters/getChartType.js
* aggregationMethod - controlled by the units https://github.com/netdata/charts/blob/main/src/sdk/filters/getAggregateMethod.js

we also have:
* dimensions mechanism when group by Node/Instance - https://github.com/netdata/charts/blob/main/src/sdk/filters/getDimensions.js


What I see missing is
* Filtered by <> - but here not really sure what defaults we should/want to place. we get the list from the metadata of the chart
* Interpolation function (MIN|MAX|SUM|etc...) - here you mean the time aggregations?

**Comment by hugovalente-pm** [comment]
@shyamvalsan was thinking about closing this since with context.js we have this, this probably will be revisited to make it available to users with the improvements on OpenMetrics that we'll need to do. wdyt?

cc/ @ralphm

**Comment by shyamvalsan** [comment]
Yes, we can close this now.
