### ISSUE TITLE
[Bug]: chart label filtering activates wrong selection when one value contains as a subset another

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#573]
### Bug description

When selecting a value from a filter key if that value contains as a subset another value both are selected when clicking the first one, example: with `filesystem` key with values `devtmpfs` and `tmpfs`on Disk Space Usage - `disk.space` 

### Expected behavior

Only the selected value should be activated

### Steps to reproduce

1. Go to https://app.netdata.cloud/spaces/netdata-cloud/rooms/all-nodes/overview#chartName=menu_mount_submenu_all&appliedFilteredIds=&liveNodeIds=&staleNodeIds=&offlineNodeIds=&filteredNodesSearchParams=
2. Open the filter by conditions selector
3. Expand filesystem
4. Click on `devtmpfs`

### Screenshots

![chrome_67y2GJbt7B](https://user-images.githubusercontent.com/82235632/188973622-838836ac-5619-4b21-b8c1-cc7994db950f.gif)

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@jjtsou @shyamvalsan just a ping to see if this isn't forgotten

**Comment by jjtsou** [comment]
https://github.com/netdata/charts/pull/142

**Comment by jjtsou** [comment]
Deployed on production @hugovalente-pm  
I am closing this issue
