### ISSUE TITLE
[Bug]: Navigation between chart menus is too slow

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#576]
### Bug description

When switching between chart menus from the charts list on the right side there is a delay to render the appropriate charts, the browser gets stuck and often crashes

### Expected behavior

Navigation between charts shouldn't be that slow

### Steps to reproduce

1. Login to netdata cloud to a space with multiple agents claimed
2. Navigate to overview tab
3. Switch between different charts by selecting the desired chart name from the menu on the right side bar
     e.g 1. Select **System overview**
           2. Select **Netdata monitoring**
           3. Select **prometheus query frontend**
4. Switching between charts is slow and browser eventually crashes

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/189338055-1e200d87-3a9b-4753-bd24-cbc202657b75.png)

Performance tab in google chrome

![image](https://user-images.githubusercontent.com/19268853/189338003-235da53e-325d-4af9-965b-b322a42d7927.png)

### Desktop

OS:MacOS
Browser Chrome
Browser 104

**Comment by dimko** [comment]
Can't attach performance logs, github is unable to service the file I am attaching any way I've tried.

**Comment by hugovalente-pm** [comment]
this is to be re-checked once the refactoring/improvements on the virtualization are completed

**Comment by dimko** [comment]
Closing
