### ISSUE TITLE
[Feat]: Shortcut to notifications page to make it easy for users to toggle whether they get notification emails or not

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#577]
### Problem

Netdata has alert notification emails enabled by default - this might be problematic for new users who in certain scenarios could get flooded with emails for issues that they do not really consider a problem (RAM alerts is one such example from a real user). It is not possible for Netdata to set ideal alert thresholds for *all* possible user environments - hence there should be an easy way tghe users can disable notifications. 

Currently the user has to go through multiple clicks to disable notifications: 
- A normal user has to click on their profile avatar, click profile, choose notifications tab and then disable notifications

This is 4 clicks and the navigation is not obvious to the user. 

### Description

There must be a notification bell icon in a clearly visible location that the user can click on which takes them directly to notifications setting where they can click to disable/enable notifications

![image](https://user-images.githubusercontent.com/24860547/189596529-25b1297c-06ca-4f1c-abd5-4fbd26e08184.png)

The icon should indicate if notifications are currently enabled or disabled, based on the setting.

### Importance

must have

### Value proposition

1. Minimize the pain of alert fatigue (or rather alert floods) for new users by making it easier to toggle notifications.

### Proposed implementation

See description

**Comment by hugovalente-pm** [comment]
this seems really helpful, even if for now it is just a shortcut to the current modal from user profile. the only concern, that we can probably solve with a tooltip, is to make sure these are user notification settings and not the space settings.

the state will probably be linked to the main toggle there
![image](https://user-images.githubusercontent.com/82235632/197179726-80baf29a-a997-4aad-b40d-8c630a323d7e.png)

@christophidesp wdyt?

**Comment by christophidesp** [comment]
I agree that this would be really helpful, and as @hugovalente-pm mentioned we can clarify with the tooltip that this refers to user notifications

![Screenshot 2022-10-25 at 12 23 21](https://user-images.githubusercontent.com/96468003/197736374-42c5ce66-0e0c-41af-a260-79e7f1a8dedd.png)


Although I am not sure that we need to expose the state of the notifications for being enabled/disabled since it is just a link to a configuration for external notifications and also maybe in the future we can have multiple methods so enabled for some and disabled for others(?). It would make more sense to me expose the state if these were in-platform notifications.

**Comment by hugovalente-pm** [comment]
@AlexNti is going to start by adding the shortcut we can then see what else we may want, if we want, I have some doubts for plans that will have more than on notification mechanism what would we show?

**Comment by christophidesp** [comment]
If we want an indication for showing enabled/disabled notifications in the icon we can do that
Enabled
![Screenshot 2022-10-27 at 14 24 28](https://user-images.githubusercontent.com/96468003/198272143-571df6f1-810f-4154-a399-9c6084c5be62.png)

Disabled
![Screenshot 2022-10-27 at 14 24 09](https://user-images.githubusercontent.com/96468003/198272181-af2dd9b4-aa32-44d5-983e-73f4afbda764.png)

@shyamvalsan @hugovalente-pm @AlexNti what do you think?

**Comment by hugovalente-pm** [comment]
ok, that makes sense. @AlexNti what do you think in terms of effort?

**Comment by hugovalente-pm** [comment]
released
