### ISSUE TITLE
[BUG] Reachable nodes not visible in tooltip in Overview screen

### ISSUE THREAD

**Issue by kaskavel** [netdata/netdata-cloud#58]
**Describe the bug**	
When a user clicks on the reachable(number in green) or on the unreachable(number in red) nodes in the top right of the overview screen, a tooltip with the expanded list of nodes comes up. In this tooltip, reachable nodes are not visible (see screenshot). 

**To Reproduce**	

Press either the green or red number on the Results:, on the top right corner of overview screen. 

**Expected behavior**	

Reachable nodes should be seen in the tooltip. 

**Screenshots**	
![image](https://user-images.githubusercontent.com/31739664/109152693-83700380-7774-11eb-9f3c-ab7a5bc688b7.png)

**Comment by novykh** [comment]
Fixed.
