### ISSUE TITLE
[Bug]: metric correlation results do not properly filter dims on some charts

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#580]
### Bug description

if i run a MC, in the results some chart dims are not filtered like the should be by default.

### Expected behavior

all charts should only have the relevant dims selected

### Steps to reproduce

1. use metric correlations, look at applications chart.

### Screenshots

https://user-images.githubusercontent.com/2178292/190195036-82054643-4fa0-45d0-8256-10d94f17fded.mp4

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
was able to reproduce it, so pushing to the backlog with high prio

**Comment by andrewm4894** [comment]
just checked and this seems worse now - only a handful of charts look to be filtered properly in the results from a few examples i ran.

**Comment by andrewm4894** [comment]
@novykh or @jacekkolasa any chance looking at this this week?

**Comment by hugovalente-pm** [comment]
@andrewm4894 this seems to have been fixed, can you check on your side? I couldn't reproduce

**Comment by andrewm4894** [comment]
Yep will do and close if fine

**Comment by andrewm4894** [comment]
done
