### ISSUE TITLE
[Feat]: Provide a URL parameter in the public space to distinguish first visitors

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#583]
### Problem

We want to be able to support our public space's use case rooms with onboarding guides that assist people looking at it for the first time. Since most public/demo space users will be completely anonymous, we can't utilize the standard, user-based targeting to launch these engagements from Gainsight. So we need a different way.

### Description

An alternative way to trigger these engagements is based on the existence or value of a specific parameter on the URL, or a URL pattern. e.g. `https://....?triggerguide=guideA` or `https://.../roomX/...?firsttime=true` 

It really doesn't matter what specific pattern is used in the URL, as long as there's a way to track and respond to the first vs additional visits **for each room**, so that we can know if we should show the postgress guide, or the redis guide etc. 

### Importance

nice to have

### Value proposition

This will make it easier for first time users to experience how Netdata supports each use case. 

### Proposed implementation

The FE should store a cookie or an application key/value pair to the user's browser after the first time they visit a demo space room. Depending on that, is should change what the URL is.

**Comment by hugovalente-pm** [comment]
don't think this will be picked up and no mention of this has been made
