### ISSUE TITLE
[Feat]: Control precision of summary chart values to make it more meaningful

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#584]
### Problem

For certain summary charts the precision is too high and this makes them look visually problematic/less appealing

![image](https://user-images.githubusercontent.com/24860547/190971232-a25909e9-24cc-4c80-8e87-eb6c17f45a06.png)

### Description

In the above example, the DB size value should be rounded to a precision of maximum 2 decimal point values. 

In the case of uptime, the max precision should be seconds - but also the time value should be represented meaningfully as the time increases. For example: Instead of 9 days 12 hours etc.. just show 1.2 weeks. So for any value > 60 minutes a max precision of minutes is sufficient and so on.

### Importance

must have

### Value proposition

1. Makes summary overview charts visually appealing and easier to understand

### Proposed implementation

Note: Once we have number charts available in the summary the above examples would use them instead of donuts/piecharts.

**Comment by hugovalente-pm** [comment]
this is fixed
