### ISSUE TITLE
[Bug]: All charts appear as Stacked in Overview Tab

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#586]
### Bug description

All charts in overview tab are represented as stacks, not respecting the chartType returned by the backend in the /charts response.

### Expected behavior

Chart type visible to user by default (without user changing the selection) should be the one returned by the agent in the /charts response

### Steps to reproduce

1. Navigate to Overview screen
2. Check a chart that was supposed to be line e.g **netdata.aclk_status**
3. Now its type is stacked

### Screenshots

Overview

![image](https://user-images.githubusercontent.com/19268853/191233983-318eb796-e9ee-48e5-9159-b5ae35708cda.png)

Single node view 

![image](https://user-images.githubusercontent.com/19268853/191234068-cd060c9b-5542-4d77-bc6c-98de89634c2a.png)

### Error Logs

Backend response for /charts request

> netdata.aclk_status
> : 
> {chartLabels: null, chartType: "line", context: "netdata.aclk_status", family: "aclk",…}
> chartLabels
> : 
> null
> chartType
> : 
> "line"
> context
> : 
> "netdata.aclk_status"
> family
> : 
> "aclk"
> firstEntry
> : 
> 1663653611
> lastEntry
> : 
> 1663668891
> priority
> : 
> 200000
> title
> : 
> "ACLK/Cloud connection status"
> units
> : 
> "connected"

### Desktop

OS: MacOS
Browser Chrome
Browser Version 104

**Comment by hugovalente-pm** [comment]
this is fixed
