### ISSUE TITLE
[Bug]: Alert events raised right before agent shutdown will be missed on the cloud

### ISSUE THREAD

**Issue by MrZammler** [netdata/netdata-cloud#587]
### Bug description

There is a case, where alert events that are created right before the agent shutdown and didn't have time to be sent to the cloud, to be lost when the agent sends it eventually after the restart. We dug and confirmed the case with @car12o (thanks!!!) in which particular case a CLEAR event was not consumed by the cloud, leaving the alert in a WARNING state.

The problem is that when the agent shutsdown, it creates a newer event (REMOVED) which updates the previous one. When the agents starts again it sends the previous event, but since it is updated, the cloud ignores it.

This is because of a check we had in the cloud that assumed that a newer event will follow an updated one eventually. However this will not happen in every case, since we started filtering similar events after the last one sent on the agent side.

One way to solve is to remove this check from the cloud, or the agent could be smarter and detect such cases and only mark as updated when the later events are to be sent to the cloud as well. Points go to the first option if we also care about the feed.

### Expected behavior

The event should be consumed by the cloud.

### Steps to reproduce

1. Tricky, needs either new events to be created before the previous one is sent to the cloud.

### Desktop

OS: [Linux]	
Browser [Firefox]	
Browser Version [??]

**Comment by hugovalente-pm** [comment]
@MrZammler @car12o this actually seems a detail on this bug https://github.com/netdata/netdata-cloud/issues/330 and do you think this https://github.com/netdata/cloud-backend/issues/353 will also solve it?

**Comment by MrZammler** [comment]
Yes, the new way should solve this as well. However, it's good to pick up and fix cases like that so that we do as less snapshots as possible.
