### ISSUE TITLE
[Bug]: Info field in alerts changes after a few seconds

### ISSUE THREAD

**Issue by MrZammler** [netdata/netdata-cloud#590]
### Bug description

The info field for alerts from the agent contains variables, that are replaced with text to be presented on alerts, etc.

On the cloud when clicking on an alert, on the popup, the info field appears ok (with replaced variables), but after a few seconds it goes back to it's initial format (with variables placeholders).

i.e. when clicking initially:

![image](https://user-images.githubusercontent.com/1905463/191552222-a7916eb9-4567-44a6-b6bb-246d67b4431f.png)

And after a few seconds:

![image](https://user-images.githubusercontent.com/1905463/191552403-97d83079-27ce-4113-92b4-e9ce59a5245e.png)

The alert is raised by 3 agents, so it could be that one of those sends a non replaced version, or it could be that the text is filled from the alert config?

### Expected behavior

Present the info field as it exists in the alert event.

### Steps to reproduce

1. Click on a postgres alert on Netdata Cloud.
2. Observe the info field.

### Desktop

Browser Version [e.g. 22]

**Comment by novykh** [comment]
This is the response coming from the active alerts.


![Image](https://user-images.githubusercontent.com/601483/192214248-c930d186-8683-4289-99c4-dcf0b93d1243.png)

**Comment by MrZammler** [comment]
Thanks @novykh ! We'll check with @car12o to see how it's built.

**Comment by car12o** [comment]
The information to show on the drawer should not come from that endpoint but rather from `/api/v2/spaces/{spaceID}/rooms/{roomID}/alarms/{alarm}/nodes/{nodeID}/charts/{chart}`, both data should not be mixed. Anyway, I will update the `alarms-active` endpoint to use the parsed values for the placeholders.

**Comment by hugovalente-pm** [comment]
@novykh I see that this is fixed, should a tech debt task be created to do as per @car12o suggestion?

> The information to show on the drawer should not come from that endpoint but rather from /api/v2/spaces/{spaceID}/rooms/{roomID}/alarms/{alarm}/nodes/{nodeID}/charts/{chart}, both data should not be mixed. Anyway, I will update the alarms-active endpoint to use the parsed values for the placeholders.
