### ISSUE TITLE
[Bug]: When checking the Space setting on Info tab can't copy space ID

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#594]
### Bug description

When visiting the space settings on Info tab it isn't possible to select the space ID to copy it

![image](https://user-images.githubusercontent.com/82235632/191933863-076345be-58ea-498f-b1bf-2e5df0cb9451.png)

### Expected behavior

We should allow the users to select and copy and/or have a button to automatically copy (like in our add nodes commands)
![image](https://user-images.githubusercontent.com/82235632/191934172-22bcc577-ea6d-4e75-9e21-cbe83bd9959a.png)

### Steps to reproduce

1.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
A user was commeting
> I wasn't able to copy/paste spaceID from space settings as text isn't selectable on this page. I had to inspect the web page...

**Comment by novykh** [comment]
Fixed on develop
