### ISSUE TITLE
[Bug]: When streaming is disabled on a parent node children charts aren't available on Nodes tab

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#597]
### Bug description

When you are streaming data from X number of child nodes to a parent node if you disable streaming on the parent the Nodes tab will not show any charts for the child nodes.

Note: If you stop the parent node, and the children are connected to Cloud directly, you will be able to see the charts

### Expected behavior

Children charts should still be available on Nodes tab even though the stream was disabled on the parent node

### Steps to reproduce

1. Connect one child node to Cloud
2. Connect a parent node to Cloud
3. Activate streaming from child to parent
4. Check Nodes tab all charts work ok for both nodes
5. Disable the streaming on the parent (under API_KEY section, parent won't receive data)
6. Check Nodes tab and only the charts for the parent node are there (this as a small delay for the step 5. to take place ~30 sec.) -- to see the issue you need to also refresh the page

### Desktop

Browser Version [e.g. 22]

**Comment by juacker** [comment]
fix deployed
