### ISSUE TITLE
Deleted software or hardware resources from nodes still remain on Cloud

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#6]
**Describe the bug**	
On nodes table	

**To Reproduce**	
Steps to reproduce the behavior:	Go to "Nodes table" -> Remove an [instance or family(software or hardware resources)](https://learn.netdata.cloud/docs/agent/web#families) from a claimed agent -> Restart the agent -> See the sparklines in the node view

**Expected behavior**	
Deleted software or hardware resources from nodes should be removed from Cloud if they were deleted and were not existing within the selected timeframe

** Image **
<img width="817" alt="deleted_instances_nodes_table" src="https://user-images.githubusercontent.com/19746055/99796483-da3ebf00-2b2d-11eb-9e78-51253bd7e955.png">

**Comment by cakrit** [comment]
This will be resolved via the charts metadata refactoring that we'll take on as soon as we're done designing the connection/disconnection refactoring.

**Comment by papazach** [comment]
This is done.
