### ISSUE TITLE
[BUG] Alarm not switched off unless we refresh page

### ISSUE THREAD

**Issue by kaskavel** [netdata/netdata-cloud#60]
**Describe the bug**	

In case we have concurrently in a room: 

- An alarm getting switched off (from either state, critical or warning) 
- No other active alarms 

In the top bar we continue seeing the alarm being active even if it is no longer the case. If we refresh the page, we see the correct information of 0 alarms. 

**To Reproduce**	

1. Trigger a single alarm (to an agent claimed to cloud in a room with no other alarms). 
2. Switch off the alarm. 
3. In the war room where the node is claimed, in the top bar where alarms are presented, the alarm will remain visible until we reload the page. 

**Expected behavior**	

We should see no active alarms in the top bar (see atached screenshot)

**Screenshots**	
![image](https://user-images.githubusercontent.com/31739664/109166252-2a5c9b80-7785-11eb-93b7-5a0b8bda1fd6.png)

**Comment by manos-saratsis** [comment]
@novykh I added the "mgmt-navigation-team-bugs" label because it was introduced with the new navigation

**Comment by novykh** [comment]
Will be fixed in next release
