### ISSUE TITLE
[Feat]: HTTPCheck should be grouped by _collect_job and have by default in the overview and have line charts

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#604]
### Problem

Group by dimension is essentially useless for these two collectors, as each job monitors a completely different thing. 
Adding latencies of two different http calls doesn't help, so line charts are preferrable.

### Description

Set the default group by to `_collect_job`.
Set the chart types to line.

### Importance

must have

### Value proposition

- Httpcheck is a very valuable collector that currently doesn't show useful data by default.

**Comment by cakrit** [comment]
Also, please for the `status` chart, have the dimension `success` selected by default:

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/43294513/193870473-183fac67-419c-437d-8cf3-310ee837bc95.png">

**Comment by jjtsou** [comment]
https://github.com/netdata/charts/pull/140

**Comment by jjtsou** [comment]
The PRs are merged. Pending release. @cakrit

**Comment by cakrit** [comment]
Ah what a nice surprise! I'll hold off on publishing the relevant content until it's deployed, thanks.

**Comment by jjtsou** [comment]
It has been deployed today! You can check it on production
I am closing this issue, thanks @cakrit
