### ISSUE TITLE
[Bug]: Alert value displayed with extra digits and without units 

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#605]
### Bug description

When user clicks to visit single node view for a specific chart id for an active alert, alert units aren't displayed inside the alert highlight for the chart and alarm value is displayed with extra digits.

### Expected behavior

Alarm values should be consistent everywhere and contain units

### Steps to reproduce

1. Trigger an alert
2. Navigate to Alerts tab 
3. Click **Chart Id** link in the alerts table
4. User is re-directed to single node view for the affected chart, units are missing and extra digits are shown

### Screenshots

How it is when clicking **Chart id**

![image](https://user-images.githubusercontent.com/19268853/193866104-04b1d3d4-1ee3-4acd-af9d-3082725116f2.png)

How it is when clicking Go To Chart from inside alert's dedicated view

![image](https://user-images.githubusercontent.com/19268853/193866305-a1da1cf4-9c7e-43f9-ab1c-e222d84d141c.png)

### Desktop

OS: Ubuntu
Browser Chrome
Browser 105

### Additional context

Backend seems to be sending the value of the alarm as 15.569827381blahblah and frontend rounds it up. But alarm units are displayed differently only for the aforementioned flow.

**Comment by hugovalente-pm** [comment]
this is fixed

**Comment by hugovalente-pm** [comment]
![image](https://user-images.githubusercontent.com/82235632/201124257-168a0a7b-8550-4f61-b224-4df1b5d7d8d0.png)
