### ISSUE TITLE
[Bug]: Area chart showing only one of the two areas

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#608]
### Bug description

Below you see two dimensions that are supposed to have a value of 5 each, but only one is properly drawn in the area chart. Dunno what happened to the other:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/43294513/194118655-7f397d41-84d1-4e32-804f-5107115bd9b4.png">

### Expected behavior

- 

### Steps to reproduce

Set up fping and try it? I'll provide access to my room if needed.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this is reproduceable here https://app.netdata.cloud/spaces/tsaousis/rooms/all-nodes/overview#after=-900&before=0&utc=Europe%2FLisbon&offset=%2B1&timezoneName=Dublin%2C%20Lisbon&metrics_correlation=false&chartName=menu_fping_submenu_all&appliedFilteredIds=&liveNodeIds=&staleNodeIds=&offlineNodeIds=&filteredNodesSearchParams=
![image](https://user-images.githubusercontent.com/82235632/194369037-d3cfd54f-c27b-403c-9e32-513d766cf635.png)

Group by `instance` and select for example 2 series on the labels

**Comment by hugovalente-pm** [comment]
yes, this is stacked charts - well spotted
for area the dynamic y-axis is ok
