### ISSUE TITLE
[Bug]: PostgreSQL header section charts with strange decimal places

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#609]
### Bug description

The header charts - DB size - on postgreSQL section have strange decimal places
![image](https://user-images.githubusercontent.com/82235632/194539660-dd2950a5-c060-4c1e-929d-46b258955fa6.png)

### Expected behavior

Expectation is to get these rules applied there https://github.com/netdata/cloud-frontend/issues/3037

### Steps to reproduce

1. Check this https://app.netdata.cloud/spaces/netdata-cloud/rooms/all-nodes/overview#chartName=menu_postgres&after=-1800&before=0&utc=Europe%2FLisbon&offset=%2B1&timezoneName=Dublin%2C%20Lisbon&metrics_correlation=false&appliedFilteredIds=&liveNodeIds=&staleNodeIds=&offlineNodeIds=&filteredNodesSearchParams=

### Desktop

Browser Version [e.g. 22]

**Comment by shyamvalsan** [comment]
@hugovalente-pm can you try again? Seems to work for me. And seems to work properly for DB size. 

![image](https://user-images.githubusercontent.com/24860547/202677670-2d01d49a-2020-4709-9a93-37cc99b8276e.png)


For uptime we still need to aggregate into higher order time units.

**Comment by hugovalente-pm** [comment]
yes @shyamvalsan , now it is working. could have been some glitch.

I agree we need to see the uptime since it even has lost the previous aggregation on the original screenshot we were grouping to days units. will probably close this one and open a specific bug for that if it doesn't exist
![image](https://user-images.githubusercontent.com/82235632/202678379-7415f703-4a74-4d55-b9f4-1f6fa8e04e8d.png)

also navigating through the charts doesn't change the DB Size or Uptime like the other ones. would say we can track that as a low prio bug

https://user-images.githubusercontent.com/82235632/202678648-e8bff5fe-a7d9-4947-9588-17399b9df936.mp4

**Comment by shyamvalsan** [comment]
> also navigating through the charts doesn't change the DB Size or Uptime like the other ones. would say we can track that as a low prio bug

Good catch - I agree.

**Comment by hugovalente-pm** [comment]
two bugs were open to tackle the other remaining issues, one is already linked to this bug and the other is this https://github.com/netdata/netdata-cloud/issues/664
closing this bug since DB size is now ok
