### ISSUE TITLE
[Bug]: Labels are not resolved in the alert notifications sent via email

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata-cloud#610]
### Bug description

The labels are not resolved before sending alert notifications to email.

<img width="711" alt="image (3)" src="https://user-images.githubusercontent.com/96257330/194834439-3e4c53e9-e50f-41c6-9525-910168939fc3.png">

This could be related to the issue reported about alert descriptions in the alert modals previously.
https://github.com/netdata/netdata-cloud/issues/590

### Expected behavior

All the labels need to be resolved before sending alert notifications to users.

### Steps to reproduce

1. Raise any alert with a label in the description

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this was an issue with the alert config, should be `$label:database`
