### ISSUE TITLE
[Bug]: Line chart in overview doesn't display the data

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#611]
### Bug description

See how there's supposed to exist a series with a value of 2 here, but it's nowhere to be found:

<img width="550" alt="image" src="https://user-images.githubusercontent.com/43294513/195177025-324d28d9-37cb-460e-bc7f-8ee4e87bb838.png">

### Expected behavior

See the correct chart

### Steps to reproduce

1. I can give access to this space/room if you can't.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this is fixed
