### ISSUE TITLE
[Bug]: Go to chart for alert redirects to wrong chart 

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#612]
### Bug description

When a new chart is added after the initial sync of charts, getting re-directed to single node view for the alert affected chart doesn't work as expected. Often a different chart is selected in the sidebar than the one having the alert

### Expected behavior

The alert affected chart should be highlighted and after user clicks go to chart or run correlations this chart should be selected and its canvas displayed.

### Steps to reproduce

1. Claim an agent to cloud
2. Wait for all initial charts to be synced
3. Add a new chart 
4. trigger an alert for the new chart
5. Click go to chart (or run correlations) from inside the alert affecting the newly added chart
6. User lands on single node view of the agent, but a different chart is selected in the sidebar

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/195295996-a78aa892-4f17-4ef9-94b7-9b49637f8c22.png)

### Desktop

OS: Ubuntu
Browser Chrome
Browser Version 106

### Additional context

This issue is not consistently reproduced, it seems to be related with the addition of new charts messing up the indexes of the list for charts sidebar (table of contents)

**Comment by hugovalente-pm** [comment]
Placing this as a medium priority, if it is a more heavily used feature would be high

**Comment by dimko** [comment]
As discussed this issue is further exposed due to the latest changes in frontend to use composite charts in single node view and becomes reproducible much more often than before so we should tackle it as soon as possible.

cc: @hugovalente-pm @novykh @juacker

**Comment by dimko** [comment]
Some more info about this issue.

After some investigation it seems that the moment user clicks **Go To Chart**

Cloud Backend returns **443** charts in the `https://staging.netdata.cloud/api/v2/nodes/45bb8b44-cb4b-421f-a86e-d3161e394377/charts?after=1667312268&before=1667312868` request.

Previously for the exact same time period before/after, returned charts where **553** and moments ago **557**

Will enhance logs with the exact same response coming from agent

**Comment by hugovalente-pm** [comment]
@dimko @papazach bumping this bug to `high` priority due to the underlying issue that was surfaced with unsync'ed contexts between Agent and Cloud
if we have an Agent bug it would be great if we identify the bug in time to get into the stable release scheduled for the 9th of Nov.

cc/ @amalkov @MrZammler

**Comment by papazach** [comment]
Hey @hugovalente-pm / @dimko I think that since @MrZammler has included the ACLK conversation log baked-in the Agents we should cross check with what was actually sent over from the Agent.
If the Agent sent it over but the Cloud does not have it in the DB we have indeed an issue we should investigate

**Comment by hugovalente-pm** [comment]
@MrZammler do you have any updates on the above? was it possible to validate if we have any issue on the syncing of contexts?

**Comment by dimko** [comment]
@hugovalente-pm I was about to comment on this one. I can no longer reproduce it. I don't see missing charts agent side, so something has changed and kinda fixed it. I propose to close it and re-open if we encounter again.
