### ISSUE TITLE
[Feat]: Expose the now available `trimmed-median`, `trimmed-mean` and `percentile` time aggregation functions

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#613]
### Problem

The problem is described here https://github.com/netdata/netdata/issues/13426

### Description

With the now available time aggregation functions `trimmed-median`, `trimmed-mean` and `percentile` on the Netdata Agent we need to provide these on the dropdown list.

![image](https://user-images.githubusercontent.com/82235632/195409840-ff90e97f-841e-4112-84d2-131086de0411.png)

There are ready available aliases for the following:
* trimmed-median
   * 1%
   * 2%
   * 3%
   * 5%
   * 10%
   * 15%
   * 20%
   * 25%
* trimmed-mean
   * 1%
   * 2%
   * 3%
   * 5%
   * 10%
   * 15%
   * 20%
   * 25%
* percentile.
   * 25th
   * 50th
   * 75th
   * 80th
   * 90th
   * 95th
   * 97th
   * 98th
   * 99th
  

### Importance

nice to have

### Value proposition

1. more flexible time aggreation options

### Proposed implementation

Just add another input if the selection is any of
* Trimmed Mean
* Trimmed Median
* Percentile

So the filter will look like: "each as <select>99th</select> <select>Percentile</select> every 2 seconds" (make it a sentence I mean)

The text for the label of the new dropdown "The percentile or percentage of the data you want to focus for the percentile or trimmed functions selected."

**Comment by andrewm4894** [comment]
Sounds good!

**Comment by hugovalente-pm** [comment]
after an initial review of the work with @burbuli8ra the following fixes were added to the ticket:
* we should the st, nd, rd, th, etc. on the numbers for percentile and a % for the trimmed
* the text for the label on the % or percentile dropdown "The percentile or percentage of the data you want to focus for the percentile or trimmed functions selected.""

**Comment by hugovalente-pm** [comment]
this is released cc/ @andrewm4894 @sashwathn @shyamvalsan (tagging you guys since I think this was helpful for some use-case content piece)
