### ISSUE TITLE
[Bug]: Consider clarify the `Contact your admin to give you access to this Node` error message for the first-time users

### ISSUE THREAD

**Issue by Dentrax** [netdata/netdata-cloud#616]
### Bug description

Fresh installed the netdata and jumped the netdata cloud page on `Nodes` tab and a popup appered on the bottom left: `Forbidden: Contact your admin to give you access to this Node`

### Expected behavior

Since I'm running the agent on my localhost, I'm already admin and the popup should not appear.

### Steps to reproduce

1. Click sign-in button on `Nodes` tab
2. Sign-in
3. See the error on bottom right

### Screenshots

1. Click sign-in button
![Screen Shot 2022-10-14 at 21 24 00](https://user-images.githubusercontent.com/16493751/195915373-73851506-61ab-4543-a33d-bab9bf52fd31.png)

2. See the error on bottom right
![Screen Shot 2022-10-14 at 21 24 12](https://user-images.githubusercontent.com/16493751/195915394-ada305c9-4375-41a6-a3c3-4cd1b489fd58.png)

### Desktop

OS: [e.g. iOS]	macOS
Browser [e.g. chrome, safari]	Firefox
Browser Version [e.g. 22] 105.0.3

**Comment by dimko** [comment]
Hey @Dentrax, thanks for taking the time to open an issue. Did you claim the node to cloud? If node isn't connected to cloud and the specified room and space you get this forbidden alert.

**Comment by Dentrax** [comment]
Hey, error has gone when I claimed the node. It'd be better not spawn this popup error for the first-time users. Maybe spawning an info popup to encounter the user to claim the agent would much better UX. I needed to find out why I was getting _forbidden_ errors. Rephrasing the message would better. 🤞

**Comment by Dentrax** [comment]
Sorry, I thought it was a bug at the first time. We can close this one or move to feature request discussions, if you want.

**Comment by dimko** [comment]
Yes I agree. It's misleading. Maybe the error message should include a prompt to claim agent in case user hasn't done so. Will bring that up to see how team can enhance this experience. Thanks for your report 🙂

**Comment by hugovalente-pm** [comment]
@jacekkolasa let's confirm also if there isn't any other bug underlying here but for the message we could go with something like:
> Forbidden: You tried to access this Node on Netdata Cloud and you don't have access to it. Please contact your Space admin to give you access to it

**Comment by jacekkolasa** [comment]
@hugovalente-pm that was good idea. We haven't been checking if node is claimed, so i added additional check (using separate `agents/${machineGUID}/info`).

**Comment by Dentrax** [comment]
Warning message contains "Please connect it", but end user might not know "how to connect it". There is also "contact your Space admin" message, but in this case, I'm the admin since I run it on my local end. If I jump to Netdata Cloud on my localhost, maybe we should say instead: "consider claiming the node", instead of say "contact with the admin".

**Comment by dimko** [comment]
Netdata Agent doesn't have roles. Cloud doesn't know if you were the one claimed the agent or not. 

Every user that has access to the local dashboard can get re-directed to Netdata Cloud. `User with agent dashboard access != "admin" of the Netdata agent`
Imagine a case where a Netdata Dashboard is used by a team in a company and a public url has been assigned to it so dashboard is accessible by every team member, however to connect it to Cloud someone needs to directly connect to the machine that hosts Netdata Agent and run the claim/connect command. 

The message on Cloud side assumes that the user that created the Space in Netdata Cloud and is an admin to it, also has admin access rights to the agent, which might not always be the case. So...

We might need to clarify what "admin" user means. 

In this case, **it's a Netdata Cloud user with admin access to the Space which enables him to reveal the claiming parameters not available to non-admin space users AND have direct admin access to the host running Netdata so he can run the claiming script**

Maybe adding a link re-directing to the **How to Connect your Agent** docs, describing the above would help.

**Comment by hugovalente-pm** [comment]
thanks for the feedback @Dentrax , the case is exactly what @dimko mentions we don't know at the local agent dashboard what permissions/role the user has on Netdata Cloud. Having a link to that page wouldn't be bad, the only concern is a link on one of these toaster notifications... not use UX it will be very friendly

**Comment by hugovalente-pm** [comment]
the fix for this has been released
