### ISSUE TITLE
[Feat]: Add button to jump to anomalies tab from alert page

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#618]
### Problem

From an alert let me get to anomalies tab for that node and timeframe in 1 click.

### Description

similar to how we have run correlations button we should also add a button called "Anomalies" that highlights 1 minute around the alert, filters for the node of the alert and taks you to the anomalies tab. 

![image](https://user-images.githubusercontent.com/2178292/196502657-f7844c3d-7331-44ae-85a9-f6d1c9991d22.png)

### Importance

really want

### Value proposition

1. make it easier to discover and explore any anomalies around when an alert was triggered

**Comment by andrewm4894** [comment]
@hugovalente-pm can you add area/ml on this when you get a chance - i dont seem to be able

**Comment by hugovalente-pm** [comment]
@andrewm4894 I think this classification of `area/xyz` is only currently available/used on the `netdata/netdata` on `netdata/netdata-cloud` we were having the teams, e.g. we have `data-products-team` label which we could re-purpose to just `data-products`

**Comment by sashwathn** [comment]
Anomaly rates exist on each chart.
