### ISSUE TITLE
[Bug]: quickly changing filters creates flickering charts

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata-cloud#619]
### Bug description

When /data calls in Overview happen with few seconds delay, a bug related with race condition can appear:
- filter setting 1 is set (dimensions or nodes)
- filter setting 2 is set
- 2 /data calls are made
- /data from setting 1 returns as last, which results in invalid chart

We should have a mechanism that prevents updating chart with older data than currently painted

### Expected behavior

Charts should not take into account /data calls if newer one has already been used to paint chart.

### Steps to reproduce

1. Go to Room Overview where nodes are not updating fast, and where random calls are sometimes slower
2. Change few times filters (can be global filter or chart filter) and observe that chart is going into bad filter state (for example  2 nodes were selected but 4 nodes are showing on the chart)

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@jacekkolasa I was trying to see if this is still there but can't be sure, could you check please?

**Comment by hugovalente-pm** [comment]
@jacekkolasa could you check if this still happens?

**Comment by jacekkolasa** [comment]
I couldn't recreate it, I think it's fixed
