### ISSUE TITLE
[BUG] time axis alignment to peaks changing in the overview screen

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#62]
As we pan an overview screen chart (tried with kubernetes charts), a specific peak appears on different times, like it's moving around in time. I shared internally a video of this happening.

**Comment by cakrit** [comment]
Tried again now and can't replicate. Will keep trying, and get some logs when it happens again.

**Comment by cakrit** [comment]
The attached has the results of some experiments we did together with @papazach 
We have two issues: Wrong first entry ts and wrong timestamp for the shift from null to value in the node ending in `qiqv`
[requests-responses.txt](https://github.com/netdata/netdata-cloud/files/6343908/requests-responses.txt)

**Comment by hugovalente-pm** [comment]
@papazach seems you looked into this in the past, do you know if this is still happening?

**Comment by papazach** [comment]
Is this still relevant @hugovalente-pm ?

**Comment by hugovalente-pm** [comment]
@papazach I asked you a similar thing in Dec.2021 😄 
I'm not aware of this issue happening at the moment, so we probably could close it
