### ISSUE TITLE
[Quick win] [Feat]: Increase max supported length of bookmarks

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#620]
### Description

We only support 20 characters for a bookmark name, which is very small

Was trying to create one for "PostgreSQL monitoring" and even that doesn't fit :) I think we should support at least 50 characters here.

![image](https://user-images.githubusercontent.com/24860547/196702739-2b73e4a8-3d9b-4072-a0a0-35df3479d68f.png)

### Importance

nice to have

### Value proposition

1. More flexibility for user

**Comment by hugovalente-pm** [comment]
@netdata/cloud-be do you know if there is any limitation on the database? just to understand if this is just an FE work or it involves more work

**Comment by vkuznecovas** [comment]
I've opened a PR to bump this to 50 on the backend side.

**Comment by hugovalente-pm** [comment]
this is released
