### ISSUE TITLE
[feat]: The visualisation of uptime chart needs to be improved

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata-cloud#621]
### Bug description

The uptime chart Y axis shows the time elapsed since the last restart and the current format is unreadable.
We should improve the unit display for also all such charts that are related to uptime.

Additionally, the default grouping for the uptime chart needs to be "By node" as averaging the uptime of multiple nodes makes absolutely no sense.

### Expected behavior

1. The Y axis should show time in a more readable format (may be just show days on the Y axis and when scrolling on the chart show the actual time as well) - @cakrit and @christophidesp and ideas?
2. The grouping for the uptime chart should be by Node by default

### Steps to reproduce

1. Open the Overview tab and look at the uptime chart

### Screenshots

Change default visualisation from this:
<img width="851" alt="Screen Shot 2022-10-17 at 18 03 09" src="https://user-images.githubusercontent.com/96257330/196709354-68006c7e-d68c-4192-bfa5-fd47ba2113bb.png">
to:
<img width="851" alt="Screen Shot 2022-10-17 at 18 05 39" src="https://user-images.githubusercontent.com/96257330/196709378-ba938956-975a-4899-aa21-2e15a4214e98.png">

And improve the units on the Y axis

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@sashwathn I believe the improvement of the y-axis was done, for the change of the group by we should be able to do it context.js update, right?

![image](https://github.com/netdata/netdata-cloud/assets/82235632/d363dd5a-4dce-41e3-9d05-f8a1ae218f8e)

**Comment by sashwathn** [comment]
@hugovalente-pm i think we can close this request.
