### ISSUE TITLE
[Bug]: Leaving a space leaves a ghost icon

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#622]
### Bug description

Left two spaces, this is what the UI shows:

<img width="40" alt="image" src="https://user-images.githubusercontent.com/43294513/196720455-70e02412-d431-49f4-bae3-b74943b10499.png">

### Expected behavior

Don't show ghost buttons

### Steps to reproduce

1. Leave space

### Desktop

Browser Version [e.g. 22]

**Comment by cakrit** [comment]
Of course they go away when I reload.

**Comment by hugovalente-pm** [comment]
this seems similar to this https://github.com/netdata/cloud-frontend/issues/3778 just the action that triggers it is different.
I see that you worked on the other one @novykh , would the same _recipe_  work for this one?

**Comment by hugovalente-pm** [comment]
fixed
