### ISSUE TITLE
[Bug]: Menus being merged unexpectedly on overview

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#623]
### Bug description

I have set up the alarms collector with 2 jobs one called "default" and one called "ml". When i look in single node view i see them as 2 different menu items as expected. 

![image](https://user-images.githubusercontent.com/2178292/196734878-936f17d2-37ab-4a2f-8a06-499769b2c579.png)

However when i look on the overview tab they all get sent to a single "Alarms" menu with all the dims on the one chart. 

![image](https://user-images.githubusercontent.com/2178292/196735138-8b204f4c-f656-4681-9326-d7345c9430b4.png)

### Expected behavior

I would expect both an "Alarms default" and "Alarms ml" menu on the overview tab that keeps the consistent separation of the single node view.

### Steps to reproduce

1. enable alarms collector.
2. create 2 jobs with different names.

### Desktop

Browser Version [e.g. 22]

**Comment by andrewm4894** [comment]
could this be because they have the same `context` ? 

![image](https://user-images.githubusercontent.com/2178292/196735820-ae258e89-7a64-4120-bc94-cba432010671.png)

![image](https://user-images.githubusercontent.com/2178292/196736134-1cc44f4f-7586-46fb-8bc4-778a39c69581.png)

**Comment by andrewm4894** [comment]
slack thread with some discussion. looks like this is expected behaviour since they do both have same context.

https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1666193401137179

**Comment by ilyam8** [comment]
> I would expect both an "Alarms default" and "Alarms ml" menu on the overview tab that keeps the consistent separation of the single node view.

That is totally expected (the whole point of the overview is to merge charts from the same source) and not a bug.

> could this be because they have the same context ?

Yes, that is how it works to my knowledge. Merged using context. The first word to dot is the source (alarms). Another example: all MySQL jobs would be merged into one MySQL section. All charts (python, go) have `_collect_job` label.

**Comment by andrewm4894** [comment]
oh didn't realize that - yep makes sense now. closing.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/2178292/196803669-0d56b4b9-ba12-45df-afc2-faff26fe528c.png">
