### ISSUE TITLE
[Bug]: app.plugin link is black for some reason

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#625]
### Bug description

![image](https://user-images.githubusercontent.com/2178292/197208543-a8d672a4-4b19-48cf-943f-ab08e64f4064.png)

### Expected behavior

be green

### Steps to reproduce

1..

### Desktop

Browser Version [e.g. 22]

**Comment by andrewm4894** [comment]
Looks like its when you click a link and its marked as visited 
![image](https://user-images.githubusercontent.com/2178292/197214239-f40fe98a-e073-4421-bbd1-b574e048c686.png)

**Comment by hugovalente-pm** [comment]
this issue is only for the dark theme
![image](https://user-images.githubusercontent.com/82235632/197480677-1725d748-ca70-4c1c-b6cc-87af4b5ec84c.png)

**Comment by hugovalente-pm** [comment]
this is released
