### ISSUE TITLE
[Bug]: /correlations gives back 404 when highlighted area is before first agent data

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#627]
### Bug description

The following request 

**https://staging.netdata.cloud/api/v2/nodes/82e56c86-e646-4567-81b7-8d31fcf1dca9/correlation**

with payload

`{'baseline': {'after': '2022-10-25T11:05:08.335Z', 'before': '2022-10-25T11:07:08.335Z'}, 'highlight': {'after': '2022-10-25T11:07:08.335Z', 'before': '2022-10-25T11:09:08.335Z'}, 'chart_contexts': ['anomaly_detection.anomaly_rate', 'anomaly_detection.detector_events', 'anomaly_detection.dimensions', 'apps.cpu', 'apps.cpu_system', 'apps.cpu_user', 'apps.files', 'apps.lreads', 'apps.lwrites', 'apps.major_faults', 'apps.mem', 'apps.minor_faults', 'apps.pipes', 'apps.preads', 'apps.processes', 'apps.pwrites', 'apps.sockets', 'apps.swap', 'apps.threads', 'apps.uptime', 'apps.vmem', 'cpu.cpu', 'cpu.interrupts', 'cpu.softirqs', 'cpu.softnet_stat', 'disk.avgsz', 'disk.await', 'disk.backlog', 'disk.busy', 'disk_ext.avgsz', 'disk_ext.await', 'disk_ext.io', 'disk_ext.iotime', 'disk_ext.mops', 'disk_ext.ops', 'disk.inodes', 'disk.io', 'disk.iotime', 'disk.mops', 'disk.ops', 'disk.space', 'disk.svctm', 'disk.util', 'groups.cpu', 'groups.cpu_system', 'groups.cpu_user', 'groups.files', 'groups.lreads', 'groups.lwrites', 'groups.major_faults', 'groups.mem', 'groups.minor_faults', 'groups.pipes', 'groups.preads', 'groups.processes', 'groups.pwrites', 'groups.sockets', 'groups.swap', 'groups.threads', 'groups.uptime', 'groups.vmem', 'ip.ecnpkts', 'ipv4.icmp', 'ipv4.icmp_errors', 'ipv4.icmpmsg', 'ipv4.packets', 'ipv4.sockstat_sockets', 'ipv4.sockstat_tcp_mem', 'ipv4.sockstat_tcp_sockets', 'ipv4.sockstat_udp_mem', 'ipv4.sockstat_udp_sockets', 'ipv4.tcphandshake', 'ipv4.tcpopens', 'ipv4.tcppackets', 'ipv4.tcpsock', 'ipv4.udperrors', 'ipv4.udppackets', 'ipv6.errors', 'ipv6.packets', 'ipv6.sockstat6_tcp_sockets', 'ipvs.net', 'ipvs.packets', 'ipvs.sockets', 'mem.available', 'mem.committed', 'mem.kernel', 'mem.oom_kill', 'mem.pgfaults', 'mem.slab', 'mem.transparent_hugepages', 'mem.writeback', 'net.carrier', 'netdata.aclk_cloud_req', 'netdata.aclk_cloud_req_http_type', 'netdata.aclk_openssl_bytes', 'netdata.aclk_processed_query_type', 'netdata.aclk_protobuf_rx_types', 'netdata.aclk_query_per_second', 'netdata.aclk_query_threads', 'netdata.aclk_query_time', 'netdata.aclk_status', 'netdata.apps_children_fix', 'netdata.apps_cpu', 'netdata.apps_fix', 'netdata.apps_sizes', 'netdata.clients', 'netdata.compression_ratio', 'netdata.dbengine_compression_ratio', 'netdata.dbengine_global_errors', 'netdata.dbengine_global_file_descriptors', 'netdata.dbengine_io_operations', 'netdata.dbengine_io_throughput', 'netdata.dbengine_long_term_page_stats', 'netdata.dbengine_ram', 'netdata.db_points', 'netdata.dictionaries.category.callbacks', 'netdata.dictionaries.category.dictionaries', 'netdata.dictionaries.category.items', 'netdata.dictionaries.category.memory', 'netdata.dictionaries.category.ops', 'netdata.heartbeat', 'netdata.net', 'netdata.page_cache_hit_ratio', 'netdata.page_cache_stats', 'netdata.prediction_stats', 'netdata.private_charts', 'netdata.queries', 'netdata.requests', 'netdata.response_time', 'netdata.server_cpu', 'netdata.sqlite3_context_cache', 'netdata.sqlite3_metatada_cache', 'netdata.sqlite3_queries', 'netdata.sqlite3_queries_by_status', 'netdata.sqlite3_rows', 'netdata.statsd_bytes', 'netdata.statsd_events', 'netdata.statsd_metrics', 'netdata.statsd_packets', 'netdata.statsd_reads', 'netdata.statsd_useful_metrics', 'netdata.strings_entries', 'netdata.strings_memory', 'netdata.strings_ops', 'netdata.tcp_connected', 'netdata.tcp_connects', 'netdata.training_stats', 'netdata.uptime', 'netdata.workers.aclkquery.cpu', 'netdata.workers.aclkquery.jobs_started_by_type', 'netdata.workers.aclkquery.threads', 'netdata.workers.aclkquery.time', 'netdata.workers.aclkquery.time_by_type', 'netdata.workers.aclksync.cpu', 'netdata.workers.aclksync.jobs_started_by_type', 'netdata.workers.aclksync.time', 'netdata.workers.aclksync.time_by_type', 'netdata.workers.cgroups.cpu', 'netdata.workers.cgroupsdisc.cpu', 'netdata.workers.cgroupsdisc.jobs_started_by_type', 'netdata.workers.cgroupsdisc.time', 'netdata.workers.cgroupsdisc.time_by_type', 'netdata.workers.cgroups.jobs_started_by_type', 'netdata.workers.cgroups.time', 'netdata.workers.cgroups.time_by_type', 'netdata.workers.cpu_total', 'netdata.workers.dbengine.cpu', 'netdata.workers.dbengine.jobs_started_by_type', 'netdata.workers.dbengine.time', 'netdata.workers.dbengine.time_by_type', 'netdata.workers.diskspace.cpu', 'netdata.workers.diskspace.jobs_started_by_type', 'netdata.workers.diskspace.time', 'netdata.workers.diskspace.time_by_type', 'netdata.workers.health.cpu', 'netdata.workers.health.jobs_started_by_type', 'netdata.workers.health.time', 'netdata.workers.health.time_by_type', 'netdata.workers.idlejitter.cpu', 'netdata.workers.idlejitter.jobs_started_by_type', 'netdata.workers.idlejitter.time', 'netdata.workers.idlejitter.time_by_type', 'netdata.workers.metasync.cpu', 'netdata.workers.metasync.jobs_started_by_type', 'netdata.workers.metasync.time', 'netdata.workers.metasync.time_by_type', 'netdata.workers.mldetect.cpu', 'netdata.workers.mldetect.jobs_started_by_type', 'netdata.workers.mldetect.time', 'netdata.workers.mldetect.time_by_type', 'netdata.workers.mltrain.cpu', 'netdata.workers.mltrain.jobs_started_by_type', 'netdata.workers.mltrain.time', 'netdata.workers.mltrain.time_by_type', 'netdata.workers.netdev.cpu', 'netdata.workers.netdev.jobs_started_by_type', 'netdata.workers.netdev.time', 'netdata.workers.netdev.time_by_type', 'netdata.workers.pluginsd.cpu', 'netdata.workers.pluginsd.jobs_started_by_type', 'netdata.workers.pluginsd.threads', 'netdata.workers.pluginsd.time', 'netdata.workers.pluginsd.time_by_type', 'netdata.workers.proc.cpu', 'netdata.workers.proc.jobs_started_by_type', 'netdata.workers.proc.time', 'netdata.workers.proc.time_by_type', 'netdata.workers.rrdcontext.cpu', 'netdata.workers.rrdcontext.jobs_started_by_type', 'netdata.workers.rrdcontext.time', 'netdata.workers.rrdcontext.time_by_type', 'netdata.workers.rrdcontext.value.hub_queue_size', 'netdata.workers.rrdcontext.value.post_processing_queue_size', 'netdata.workers.service.cpu', 'netdata.workers.service.jobs_started_by_type', 'netdata.workers.service.time', 'netdata.workers.service.time_by_type', 'netdata.workers.stats.cpu', 'netdata.workers.statsd.cpu', 'netdata.workers.statsdflush.cpu', 'netdata.workers.statsdflush.jobs_started_by_type', 'netdata.workers.statsdflush.time', 'netdata.workers.statsdflush.time_by_type', 'netdata.workers.statsd.jobs_started_by_type', 'netdata.workers.statsd.time', 'netdata.workers.statsd.time_by_type', 'netdata.workers.stats.jobs_started_by_type', 'netdata.workers.stats.time', 'netdata.workers.stats.time_by_type', 'netdata.workers.tc.cpu', 'netdata.workers.tc.jobs_started_by_type', 'netdata.workers.tc.time', 'netdata.workers.tc.time_by_type', 'netdata.workers.tc.value.number_of_classes', 'netdata.workers.tc.value.number_of_devices', 'netdata.workers.tc.value.tc_script_execution_time', 'netdata.workers.timex.cpu', 'netdata.workers.timex.jobs_started_by_type', 'netdata.workers.timex.time', 'netdata.workers.timex.time_by_type', 'netdata.workers.web.cpu', 'netdata.workers.web.jobs_started_by_type', 'netdata.workers.web.threads', 'netdata.workers.web.time', 'netdata.workers.web.time_by_type', 'net.duplex', 'netfilter.conntrack_changes', 'netfilter.conntrack_errors', 'netfilter.conntrack_expect', 'netfilter.conntrack_new', 'netfilter.conntrack_search', 'netfilter.conntrack_sockets', 'net.mtu', 'net.net', 'net.operstate', 'net.packets', 'net.speed', 'system.active_processes', 'system.clock_status', 'system.clock_sync_offset', 'system.clock_sync_state', 'system.cpu', 'system.ctxt', 'system.entropy', 'system.forks', 'system.idlejitter', 'system.interrupts', 'system.intr', 'system.io', 'system.ip', 'system.ipc_semaphore_arrays', 'system.ipc_semaphores', 'system.ipv6', 'system.load', 'system.net', 'system.pgpgio', 'system.processes', 'system.processes_state', 'system.ram', 'system.shared_memory_bytes', 'system.shared_memory_segments', 'system.softirqs', 'system.softnet_stat', 'system.swap', 'system.swapio', 'system.uptime', 'users.cpu', 'users.cpu_system', 'users.cpu_user', 'users.files', 'users.lreads', 'users.lwrites', 'users.major_faults', 'users.mem', 'users.minor_faults', 'users.pipes', 'users.preads', 'users.processes', 'users.pwrites', 'users.sockets', 'users.swap', 'users.threads', 'users.uptime', 'users.vmem'], 'method': None, 'options': None, 'group': None}`

Gives back a **404**  with error `'{"errorMsgKey":"ErrNodeResourceNotFound","errorMessage":"requested resource not found","errorCode":"glGWaqbJRr-101089"}'`

### Expected behavior

It should run correlations for selected area and time period and bring back results.

### Steps to reproduce

Select a valid metrics correlation area including a time period where agent didn't have data yet.

### Screenshots

**Metrics correlation selection including time period where didn't have data yet**

![image](https://user-images.githubusercontent.com/19268853/198044944-6acb5ac0-cf6a-4c2a-b381-feba236f7d58.png)

**Metrics correlation selection after initial sync of agent**

![image](https://user-images.githubusercontent.com/19268853/198045221-227c091a-44ee-4802-9d30-1f5a161dcab3.png)

**After agent shutdown, metrics correlation works even though agent didn't have data in the selected period.**

![image](https://user-images.githubusercontent.com/19268853/198045419-81fc1b4a-31d3-45df-b166-1a9740a4ae05.png)

**Comment by hugovalente-pm** [comment]
on the daily @juacker mentioned that he would try to look into this with @dimko

**Comment by dimko** [comment]
So the issue seems to be on the agent side. It was probably introduced in this version of netdata agent **1.36.0-257-nightly** and it's not related to anonymous access but applies to all cases where user uses the metrics correlation endpoint.

will be updating the description of the ticket

**Comment by dimko** [comment]
@hugovalente-pm AFAIK there is no way to trigger this request from inside the agent, unless you hit directly this endpoint through some client

**Comment by hugovalente-pm** [comment]
ahh,! you are right this is in a previous nightly on the most recent ones it doesn't happen, right?
if it is like that let's close it with `won't fix` no?

**Comment by dimko** [comment]
Truth is it doesn't sound very important, unless there are other functionalities affected as well. I am not sure if we should even bother fixing or investigating. Closing
