### ISSUE TITLE
[Feat]: Merge anomalies filtering into Metric Correlation on Overview/Single Node

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#630]
### Problem

On the Overview and Single Node view tabs I want to be able to filter charts based on their anomaly rate, like we do on Metric Correlations, expanding even the anomaly bit on every chart by default.

### Description

Introduce a new button called **Anomalies** that would have a similar behaviour to the Metric Correlations. Based on a slider it would be possible to indicate a threshold you wanted to use to filter the displayed charts

### Importance

must have

### Value proposition

1. We would provide an easy filtering mechanism on charts directly on these tabs

**Comment by andrewm4894** [comment]
@hugovalente-pm user should be able to press button without a filter and so full visible window becomes the implicit highlight basically.

So highlighting should be optional for the user. Obviously if they highlight an area then that's what should be used to get the AR's. 

tbh this is kinda exactly what i wanted with this feature (issues below) - albeit i was proposing to just "decorate" the right hand side menu so as to help "guide" the user on what they might want to click as opposed to filtering the dashboard for them.  

https://github.com/netdata/product/issues/2795
https://github.com/netdata/product/issues/2794

One problem with any filtering based approach here is what anomaly rate % do you threshold on? This is something a user would need to learn and it can also cut off seeing what it just beyond that filter that you might really care about. Thats why i would rather we show them what parts of the dashboard are most anomalous, regardless of what the anomaly rates actually are (they don't even need to care really - just see if what charts are most anomalous do indeed have something anomalous on them). 

There is also the case where maybe user has a hypothesis and so being able just to see all the usual menu items with their AR rates next to them and then decide what to click can be more powerful and build nicely on current flow of the overview screen. 

This will also be a lot easier to implement id imagine - one call to /weights endpoint and basically render the anomaly rates in menu, averaging up all levels on the fly.

Here is app i made to show how realistic data would look:

https://andrewm4894-netdata-ml-app-streamlit-app-ar-toc-5b9d7r.streamlitapp.com/

Paste in a agent url like this: 

http://london.my-netdata.io/#after=1666794134000;before=1666801332000;menu_system_submenu_cpu=undefined;highlight_after=1666799268768;highlight_before=1666799641781;theme=slate;utc=Europe%2FLondon

Here is a little 5 min video showing what i mean: https://drive.google.com/file/d/1dpJFSp22_nQkeWN2N5Z67mS-DFGdyYcF/view?usp=sharing

**Comment by hugovalente-pm** [comment]
@andrewm4894 sorry haven't been able to come to this yet... booked a slot next weekso we can see what is that we would like to do from Product perspective

**Comment by hugovalente-pm** [comment]
based on a conversation with @andrewm4894 @amalkov and @hugovalente-pm we are going to try to merge the two suggestions, the summary of the expected work is here and will be used to update this ticket.

major points:
* we know we need to review and consolidate our filtering approach but due to the nature of the way we want to interact with MC and Anomaly Advisor we will need these to be kept on a different place (currently the top of the page). these need to have a finer-grain precision slider that users need to interact with to explore the results of these metrics scoring algorithms
* we should merge the Anomalies as a method option like we have `ks2` and `volume` and consider the current MC and Anomalies as metric scoring algorithms (both provided by the `/weights´ endpoint)
![image](https://user-images.githubusercontent.com/82235632/200909218-31171517-6fe8-4749-9cc4-6f8584d3f942.png)
* Anomalies should be the default method chosen since we can trigger a call to the `/weights` endpoint as soon as the clicks on the button to open this and we can at that point also do the _overlay_ on TOC to do this https://github.com/netdata/product/issues/2795
  * if user doesn't have any highlighted area this considers the selected timeframe
  * when with Anomalies method the slider should not filter out any results and by default show the full list (anomalies >= 0%)
* this metric scoring functionality should be accessible on user highlight from any chart from any place (Custom Dashboards, Alerts Landing page, etc.), currently this is only allowed on Overview and Single Node view
* Alerts landing page should keep the button to run the metric scoring as a CTA but once users click on that we should immediately trigger the call to that, users shouldn't need to get directed to Single Node View and then need to click on **Find correlations** to get the outcome

 
the full discussion can be found [here](https://drive.google.com/file/d/1yvaVzL5HWef5uD3ECzFKN1CrD1xYl26M/view)

@novykh @ralphm @shyamvalsan fyi

**Comment by amalkov** [comment]
We also have an open question about the CTA name. The current name is "Metric Correlation", after adding the Anomalies method we might need to rename it or keep everything under the umbrella of metric correlation...

Discussed names: 
- score based
- machine learning 
- correlations

It would be good to add in-app engagement as well to educate people about the new available method options and the difference between them

**Comment by hugovalente-pm** [comment]
yes, good point @amalkov . in my description I was calling it **metric scoring** and maybe that could a good one (similar to Score based but with an action in the name)
definitely we will need to have the in-app engagement and review the appropriate docs

if we are in agreement on what we want to do I'll update the ticket description to document this and add an entry to our planning/roadmap doc

**Comment by shyamvalsan** [comment]
I wonder if "score" will be ambiguous to users - personally I'd prefer something like "Find correlations" which is obvious. The way that correlations are calculated could be based on anomalies or ks2 or volume, but what the user is trying to do with this button is still to find events or metrics correlated to the chart they are interacting with.

**Comment by shyamvalsan** [comment]
@hugovalente-pm @andrewm4894 do we have any real world comparisons for: anomalies vs ks2 vs volume? That helps us get an idea on when what works best or what should be the preferred default. 

If a user sees the options and wants to know when a particular algorithm should be used vs another, is there a clearly thought out answer we can document somewhere?

**Comment by hugovalente-pm** [comment]
> @hugovalente-pm @andrewm4894 do we have any real world comparisons for: anomalies vs ks2 vs volume?
If a user sees the options and wants to know when a particular algorithm should be used vs another, is there a clearly thought out answer we can document somewhere?

@andrewm4894 started this on the docs https://learn.netdata.cloud/docs/cloud/insights/metric-correlations#usage-tips, when we combine all together we probably will need to merge the docs as well
it has some explanation why we use ks2 as a default on Metric Correlations. 

for the use of anomalies as a default it is a logical thing from a technical and product perspective since we can also do the overlay on the TOC immediately and technically it is just a query to the agents, no calculations required on the spot.

**Comment by andrewm4894** [comment]
This is my understanding of what involved here. 

1. Add a new method to MC called "Anomaly Rate". It will just be based on a call to /weights like below but would also need `post_aggregation_methods=["one-minus"]` so that instead of anomaly rates we get back "normal rates" (1-AR) - this is to make existing slider work, more below. @juacker we would need to make the `one-minus` work when `method=anomaly-rate`.
2. Anomaly Rate method will be the new default for MC. So when you press "Metric Correlations" button you just get the default results of the "Anomaly Rate" method. The slider will by default for method=anomaly-rate be all the way to the right so that its showing everything. eg filter threshold is set to 100% normal rate aka everything will be shown by default for this method. All menu items on rhs menu will have the anomaly rate next to them so in this default landing page you can just "see" from the menu what parts have highest aggregated anomaly rates and drill in from there. Or you can move the slider to the left to start filtering. As you move to to the left the slider would go (for example) from 100% normal rate to 95% normal rate and so all metrics with AR >= 5% would be displayed.
3. Now that AR is default method for MC we can remove the step that has the "Find Correlations" button. It's not needed, as @amalkov pointed out probably not even needed today (apart from it does tell you if dont have a highlight but no real reason that should not happen when you press starting MC button).
4. You no longer need to have highlighted a time frame to press the "Metric Correlations" button since the anomaly rate method does not need this. Will still need to have highlight selected to be able to do ks2 or volume so perhaps they just greyed out in dropdown or something we need fugure out there,
5. "Metric Correlations" gets rebranded as "Smart Filter" or something if we want. I kinda am less bothered about even changing the "Metric Correlations" name tbh as "correlations" is a standard feature now in our space (everyone has some feature that is based on concept of "correlations") so part of me thinks why change it and also hassle to have to change it all - is it even worth it. But can see either side.

**Comment by andrewm4894** [comment]
> @hugovalente-pm @andrewm4894 do we have any real world comparisons for: anomalies vs ks2 vs volume? That helps us get an idea on when what works best or what should be the preferred default.
> 
> If a user sees the options and wants to know when a particular algorithm should be used vs another, is there a clearly thought out answer we can document somewhere?

https://learn.netdata.cloud/docs/cloud/insights/metric-correlations#usage-tips

**Comment by andrewm4894** [comment]
On naming some other ideas. I think "Smart Filter" makes sense but is maybe a little corny - the whole "Smart X" meme is kinda on its way out.

- "ML Filtering"
- "Advanced Filter"
- "Correlations"

Tbh "Correlations" or "Metric Correlations" would be fine technically. Nothing in ks2 or volume really has anything to do with correlations - the "correlation" part if implicit in the UI/UX of the metrics you see on the screen at the same time. So technically speaking method="Anomaly Rate" is also similar in that it shows what metrics where anomalous **at the same time** and this is where the "correlations" come in. 

So i'm kinda easy either way.

**Comment by shyamvalsan** [comment]
I would stick with something that has "correlations" in the name - the name should correspond to a user action.  Advanced filtering is the other closest option but might get confusing with all the other filtering we do.

**Comment by shyamvalsan** [comment]
Agree and think we should close this issue @hugovalente-pm

**Comment by hugovalente-pm** [comment]
@andrewm4894 @shyamvalsan if I understood correctly the #756 is to place the anomaly rate on the TOC "basically" (linking to area selections, etc.) but it doesn't replace the filtering of charts based like we do with Metric Correlations, right?

I don't actually think one replaces the other and the goal of this one was to merge these _smart filtering_ options and have also Anomalies available like metric correlations

priority can be discussed of course but doesn't feel like a replacement

**Comment by andrewm4894** [comment]
yeah could be a place for both really i guess now that you mention it.

**Comment by hugovalente-pm** [comment]
afaik, this won't be done
