### ISSUE TITLE
[Bug]: Filtering on dimension on wmi.dpu_dpcs fails

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#633]
### Bug description

Filtering on dimension on wmi.dpu_dpcs fails
<img width="566" alt="image" src="https://user-images.githubusercontent.com/43294513/199501232-3017dbec-e179-4987-a148-ce3f8f51263e.png">

I suspected it's because the dimensions have a comma in them, but the request is flawless

Request payload:
```
{"filter":{"nodeIDs":["4dfcb1b0-a61b-40dc-9439-70a2f91699cf"],"context":"wmi.cpu_dpcs","dimensions":["core0,11","core0,10"]},"aggregations":[{"method":"sum","groupBy":["dimension"]}],"agent_options":["jsonwrap","flip","ms"],"points":542,"format":"json","group":"average","gtime":0,"after":-300,"with_metadata":true}
```

Response:
```
{"errorMsgKey":"ErrAllNodesFailed","errorMessage":"ErrAllNodesFailed","errorCode":"N2rperBGow-275130627","nodes":[{"id":"4dfcb1b0-a61b-40dc-9439-70a2f91699cf","name":"DESKTOP-C7OKV71","routing_latency":"1.143368ms","adc_latency":"247.829981ms","error":{"errorMsgKey":"ErrContextNotFound","errorMessage":"node doesn't have the requested context","errorCode":"N2rperBGow-275130627"},"chartIDs":[],"hops":0,"coverage":1,"db_points_per_tier":null}]}
```

### Expected behavior

-

### Steps to reproduce

1. This is on a personal test space, I can invite you to see it, so you don't have to install the wmi collector

### Desktop

Browser Version [e.g. 22]

**Comment by cakrit** [comment]
All dimensions works fine by the way, it's only the filtering that does it.

**Comment by hugovalente-pm** [comment]
@cakrit have you had a chance to check on this?
wondering if we could close the bug?

**Comment by cakrit** [comment]
Yes, it looks very different now.
