### ISSUE TITLE
[Bug]: Missing "Plugin" from chart info

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#634]
### Bug description

On every chart I've clicked, I see an empty plugin
 
<img width="272" alt="image" src="https://user-images.githubusercontent.com/43294513/199506079-20eabe77-0823-423c-aa4a-a080465128f3.png">

### Expected behavior

See the plugin

### Steps to reproduce

1. Click info on a chart

### Desktop

Browser Version [e.g. 22]

**Comment by jacekkolasa** [comment]
@netdata/cloud-be I don't see `plugin` in `rooms/:roomID/charts` payload, do you think it should be there? If I add mock `plugin` property for the chart, the `plugin` is displayed in the Information tab.

**Comment by hugovalente-pm** [comment]
@jacekkolasa this is currently available on the `/data` response on chart labels. is it possible to use from there?
![image](https://user-images.githubusercontent.com/82235632/209321138-c4b63c76-3694-4a4f-92b6-555ec7905f0b.png)

**Comment by jacekkolasa** [comment]
@hugovalente-pm good catch, i think we can. I'll add it but will wait with merge/release until we'll have confirmation from BE, that it's ok to get it from all_chart_labels

**Comment by jacekkolasa** [comment]
it's on production for some time already

**Comment by jacekkolasa** [comment]
@hugovalente-pm thanks for pointing out, it's not on production yet. cloud-fe haven't been updated with latest `charts`.

**Comment by jacekkolasa** [comment]
now it's definitely on production
