### ISSUE TITLE
[Bug]: Bookmark url input validation

### ISSUE THREAD

**Issue by andresmazzo** [netdata/netdata-cloud#635]
### Bug description

Copy url of a netdata dashboard. Click "New Bookmark" and paste url on input. :( .
Error message:
`This is not a valid URL                                              163/255`
Example urls: 
`https://app.netdata.cloud/spaces/example-issue/rooms/apps/dashboards/general#appliedFilteredIds=&liveNodeIds=&staleNodeIds=&offlineNodeIds=&filteredNodesSearchParams=`

`https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=example;start=PT3H`

### Expected behavior

Support urls with characters & : ;
Support > 255 characters. Maximum length is 2048 characters for url. And nowadays applications sometimes use long urls for metadata :(.

### Steps to reproduce

1. Copy url of a netdata dashboard. 
2. Click "New Bookmark"
3. Paste url on input
4. Error message: `This is not a valid URL                                              163/255`

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
thanks for raising thus @andresmazzo we will take a look to review these limitations on URLs
the characters that were causing this issue on the example were `=` and `&` but as @andresmazzo mentions the `:` and `;` also make the validation fail

the validation of the characters is happening on the FE but the limitation is also restricted by the BE.

suggestion:
* @netdata/cloud-be let's allow longer URLs as suggested, up to 2048 characters
* @netdata/cloud-fe let's review the URL validation to accept the characters mentioned and once character limitation is increased allow that as well

**Comment by hugovalente-pm** [comment]
@andresmazzo this has been fixed and release, thanks again for raising it

**Comment by andresmazzo** [comment]
Thanks @hugovalente-pm for the quick response! It's a pleasure to collaborate on such great tool :)

**Comment by hugovalente-pm** [comment]
great to know @andresmazzo! do keep any bug of feature requests coming through- the help of the community is huge to ensure we are moving towards the right direction
