### ISSUE TITLE
[Feat]: Add ability to edit bookmarks

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#638]
### Problem

I can't edit bookmarks once created - and have to delete and add them again. Not user friendly.

### Description

Bookmarks once created only have a "Delete" option, there's no "Edit" option. Which means if I want to update one or even just fix a typo I have to delete it and re-create it. 

![image](https://user-images.githubusercontent.com/24860547/200261499-ca5851ab-89a7-48ca-8d05-b2cd6e12c225.png)

### Importance

nice to have

### Value proposition

1. Improve usability of bookmarks feature

### Proposed implementation

An edit icon next to the delete icon that lets user edit the bookmark.

**Comment by hugovalente-pm** [comment]
bookmarks were ☠️
