### ISSUE TITLE
[Bug]: Pausing a chart still requests /data

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#639]
### Bug description

When pausing date time picker data requests are still issued, but with a lower frequency

### Expected behavior

No data requests should be issued while paused

### Steps to reproduce

1. Navigate to overview tab (or single node view)
2. Pause charts by clicking the date time picker
3. Without scrolling between charts check network requests. No /data requests should be issued

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/200412692-93547c85-6867-496e-9f87-9f243b0affd7.png)

### Desktop

OS: Ubuntu
Browser Chrome
Browser Version 106

**Comment by novykh** [comment]
Since today the release was blocked maybe I can do this change as well. It's a really good point.

**Comment by hugovalente-pm** [comment]
the `/data` one seems to be fixed so I think we can close this, can you confirm @novykh 

the `/charts` is getting updated every minute as a polling mechanism which was part of another ticket to review polling times.
if we don't need it we can remove it but let's open a separate ticket for that

**Comment by dimko** [comment]
What seems to be causing the extra `/data` requests seems to be the `/nodes` request.
Even though there are no new nodes added, the sorting of node's capabilities change so FE issues a new /data request as it thinks there are node changes.

**Comment by hugovalente-pm** [comment]
this is fixed
