### ISSUE TITLE
[BUG] List options of individual node screen charts appear behind the next chart's menu

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#64]
![image](https://user-images.githubusercontent.com/43294513/109992023-b6a81a80-7cbf-11eb-9e76-ac1b9cae1b03.png)

![image](https://user-images.githubusercontent.com/43294513/109992072-c293dc80-7cbf-11eb-8043-c005f6b040ee.png)

Workaround is to increase the height of the chart, but we should fix it.

**Comment by apostolidhs** [comment]
Fixed on `release/2.1.3`
