### ISSUE TITLE
[Bug]: Favorites (Pinning a section) doesn't bring subsections along with it

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#640]
### Bug description

Favoriting (pinning a section) only shows the main section name on top - and all subsections are not available here. 

![image](https://user-images.githubusercontent.com/24860547/200539656-4a07c812-9e7c-4f07-92da-3936b3bacdc7.png)

To see sub sections user needs to scroll down 

![image](https://user-images.githubusercontent.com/24860547/200540125-694e26fb-74aa-4f74-93c9-6272e3335433.png)

I'm not sure but I think this used to work previously and maybe a recent change broke this?

### Expected behavior

ideally the subsections should be visible along with the favorited section name to avoid user scrolling. 

### Steps to reproduce

1. Just visit the demo space https://app.netdata.cloud/spaces/netdata-demo/rooms/redis/

### Desktop

Browser Version [e.g. 22]

**Comment by shyamvalsan** [comment]
cc: @hugovalente-pm @novykh @sashwathn

**Comment by novykh** [comment]
This is working like this from the introduction of this feature. By pressing a favourite it takes you down to the actual menu item.

**Comment by shyamvalsan** [comment]
That's the thing @novykh pressing on a favorite is not taking me down tot he actual menu item. 

![Netdata Cloud (17)](https://user-images.githubusercontent.com/24860547/200557244-a3a0699c-8dc1-4ffd-a8de-6676e7788b04.gif)

**Comment by novykh** [comment]
That's true. I will push a fix for showing the correct menu on the sidebar.

**Comment by hugovalente-pm** [comment]
this has been fixed
