### ISSUE TITLE
[Bug]: Filtering nodes waits for the next chart update to refresh the results

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#641]
### Bug description

When we filter nodes either from the top menu or from the right menu in the Anomalies tab, the charts do not refresh until the next time they were going to be refreshed anyway. This causes a very bad UX, especially when you have zoomed out to see a larger time frame.

### Expected behavior

Filtering nodes should have an immediate effect on the visible charts. 

### Steps to reproduce

1. Select a long time frame (a few hours is fine)
2. Go to the anomalies tab
3. Filter to see different nodes from either the right menu or the top menu

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this is a bad one UX/UI-wise, @novykh can we tackle it soon?

**Comment by hugovalente-pm** [comment]
this feels like there is a _missing event_ to communicate the change from the filter to the charts once the focus is "back" on charts it works ok

https://user-images.githubusercontent.com/82235632/200790539-d64ef269-454f-4143-9d4e-e229fe46e11f.mp4

**Comment by hugovalente-pm** [comment]
this is fixed
