### ISSUE TITLE
[Feat]: Hide Not configured and Not capable sections in Anomaly Advisor menu when empty

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#642]
### Problem

In the anomaly advisor node selector menu, the sections for "Not configured" and "Not capable" nodes are always visible with their accompanying message and hyperlinks - even when there are zero nodes that meet this criteria. 

![image (1)](https://user-images.githubusercontent.com/24860547/200620130-46cc9aa0-9925-4f7e-9204-582808e07a4f.png)

This causes unwanted clutter and eats up screen real estate.

### Description

Now that ML is enabled by default and has been for a number of Netdata agent releases these messages are not as useful as they were initially. 

If the user has no nodes that fall into these sections then the sections themselves should be hidden.

### Importance

must have

### Value proposition

1. Remove superfluous content that's not helping users from UI

**Comment by shyamvalsan** [comment]
cc: @ralphm @amalkov @novykh

**Comment by amalkov** [comment]
Agree 👍

**Comment by hugovalente-pm** [comment]
this is done
