### ISSUE TITLE
[Bug]: used ram gauge is now in GB and always full. Used to be % based like on agent dashboard

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#647]
### Bug description

found by a lovley user on discord: https://discord.com/channels/847502280503590932/847502280503590935/1039619269421449296

used ram gauge is now in GB and always full. Used to be % based like on agent dashboard

![image](https://user-images.githubusercontent.com/2178292/200857109-8d3a5299-f1fa-47bb-86b1-136e4f64c1c8.png)

### Expected behavior

I would expect it to be % used like this: 
![image](https://user-images.githubusercontent.com/2178292/200857361-6a6a6493-322d-4273-8116-e803da84ba36.png)

### Steps to reproduce

1.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this is fixed
