### ISSUE TITLE
[Bug]: No message displayed when user tries to leave last space

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#649]
### Bug description

When user tries to leave his last space he can't do it but no message is displayed
![image](https://user-images.githubusercontent.com/82235632/201079989-4d287154-90ec-465a-90e8-329da5de8693.png)

### Expected behavior

A message should be presented to the user or the `Leave` button should not be enabled

### Steps to reproduce

1. Have a user that only has one Space - which has at least another admin user there
2. Try to leave the space
3. Modal doesn't disappear and no message is disaplayed

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this is fixed

**Comment by burbuli8ra** [comment]
Released on [v4.0.0](https://github.com/netdata/cloud-frontend/releases/tag/4.0.0)
