### ISSUE TITLE
[BUG] Going to a node from a k8s popup opens a new browser tab and shows a tab with no name

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#65]
Started here and clicked the little arrow to see the node:

![image](https://user-images.githubusercontent.com/43294513/110146376-584a6d00-7d8f-11eb-996d-aa734148bb4e.png)

Got a new browser tab, with this:
![image](https://user-images.githubusercontent.com/43294513/110146441-7021f100-7d8f-11eb-98e4-82cb3de880a0.png)

Expected behavior:
- Since we have our own tabs now, should see a new tab where I am.
- The name should appear.

**Comment by manos-saratsis** [comment]
Similar to https://github.com/netdata/netdata-cloud/issues/67
