### ISSUE TITLE
[Bug]: MC results filters follow me across spaces

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#653]
### Bug description

If i run a MC in one space and get the filtered results. If i then go to another sapce that same metric filters etc seem to apply in that space. They should not. 

https://user-images.githubusercontent.com/2178292/201344020-79665590-8495-46ff-be53-a0113771b812.mp4

### Expected behavior

Changing space should essentially close or X out of the MC results. 

### Steps to reproduce

1.

### Desktop

Browser Version [e.g. 22]

**Comment by andrewm4894** [comment]
@hugovalente-pm @novykh seems like a potential high priority bug just given the sort of confusion it could cause a user when navigating spaces after doing an MC.

**Comment by hugovalente-pm** [comment]
this is fixed, applied X out of the MC results.

**Comment by hugovalente-pm** [comment]
@andrewm4894 this seems to be fixed, could you also check?

**Comment by hugovalente-pm** [comment]
this is fixed
