### ISSUE TITLE
[Bug]: Alert re-direct from email for cleared alerts doesn't work

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#656]
### Bug description

Once an alert is cleared, if user uses the email to access that alert in Netdata Cloud an error page is displayed that alert can't be found

### Expected behavior

User should be re-directed to Alert Dedicated View and be able to see the alert affected chart and information about the alert and run correlations for the time period the alert transitioned to the cleared status

### Steps to reproduce

1. Trigger an alert in Netdata Cloud for a specific agent e.g Alert in **WARNING** status
2. Clear the alert
3. In user's mailbox, click on the email saying the alert is in Warning state or in Cleared state

### Screenshots

example of a cleared alert email

![image](https://user-images.githubusercontent.com/19268853/202154029-0cd8b96f-f1f6-4ded-9854-16195e692186.png)

What user sees once she lands to Netdata Cloud

![image](https://user-images.githubusercontent.com/19268853/202153864-af32ee39-886e-4ff6-a715-7b73a1230123.png)

### Desktop

OS: Ubuntu
Browser Chrome
Browser Version 106

### Additional context

This was affected in the context of the "contexts everywhere" change in the Frontend

**Comment by hellreturn** [comment]
I am facing "maybe" similar issue. Is their any bug fix for this one? Thanks

**Comment by hugovalente-pm** [comment]
@dimko I tested this and it seems to be fixed, at least I got to the alert landing page in 3 cleared emails

**Comment by dimko** [comment]
@hugovalente-pm yes the re-direct works now. 

On a side note, There is a **something went wrong** message inside the chart so there is something else that is also failing here, agent side probably. 
![image](https://user-images.githubusercontent.com/19268853/208949811-73e836ca-7658-48e0-9f73-0d1e03711a3d.png)

Closing this one. Thanks for the update.
