### ISSUE TITLE
[Feat]: ability for user to choose the "every Ns" on each chart

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#657]
### Problem

Sometimes i end up witrh a chart like this: 
![image](https://user-images.githubusercontent.com/2178292/202161504-af0f968b-dc2a-48ee-b402-f665a16e12d4.png)

What i'd love to be able to do would be to smooth this a bit more to make things a little more aggregated and get more of a rolling average for each line.

### Description

Ability to go from chart above to a more smoothed version.

### Importance

really want

### Value proposition

1. give users more control over how data is queried and presented.

### Proposed implementation

I think there are two ways to do this. 

(A) let me as the user define my own "every Ns" in the chart which would control the level of aggregation on the data queried from the agents. In my example above you can see its "every 58s" dynamically based on the charting library and visible window. But why not just let me change that to "every 5m" an so get less but more smoothed data from the agent in the first place. THis will also make some of the aggregation functions more useful since a median for example is more meaningful to me over a 5min aggregation then a 58sec one. 

or

(B) add something to the FE charts that lets you further transform or smooth the visible data on the actual chart.

**Comment by andrewm4894** [comment]
https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1684845534368559

**Comment by andrewm4894** [comment]
eg it would be great if i could define whatever time aggregation i want in here and then have a bar to summarise it big "point"

![image](https://github.com/netdata/netdata-cloud/assets/2178292/cd2bef7d-2dd5-40d1-89fb-5d2ad23d7ee4)

**Comment by mrtncls** [comment]
Thanks @netdata-community-bot for linking my topic.

Customizable grouping timespan would work for me.
So, I could see the daily/weekly/monthly internet bandwidth consumption.

**Comment by andrewm4894** [comment]
I think the user here could benefit from this too: https://www.reddit.com/r/netdata/comments/15e9t6s/comment/ju7184a/?utm_source=share&utm_medium=web2x&context=3

eg being able to have a bar per hour or day etc

**Comment by sashwathn** [comment]
Do not intend to implement.
