### ISSUE TITLE
[Feat]: Would be nice to have a filter box i could type into to filter the list so i dont need to scroll to it

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#658]
### Problem

It would be nice to be able to type into a search box to filter the list of options in the dropdown so i dont have to scroll so much. Especially useful when we have charts with lots of dims. 

![image](https://user-images.githubusercontent.com/2178292/202199537-dd31c556-4855-4b9c-9094-a3e6afcec9a5.png)

### Description

.

### Importance

nice to have

### Value proposition

1. small quality of life improvement

### Proposed implementation

A search box at top of drop down that i can type into to filter available options.

**Comment by hugovalente-pm** [comment]
this is done
