### ISSUE TITLE
[Bug]: Dashboard broken state

### ISSUE THREAD

**Issue by andresmazzo** [netdata/netdata-cloud#665]
### Bug description

The structure of the content (sizes, grid, etc) it's not the configured. And if you close window it asks for unsaved changes. 
I cannot move graphs. If i add new metrics or create a new dashboard, it also fails to render graphes.
This happens in all the dashboard i have.

Netdata agent is v1.36.1.

### Expected behavior

Show dashboard in the configured format.

### Steps to reproduce

1.Have an already dashboard

### Screenshots

![netdata_bug_dashboard_2022-11-20_17-36-38](https://user-images.githubusercontent.com/53318228/202924919-ea1268db-e6ac-42f8-8224-53c1316d379a.png)

### Error Logs

general#after=166896…odesSearchParams=:1 Uncaught (in promise) o {message: 'canceled', name: 'CanceledError', code: 'ERR_CANCELED', isCancel: true, __sentry_captured__: true}
![netdata_bug_dashboard_2_2022-11-20_17-40-43](https://user-images.githubusercontent.com/53318228/202925133-4baeeba3-af45-435a-a954-58eff87471b2.png)

### Desktop

OS: Linux
Browser chromium	
Browser Version 107.0.5304.110

**Comment by hugovalente-pm** [comment]
This is confirmed there seem to be two things here:
* component that allowed the dragging of charts on dashboards isn't available any longer
* re-sizing and/or repositioning of components isn't working

**Comment by hugovalente-pm** [comment]
@andresmazzo we just released an hotfix for this, please try it out and let us know if all looks good from your side

**Comment by andresmazzo** [comment]
Thanks @hugovalente-pm . I confirm i can resize and move components :+1:
