### ISSUE TITLE
[Bug]: Chart only present on child agent isn't synced to cloud

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#669]
### Bug description

In a parent/child setup where child is streaming data in cloud through a claimed parent (only parent is claimed to netdata cloud, NOT the child), a chart X that lives on child but doesn't exist on parent **doesn't sync in cloud although it exists on agent dashboard**

### Expected behavior

All charts should sync to cloud eventually.

### Steps to reproduce

1. Setup parent and child agents
2. Claim parent to netdata cloud
3. Create a chart in child agent (e.g connect a usb flashdrive on the child host which doesn't exist on parent)
4. Chart should sync to cloud and appear in charts list

### Error Logs

Logs on child's side

```
2022-11-22 09:33:30: STREAM: 377 from 'parentd3tqypgcj2v:19999' for host 'child_one_d3phxg4jzio': REPLAY_CHART "mock_test.mock-area" "true" 0 0
2022-11-22 09:33:30: STREAM: 377 from 'parentd3tqypgcj2v:19999' for host 'child_one_d3phxg4jzio': REPLAY_CHART "netdata.runtime_mock_test" "true" 0 0
```

Parent is full of

`sending empty replication because first entry of the child is invalid (0)`

even though both have been claimed and streaming for more than 2 mins

### Desktop

OS: ubuntu
Browser Chrome
Browser Version 106

### Additional context

This seems to be an agent issue that affects syncing of charts in cloud. Agent dashboard seems to work as expected.

agent version is the latest nightly. Issues started appearing on 22/11/2022

**Comment by dimko** [comment]
https://github.com/ktsaou/netdata/tree/replication-fixes3 seems to be fixing this one

**Comment by hugovalente-pm** [comment]
@dimko saw the thread yesterday with you and @ilyam8 , I believe this can be closed right?
 the issue with alerts is a different thing, no?

**Comment by dimko** [comment]
We can close this yes. Part of the alerts thing was also fixed as it seems but still something remains. WIll open a different one for it. Closing this.
