### ISSUE TITLE
[Feat]: add space name to node alerts from netdata cloud

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#673]
### Problem

i would like to see in the alert title and somewhere obvious on alert email what space the node is claimed to in netdata cloud. 

at the moment i have to know what node names are in what spaces and its confusing when all i get is a node name. 

### Description

add space name to the alert subject and somewhere obvious in the email template

### Importance

really want

### Value proposition

1. will makec it clearer where alerts are coming from.
2. will also make it possible to route alerts in email clients based on space name.

**Comment by andrewm4894** [comment]
@hugovalente-pm i wonder if just as easy to add this to existing ongoing work being done on the intergrations side ? 

or would rather do it later as follow on work?

**Comment by andrewm4894** [comment]
eg prob be easy to just add in these: 

https://github.com/netdata/cloud-notifications-dispatcher-service/pull/19
https://github.com/netdata/cloud-notifications-dispatcher-service/pull/21 
https://github.com/netdata/cloud-notifications-dispatcher-service/pull/22

**Comment by hugovalente-pm** [comment]
Adding the space name on the body of the notification I'm totally up for it, not sure about adding it to the title... saying this because we are trying to discuss how to make the title more intuitive to the user of what the problem is and not _clutter_ it with more info

https://github.com/netdata/netdata/discussions/14059

I can't see those PRs, don't have access to the repo, but probably @car12o can chime-in on this

**Comment by car12o** [comment]
@hugovalente-pm those PR's add new integrations let's not mix stuff.
tbh @juacker is the one in charge of such changes so better ask him, but I feel we may need to schedule a meeting with someone from the design team to review all the templates we have for notifications.

**Comment by hugovalente-pm** [comment]
@car12o as I mentioned I can't see the PRs so don't know what they are 😄 

> I feel we may need to schedule a meeting with someone from the design team to review all the templates we have for notifications.

totally agree, we need to agree on what we want to show on the notifications and then decide how do display them, that is why I also linked the github discussion

cc/ @amalkov @christophidesp @ralphm

**Comment by andrewm4894** [comment]
@hugovalente-pm yep - title gets messy but actually space name in title is most important thing for setting up routing rules in your email provider. eg i can just set up a rule for each space name in email title very easily. 

tbh i think it should be more like "[space] - [node] - [status] [alarm name] [alarm value]" or something more like that

**Comment by andrewm4894** [comment]
@hugovalente-pm you totally should have read access to all repos - i bumped this ticket as it happens me too and is frustrating when cant read all repos: https://github.com/netdata/infra/issues/2995

**Comment by hugovalente-pm** [comment]
> for setting up routing rules in your email provide

This is also achievable through the content and, at least, in Google it is pretty effective. Example of using the `Family` from the body
![image](https://user-images.githubusercontent.com/82235632/204521011-5804d7a0-c2bd-45c5-89f3-7e7f2d7808ba.png)

> really though it should just also be a configurable template so we dont even need to waste time on even trying to think about what a good title is - instead we pick a sensible defualt but let it be extendable or customizable so users can make it whatever they want if they would rather something else.

This should really be our end-game, allow to do something like Datadog does when configuring monitors but this is some bigger change:
![image](https://user-images.githubusercontent.com/82235632/204521273-46bd19e6-2c52-4fea-85d9-daced93a150b.png)

**Comment by andrewm4894** [comment]
So i guess so long as space name goes in in a safe/structured way (given we cant know what users might call a space), then a similar rule could work for now, for gmail. 

My point was that i would imagine there are some systems that probably are not as flexible and would assume all they have might be email subject and that alone to do routing/filtering. I dont have any concrete examples to hand but i think not a bad assumption to make just in case - unsure though.

**Comment by juacker** [comment]
Hi guys, I too think we should have a meeting to talk about the content of the notifications. It's something I wanted to do from the beginning, but as we have the focus on trying to get the endpoints ready to unblock FE team as soon as possible I hadn't the time to focus on this yet.

The content of the current notifications needs to evolve, they were initially created with the intention of supporting the integration only. As a starting point, I show you how the same notification would currently look like for different types of integration:

### Slack
![Captura desde 2022-11-30 13-25-01](https://user-images.githubusercontent.com/2930882/204798344-d511956c-a1fc-442a-ad1b-0c685202682d.png)


### PagerDuty

#### details hidden
![Captura desde 2022-11-30 13-23-11](https://user-images.githubusercontent.com/2930882/204798366-bc856a53-bc1d-4999-8c07-8272c0e65695.png)

#### details expanded
![Captura desde 2022-11-30 13-46-30](https://user-images.githubusercontent.com/2930882/204800054-9b1a980e-515e-4431-a6d5-49478ff41003.png)


### Discord

![Captura desde 2022-11-30 13-25-32](https://user-images.githubusercontent.com/2930882/204798385-3e0bd58f-c4c0-4def-b934-1cc481c68e9e.png)

**Comment by hugovalente-pm** [comment]
this has been added to the templates across the available notification methods
