### ISSUE TITLE
[Bug]: metric correlations - adjusting highlight should retrigger it

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#676]
### Bug description

when i change the highlighted window from within a MC results view, it should retrigger a fresh MC call. At the moment it does nothing. 

### Expected behavior

https://user-images.githubusercontent.com/2178292/203828617-18ce6a25-9cd8-4fc8-8d1c-04cf1fd094a1.mp4

### Steps to reproduce

1. use MC
2. pick a new highlight window
3. nothing happens

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
I think this was not part of the original _specs_ what probably is misleading is that we don't clear the previous results

iirc we didn't do that because the user could want to do a different action on the highlight selection, in the past we had run correlations and zoom. 
we will probably have more actions to trigger from highlight so not sure this is the best experience once we have more

so this actual ticket would consider a feature enhancement not a bug, the bug which I'm not 100% sure it is could the fact it is misleading the doing a new highlight doesn't change anything or indicate the user something

wdyt @christophidesp @novykh ?

**Comment by andrewm4894** [comment]
yeah i cant recall if it ever did this - i have a feeling it did else i feel like i would have defo spotted this before. Not 100% sure though. 

i think if i change the highlight in any way its most natural to retrigger MC else what's rendered on the screen is sort of wrong. 

when the MC bar is visible on top im in MC mode so even if we had other actions available on highlight (like in a little toolbox) i think it should still rerun and in that case you would need to X out of MC to enable the other options. 

Either way - at moment if you want to run another MC on a different highlight it's a bit broken and confusing experience since you either need to X out of it all and go back in again (which is silly) or you interact with a drop down to trigger it which is confusing too.

**Comment by andrewm4894** [comment]
Maybe would solution could be a sort of "refresh" or "rerun" little icon that appears when you change the highlight. Or could be there all time....

oh wait - i do see this button that does this 

![image](https://user-images.githubusercontent.com/2178292/203972834-d96365be-ac74-4fc4-aed1-2145a5e9d66f.png)

**Comment by andrewm4894** [comment]
so maybe its just me but it feels more natural to automatically rerun when you highlight a different window - unless we can come up with good reasons why you would not? 

not sure i can think of any

**Comment by christophidesp** [comment]
Imo it should re-run the correlations when highlighting a new timeframe. I think that it feels the natural thing to happen, but not sure if there are corner cases that prevent this from happening.

**Comment by hugovalente-pm** [comment]
the only reason I see to not do it automatically is what I mentioned previously:

> iirc we didn't do that because the user could want to do a different action on the highlight selection, in the past we had run correlations and zoom.
we will probably have more actions to trigger from highlight so not sure this is the best experience once we have more

we maybe could still see that the user in the metric correlation _mode_ but we will need to verify this when we face this situation

my suggestion then will be to probably keep this a UX bug but with lower prio

**Comment by jacekkolasa** [comment]
I implemented the auto-refresh on timeframe change, in all cases where "Refresh" button was showing up, so I removed that button because it makes no sense now.

**Comment by andrewm4894** [comment]
Cool, I'll do a last check today and then close this.

**Comment by andrewm4894** [comment]
Working as expected - thanks! closing
