### ISSUE TITLE
[Bug]: After adding existing users to room, row selection doesn't clear

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata-cloud#677]
### Bug description

When adding existing users to room, the selection in the list is not cleared. This happens in "Manage War Room / Add Users" modal, in room settings:

before:
[ ] user1
[x] user2
[ ] user3

after clicking "Add 1 members", the result is:
[ ] user1
[x] user3

### Expected behavior

after clicking "Add 1 members", the result should be:
[ ] user1
[ ] user3

### Steps to reproduce

1. As an admin, go to any room except "All nodes" room.
2. Go to "War room settings" / Users, and click "Invite users" (plus icon)
3. select any user
4. click "Add 1 members"
5. after success, the previously selected user is gone, but the next user is selected

**Comment by hugovalente-pm** [comment]
this is fixed
