### ISSUE TITLE
[Bug]: Inviting users not work. No email arrives

### ISSUE THREAD

**Issue by wwwDESIGN-basti** [netdata/netdata-cloud#678]
### Bug description

If i invite email adresses to a space, no email was sending to the target (checked the spam folder too)

### Expected behavior

A Invite E-Mail

### Steps to reproduce

1. Select Space
2. Click "Invite Users"
3. Add a (valid) E-Mail Address
4. Notify Msg tells me mail was sendet.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@wwwDESIGN-basti thank you for reporting this, for us to be able to troubleshoot this could you help us with some more details?
please send them through email to hugo@netdata.cloud

1. what is your space ID?
2. what is the recipient's email address?
3. how many times have you tried?
4. do you know approximately at what time you tried this?

**Comment by hugovalente-pm** [comment]
@wwwDESIGN-basti just checking if you had a chance to see my request for some additional data?

**Comment by hugovalente-pm** [comment]
just to update and close the ticket, as shared by e-mail the e-mail provider seems to be blocking our domain.
in this cases, users need to reach out to their e-mail providers to understand why such a block is in place.
