### ISSUE TITLE
[Bug]: home tab does not update when i delete nodes

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#679]
### Bug description

when i delete nodes the home tab no longer updates right away to reflect this fact. 

### Expected behavior

home should be updated right away 

### Steps to reproduce

1. delete some nodes
2. go see how home tab no displays stale info

### Screenshots

i have deleted those 25 offline nodes about 5 minutes ago. home tab actually confused me and made me think i had not deleted them.

![image](https://user-images.githubusercontent.com/2178292/204856774-1702b084-d28d-4882-aa11-4a05120d756b.png)

### Desktop

Browser Version [e.g. 22]

**Comment by M4itee** [comment]
I have same thing. Difference is that I even restarted whole kubernetes cluster today few times and this is still an issue 
![image](https://user-images.githubusercontent.com/60339703/205085554-cfa2427e-52ce-48db-8788-61a32df87f36.png)

**Comment by hugovalente-pm** [comment]
checking the output of the `/stats/ endpoint it seems to be a @netdata/cloud-be issue
![image](https://user-images.githubusercontent.com/82235632/205308571-a7f008ad-92c1-4ce0-8262-53d7682630a4.png)

**Comment by dertom** [comment]
Hi, same here. In netdata cloud count of hosts is wrong
![SCR-20221210-njx](https://user-images.githubusercontent.com/185302/206863920-1230e667-eed3-4d40-a728-ee9f478ee02c.png)

**Comment by papazach** [comment]
Hello all and thank you for bringing this to our attention.

A fix has been released addressing this issue (with a retroactive effect), feel free to check again your Home tabs.

**Comment by andrewm4894** [comment]
This looks to be fixed now to me following work by @papazach on the backend.

**Comment by dertom** [comment]
here it is also fixed! Thanks!
