### ISSUE TITLE
[Bug]: Make page count in home tab panel more intuitive

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#685]
### Bug description

I see this in my home tab

![image](https://user-images.githubusercontent.com/24860547/206405052-0f322358-38ef-4228-bf52-3eab222401d4.png)

But when I go to each node and click on the info icon and read the agent version -- or in this case click on the warning modal for agents with outdated version, all the agent versions per node are clearly displayed. There are no "unknown" agent versions.

![image](https://user-images.githubusercontent.com/24860547/206405241-b2c4e166-fcff-4f2f-bad8-14422790c86c.png)

### Expected behavior

The table in home tab should show the accurate agent versions - since it is known to Netdata cloud and visible in other parts  of the UI

### Steps to reproduce

1. Problem is visible in the demo space right now: https://app.netdata.cloud/spaces/netdata-demo/rooms/all-nodes/home

### Screenshots

See above

### Desktop

Browser Version [e.g. 22]

**Comment by shyamvalsan** [comment]
See https://netdata-cloud.slack.com/archives/C03NJP9M2PL/p1670489932618569 for discussion with @novykh

**Comment by burbuli8ra** [comment]
At the moment the block that contains all info about **Nodes by Agent version** is scrollable and will be available on the next release!
I am closing this issue and if we see in the future that by making it scrollable is still confusing for the users, we can re-open this one of create a now one to update it with pagination.
