### ISSUE TITLE
[Bug]: chart options not displaying correct anymore

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#686]
### Bug description

i cant see the chart options anymore 
![image](https://user-images.githubusercontent.com/2178292/206442185-4b43968d-039b-4bf5-87aa-b68ca25b0b2b.png)

### Expected behavior

i can see them

### Steps to reproduce

1.

### Desktop

Browser Version [e.g. 22]

**Comment by nil0x42** [comment]
Note that the issue also appears in the `Sort dimensions by name or value` button.

This makes the dashboard very hard to use
![2022-12-09_10-21](https://user-images.githubusercontent.com/3504393/206668557-02cbe508-30f3-4d45-bf83-a77222401d3a.png)

**Comment by dimko** [comment]
Increasing priority to high due to the @nil0x42 comment. Thanks

**Comment by cakrit** [comment]
It's getting published today. There was a regression issue that delayed it.

**Comment by hugovalente-pm** [comment]
@nil0x42 this should have gone with a release just done few moments ago.
please let us know if you still find any issue (hopefully not)
