### ISSUE TITLE
[Bug]: filtering not working on anomalies tab

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#688]
### Bug description

filters do not work on anomalies tab. they do not get reflected in the charts

https://user-images.githubusercontent.com/2178292/207582549-d51d1318-9599-465e-a7ed-535cdc3ad941.mp4

### Expected behavior

as i select and unselect nodes in the filter while on anomalies tab that charts update to reflect it

### Steps to reproduce

1. filter for some nodes
2. open anomalies tab
3. try change filters in RHS filter box
4. see that charts dont update to reflect it

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this seems to be fixed @andrewm4894 , could you check again?

**Comment by hugovalente-pm** [comment]
this is fixed
