### ISSUE TITLE
[Bug]: MC seems to be getting triggered when going from anomalies tab back to overview

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#689]
### Bug description

It seems like `metrics_correlation=true` is being set by something for some reason when i use the anomalies tab and go back to the overview tab.

https://user-images.githubusercontent.com/2178292/207616540-9b152b65-507c-4bdd-8f5b-d72cc63cc526.mp4

### Expected behavior

phantom metric correlations do not occur.

### Steps to reproduce

1. use anomalies tab
2. highlight area on anomalies tab
3. go back to overview tab
4. you will see MC results for some reason.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@novykh not sure what could have caused this just pinging for fyi

**Comment by hugovalente-pm** [comment]
this has been fixed
