### ISSUE TITLE
[BUG] Cannot save chart in Dashboard

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#69]
**Describe the bug**	
See: https://www.youtube.com/watch?v=u1t57t8tg-Q
The user could not save the chart. Unsure if the issue is limited to 3rd party collector charts

**To Reproduce**	
Steps to reproduce the behavior:	See video 

**Expected behavior**	
Being able to add a chart in a dashboard and save

**Comment by OdysLam** [comment]
Resolved as informed by the user in that youtube video
