### ISSUE TITLE
[Bug]: AA shows ML=OFF when it is in fact ON.

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#692]
### Bug description

https://user-images.githubusercontent.com/2178292/208430049-000b58f3-666c-40ce-9f87-d02d795583db.mp4

If i look at ml_info for that node i see valid data:

![image](https://user-images.githubusercontent.com/2178292/208430269-78a4b20b-fd7b-4148-a26f-5a9faf582580.png)

Likewise at the info endpoint:

![image](https://user-images.githubusercontent.com/2178292/208430379-6ce6c100-e14e-4ea5-ad49-415de6d3e9c0.png)

So seems like cloud is flagging it as OFF maybe. 

Indeed seems like ml_info cloud endpoint only returns the 2 nodes instead of the expected 3. 

![image](https://user-images.githubusercontent.com/2178292/208430626-9ccbb728-25de-41f1-8a70-0b7218ce2f47.png)

### Expected behavior

All 3 nodes should have ML=ON

### Steps to reproduce

1. go [here](https://app.netdata.cloud/spaces/ml-demo-space/rooms/all-nodes/anomalies#metrics_correlation=false&after=1671450314000&before=1671452703000&utc=Europe%2FLondon&offset=%2B0&timezoneName=Edinburgh%2C%20London&modal=&modalTab=&6045dc92-0a0c-48d8-960c-d2e0f31aa95d--selectedNodeIds=8ca367d1-e410-4789-870b-8df0388e48e4%2C13b68eec-7700-4be8-abdd-a89f15f4bead%2C61092b71-6df3-4233-90b2-043a7a0b9472&modalParams=&highlight_after=1671451793000&highlight_before=1671451817000&6045dc92-0a0c-48d8-960c-d2e0f31aa95d-fn-selectedNodeIds=8ca367d1-e410-4789-870b-8df0388e48e4&6045dc92-0a0c-48d8-960c-d2e0f31aa95d-fn-selected=processes&6045dc92-0a0c-48d8-960c-d2e0f31aa95d-fn-isPolling=true&6045dc92-0a0c-48d8-960c-d2e0f31aa95d-fn-pollingInterval=2&6045dc92-0a0c-48d8-960c-d2e0f31aa95d-overview-chartName=menu_anomaly_detection_submenu_anomaly_rate&threshold=0.1&6045dc92-0a0c-48d8-960c-d2e0f31aa95d-anomalies-selectedNodeIds=8ca367d1-e410-4789-870b-8df0388e48e4%2C13b68eec-7700-4be8-abdd-a89f15f4bead%2C61092b71-6df3-4233-90b2-043a7a0b9472) in ml-demo space

### Desktop

Browser Version [e.g. 22]

**Comment by andrewm4894** [comment]
@juacker looks like this maybe could be on the cloud side potentially.

**Comment by juacker** [comment]
having a look @andrewm4894

**Comment by hugovalente-pm** [comment]
@juacker could FE be looking at the capabilities? I think we wanted to move to that information instead of the endpoint response

**Comment by juacker** [comment]
@hugovalente-pm, the scenario in this issue was the following:
- `Child` with ML=ON 
- `Parent` receiving data from `Child`, but with ML=OFF

At some point Child lost connection to the cloud and could not reconnect, due to the ACLK bug fixed some days ago (I cannot find the fix link now).

On the cloud, only Parent was connected, and due to the fact that parent had ML=OFF the cloud response was ML=OFF for the child node.

I'm not sure if FE should go to get capabilities (sorry I have no context about that conversations) but the current response on the `/nodes` endpoint was correct due to the explanations above.

I think @andrewm4894 can confirm, but updating the agents to the last version solved the problem.

**Comment by hugovalente-pm** [comment]
thanks for the explanation @juacker , about capabilities I may be confusing with something.
then this ticket can be closed, right?

**Comment by juacker** [comment]
It seems the agent has not been updated yet, it's still in the version affected by the ACLK bug:
![image](https://user-images.githubusercontent.com/2930882/209107640-2fbc4b8a-bee9-42cb-a110-663ca7efaf99.png)

So we still see ML=OFF in the cloud, as currently the agent is not directly connected:

![image](https://user-images.githubusercontent.com/2930882/209108020-e31b9bfb-871e-47d2-9170-0cb962b4b914.png)


I don't have a way to update the agent, so maybe we need to wait for @andrewm4894 until they can be updated.

**Comment by hugovalente-pm** [comment]
ok but I mean the action required is identified and no fixes are needed, what needs to happen is an agent upgrade?
of course we can leave this open until that is done just to confirm updating the agent version gets this fixed

**Comment by juacker** [comment]
> ok but I mean the action required is identified and no fixes are needed, what needs to happen is an agent upgrade?

yes, the agent upgrade should fix the issue. We can leave this open until the upgrade, or close it and reopen after if that didn't fix the issue, as you prefer.

**Comment by andrewm4894** [comment]
I have updated the all today and added nightly flag. I'll retest this again and close if all good.

**Comment by hugovalente-pm** [comment]
this is fixed
