### ISSUE TITLE
[Bug]: typing in dim filter on chart crashes app

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#695]
### Bug description

if i type in here: 

![image](https://user-images.githubusercontent.com/2178292/211008935-1565ddcb-d612-4f59-9498-92484bac9f90.png)

i get a crash:

![image](https://user-images.githubusercontent.com/2178292/211008977-ad09bece-da71-45fc-9afc-f23636b6b652.png)

https://user-images.githubusercontent.com/2178292/211008826-3afafd20-9db8-48df-8d75-ad8669b918d2.mp4

### Expected behavior

no crash and filter selection box as expected

### Steps to reproduce

1. above

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this seems to be the same issue as we had on this bug on search for chart instances https://github.com/netdata/netdata-cloud/issues/695

**Comment by burbuli8ra** [comment]
Release on [v4.2.2](https://github.com/netdata/cloud-frontend/releases/tag/4.2.2)
