### ISSUE TITLE
[Feat]: add tooltips to sidebar tabs/sections

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#698]
### Problem

They probably should be tooltips on these icons in the side bar 
![image](https://user-images.githubusercontent.com/2178292/211291871-695d06af-0785-4b46-bce3-aa0716dd2b86.png)

### Description

tooltips to make it obvious and clear to users what things in the app are supposed to be or do. 

### Importance

must have

### Value proposition

1. make it easier for users to understand and get familiar with the app.

**Comment by hugovalente-pm** [comment]
this is done
