### ISSUE TITLE
Agent user is signed-in but the Spaces and War Rooms are missing from the left bar and panel

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#7]
**Describe the bug**	
Agent user is signed-in but the Spaces and War Rooms are missing from the left bar and panel

**To Reproduce**	
Steps to reproduce the behavior:	Not always reproducible

**Expected behavior**	
The user is expected to see the left bar and panel populated with the available Spaces and War Rooms after being signed-in

**Screenshots**	
![no_spaces_left_panel](https://user-images.githubusercontent.com/19746055/99797656-f5aac980-2b2f-11eb-801a-1e2f4bc9a1cf.png)

**Comment by cakrit** [comment]
I've never noticed this happen @manos-saratsis. Has anyone observed it since November? If not, I suggest we close.
