### ISSUE TITLE
[BUG] After disabling disk usage for mount Cloud shows empty chart instead of hiding

### ISSUE THREAD

**Issue by ph33rtehgd** [netdata/netdata-cloud#70]
**Describe the bug**	
I want to show the disk usage on the Netdata Cloud nodes page for relevant mounts/paths. I added such a column, but I'm left with many /run/* mounts showing. I want to filter these out, so I've added the below to my netdata.conf file:
```
[plugin:proc:diskspace]
    exclude space metrics on paths = /run/* /dev/* /snap/* /boot/* /sys/*
    exclude space metrics on filesystems = *gvfs *gluster* *s3fs *ipfs *davfs2 *httpfs *sshfs *gdfs *moosefs fusectl autofs tmpfs
```

After doing this the data isn't captured for these mounts anymore, which is good, but the Netdata Cloud page now shows a bunch of empty graphs for these mounts, even after refreshing. I've attached a screenshot to show what I mean. When I look at the local netdata dashboard directly on the host I do not see these mounts that I've excluded.

**To Reproduce**	
1. Add mounts/paths to exclude from disk space stat collection
2. Restart netdata agent
3. Refresh netdata cloud dashboard

**Expected behavior**	
The mounts for which the data collection was disabled should not show any charts in the Netdata Cloud dashboard.

**Screenshots**	
![netdata_empty_charts](https://user-images.githubusercontent.com/13082261/110860065-4cc4dd80-828a-11eb-98fe-821adaab329b.png)

**Error logs**	
HAR file attached.
[app.netdata.cloud.har.zip](https://github.com/netdata/netdata-cloud/files/6126181/app.netdata.cloud.har.zip)

**Desktop (please complete the following information):**	
 - OS: Windows
 - Browser: Chrome	
 - Version: 88

**Additional context**

**Comment by cakrit** [comment]
This is a known bug, we're not correctly updating the list of charts based on what's happening on the agent side. 
We have the option for a workaround (query the agent directly), until we properly implement the new design we're finalizing, which will take a couple of months. So the question gents is if utilizing the ADC in the meantime is a valid option for this view.

**Comment by dimko** [comment]
This has been fixed as stale charts are now synced to cloud. Closing
