### ISSUE TITLE
[Bug]: unable to scroll in RHS bar for node info

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#703]
### Bug description

i can no longer scroll down in here 
![image](https://user-images.githubusercontent.com/2178292/212893955-425c4591-a4c2-4252-8a15-017273cefa8b.png)

https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1673954500190609

### Expected behavior

i should be able to scroll up and down

### Steps to reproduce

1. go [here](https://app.netdata.cloud/spaces/netdata-demo/rooms/all-nodes/nodes/e455a2fe-1c3a-4d41-8185-be66e131064f#metrics_correlation=false&after=-900&before=0&utc=Europe%2FLondon&offset=%2B0&timezoneName=Edinburgh%2C%20London&modal=&modalTab=&d8a4e0c5-7c79-4145-900e-83a9f06fcb6a-overview-chartName=menu_system&d8a4e0c5-7c79-4145-900e-83a9f06fcb6a-e455a2fe-1c3a-4d41-8185-be66e131064f-chartName=menu_system) and try scroll down in node info side bar 

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
I noticed that this behaviour is specific to the Single Node tab where the vertical scrollbar isn't displayed (doesn't happen on the node tab) @christophidesp is this something you can help?

https://user-images.githubusercontent.com/82235632/235118641-2c87fbfd-d981-4e64-9e58-e8dba05d0c03.mp4

**Comment by hugovalente-pm** [comment]
this is fixed
