### ISSUE TITLE
[Bug]: RHS menu bar is now excessively wide

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#704]
### Bug description

This is too wide and not adjustable by the user

It used to be not as wide - now its taking too much space on my screen

![image](https://user-images.githubusercontent.com/2178292/212894591-4c3e73bb-0eac-4aa1-9532-a53b506e561c.png)

### Expected behavior

it is not as wide as this or i can just drag it to resize and have netdata cloud remember that. 

### Steps to reproduce

1.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
just linking that for the resize there is a feature request open to track it https://github.com/netdata/netdata-cloud/issues/699

**Comment by andrewm4894** [comment]
oh haha - i opened that too - ill close this
