### ISSUE TITLE
[Bug]: Wrong unit of measurement for Postgres - DB Size gauge

### ISSUE THREAD

**Issue by cuu508** [netdata/netdata-cloud#707]
### Bug description

In app.netdata.cloud, I'm looking at the "Postgres" section of a database server. At the top of the section are 5 gauges, one of them is "DB Size". The unit of measurement appears to be wrong:

![image](https://user-images.githubusercontent.com/661859/213114197-810de3ea-552f-403d-9d1b-c70b72532e22.png)

It shows "PiB", in reality the database size is ~15 GiB.

Further down, in the "Size" section, the unit of measurement is shown correctly:

![image](https://user-images.githubusercontent.com/661859/213114481-cc29d901-979f-401a-87ec-7e671c654ff8.png)

### Expected behavior

It should show "GiB" as the unit of measurement in the gauge.

### Steps to reproduce

1. Set up Postgres monitoring using the go.d.plugin
2. Inspect the "Postgres" section of a monitored database host in app.netdata.cloud 

### Desktop

OS: Ubuntu
Firefox 109

**Comment by hugovalente-pm** [comment]
this has been fixed
