### ISSUE TITLE
[Feat]: add utm links to readme and infographic to better understand how users arriving to docs and website

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#709]
### Problem

Creating an issue for myself to add some utm links into the README of netdata/netdata and on the infographic to try understand what portion of users arriving at learn or website might be coming from these links in GitHub. 

Will inform how we evolve the readme and infographic. 

### Description

.

### Importance

nice to have

### Value proposition

1.

**Comment by andrewm4894** [comment]
@hugovalente-pm apologies i cant assign myself to this - can you assign me? Just making issue here so i don't forget about it.

**Comment by hugovalente-pm** [comment]
strange, just did it

**Comment by andrewm4894** [comment]
I think is related to GH permissions. I might just ask to be added to the product GH team as that would sort it.

**Comment by hugovalente-pm** [comment]
not done and not seen as an issue/prio
