### ISSUE TITLE
[Bug]: Metric Correlations filters not being applied

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#710]
### Bug description

following report from a user here: https://community.netdata.cloud/t/metric-correlation-broken/3781/2

it seems like the filters returned by MC are not being applied. 

### Expected behavior

charts and dims should be filtered like they used to be.

### Steps to reproduce

1. use MC
2. observe that filters are not applied when you get results.

### Screenshots

https://user-images.githubusercontent.com/2178292/214040412-c84b5901-95e6-4646-8d9e-4f08ca60e0bf.mp4

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this seems to only happen on Single Node view tab, if you apply it on Overview even with just one node selected it works
@netdata/cloud-fe not sure the above finding helps.

**WORKAROUND** for users wanting to use this for one node please filter by it on Overview and run MC there

**Comment by jacekkolasa** [comment]
Those 2 bugs were actually different things (not running correlations in node-view, not running correlations when selecting nodes from right-hand filter in room-overview), so @hugovalente-pm your finding helped a lot :)
I prepared fixes, it's landing in testing ATM

**Comment by andrewm4894** [comment]
Testing looking good to me, thanks!

**Comment by hugovalente-pm** [comment]
this is released
