### ISSUE TITLE
[Bug]: Not enough space for text labels below graphs

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata-cloud#711]
### Bug description

Not enough space for text labels to display clearly below graph and charts in Netdata Cloud nodes.

![image](https://user-images.githubusercontent.com/13329789/213707799-7ca1fe46-a8d5-4c27-b705-9b257f1d98ee.png)

### Expected behavior

To be able to see the labels clearly in order to read and understand them without confusion.

### Steps to reproduce

1. Install Netdata and access the Netdata Cloud
2. View a node with Firefox browser
3. Look under any and all of the graphical charts, the top of the text is cut-off.
...

### Installation method

kickstart.sh

### System info

```shell
uname -a; grep -HvE "^#|URL" /etc/*release
Linux vpsxxx.example.com 3.10.0-1160.53.1.vz7.185.3 netdata/netdata#1 SMP Tue Jan 25 12:49:12 MSK 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
# $(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
Version: netdata v1.37.0-167-gc3a7af127
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by hugovalente-pm** [comment]
thanks for reporting this @TheOldMan2000 , this in fact seems an issue with the horizontal scroll bar style on Firefox. we will check what is happening there

please see below an example on Chrome
![image](https://user-images.githubusercontent.com/82235632/214523991-e17f0d09-ef87-4b76-9a95-0379d8cd2ba4.png)

**Comment by hugovalente-pm** [comment]
also @TheOldMan2000 can you also share the browser version:

was testing this on Firefox and don't get it 
![image](https://user-images.githubusercontent.com/82235632/214525245-aada4835-7d9c-4893-886c-85a53632fe92.png)

mine is:
* OS: Ubuntu 20.04.5 LTS (Focal Fossa)
* Browser: Firefox
* Browser Version [e.g. 22]; 109.0 (64-bit)

**Comment by TheOldMan2000** [comment]
Screenshots from Chrome Version 109.0.5414.120 (Official Build) (64-bit)on same PC:

![image](https://user-images.githubusercontent.com/13329789/214599056-8f7c3a3c-296d-4918-a9c0-bd74f39e3733.png)

![image](https://user-images.githubusercontent.com/13329789/214599436-280fb7cf-e5dd-4a4b-a109-07e051b8c7af.png)

**Comment by TheOldMan2000** [comment]
Going back to Firefox, when there is enough screen size real estate (4K monitor), its fine when the scroll bars aren't needed:

![image](https://user-images.githubusercontent.com/13329789/214600647-fb8d8abb-a104-4d64-89d3-a60762ac89db.png)

**Comment by hugovalente-pm** [comment]
thank you for the added details, these will be helpful to try to find a fix

**Comment by hugovalente-pm** [comment]
@TheOldMan2000 with the new release of charts this seems to have improved, could you check from your prespecitve?

**Comment by hugovalente-pm** [comment]
closing this, if you still experience this issue let us know
