### ISSUE TITLE
[Bug]: No war rooms visible in Netdata Demo Space when user is not signed in

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#714]
### Bug description

Looks like the demo space is broken - if you are signed out, none of the war rooms are visible. (They are visible when signed in).

![image](https://user-images.githubusercontent.com/24860547/214868530-810c7e46-09f5-436d-92f2-a57789cbd7d7.png)

### Expected behavior

Demo space rooms should always be visible - irrespective of whether user is signed in or not. 

### Steps to reproduce

1. Just sign out and visit https://app.netdata.cloud/spaces/netdata-demo/

### Screenshots

See above

### Error Logs

N/A

### Desktop

Google Chrome, Windows

**Comment by jacekkolasa** [comment]
this has been released
