### ISSUE TITLE
[Feat]: some initial functions feedback from dogfooding

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#719]
### Problem

it would be nice to have tooltips for all of these - eg i dont know what RSS is?
![image](https://user-images.githubusercontent.com/2178292/217279180-1ca649e9-905b-41d0-8448-e7a4c13cd8b8.png)

i think it could be useful if category and user linked my to the relevant chart as best we can:
![image](https://user-images.githubusercontent.com/2178292/217279487-4fe25032-1662-4f8b-9794-c9e8a4eabe8d.png)

eg if i click "stress" then show me something like this - a dynamic custom dashboard of sorts that just showed me the main apps charts for the stress dim would be almost magical if done nicely - eg maybe even some sort of pop up modal as opposed to taking me away into another tab, but even that would still be good i think. 
![image](https://user-images.githubusercontent.com/2178292/217279845-d641c0ca-122c-4ca0-ab2a-a63e00255efd.png)

### Description

.

### Importance

nice to have

### Value proposition

1.

**Comment by hugovalente-pm** [comment]
easiest thing is done with the tooltips
![image](https://github.com/netdata/netdata-cloud/assets/82235632/50f60f6c-bf2e-4095-b3d3-8b5321cd559c)

the navigation to charts isn't considered since some metrics/stats may not relate directly to a chart
