### ISSUE TITLE
[Bug]: links in my slack notifications dont seem to work

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#720]
### Bug description

When i click on an alert link from slack like this:

![image](https://user-images.githubusercontent.com/2178292/217285716-b42eb066-7b66-4785-9aad-4cfeb906f500.png)

I end up seeing this: 

![image](https://user-images.githubusercontent.com/2178292/217285823-bc6e5ea8-adbc-4c72-9079-47f20ee508ad.png)

![image](https://user-images.githubusercontent.com/2178292/217285946-1d66370e-2723-458c-b9cc-de50bb4da551.png)

### Expected behavior

I'm pretty sure there is data here so i expect to see the chart with data

### Steps to reproduce

1. click a link on an alert in a slack channel

### Desktop

Browser Version [e.g. 22]

**Comment by andrewm4894** [comment]
I seem to be able to manually get to what i was expecting to see:

![image](https://user-images.githubusercontent.com/2178292/217286967-57b55c12-bb56-446c-b839-6ff7c8040722.png)

**Comment by hugovalente-pm** [comment]
@andrewm4894 can you re-check? was trying this out and seems to be working

**Comment by andrewm4894** [comment]
yep - looking like its fixed now somehow - will close this.
