### ISSUE TITLE
[Feat]: ability to regenerate claim token

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#722]
### Problem

it could be useful to be able to regenerate my claim token if i want to expire the existing one for any reason

### Description

ability to rotate or just drop and recreate a new claim token in a netdata space

### Importance

nice to have

### Value proposition

1. ability to thrash claim token if needed without having to delete and create new spaces etc

**Comment by luisj1983** [comment]
Definitely a requirement. What if the token is compromised:
- silly permissions
- employee leaves the business
- team moves Prod nodes to new totally new Prod instance but Dev keep hammering agents into the old generic instance.

**Comment by sboulanger29** [comment]
+1 on the defo requirement. Someone inadvertently added a clear text claim token in an ansible playbook, and our Security Team raised a security concern, and now asking to rotate the claim token. My understanding is that it is still not possible as of today. 

Unless we find an alternate solution, we might be forced to abandon Netdata as a monitoring solution. NB: we are currently using the Business plan.

**Comment by hugovalente-pm** [comment]
this issue was recently discussed internally and we will change the approach we manage these claim tokens and provide a means on the UI for user to be able to recycle it themselves.

**Comment by hugovalente-pm** [comment]
this is now available next to the connect node commands on the UI, e.g.
![image](https://github.com/netdata/netdata-cloud/assets/82235632/cc0eeab8-0134-4bba-a03d-4881da5f24e8)

**Comment by sboulanger29** [comment]
Awesome support and follow-up from the Netdata Team!!! Thanks so much for resolving this issue!
