### ISSUE TITLE
[Bug]: ViewAlert URL truncated in Outlook App - doesn't allow to bypass safelinks

### ISSUE THREAD

**Issue by cavemancanada** [netdata/netdata-cloud#723]
### Bug description

Similar to bug #515 - if we get a alert from netdata, the "view alert" button / URL is truncated in the Outlook for desktop app, thereby invalidating the clickthrough allow we have set for our safelinks policy. If i click it in Outlook for web - no issues. 

### Expected behavior

click "view alert" - have it go through to the netdata portal.

### Steps to reproduce

1.safelinks / url link of the "view alert" in Outlook APP
https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fu8647778.ct.sendgrid.net%2Fls%2Fclick%3Fupn%3DvWWQSJ82NaXwl1rg387b639Q777QuIfiMRznsJ3-2BNzwVhzkhVAgHpKjE-2FhemUdVi-2Bp-2FASBbwu00Tb8tRLAmKAANks-2BJ6Ru2fBqSFKSeZHmfi88ttWOpX6DewCGa4pXF4OB14oQHH6xOCTgmcRt1Awii6clYmykb8ie01LyIuT88l4ju-2BW0oeQBQtIHNskKnfwkKMZW9FinCO34bxAeyEPkjxD326IiT2ddSorLmw3CjOT313F2hzHJEK0b5FfsrDHM_5_BzL71Iq2G9-2F1EmNzIPxI-2BzaM9RFwHnA1f1RKRoNz7JukcQEIcl4Cr2B-2BaLmnnyMbOD-2BT5-2BOmnC3jzL183hNCPyfNw9UTBbACPfOV3hxAVPIX9Rpo3FR4M4-2BMC2-2FGBv4KaC8gfD-2B9dnoV0PAh35GCrkNhkGuoyvaX-2B5FSlyLHtmdGwFjUCSckKsCj34g55LsHuk7HG5Z27qWLClDRNQPjvj6wgJo3Cy1d2KStVDibd9sTAsx5BF9-2FNRk-2BBZr35JIA5TlmXDDt0pjwyy0KG52JgUCJswwKs8ZfdGgm0B17m00LzvpuX078mBG776glnr9EIhsuqIRB6kHjNDjq3KlIc34VSoMK8Sr0KuRRwkQ2eg57KR6-2FBwzyEumcMZoiWMF0UnmREds7Ui-2FQHHMoAP-2FUpsy6LckMmpCXwhNtXYKKoI-2FrOA4HH9GzO3e8SbhOC-2FbAQuhRF6P1Z-2FjOmpriioV7GnqeryFyzffrSsOx4o2KOPLrPGwKgAuGZq5D0zHLUaDOcniIwWF4-2Bdx8A8SkJHZFEwHsKAaL9MpOJQrPtV8K-2FaEI9ATuDVDRgNISFJWAGfn-2Fu1sRrCrua5K8jc8lNL3aS-2FHDcqRO-2BF18K7Q4jr2n-2FyvS0zuZ0IM0lDlWvvhDZ2A674oylVMcH2baG9RBKlvY8j2-2Ft97u0VYF83Tfto007m5bPMo15wvrkx4z0vLGKFXcptm-2FiDQaTxWysb-2Fy6kATegc2u5XlFOQc5Zd4etp8UF85aDo9b8Ly9ZXW-2BPXr6NxnWFDf5s9rxB-2B-2BHQi-2FRa1RfZMjCsTSMLxwXaMPuf-2FLk84gbGQoGKleNLbH-2BBkQXqA6KmpWvh4kdhgXZ6ce5FslC2gtFeCJX06U9-2BddABWLmmHZHBdYakbgu-2FvbEAKcMOLLMFgsWGbfbt-2BwcDqNN50gO-2BuVf7aTJTavFJ8xwnDC04HEFxW-2FnKUJ7OmQQ05j8DPRxo4k4ajetMl3o4gseY9CulqSU29u-2BmyM77H6Zx3kS1i3Ks6i2zJEInRtmemb9f3tvNOO3b6FPwVc6jXoAg59P5FbFy6B34DSvmkL0oUHW9XY81srWH7LivXjf-2Fzzm-2F70yjPYJ63VX7YNLJcKSGnHn9FfDtnCYoXm5disS97HWTAYjPcGHPvR2oDXyv5m6BsMno8JYeaLXxJfEidU-2BQYFLLPIdffQa2zJB-2F7CkybhmPZTugAt6o-2FqyAeDbMeLOvzzjhuVmKrE-2FsVMIPXJ0dJKz-2Bensk27WmtS4Q6fW6VIhdkfZQ7DtbJ-2FdOsgEyB6bwRR4leA48yqxNh-2B0eZ7ICGB2UZalbwfPYbnt4chAV-2BYvnH-2FCQf-2FuRMItdwmdobpBhKqX8I803kR-2FmcI90TaZJByKeUb1afSikDPvjgvNR-2B0BV-2BtYSOi3VBlwI3P5U0uMQIf8u9p7nkITh670KecKBzdMB2LkQxoWY8pTAS3HUdpmBj5f05JeFA678lajUlIz7MPasFltzxOXV4a8MHB4LzrqFIRrB8Uh6CzGDz3P27MESFS6ecFBfYRkQKSFTyFyaeThiGmW6vPaqUg7OMz6scuYCpI5dGKMOR9EyJUVPVXEsZrDE9j-2BM9nKZz

safelinks / url link of the "view alert" in Outlook for Web - no truncation - works fine:

https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fu8647778.ct.sendgrid.net%2Fls%2Fclick%3Fupn%3DvWWQSJ82NaXwl1rg387b639Q777QuIfiMRznsJ3-2BNzwVhzkhVAgHpKjE-2FhemUdVi-2Bp-2FASBbwu00Tb8tRLAmKAANks-2BJ6Ru2fBqSFKSeZHmfi88ttWOpX6DewCGa4pXF4OB14oQHH6xOCTgmcRt1Awii6clYmykb8ie01LyIuT88l4ju-2BW0oeQBQtIHNskKnfwkKMZW9FinCO34bxAeyEPkjxD326IiT2ddSorLmw3CjOT313F2hzHJEK0b5FfsrDHM_5_BzL71Iq2G9-2F1EmNzIPxI-2BzaM9RFwHnA1f1RKRoNz7JukcQEIcl4Cr2B-2BaLmnnyMbOD-2BT5-2BOmnC3jzL183hNCPyfNw9UTBbACPfOV3hxAVPIX9Rpo3FR4M4-2BMC2-2FGBv4KaC8gfD-2B9dnoV0PAh35GCrkNhkGuoyvaX-2B5FSlyLHtmdGwFjUCSckKsCj34g55LsHuk7HG5Z27qWLClDRNQPjvj6wgJo3Cy1d2KStVDibd9sTAsx5BF9-2FNRk-2BBZr35JIA5TlmXDDt0pjwyy0KG52JgUCJswwKs8ZfdGgm0B17m00LzvpuX078mBG776glnr9EIhsuqIRB6kHjNDjq3KlIc34VSoMK8Sr0KuRRwkQ2eg57KR6-2FBwzyEumcMZoiWMF0UnmREds7Ui-2FQHHMoAP-2FUpsy6LckMmpCXwhNtXYKKoI-2FrOA4HH9GzO3e8SbhOC-2FbAQuhRF6P1Z-2FjOmpriioV7GnqeryFyzffrSsOx4o2KOPLrPGwKgAuGZq5D0zHLUaDOcniIwWF4-2Bdx8A8SkJHZFEwHsKAaL9MpOJQrPtV8K-2FaEI9ATuDVDRgNISFJWAGfn-2Fu1sRrCrua5K8jc8lNL3aS-2FHDcqRO-2BF18K7Q4jr2n-2FyvS0zuZ0IM0lDlWvvhDZ2A674oylVMcH2baG9RBKlvY8j2-2Ft97u0VYF83Tfto007m5bPMo15wvrkx4z0vLGKFXcptm-2FiDQaTxWysb-2Fy6kATegc2u5XlFOQc5Zd4etp8UF85aDo9b8Ly9ZXW-2BPXr6NxnWFDf5s9rxB-2B-2BHQi-2FRa1RfZMjCsTSMLxwXaMPuf-2FLk84gbGQoGKleNLbH-2BBkQXqA6KmpWvh4kdhgXZ6ce5FslC2gtFeCJX06U9-2BddABWLmmHZHBdYakbgu-2FvbEAKcMOLLMFgsWGbfbt-2BwcDqNN50gO-2BuVf7aTJTavFJ8xwnDC04HEFxW-2FnKUJ7OmQQ05j8DPRxo4k4ajetMl3o4gseY9CulqSU29u-2BmyM77H6Zx3kS1i3Ks6i2zJEInRtmemb9f3tvNOO3b6FPwVc6jXoAg59P5FbFy6B34DSvmkL0oUHW9XY81srWH7LivXjf-2Fzzm-2F70yjPYJ63VX7YNLJcKSGnHn9FfDtnCYoXm5disS97HWTAYjPcGHPvR2oDXyv5m6BsMno8JYeaLXxJfEidU-2BQYFLLPIdffQa2zJB-2F7CkybhmPZTugAt6o-2FqyAeDbMeLOvzzjhuVmKrE-2FsVMIPXJ0dJKz-2Bensk27WmtS4Q6fW6VIhdkfZQ7DtbJ-2FdOsgEyB6bwRR4leA48yqxNh-2B0eZ7ICGB2UZalbwfPYbnt4chAV-2BYvnH-2FCQf-2FuRMItdwmdobpBhKqX8I803kR-2FmcI90TaZJByKeUb1afSikDPvjgvNR-2B0BV-2BtYSOi3VBlwI3P5U0uMQIf8u9p7nkITh670KecKBzdMB2LkQxoWY8pTAS3HUdpmBj5f05JeFA678lajUlIz7MPasFltzxOXV4a8MHB4LzrqFIRrB8Uh6CzGDz3P27MESFS6ecFBfYRkQKSFTyFyaeThiGmW6vPaqUg7OMz6scuYCpI5dGKMOR9EyJUVPVXEsZrDE9j-2BM9nKZzFg7QDE-2FJ-2BIvubUk1M6AzOLRiaOOvuqhGGG9eQow3HVXwcTwdwvgGXYHcVwxj0qzKE85QJsdGyfQAg3nr1gPtK20YMsgBxm19Yh5z0V-2FVAnn7Q6JdINVby504qDjxCp8sZ7cNaKX6qO9WpCZOTyy2EjEcUIo-2FBb23MwOTfenRxgxfx-2BRZiGlUJKu1V26vNXSYOpMXudQeNmNSUdtPP1aNJ26RcVAo8pUg0bupZjStQg0FrLsxjt2eNNMeYpHZvt4wtugG-2FtFhAuGDu3xuYG-2BieqOQzADJXtMRyI5La4ng14uUrFNvyhQmtTMjMtZe-2FM-2F8pJv-2FYMqXqkLtkAoDuObdonqzRV-2FMpZgvpU8mSCsFSakUwKga7UjT0KmTWPf13vl7gThsYHBe3SNljH6cQCKePMsZxAKft0A5f9jOrVwh1VAxk1SdpV5Ykx65T7ms8rIEy6RJdfO55Wayc64k79q4KYeoN2ZVRrXBTR3YXcPIXq7kLvRn0IuSFUQRupcXrHNk6x4NEhFxQ&data=05%7C01%7Cmartin.salovsky%40irisenergy.co%7Cebafc9255ecd49d2a1af08db0a0f5463%7C240ceff4b1714eb5bd9eeb62dd94fcf0%7C0%7C0%7C638114833178763187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BCykogoRfnIh5vaOPbh9gEehcpoTswgWtCGg0vxCOFs%3D&reserved=0

### Desktop

Browser Version [e.g. 22]
Windows 10 64 bit, enterprise, Microsoft Edge
Version 109.0.1518.78 (Official build) (64-bit)

Outlook version 2212 (build 15928.20216 click to run)

**Comment by hugovalente-pm** [comment]
@cavemancanada thanks for raising this to us.
@iorvd I know you worked on the previous bug where we had this issue, could the same solution be applied here?

**Comment by iorvd** [comment]
@hugovalente-pm the situation is slightly different here. We encode the direct link to an alert in a room, which is `https://app.netdata.cloud/spaces/data-collection/rooms/all-nodes/alerts/system.load.load_average_15:::10749c78-10e1-4cc6-b95a-4aa3da3375c3?chart=system.load&amp;alarm=load_average_15` for this case. I don't think there is a fast way for us to reduce the size of the link without making a sacrifice of something.

**Comment by elrond1999** [comment]
How come this short link https://app.netdata.cloud/spaces/data-collection/rooms/all-nodes/alerts/system.load.load_average_15:::10749c78-10e1-4cc6-b95a-4aa3da3375c3?chart=system.load&amp;alarm=load_average_15 blows up to the huge encoded link? Why not just put the short link directly in the email?

**Comment by hugovalente-pm** [comment]
@elrond1999 we had thought about putting the direct URL but we decided to not do it. you can find why on this answer on this forum post https://community.netdata.cloud/t/wrong-link-page-received-when-trying-to-verify-my-email/3132/13

we need sendgrid's encoded URL because of the analytics we get out of it

**Comment by elrond1999** [comment]
That is a lot of bytes added to the url just for some analytics. Seems
excessive.

tor. 23. mar. 2023 kl. 11:55 skrev Hugo Valente ***@***.***>:

**Comment by hugovalente-pm** [comment]
The issue here is the long links generated by Sendgrid's wrapping for tracking purposes
This issue will persist for users with older (mostly microsoft) email clients and if anyone is still using some old IE versions.

this was revised internally and we won't be doing anything for now - the workaround is opening the e-mail on a webapp version of outlook
