### ISSUE TITLE
[Bug]: Can't run functions on Node and get ErrForbidden

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#725]
### Bug description

As `Member` a user is not able to run the functions on a given node and gets a screen with just **ErrForbidden**
Note: The node in question is on `v1.37.0-260-gb7ac4a6d8`

![image](https://user-images.githubusercontent.com/82235632/218556205-6ff39eb3-9f9c-4aed-9e53-79f54a88f860.png)

### Expected behavior

If the function can't run on a Node a better error screen/message should be displayed to the user

### Steps to reproduce

1. Trigger a Function call for a node on v1.37.0-260-gb7ac4a6d8
2. The user is a `Member` on a space

### Error Logs

```
{errorMsgKey: "ErrForbidden", errorMessage: "Forbidden", errorCode: "cEYegL7Op1-296871020"}
```

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
User has updated the node to the most recent version and error still persists

**Comment by juacker** [comment]
I'm not able to reproduce claiming one docker agent with a member account, @hugovalente-pm do you have any additional info for this user? (space_id, account_id, etc)

**Comment by hugovalente-pm** [comment]
thanks @juacker , this is from this discord thread https://discord.com/channels/847502280503590932/1074763025518698496
shared some details in PM

**Comment by juacker** [comment]
We had an issue affecting node authorization. The fix is released and the user should be able to access functions. 

** I was able to test it for this user using impersonation.

**Comment by lokerhp** [comment]
Will test it out wheb i'll get home.

Did you just impersonate me? 🤣🙃😅🤩 cool

Thanks for the fix!

**Comment by hugovalente-pm** [comment]
will close this and open one on FE for improving this error screen if it comes for any reason https://github.com/netdata/netdata-cloud/issues/735
