### ISSUE TITLE
Nodes view not rendered correctly in Safari 

### ISSUE THREAD

**Issue by scubashan** [netdata/netdata-cloud#73]
**Describe the bug**	
The Nodes view not rendered correctly in Safari. This renders correctly in Chrome. 
**To Reproduce**	
View nodes tab in Safari 

**Expected behavior**	
Be able to see the nodes	

**Screenshots**	
<img width="681" alt="Screen Shot 2021-03-22 at 8 01 47 am" src="https://user-images.githubusercontent.com/2850123/111920815-2eaa7900-8ae5-11eb-90c2-39735444d2f2.png">

**Error logs**	

**Desktop (please complete the following information):**	
 - OS: Mac OS 11.1
 - Browser Safari 	
 - Version 14.0.2 (16610.3.7.1.9)

**Additional context**

**Comment by scubashan** [comment]
This is still happening, has the fix been pushed ?

**Comment by novykh** [comment]
> This is still happening, has the fix been pushed ?

Will be deployed later today. Thank you
