### ISSUE TITLE
[Bug]: After highlighting area on anomalies tab when i go back to overview tab, it runs a MC for some reason

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#731]
### Bug description

When i go to the anomalies tab and highlight an areas, when i go back to overview tab it seems to have done a phantom metric correlations for some reason. 

### Expected behavior

It does not do this.

### Steps to reproduce

1. open overview tab
2. open anomalies tab
3. highlight an areas
4. get results
5. navigate back to overview tab
6. MC results will be there for some reason

### Screenshots

https://user-images.githubusercontent.com/2178292/220325491-05cd0079-c8e6-4706-99db-13ee3ce5a503.mp4

### Desktop

Browser Version [e.g. 22]

**Comment by andrewm4894** [comment]
@hugovalente-pm can we try see about this bug at some stage next week maybe?

**Comment by hugovalente-pm** [comment]
will try to push for this to be fixed, thanks for the ping @andrewm4894

**Comment by jacekkolasa** [comment]
@andrewm4894 fix is on production, can you please check if the experience is now better?

**Comment by andrewm4894** [comment]
Cool, I lll retest on my end to make double sure. Thanks!
