### ISSUE TITLE
[Bug]: Billing usage chart shouldn't display the today's daily/period count figures

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#732]
### Bug description

The Netdata Usage chart is displaying data up-to today, this isn't accurate since we don't have values calculated for the current day (last day is the previous) day.
We can't display daily or period counts as 0 (zero) value

### Expected behavior

Don't display today's value or display it to indicate it is not yet calculated (preferable the first).
This could mean to not allowing the user to select on the datetime picker today's date.

### Steps to reproduce

1. Go to Space settings under Plan & Billing
2. Check the Netdata Usage chart that it shows today's counts as zero

### Screenshots

![image](https://user-images.githubusercontent.com/82235632/220631053-0751322f-be62-4fd4-a034-510bd260a48a.png)

### Desktop

Browser Version [e.g. 22]

**Comment by novykh** [comment]
Removed on the frontend side the ability to select `today`'s date.

**Comment by vkuznecovas** [comment]
BE fixes have also been rolled out, closing this.
