### ISSUE TITLE
[Bug]: Submitting an invalid email in billing info gives a 500 error

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#734]
### Bug description

There is no frontend verification for email in the billing email input field. Submit button is enabled even though the email isn't valid.

When user submits the order, backend gives back a 500 error, but it's not communicated to the user what exactly failed.

### Expected behavior

1. Give a non 5XX status code when email is invalid - 422
2. Not allow to submit the order if email is invalid by disabling the button
3. Get an error message what failed, why it failed and which field provided in the request payload is invalid

### Steps to reproduce

1. Navigate to Billing tab in space management modal
2. Click to upgrade a plan from community to pro/business
3. Input an invalid email in the billing email field e.g error@email.comerror@email.com

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/220872060-fd51e4ce-cea3-430d-8487-698cf7beca68.png)

![image](https://user-images.githubusercontent.com/19268853/220872101-ed9bc6fe-d2a9-440b-a18e-8a26d7f72249.png)

### Error Logs

> Request URL: https://app.netdata.cloud/api/v2/spaces/dff28746-14cb-41c4-8029-07de81119b36/billing/plan
> Request Method: PUT
> Status Code: 500 
> Remote Address: 44.196.50.41:443
> Referrer Policy: strict-origin-when-cross-origin

Response

> 
> {
>   "errorCode": "cEYegL7Op1-420816202",
>   "errorMsgKey": "ErrInternalServerError",
>   "errorMessage": "Internal Server Error"
> }

### Desktop

OS: Ubuntu
Browser Chrome
Browser Version 110

**Comment by hugovalente-pm** [comment]
@dimko is this FE? is BE sending a proper error?

**Comment by papazach** [comment]
Nope we're not performing any check in the be (only not empty), will create a PR for that.
We should probably apply a check in the fe as well btw.

**Comment by hugovalente-pm** [comment]
agreed, will add it to a list of improvements (small ones) for billing - big ones are to be tracked differently

**Comment by papazach** [comment]
<img width="1723" alt="Screenshot 2023-02-23 at 2 44 31 PM" src="https://user-images.githubusercontent.com/8328670/220909513-d3fe2eba-10d7-4b1e-94ae-e77ef4d57697.png">

After the be fix this is how it looks like. I think it looks good.
Wdyt @hugovalente-pm @dimko

**Comment by papazach** [comment]
This is deployed to all envs.

**Comment by hugovalente-pm** [comment]
lgtm, will track the validation of email on FE on another ticket as mentioned above.
for me this one can be closed, wdyt @dimko ?

**Comment by dimko** [comment]
@hugovalente-pm Hey, sorry for the delayed response. We can close it yes. Unless we decide that we need a validation on Frontend side to disable the button if mail is invalid like we do in the invitation modal, but this seems sufficient for now.
