### ISSUE TITLE
[Bug]: When there is an error on the BE running functions we need to display a better error screen

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#735]
### Bug description

When there is an error, like the one reported here https://github.com/netdata/netdata-cloud/issues/725, we need to display a better error screen

### Expected behavior

We should to a similar one like when we have no charts to display

### Steps to reproduce

1.

### Screenshots

![image](https://user-images.githubusercontent.com/82235632/220881674-37f80a45-bbfc-42bf-b08c-a26a8948160b.png)

### Desktop

Browser Version [e.g. 22]

**Comment by jacekkolasa** [comment]
@hugovalente-pm @christophidesp how about our common error screen?

![image](https://user-images.githubusercontent.com/5786722/223126064-b0941c76-722c-44e6-ae16-f2e2ec1eec0e.png)

**Comment by hugovalente-pm** [comment]
@jacekkolasa for the charts you mean this one below?
![image](https://user-images.githubusercontent.com/82235632/223127641-bd709ac7-e966-4d7f-bfc7-907d5e6f502b.png)

Between both I personally prefer the one you suggested because if a function fails to run and we throw some unexpected error scenario I don't think we can give any hints to the user to change anything from his side... we should be sure we capture such issues either BE metrics/logs or FE sentry (?)

cc/ @juacker since you worked on the BE issue pair to this

**Comment by hugovalente-pm** [comment]
sounds good @jacekkolasa

**Comment by hugovalente-pm** [comment]
this is released
