### ISSUE TITLE
[Bug]: Double click to resume playing in chart causes chart to get error

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#739]
### Bug description

Double clicking on a chart used to resume it if in paused mode. Now in some cases it doesn't and chart gets an error with 400 bad request as response for the /data request right after resuming through a double click. This doesn't happen when resuming from the datetime picker play/pause buttons

### Expected behavior

play when double clicking a paused chart with no errors

### Steps to reproduce

1. Claim an agent to netdata cloud
2. Navigate to overview or single node view
3. Double click inside a chart

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/221158336-486208b6-d7f8-4ca9-9f16-e9ae284d8985.png)

### Error Logs

Request:

> https://staging.netdata.cloud/api/v2/spaces/d7574e05-c430-4b7a-b92d-987b8f3372a4/rooms/08e4bee5-5725-4bd2-aa84-9b418be82b10/data
> Request Method: POST
> Status Code: 400 
> Remote Address: 18.211.119.195:443
> Referrer Policy: strict-origin-when-cross-origin

Response

> {errorMsgKey: "ErrBadRequest", errorMessage: "Bad Request", errorCode: "reJJ7y1qfx-034342"}

### Desktop

OS: Macos
Browser CHrome
Browser Version 110

**Comment by dimko** [comment]
@netdata/cloud-fe  This popped up in yesterday's regression, so seems to have broken in one of our latest releases while we had the tests disabled

**Comment by dimko** [comment]
Editing as the issue seems to be slightly different with much lower impact.

**Comment by novykh** [comment]
Double clicking seems to reset also the `after` attribute, passing `null` to the request.

**Comment by novykh** [comment]
Fixed on charts repo, will be included in one of the next release on cloud.

**Comment by hugovalente-pm** [comment]
closed as completed
