### ISSUE TITLE
[Bug]: Event filters is missing facets for alert status and event reason.

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata-cloud#740]
### Bug description

Even though the information is available, no facets are shown for the current status on alert events. Additionally, there should be a facet for the `event.reason` field, for those events that have them.

### Expected behavior

Show additional facets.

### Steps to reproduce

1. Go to the events tab.
2. Have a list of events that includes alert or agent disconnect events
3. Observe missing facets.

### Screenshots

![image](https://user-images.githubusercontent.com/116741/221180802-1893eb03-ca7c-41e6-a8be-2bb884a4b4a8.png)

**Comment by ralphm** [comment]
At the least the above PR should resolve the backend side of this issue. We also need to verify that the corresponding values are correctly mapped to the human readable display names.

**Comment by hugovalente-pm** [comment]
this is fixed with the above PR
