### ISSUE TITLE
[Bug]: Overlapping sidebars on any page in Firefox

### ISSUE THREAD

**Issue by Dim-P** [netdata/netdata-cloud#741]
### Bug description

When I try to reach for the right-hand side sidebar on any page on the cloud, a new "browser sidebar" appears on top of that, so I cannot select the one underneath. See attached screenshots that show the exact problem.

It looks as if the vertical height of the outer container does not exactly fit my window.

### Expected behavior

I would expect just the themed sidebar to show up.

### Steps to reproduce

1. Go on any page on Netdata Cloud using Firefox on Linux

### Screenshots

![Screenshot from 2023-02-23 19-16-08](https://user-images.githubusercontent.com/5953192/221187591-8c9dee2b-39e4-42db-b596-1401d7c17dc0.png)
![Screenshot from 2023-02-23 19-16-28](https://user-images.githubusercontent.com/5953192/221187593-6ca38210-7796-4db6-b952-a8346ec35b43.png)

### Desktop

OS: Fedora 37
Browser: Firefox
Browser Version: 110.0 (64-bit)

**Comment by hugovalente-pm** [comment]
another know issue with Firefox is this one https://github.com/netdata/netdata-cloud/issues/711
