### ISSUE TITLE
[Feat]: display number of children on a node in the nodes view

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#744]
### Problem

I would like to quickly see how many children are streaming to each parent node in the nodes view of NC. 

### Description

For each node that is a parent node i would like to see an indication of this in the nodes view and a count of the number of nodes streaming to that parent.

![image](https://user-images.githubusercontent.com/2178292/221558774-316e6df1-7b77-4b6a-8f1f-5e52d2c9b06b.png)

### Importance

really want

### Value proposition

1. make it much easier to quickly see which nodes are parents and how many children are streaming to them from the NC UI.

**Comment by hugovalente-pm** [comment]
should probably be accessible on the Info and with the work on Home tab we should be able to show this visualize - @shyamvalsan related to the comment I raised on the home tab ticket

**Comment by shyamvalsan** [comment]
@hugovalente-pm yes this will be handled in the home tab work, as well as in the updates to node inspector sidebar
