### ISSUE TITLE
[Feat]: Remove Nodes by ML from home tab

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#746]
### Problem

It adds almost zero value since ML is now enabled by default.

### Description

Remove this from home tab

![image](https://user-images.githubusercontent.com/24860547/222092123-161260a2-9503-4fd0-9f1c-b688a04752a3.png)

### Importance

really want

### Value proposition

1. Remove dead space from home tab

**Comment by hugovalente-pm** [comment]
updating based on chat on slack:

> Looks like about 85% nodes have ml enabled, would be wanting that number be more like 95+ maybe to have it be a clear no brainer



> a more detailed quick analysis it to be done add it to the ticket in GitHub. That 86% includes a lot of old stuff probably and would be better to see it on active nodes and by node age too etc.

**Comment by shyamvalsan** [comment]
[Link ](https://grafana.corp.app.netdata.cloud/d/OdZ8APK4z/netdata-business-metrics-explorer?orgId=1&var-metric_name=nodes_ml_enabled_rate) to track the % mentioned above.

Currently at 88%

**Comment by hugovalente-pm** [comment]
this will be solved with https://github.com/netdata/product/issues/2907
