### ISSUE TITLE
[Bug]: Uncalled for high contrast in cloud dashboard

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#750]
### Bug description

User reports that cloud dashboard shows up with weirdly high contrast in grid lines making it hard to use -- local dashboard works as expected.

cloud dashboard: 

![image](https://user-images.githubusercontent.com/24860547/222428348-6741bc68-9d47-46b1-8a41-b03a22264b15.png)

local dashboard:

![image](https://user-images.githubusercontent.com/24860547/222428377-5958eecf-e90e-47d3-97e8-8ef7aaca600a.png)

### Expected behavior

Normal cloud dashboard visualization

### Steps to reproduce

I could not reproduce this, but for the user the problem always exists

### Screenshots

More screenshots from user

![image](https://user-images.githubusercontent.com/24860547/222428581-5297bbfa-20e6-4525-9613-058fd8fe8b65.png)

### Desktop

OS: MacOS 12.6.3
Browser Chrome (and Safari)
Browser Version Chrome Version 110.0.5481.177 (Official Build) (arm64)

### Additional context

Asked user to flip between dark and light mode and back --> this did not help

Check if any extensions are causing issues --> User has zero extensions installed in either browser. 

Chrome (guestmode = no extension) / Safari

**Comment by taiyodayo** [comment]
thanks for opening this track (I'm the reporter)

just noticed two errors in the console, not sure if it's related but I'm sharing in case it is
<img width="593" alt="Screenshot 2023-03-02 at 21 42 41" src="https://user-images.githubusercontent.com/5040379/222432471-7102f2cf-cc24-49c1-acbe-ec89e71a9bb3.png">

please advice if I could share anything more that may help find the issue.
this is happening on 5+ machines I use

**Comment by jacekkolasa** [comment]
@taiyodayo thanks for your submission. We've checked in database that your account has `theme: "unspecified"` which means that the setting in the app was not set, or there was an api error.
Perhaps there was a misunderstanding and you flipped the `theme` setting in your OS, but not in our app?

Our theme setting is under avatar/Settings/Theme tab

![image](https://user-images.githubusercontent.com/5786722/223377960-9f999f9f-970e-4672-be80-7caaf757ae90.png)

![image](https://user-images.githubusercontent.com/5786722/223378034-98b9234a-5e87-4260-9daa-148f7f6e2a24.png)

If you did that before, can you please change the setting to `light` and paste a screenshot how the app will look like? Thanks

**Comment by taiyodayo** [comment]
Thank you! tried that and everything is looking great! 
yes I tried toggling OS setting, not the netdata cloud setting. 
Wonder how it got to be set undefined? I had account for quite a while, perhaps predating dark mode support.

I can monitor my machines so easily now. Thanks again!

**Comment by jacekkolasa** [comment]
@taiyodayo Great, glad it's working now. :) We had this bug long time ago, which is perhaps related to the fact that you had your account for quite a while :)
We'll be trying to see if others can have this issue, too.

Thank you, and happy monitoring! :)
