### ISSUE TITLE
[Bug]: Notification dropdown contrast

### ISSUE THREAD

**Issue by vkuznecovas** [netdata/netdata-cloud#753]
### Bug description

When a dropdown is open on the notification settings tab, the open dropdown blends into the background. If you have multiple rooms, it becomes unclear where the dropdown ends and another select element begins.

![image](https://user-images.githubusercontent.com/18392269/222701718-5c05b78e-7c83-4496-85a5-ae29a4daf22b.png)

### Expected behavior

I'd like to see more contrast, so it's easier to see what is the dropdown and what's the background

### Steps to reproduce

1. Open notification settings
2. Open one of the dropdowns.

### Desktop

OS: All
Browsers: All

**Comment by hugovalente-pm** [comment]
@christophidesp probably something you can help with?

**Comment by novykh** [comment]
Will be fixed in next release.
