### ISSUE TITLE
[Feat]: add anomaly rate to alert view in NC

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#759]
### Problem

It would be good if the corresponding anomaly rate for the raw data associated with an alert could be shown. 

It would help give me some context for how i should think about the `6182.05 Ms` in the image below - is this normal for this node?

Surfacing the anomaly rate around this alert is one way that could help me quickly answer this as a user.

![image](https://user-images.githubusercontent.com/2178292/223721494-3c6e2df4-160b-4534-baa9-aba098cffe23.png)

### Description

We should add another key value to the list below that is "1 min AR%": "10.5%" for example. Assuming that 10.5% is the anomaly rate for the underlying metric in the 60 seconds before (or around, more ideal would be around) the alert.

It could also be nice to add a highlight to the chart and somewhere also display the 1 min AR value as a pill similar to the alert value itself. Would need to do this in a way that's subtle and not distracting from the main alert value pill - so maybe some UI stuff to figure out here but should be easy enough.

![image](https://user-images.githubusercontent.com/2178292/223722868-cbd959d9-3bae-4721-83a5-7f1e2393e7d0.png)

On the chart itself we should also add the mini chart with corresponding anomaly rate similar to charts on the overview screen:

![image](https://user-images.githubusercontent.com/2178292/223723696-4ba915e8-8964-4b44-adf4-681eb97dbe39.png)

In fact if we just added that then it would be more obvious where to highlight and add the AR pill - it could easily go on the top chart that just shows the anomaly rate.

### Importance

must have

### Value proposition

1. provide anomaly rate as some additional context on the alert screen.

### Proposed implementation

- This should build off https://github.com/netdata/netdata-cloud/issues/757 such that we can ideally use the same info in the updated alert templates in this screen on the app.

**Comment by hugovalente-pm** [comment]
this is achieved with the AR on the chart
![image](https://github.com/netdata/netdata-cloud/assets/82235632/5339cf0a-f6b8-4f9a-b381-be597772aac8)
