### ISSUE TITLE
[Feat]: Anomaly rate per section

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#762]
### Description

There should be a way to fetch the anomaly rate per family or per section. The user should be able to see the anomaly rate of only metrics related to a particular collector if they so wish.

Eg. 10% of Postgres metrics are anomalous right now.

### Importance

really want

### Value proposition

1. Improved usability
2. Faster monitoring and troubleshooting

This is required for implementing:
- https://github.com/netdata/netdata-cloud/issues/546
- https://github.com/netdata/product/issues/2795

**Comment by shyamvalsan** [comment]
@andrewm4894 @MrZammler what should we do with this one?

**Comment by andrewm4894** [comment]
Hmm, let me add it to the ml project and we can discuss if or how much is covered by other stuff.

Eg I think lots of overlap with this too maybe.

**Comment by andrewm4894** [comment]
this also would partly be covered a bit by this: https://github.com/netdata/netdata/issues/14788

**Comment by shyamvalsan** [comment]
This has been released.
