### ISSUE TITLE
[Feat]: Add appropriate icons in Netdata UI

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#768]
### Problem

Need appropriate icons for the following sections to be used on the Netdata UI

### Description

The following sections do not have icons assigned or have incorrect icons assigned

- Sendgrid
- Coredns
- Containers & VMs
- DNSQuery
- Systemd
- Bind
- MongoDB
- Smartd log
- Kubelet
- Kubeproxy

### Importance

must have

### Value proposition

1. Having appropriate icons makes Netdata UI look more professional and makes it easier and more intuitive for users to find what they are looking for

### Proposed implementation

Here are some suggested icons to use: 

- [Sendgrid](https://sendgrid.com/wp-content/themes/sgdotcom/pages/resource/brand//2016/SendGrid-Logomark.png)
- [Coredns](https://avatars.githubusercontent.com/u/21110084?s=200&v=4)
- [MongoDB](https://1000logos.net/wp-content/uploads/2020/08/MongoDB-Emblem.jpg)
- [Kubelet](https://wikitech.wikimedia.org/wiki/File:Kubernetes-icon-color.svg)
- [Kubeproxy](https://wikitech.wikimedia.org/wiki/File:Kubernetes-icon-color.svg)
- [Systemd](https://brand.systemd.io/assets/svg/systemd-logomark.svg)

Couldn't find appropriate ones for these
- Containers & VMs (current one is too small)
- DNSQuery (Could use a generic DNS one)
- Bind (Could use a generic DNS one)
- Smartd log

**Comment by shyamvalsan** [comment]
@andrewm4894 I know you wanted to fix some of the missing icons as well, just add them to the list here if you know any that aren't fixed yet.

**Comment by hugovalente-pm** [comment]
done
