### ISSUE TITLE
[BUG] moving between nodes does not update overview stats

### ISSUE THREAD

**Issue by jpeizer** [netdata/netdata-cloud#77]
**Describe the bug**	
Using the cloud install with a kubernetes deployment (using standard netdata tutorial) I was able to get all the nodes to show up on my cloud page.  However if I open each node in it's own tab the stats for each node does not fully update as expected.

**To Reproduce**	
Steps: 
(This was on a new account, running in Firefox)
Assumes the user is using a cluster based netdata setup (I used microk8s for my kubernetes 1.20.4 (latest))
Using https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kubernetes install netdata
Once in the war room, select nodes
Click on each node to open a new tab
switch between the detailed views

**Expected behavior**	
When switching between nodes the system overview does not accurately update, when it should.

**Screenshots**	
See attached video - [cloudnetdata.zip](https://github.com/netdata/netdata-cloud/files/6239226/cloudnetdata.zip)

**Error logs**	
None, web 

**Desktop (please complete the following information):**	
 - OS: Windows 10 20H2 19042.906
 - Browser Firefox
 - Version 87.0

**Additional context**

**Comment by manos-saratsis** [comment]
@jpeizer thx. I cannot open the video, can you please ensure that is not corrupted. Also can you please provide images of the unexpected behavior, it is hard to understand

**Comment by jpeizer** [comment]
[bugmp4.zip](https://github.com/netdata/netdata-cloud/files/6245308/bugmp4.zip)

Screenshots will not illustrate this in a meaningful way.  So I created a new video using mp4.

In general, the system overview does not update correctly when switching between already opened node tabs within a war-room view

**Comment by novykh** [comment]
@jpeizer thank you. We will deploy a fix later today or Monday morning.

**Comment by novykh** [comment]
@jpeizer deployed. Thanks for reporting this ;)
