### ISSUE TITLE
[Bug]: Go to chart/Run Correlations from alert page breaks play/pause functionality on date time picker

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#770]
### Bug description

When user follows the re-direct from alert's dedicated page to single node view, by either clicking Go to Chart button, or Run Correlations, PLAY/PAUSE buttons on the date/time picker lose their effect -clicking them does nothing. No error raised in dev tools console

### Expected behavior

User should be able to effectively interact with datetime picker play/pause options after following an alert for a node.

Default state after alert re-direct to single node view is PAUSE, if user clicks PLAY it should resume chart syncing.

### Steps to reproduce

1. Trigger an alert on a claimed node
2. Go to Alerts page, click the alert name to visit the alert's dedicated view
3. Click Go to chart

### Desktop

OS: Macos
Browser Chrome
Browser Version 110

**Comment by jacekkolasa** [comment]
i'm unnassigning from this one, as it will be fixed after new charts will be ready

**Comment by hugovalente-pm** [comment]
this is fixed
