### ISSUE TITLE
[Bug]: Problem with sorting on last visible chart

### ISSUE THREAD

**Issue by M4itee** [netdata/netdata-cloud#772]
### Bug description

Last visible chart have a problem with sorting button when it is low enough. This problem I found in custom dashboards but looks like it is appearing everywhere. Looks like cursor is switching between text pointer and hand constantly. Probably because tooltip is appearing the same place as we have our mouse

### Expected behavior

Probably tooltip should be in a different place

### Steps to reproduce

1. Scroll low enough on any visible chart and try to sort on the legend

### Screenshots

<img width="190" alt="image" src="https://user-images.githubusercontent.com/60339703/226919755-2b330d4d-0507-4f31-8b45-4fdd69b3ad0b.png">

Hard to show but this right before hand will change into text pointer.

### Desktop

OS: MacOS Ventura 13.2.1
Browser Chrome - Version 111.0.5563.64 (Official Build) (arm64)

### Additional context

[Bug post](https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1679491225808849) on an internal dogfooding channel.

**Comment by jacekkolasa** [comment]
on production
