### ISSUE TITLE
[Bug]: Netdata seems to be showing nodes with over 100% cpu and its truncated off cpu chart. 

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#774]
### Bug description

(1). I seem to have nodes showing over 100% cpu usage when i group by node and just look at `system` and `user` dims. 
(2). The values are not displaying on the CPU chart because it is limited to 100%

![image](https://user-images.githubusercontent.com/2178292/227194638-847ce4f1-ca3e-4fb5-b9d0-e829889ddc02.png)

### Expected behavior

Values I think are expected to not be over 100% on this chart. 

Debatable if maybe the axis here should just scale up as needed to i can at least still see the data?

### Steps to reproduce

1. [link](https://app.netdata.cloud/spaces/ml-demo-space/rooms/all-nodes/overview#6045dc92-0a0c-48d8-960c-d2e0f31aa95d-overview-chartName=menu_system_submenu_cpu&after=-32399&before=0&utc=Europe%2FLondon&offset=%2B0&timezoneName=Edinburgh%2C%20London&modal=&modalTab=&modalParams=&metrics_correlation=false) to internal ml demo space where this is occurring

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
I pinged @ktsaou and @novykh on another related but to this, I don't think we should enforce this limit if the data on the chart goes above the 100%. if it is below 100% we could keep the y-axis scale fixed but only in those cases.

**Comment by hugovalente-pm** [comment]
was trying to validate if there had been some fix for this but I can't reproduce this.
can you check it as well @andrewm4894 ?

**Comment by andrewm4894** [comment]
hmm - i cant recreate this either. i also think maybe new charts has made this not relevant. will close and i will reopen if i come across it again.
