### ISSUE TITLE
[Bug]: Drag and drop cursor is mislead on custom dashboards

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#776]
### Bug description

When on custom dashboards if you over on the chart title you get an indication from the cursor that you can already drag the chart but this isn't true. You can only drag the chart on the row on top of the title
This is misleading and user may think the functionality is broken

![image](https://user-images.githubusercontent.com/82235632/227491823-c985d669-165c-418b-9fc4-eb26dc96dbb3.png)

### Expected behavior

Either allow the drag to also happen over the chart title or only change the cursor on the top row (preferably the 1st suggestion)

### Steps to reproduce

1.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@netdata/cloud-fe I see that this is merged, can you confirm if this has been released?

**Comment by burbuli8ra** [comment]
@hugovalente-pm the last release made on `cloud-frontend` did not contain this update

**Comment by hugovalente-pm** [comment]
thanks for confirming this @burbuli8ra, I understand this will go on the next release

**Comment by hugovalente-pm** [comment]
this is fixed and released
