### ISSUE TITLE
[BUG] New side nav panel

### ISSUE THREAD

**Issue by OdysLam** [netdata/netdata-cloud#78]
**Describe the bug**	
- Wrong link on open a GH issue for agent/cloud (it should link to the respective bug template, not empty issue)
- Copy needs improvement (see [Friction log)](https://docs.google.com/document/d/1q6bWgMFn7H5NLscQSjniwZ5cvLrVuUKzzk9VZCdW5ac/edit#heading=h.qxgwj4l8bh42))
- Community tab on search brings back results from netdata.cloud, not posts from the community. To bring posts from the community, we will need to use Discourse API and it's `/search` endpoint.

**To Reproduce**	
- Go manually over the feature in production

**Expected behavior**	

Thoughts about the UX and the wanted behaviours can be found on the [Friction Log](https://docs.google.com/document/d/1q6bWgMFn7H5NLscQSjniwZ5cvLrVuUKzzk9VZCdW5ac/edit#heading=h.qxgwj4l8bh42).

**Comment by novykh** [comment]
Since those look like new specs. Let's put them to an internal story and plan it.

**Comment by manos-saratsis** [comment]
@novykh the links are a bug and the rest is a feature improvement indeed. @allelos will work on it early next week, minor changes required

**Comment by novykh** [comment]
Yeah, but the links are the ones according to the story as well. Let's add them to the new story in order to be updated without any issues.

**Comment by manos-saratsis** [comment]
Closing this and will follow up with @allelos and #1951
