### ISSUE TITLE
[Bug]: Alert trigger time does not correspond with feed events

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata-cloud#780]
### Bug description

When showing an active alert, the timestamp shown as when it was _triggered_ does not correspond with the last alert _node_ transition event. Instead it appears to show the timestamp of the last _node instance_ alert transition received by cloud. The problem is that if a user would like to inspect the alert history in the Events tab, they cannot find any events around the timestamps mentioned.

### Expected behavior

One of:

1. First time the alert was triggered (when the alert moved from CLEAR to WARNING or CRITICAL)
1. The timestamp of the last change to the _node_ alert state.

### Steps to reproduce

See the screenshots and explanation there.

## Alerts tab

Take the CRITICAL `httpcheck_web_service_bad_content` alert for `netdata-collectors-0` in the Netdata Demo space. It states that the alert value was updated 9 seconds ago, and that the alert was raised 5 hours ago, on **March 27 at 11:15** local time. 

![image](https://user-images.githubusercontent.com/116741/227973904-32a56ff9-3cb6-4f4e-b240-eb62a466685a.png)

## Alert details

The same is shown at the top in the alert details. A bit further down the individual node instances for this alert are shown:

1. The node itself, with its Agent directly connected to Cloud. This node instance last reported this alert CRITICAL at **27 March at 11:15**.
1. The same node via its parent Agent. The parent last reported this alert as CRITICAL **yesterday (26 March) at 11:52**.

![image](https://user-images.githubusercontent.com/116741/227974079-58c389f3-94b9-4aeb-a940-f19604c70d80.png)
![image](https://user-images.githubusercontent.com/116741/227974148-43c2edb5-d87c-41f0-8f77-e670a9e0c40d.png)

Note: Alert transitions at the _node_ level are what we send out notifications for. They are the aggregate of the _node instance_ level alerts for all node instances of the same node, for the same alert.

# Feed events

These are the Feed events for this particular alert. It shows:

- The `alert-node-transition` events that go from or to CLEAR, WARNING, or CRITICAL, which also appear in the Events tab.
- The `alert-node_instance-transition` events that are kept internally to track all alert changes.

![image](https://user-images.githubusercontent.com/116741/227973467-22e0a59c-6544-40be-8dfd-74cdc95028be.png)

In sequence, we see:

1. The _node_ alert going from CLEAR to WARNING at **March 25 00:56:44**, following a corresponding _node instance_ alert transition from the parent Agent (`4efe5568-d0e0-4fbb-97ee-97cda5d3e59e`).
1. A few seconds later, the node's directly connected Agent (`add2fe3c-c2b2-4fea-9cf8-dbda5749e045`) reports the same.
1. Two minutes later, at **March 25 00:58:14**, the alert escalates to CRITICAL.
1. Then a few internal transitions that move between CRITICAL, REMOVED, and UNKNOWN:
  
    - These are the result of agent restarts (daily automatic Agent upgrades).
    - The last for the parent Agent is on **March 26, 11:52**.
    - The last for the child Agnet is on **March 27, 11:15**.
  
    None of these internal transitions change the _node_ level alert status, as they just confirm the CRITICAL level of the alert from different node instances. So the event from **March 25 00:58** is the last event representing this alert.

## Summary

So even though the initial problem was reported **two days ago**, initially a WARNING, and then to CRITICAL, the alert states **5 hours ago**. A user would not know to look further back in the alert history, unless they also look at alert notifications (e.g. via E-mail).

**Comment by car12o** [comment]
great catch @ralphm.
I agree that we should show the triggered timestamp as when the transition first occurred.
Already created a PR to address it.

**Comment by hugovalente-pm** [comment]
the related BE work has been released so closing the bug
