### ISSUE TITLE
[Feat]: increase the space name length from 20 chars and allow hyphens/underscores in the space name

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#781]
### Problem

Sometimes the below limitations can make naming spaces hard.

- Need more space when naming spaces
- Allow hyphens/underscores in the space name

### Description

- Need more space when naming spaces
- Allow hyphens/underscores in the space name

https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1680001923169179

### Importance

really want

### Value proposition

1. better space names

**Comment by jacekkolasa** [comment]
@netdata/cloud-be i checked that BE allows using hyphen and underscores, are you OK with me enabling it on FE?

FTR 20 chars limit is enforced on BE, too

**Comment by vkuznecovas** [comment]
> https://github.com/orgs/netdata/teams/cloud-be i checked that BE allows using hyphen and underscores, are you OK with me enabling it on FE?

I see no issues with that, go ahead.

**Comment by vkuznecovas** [comment]
As far as the char limit goes - once I get some time I'll bump it.

**Comment by hugovalente-pm** [comment]
only thing pending is the limit of 20 chars, don't see further request on this so closing
