### ISSUE TITLE
[Bug]: Cannot scroll down to add a node

### ISSUE THREAD

**Issue by vkuznecovas** [netdata/netdata-cloud#782]
### Bug description

I can not scroll down when trying to add an existing node to a room.
<img width="1453" alt="Screenshot 2023-03-28 at 14 17 58" src="https://user-images.githubusercontent.com/18392269/228229708-c017eb63-b905-4ffe-8091-e8473e390210.png">

### Expected behavior

I should be able to scroll down.

### Steps to reproduce

1. Have 1 node in a space.
2. Create a new room.
3. Try to add the node to the room.

### Desktop

OS: macos
Browser: firefox

**Comment by vkuznecovas** [comment]
Same applies to custom dashboards
<img width="1441" alt="Screenshot 2023-05-03 at 12 59 48" src="https://user-images.githubusercontent.com/18392269/235893679-f9fcca11-eaf0-4f38-b935-f79f4b9febe5.png">

**Comment by hugovalente-pm** [comment]
this is fixed
