### ISSUE TITLE
[Bug]: cannot seem to filter nodes in setting table

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#783]
### Bug description

I don't seem to be able to select all offline nodes and then remove them like i used to. Video shows what i mean.

in a nutshell - this dropdown button seems to do nothing: 

![image](https://user-images.githubusercontent.com/2178292/228519318-60c586c9-26c7-4186-b829-3e2b88ff98fb.png)

https://user-images.githubusercontent.com/2178292/228519042-c15ec705-61ab-4364-b973-a346d2ea8eea.mp4

### Expected behavior

The drop down lets me just filter for all offline and i can select them all and then delete them.

### Steps to reproduce

1. try use dropdowns in settings tab for nodes.

### Desktop

Browser Version [e.g. 22]

**Comment by andrewm4894** [comment]
a workaround seems to be to type to filter for now

![image](https://user-images.githubusercontent.com/2178292/228520888-73656edb-b757-4ebb-b012-b956c3cead44.png)

**Comment by hugovalente-pm** [comment]
@andrewm4894 it also works if you type it on the search bar on the column itself and press enter
![image](https://user-images.githubusercontent.com/82235632/228578292-8a740e1a-a09d-405a-b371-3bf9d6b2f8f2.png)

**Comment by andrewm4894** [comment]
i still am seeing this issue?

**Comment by andrewm4894** [comment]
https://user-images.githubusercontent.com/2178292/230062823-2fc91d91-b4ea-4b5a-94f2-0fb85d2ecf95.mp4

**Comment by andrewm4894** [comment]
@netdata/cloud-fe i think we might just need to double check this one

**Comment by novykh** [comment]
Fixed.
