### ISSUE TITLE
[BUG] cpuidle dimension labels all look the same

### ISSUE THREAD

**Issue by chrikar** [netdata/netdata-cloud#79]
**Describe the bug**
Dimension names for different CPUs all look the same for cpuidle.
![Screenshot 2021-04-12 at 12 50 52 PM](https://user-images.githubusercontent.com/2836342/114376420-4928bd00-9b8e-11eb-90d4-ae4cc2d59531.png)

**To Reproduce**	
This is mostly noticeable on k8s-enabled nodes.

**Expected behavior**	
Independent labels for different CPUs.

**Desktop (please complete the following information):**	
 - OS: macOS Big Sur
 - Browser: Google Chrome
 - Version: 89.0.4389.114

**Additional context**

**Comment by chrikar** [comment]
From some initial investigation it looks like the dimension_ids are different but the names are all the same:
![Uploading Screenshot 2021-04-12 at 2.08.15 PM.png…]()

**Comment by cakrit** [comment]
This looks fine now, we have one chart per cpu:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/43294513/170510304-4e4e5284-6ae6-494c-8445-fd6b23ee9ba8.png">
