### ISSUE TITLE
[Bug]: Wrong "What is a context" and "What is a dimension" link redirects

### ISSUE THREAD

**Issue by Dim-P** [netdata/netdata-cloud#790]
### Bug description

When trying to add a new metric on a war room, "What is a context" and "What is a dimension" help links redirect to https://learn.netdata.cloud/docs/improving-netdata---developers/web . This doesn't contain any useful answers to these questions.

### Expected behavior

The links should instead take the user to the respective sections of https://learn.netdata.cloud/docs/data-collection/chart-dimensions-contexts-and-families .

### Steps to reproduce

Click "Add new metric" on "Metrics" :
![Screenshot from 2023-04-06 20-43-04](https://user-images.githubusercontent.com/5953192/230478989-a9f72622-f760-4dea-b1ea-c2704421cd8b.png)

Check "What is a context" and "What is a dimension" redirections:
![Screenshot from 2023-04-06 19-26-35](https://user-images.githubusercontent.com/5953192/230479113-25bb989f-61d8-470d-9621-dda5c296673f.png)

### Desktop

-

**Comment by hugovalente-pm** [comment]
this is fixed
