### ISSUE TITLE
[Bug]: custom dashboard seems to double my nodes

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#791]
### Bug description

When i go to a custom dashboard i had saved in my space i am seeing 2 entries for each node for some reason. 

There are 16 nodes but it says 32 for some reason

![image](https://user-images.githubusercontent.com/2178292/231109543-e026b621-a514-4a06-84d9-e1da39966939.png)

https://user-images.githubusercontent.com/2178292/231109579-0024739a-6822-4b21-9dca-f0f92ab78d98.mp4

### Expected behavior

There should only be 16 nodes and no nodes should be duplicated in the chart on custom dashboard. 

### Steps to reproduce

1. not sure

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
![image](https://user-images.githubusercontent.com/82235632/232051580-10293dff-7cd4-4c47-82cd-6452e5ebc00c.png)


what I could spot from my search, the list of 42 nodes (now there are some more) includes the offline nodes, picking the example of `ml-demo-ml-disabled` this one has 3 entries with different node ids:
* `649de00a-48b7-48a0-ab75-5e3e90007f79`
* `a2bb048b-07df-485a-922b-cf055194a5ec`
* `93bb7ad5-3684-460e-8eb3-e1b36c2e97`

Looking to the nodes list and `/nodes` endpoint what we can see for these nodes is that only one is Live / Reachable:
![image](https://user-images.githubusercontent.com/82235632/232052326-d8312f66-9dda-4978-a526-cb5c00932185.png)

If we look to the `/data` request from the Overview screen for the same chart we see that it queries just the 15 live nodes
![image](https://user-images.githubusercontent.com/82235632/232052987-a62b42e2-7df1-493b-976a-9b2a37418bf9.png)

Whereas in the Custom dashboard the `/data` request takes all the nodes in the room including the Offline
![image](https://user-images.githubusercontent.com/82235632/232053432-92f8a7e4-8888-4653-8820-4fb279331e93.png)

I think the fix here should be to not query `Offline` nodes, which the Overview isn't doing

**Comment by hugovalente-pm** [comment]
@netdata/cloud-fe what do you think?

**Comment by novykh** [comment]
This is fixed since April
