### ISSUE TITLE
[Bug]: nvidia-smi python plugin can not list all A100

### ISSUE THREAD

**Issue by pythonmandev** [netdata/netdata-cloud#795]
### Bug description

nvidia-smi python plugin can not list all A100

### Expected behavior

list 8 A100

### Steps to reproduce

1.
click "nvidia smi"

### Screenshots

![netdata](https://user-images.githubusercontent.com/50359848/233642182-0762be76-af39-42ea-8a00-0c5a0f95b0fb.png)

### Desktop

OS: [e.g. iOS]	 macosx 
Browser [e.g. chrome, safari]	chrome
Browser Version [e.g. 22]112

**Comment by hugovalente-pm** [comment]
@pythonmandev our charts are context based charts where all individual charts that you would see on the local Agent dashboard are grouped under a single context.
could you go to the "instances" dropdown and see if all 8 that you expect are displayed there? you can also change the group by to `instance` and see that you can change how the data is grouped on the chart.

**Comment by hugovalente-pm** [comment]
@pythonmandev closing this, if you still have some issue with this just let us know
