### ISSUE TITLE
[Bug]: Nvidia A100 temperatures count problem.

### ISSUE THREAD

**Issue by pythonmandev** [netdata/netdata-cloud#796]
### Bug description

8 A100s, each at 30 degrees Celsius, but not all temperatures should display as 240 degrees.

### Expected behavior

Display the highest temperature instead of adding up all the temperatures.

### Steps to reproduce

click nvidia smi

### Screenshots

<img width="806" alt="temp_all" src="https://user-images.githubusercontent.com/50359848/233643781-e3187463-ebe0-44a4-9837-133bb8e69dc3.png">
![temp1](https://user-images.githubusercontent.com/50359848/233643788-645da369-5669-47ce-8164-3fe58a90137d.png)

### Desktop

Browser Version [e.g. 22]

**Comment by pythonmandev** [comment]
![temp1](https://user-images.githubusercontent.com/50359848/233644513-83dee9a2-5763-4fc9-af21-1500c8c0888f.png)

**Comment by hugovalente-pm** [comment]
your suggestion makes total sense, it seems by default we are displaying there the SUM across all the instances
our summary charts have some limitations, like not being able to specify different aggregations, but we are currently working on enhancing this. we will take your suggestion and apply here the MAX aggregation

**Comment by hugovalente-pm** [comment]
once we get the work being done on new charts this should be fixed, we will update here once that happens

**Comment by hugovalente-pm** [comment]
@pythonmandev the release where this was shipped was done, could you validate if all looks ok now?

**Comment by hugovalente-pm** [comment]
we are closing this, if you still have an issue on these charts let us know.
