### ISSUE TITLE
A pinned & minimized dashboard does not get updated when adding charts from other views

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#8]
**Describe the bug**	
Pinned&minimized dashboard does not get updated when adding charts from views other than the dashboard itself.

**To Reproduce**	
Steps to reproduce the behavior:	Go to single node, add a chart in a dashboard while the dashboard is pinned&minimized. The dashboard does not get updated

**Expected behavior**	
Pinned & minimized dashboards should be automatically updated after addition of a chart from outside the dashboard.

**Comment by cakrit** [comment]
Shouldn't be on @jacekkolasa , it's for the visualizations team.

**Comment by novykh** [comment]
Fixed.
