### ISSUE TITLE
[Bug]: Nodes over type of machine/technology in home tab is cut off

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#800]
### Bug description

Screen is cut off and no horizontal scroll functionality

### Expected behavior

It should show all the data and adjust to screen size 

### Steps to reproduce

1. claim several nodes 
2. navigate to home tab

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/234283728-8a2d23ec-4b39-4e50-8389-e15da2cb74d3.png)

How it's supposed to look like

![image](https://user-images.githubusercontent.com/19268853/234283870-10e0ec03-361b-41e8-b96f-eb4dd59a3c07.png)

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@christophidesp do you think this is something you can pick-up?

**Comment by christophidesp** [comment]
@hugovalente-pm 
https://github.com/netdata/cloud-frontend/pull/4146

**Comment by hugovalente-pm** [comment]
this is fixed
