### ISSUE TITLE
[Bug]: anomalies tab sorting is broken

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#805]
### Bug description

anomalies tab sorting seem broken since recent changes

we should go back to the previous implementation of using method=anomaly-rate and two weights calls to filter out rubbish.

### Expected behavior

it should have better results similar to how it used to

### Steps to reproduce

1. use anomalies tab across multiple nodes
2. observe that results no longer typically as useful as used to be

### Desktop

Browser Version [e.g. 22]

### Additional context

https://netdata-cloud.slack.com/archives/C04R2FC41D3/p1683625539227339

**Comment by novykh** [comment]
Still on WIP. Will revisit

**Comment by andrewm4894** [comment]
cool yep - will try add more details and flesh out these tickets a bit more in case helps

**Comment by novykh** [comment]
Dup of #823

**Comment by andrewm4894** [comment]
Not a dupe of that one but is superseded by #830 as that adds more details and evidence
