### ISSUE TITLE
[Bug]: low precision values in hover

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata-cloud#809]
### Bug description

Hovering over charts with large changes in values or with small changes for metrics with units with a large value prefix makes it impossible to see useful values.

### Expected behavior

Scale individual values instead of forcing the same precision on all values, or present full precision.

### Example 1

1. Go to `netdata.uptime` around the time of the daily Agent upgrade
2. Group by instance
3. Hover over the chart and observe that the small values after the reset all have `0d:00`

### Example 2

1. Go to `dockerhub.pulls` and find a spot with a gradual change
2. Notice that when hovering the displayed value is rounded at whole numbers
3. Select just one dimension
3. Notice that when hovering the displayed value now has better precision, but still not *full* precision as the last digit is missing.

### Example 1

![image](https://github.com/netdata/netdata-cloud/assets/116741/70d9641e-9d11-4f65-b080-a57e38d148e6)

### Example 2

![image](https://github.com/netdata/netdata-cloud/assets/116741/bf48a09c-6a25-49be-8c8c-06aff7811c3c)
![image](https://github.com/netdata/netdata-cloud/assets/116741/8bea57ba-3801-4917-a3b6-f3147ed60c11)

**Comment by hugovalente-pm** [comment]
@novykh placed this as FE bug since I believe this scaling/rounding logic is on FE right?

**Comment by novykh** [comment]
Let's make it part of the UCUM units feature.
