### ISSUE TITLE
[BUG] Dashboard grouping is not properly saved

### ISSUE THREAD

**Issue by IvMisticos** [netdata/netdata-cloud#81]
**Describe the bug**	
When changing grouping of a chart in a dashboard, all grouping settings on other charts is reset.

**To Reproduce**	
1. Create a dashboard
2. Add two charts
3. Set one chart grouping to "by node"
4. Save
5. Set second chart grouping to "by node"
6. Save

Result: First chart has grouping set to by dimension.

**Expected behavior**	
Instead the other chart grouping should be saved too, so that both have grouping set to by node.

**Screenshots**	
![image](https://user-images.githubusercontent.com/21005901/114836325-335c0780-9ddb-11eb-8ee8-e10959d8c59c.png)
Change first one to "node"
![image](https://user-images.githubusercontent.com/21005901/114836530-70c09500-9ddb-11eb-9a12-f70b77776733.png)
Save and refresh the page
![image](https://user-images.githubusercontent.com/21005901/114836654-8f269080-9ddb-11eb-8d1f-27ec04b979e6.png)

**Desktop (please complete the following information):**	
 - OS: Windows
 - Browser Firefox v87

**Comment by hugovalente-pm** [comment]
This has been fixed.
