### ISSUE TITLE
[Feat]: Summary Tile Tooltip

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#812]
### Problem

Summary tiles should have tooltip when user hovers on them that display more information

### Description

When a user hovers on a summary tile, a tooltip should pop up with the following information

1. Name of chart/context/dimension which contributed to the summary
2. Any group_by/aggregation that has been applied
3. Info text of chart
4. Hyperlink which takes user to the full chart
5. Anomaly rate %
6. Any active alerts on this chart

### Importance

really want

### Value proposition

1. Make the summary dashboard more useful - and sufficient for casual monitoring on its own without having to scroll around.

**Comment by hugovalente-pm** [comment]
most of this has been done
![image](https://github.com/netdata/netdata-cloud/assets/82235632/970ec999-b2ea-41ca-92a6-ada5446627b6)

what I see missing:
> Info text of chart
> Any active alerts on this chart

some parts of this below can be seen on NIDL framework like charts and dimensions
> Name of chart/context/dimension which contributed to the summary

@shyamvalsan do you think we should keep this open?

**Comment by shyamvalsan** [comment]
I think we can close this @hugovalente-pm
