### ISSUE TITLE
[Bug]: Gauge charts have a weird overhang inside the panel

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#814]
### Bug description

Gauge charts have a weird overhang inside the panel (see screenshot)

### Expected behavior

Gauge charts should look clean and not-weird.

### Steps to reproduce

1. Just observe different gauge panels in Netdata cloud summary dashboards.

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/24860547/e16e8138-53ec-4be8-a9ed-221ce94eb04f)

### Error Logs

N/A

### Desktop

N/A

**Comment by shyamvalsan** [comment]
![image](https://github.com/netdata/netdata-cloud/assets/24860547/cfdd2515-55c1-482a-be08-7e9652c5cb2a)

**Comment by novykh** [comment]
Fixed
