### ISSUE TITLE
[Feat]: Add a Windows section to the "Add nodes" modal

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#815]
### Problem

The Add Nodes tab has no information on how a user can add windows nodes.

### Description

The add nodes modal should have a windows tab which explains how the user can add Windows nodes

### Importance

must have

### Value proposition

1. Ease of use (especially for new users)

### Proposed implementation

Use the following information to craft the message for this tab:

1. Install [Windows Exporter](https://github.com/prometheus-community/windows_exporter) on every Windows host you want to monitor.
2. Install Netdata agent on a Linux, FreeBSD or Mac node.

3. Configure Netdata to collect data remotely from your Windows hosts by adding one job per host to windows.conf file. See the [configuration section](https://learn.netdata.cloud/docs/data-collection/monitor-anything/System%20Metrics/Windows-machines#configuration) for details. 
4. Enable `virtual nodes` configuration so the windows nodes are displayed as separate nodes.

**Comment by shyamvalsan** [comment]
This request was brought up by a user during the Discord meetup.

**Comment by thiagoftsm** [comment]
Hello @shyamvalsan ,

About the sentence `Install Netdata agent on a Linux node.`. This is the most common scenario that we have nowadays, but considering that `go.d.plugin` can also run on BSD and I also think on Mac OS, we should also add these two OS in the list.

Best regards!

**Comment by hugovalente-pm** [comment]
@shyamvalsan this was what we had planned in the past for the Windows instructions, pointing to the `netdata.msi` 
https://github.com/netdata/product/issues/3041

should we consider your suggestion instead of that one?

**Comment by shyamvalsan** [comment]
@hugovalente-pm I think we should stick with what I defined above the netdata.msi is not stable enough to put it on the connect nodes page imo. 

We can also update it as @thiagoftsm suggested so it would be:

1. Install [Windows Exporter](https://github.com/prometheus-community/windows_exporter) on every Windows host you want to monitor.

2. Install Netdata agent on Linux, FreeBSD or Mac.

3. Configure Netdata to collect data remotely from your Windows hosts by adding one job per host to windows.conf file. See the [configuration section](https://learn.netdata.cloud/docs/data-collection/monitor-anything/System%20Metrics/Windows-machines#configuration) for details.

4. Enable virtual nodes configuration so the windows nodes are displayed as separate nodes.

**Comment by shyamvalsan** [comment]
And I think we should do this along with the current work to improve the onboarding.

**Comment by hugovalente-pm** [comment]
this is done
