### ISSUE TITLE
[Bug]: Total Network Outbound values vary more than expected (low volatility)

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#816]
### Bug description

Sometimes the value jumps although the traffic should only vary within a couple of percent in reality, there is no such volatility.
Value jumps from  ~30 to  ~20

https://github.com/netdata/netdata-cloud/assets/80083/0c760f0b-f4f6-4b04-a3b7-a555c3de39f4

### Expected behavior

Value should be consistent

### Steps to reproduce

See video

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@cheluskin we have noticed that when the summary charts are trying to refresh the data displayed the Netdata icon turns read, this means that there was some issue with the `/data` requests
could you look into the dev-tools of your browser and on the Network tab try to see if there are falling requests? if so, could you share some responses?

**Comment by cheluskin** [comment]
> @cheluskin we have noticed that when the summary charts are trying to refresh the data displayed the Netdata icon turns read, this means that there was some issue with the `/data` requests
> could you look into the dev-tools of your browser and on the Network tab try to see if there are falling requests? if so, could you share some responses?

```
[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (command, line 0)
https://esp.aptrinsic.com/rte/v1/command?p=AP-WA6UGT2X7KII-2&sv=0.49.0&v=undefined&vt=0&ai=undefined&s=AP-WA6UGT2X7KII-2-1683797325898-56161722&et=identify&rf&sc=https%3A%2F%2F&ho=app.netdata.cloud&pa=%2Fspaces%2Fcdnnet%2Frooms%2Fbcdn%2Foverview&q&ha=%23metrics_correlation%3Dfalse%26after%3D-900%26before%3D0%26utc%3DEurope%2FKiev%26offset%3D%2B3%26timezoneName%3DHelsinki%2C%20Kyiv%2C%20Riga%2C%20Sofia%2C%20Tallinn%2C%20Vilnius%26modal%3D%26modalTab%3D%2632147de0-baa6-439f-99c1-02d6c20b09e0--chartName%3Dmenu_system&sch=473&scw=1515&pt=Netdata%20Cloud&ep=%7B%22usf%22%3A%7B%22ide%22%3A%220389b2ea-386b-4ff1-a7bd-c53bfedf8cea%22%2C%22usem%22%3A%22bystrov1984%40gmail.com%22%2C%22firstName%22%3A%22cheluskin%22%2C%22customAttributes%22%3A%7B%22netdata_cloud_account_created_at%22%3A%222019-10-10T08%3A18%3A39.938821Z%22%2C%22netdata_cloud_account_created_days_ago%22%3A1309%7D%7D%7D&cb=1683797787483-3463
```
In the console, there is a 400 error at the beginning, but it does not affect anything. Usually, this happens under heavy loads in the evening. It's possible that some agents are having trouble transmitting data in a timely manner, and this is not a problem on your end.

**Comment by hugovalente-pm** [comment]
@cheluskin it can be that, the load on the agents and them not being able to respond but we would be able to see that on the responses.
instead of looking at the console could you look on the Network tab maybe even filter by `/data`? also if you click on the Netdata icon you can trigger a manual refresh

note: this video was done using Chrome

https://github.com/netdata/netdata-cloud/assets/82235632/bd7a3735-1561-476f-9d33-9562f5eeb7a9

**Comment by hugovalente-pm** [comment]
@cheluskin were you able to check this?

**Comment by cheluskin** [comment]
https://filetransfer.io/data-package/16zqcyrS#link

I have checked, and there are no delivery errors in the network. It's working as expected. However, as you can see, it shows 15 instead of 22. The load from 19 servers is 22 gigabits, which is currently slightly over half of their maximum capacity. This means there is no network or processor overload causing the agent to potentially not transmit the data on time. Additionally, there is a high volume of data packets with sizes ranging from 7 to 17 kilobytes. If you provide your email, I can expand the room for you.

**Comment by hugovalente-pm** [comment]
sure, please invite me to your room. my email is hugo@netdata.cloud

**Comment by hugovalente-pm** [comment]
looking to a wider timeframe what I noticed is that the there is a pattern on your bandwidth utilization and it is the same everyday for the Network Outbound:
- lowest value verified for is between 4.5 and 6 gigabits/s at around 2h/3h GMT
- highest amount verified is between 24 and 29 gigabits/s at around 19h/20h GMT

![image](https://github.com/netdata/netdata-cloud/assets/82235632/c738f1dd-e370-46a1-a240-0c317254016d)

Filtering on the specific dimension and grouping by node all of them have the same pattern
![image](https://github.com/netdata/netdata-cloud/assets/82235632/ee20561e-b5bb-4d86-a5e6-98fbb3f43b4d)

This seems to indicate that there is some volatility here. Does your outbound traffic of physical network interfaces change throughout the day?

**Comment by cheluskin** [comment]
Yes, that's correct. It changes throughout the day. But in all the videos I've attached, you can see that it changes within seconds, not hours. And then it returns to normal within seconds again. It jumps. This has been a long-standing issue.

**Comment by cheluskin** [comment]
And also, the scale is not highlighted in color at the moment. Whereas when the numbers are correct, there is always highlighting. What does this mean?

**Comment by hugovalente-pm** [comment]
ok, sorry for getting side-tracked. let me keep your space open for a while and try to confirm that

> the scale is not highlighted in color at the moment

what do you mean by highlight?

**Comment by cheluskin** [comment]
> ok, sorry for getting side-tracked. let me keep your space open for a while and try to confirm that
> 
> > the scale is not highlighted in color at the moment
> 
> what do you mean by highlight?

When the numbers are incorrect, they are like those shown in the right screenshot. (Green line)

<img width="123" alt="Снимок экрана 2023-05-18 в 16 39 50" src="https://github.com/netdata/netdata-cloud/assets/80083/b51d8dd1-46ec-4564-af7d-05dadb43bc1f">

<img width="124" alt="Снимок экрана 2023-05-18 в 16 46 05" src="https://github.com/netdata/netdata-cloud/assets/80083/c64ab50f-95f2-43be-8237-5c6107a2d9da">

**Comment by hugovalente-pm** [comment]
@cheluskin this seem hard to catch and even reproduce.
if this happens sporadically and _self-heals_ would probably suggest to close this ticket. a new can be opened if the situation gets worst
