### ISSUE TITLE
[Bug]: Visiting node from an alert causes issues

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#817]
### Bug description

Clicking on the node name of various raised alerts has various unexpected consequences. We always get a new tab named after the node we clicked on and the chart related to the raised alert is always the first one shown, but:
- Often the vertical line is not shown at all, because the start/end time is not correctly set to ensure the alert state transition is shown.
- At some point I would see the line, but clicking on the chart to zoom in or out caused a serious error and no charts were shown. This may have been a transient error, as I can no longer reproduce it and didn't get a screenshot. But do try to zoom in/out from within the chart while testing the first issue, as it might appear again. 
 

### Expected behavior

Chart visible time frame is set to include the start time of the alert (it's already shown on the alert page).

### Steps to reproduce

1. Go to the alerts tab, select an alert older than the selected time frame from the datetime picker and click on the node name.
2. (for the second issue) Click on the chart zoom in/out buttons to see if you'll get a complete failure.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this is fixed
