### ISSUE TITLE
[Bug]: Error when clicking on timeframe to change it

### ISSUE THREAD

**Issue by Inrego** [netdata/netdata-cloud#818]
### Bug description

Whenever I click the timeframe to see another timeframe, I'm getting the following error:
![image](https://github.com/netdata/netdata-cloud/assets/2242329/35b43213-1717-42df-b567-7381aa0edcd8)

Dev tools show this error:
![image](https://github.com/netdata/netdata-cloud/assets/2242329/9ee22ac0-44f8-4a4a-a848-f8961cc00f05)

Using Microsoft Edge browser on Windows.
Windows Language: en-US
Windows Locale: da-DK

### Expected behavior

I expected to be able to change the timeframe.

### Steps to reproduce

1. Open netdata cloud
2. Click on the timeframe
3. Possible requirement: da-DK locale

### Desktop

OS: Windows 11
Browser Chrome and Edge
I've also tried on Safari on my Mac, where it's working correctly.

**Comment by novykh** [comment]
@Inrego could you please check again? A new release has been deployed. If you are still experiencing the same issue feel free to reopen the issue.

**Comment by Inrego** [comment]
It's working, great!
