### ISSUE TITLE
[Feat]: Able to remove stale nodes.

### ISSUE THREAD

**Issue by david9991** [netdata/netdata-cloud#821]
### Description

I am using NetData in Google Cloud Platform (GCP) to monitor Google Kubernetes Engine (GKE) nodes of type Spot. These nodes can be preempted at any time, and a new node will be created later when resources become available.

However, when preempted, the SpotVM nodes displayed in NetData become stale and cannot be deleted until all associated persistent volumes (PVs) with the NetData agents are removed first. It would therefore be beneficial to have the ability to delete stale nodes, similar to deleting nodes in the offline state.

### Importance

really want

### Value proposition

1. It is easier to monitor Spot nodes.

**Comment by david9991** [comment]
<img width="1030" alt="Screenshot 2023-06-16 at 11 26 53" src="https://github.com/netdata/netdata-cloud/assets/123219/8f2e80eb-9711-418f-b61e-4ae9e7aa330f">

**Comment by andrewm4894** [comment]
Cross linking as related

https://github.com/netdata/netdata-cloud/issues/690

**Comment by david9991** [comment]
My solution is to use distributed filesystem to prevent data inconsistency, and this issue has already been filed in #690, so closing this one.
