### ISSUE TITLE
[Bug]: After resizing the browser window, some UI elements became corrupted.

### ISSUE THREAD

**Issue by david9991** [netdata/netdata-cloud#822]
### Bug description

After resizing the browser window, some UI elements became corrupted.

### Expected behavior

The UI should still be displayed correctly even when the browser window is resized.

### Steps to reproduce

1. Open NetData
2. Resize the browser window.

### Screenshots

<img width="1436" alt="Screenshot 2023-05-19 at 22 23 32" src="https://github.com/netdata/netdata/assets/123219/7138f5da-9c7c-442f-8641-8ad949c3145a">

### Desktop

OS: macOS
Browser safari
Browser Version 16.4

**Comment by hugovalente-pm** [comment]
@novykh was able to reproduce, moving to the backlog

**Comment by novykh** [comment]
This should be fixed on prod.
