### ISSUE TITLE
[Bug]: Anomalies tab is broken

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#823]
### Bug description

Anomalies tab is completely broken after recent chart changes.

### Expected behavior

1. Charts not hidden

These two charts should be minimized by default - this setting seems to have been reset after latest changes.

![image](https://github.com/netdata/netdata-cloud/assets/24860547/4a6ae3ae-e3d2-4381-a6cf-cff801ba7bfa)

2. Charts must be grouped by node by default and be displayed as "area" chart

The default options have been messed up

![image](https://github.com/netdata/netdata-cloud/assets/24860547/bfc0e792-445d-4eca-a5b3-90944418f98f)

Should look like

![image](https://github.com/netdata/netdata-cloud/assets/24860547/6892f508-d1ff-444b-a851-163666a9c7f3)

4. Bottom half is always showing up in dark mode

This is just wrong.

![image](https://github.com/netdata/netdata-cloud/assets/24860547/c2c40060-b384-4ef4-aa9d-f0009e05e54f)

5. Highlighting a timeline doesn't work (This appears to be working now)

Highlighting an area doesn't seem to bring up the anomalous metrics.

https://github.com/netdata/netdata-cloud/assets/24860547/af7bcb65-0091-475a-8356-258b417aab7c~~

6. There was an adjustment to ensure the anomaly rate charts have a fixed min height on the y axis of 10 so that miniscule anomaly rate spikes should not be auto scaled to show up as a big spike

![image](https://github.com/netdata/netdata-cloud/assets/24860547/a2965d8c-78fb-458e-9442-c750b56df7da)

### Steps to reproduce

1. Just visit any space

### Screenshots

See above

### Error Logs

N/A

### Desktop

N/A

**Comment by andrewm4894** [comment]
Cross linking - going to try cover these issues in a bigger issue with various tasks if we can. If not will take this individually.

https://github.com/netdata/netdata-cloud/issues/825

**Comment by hugovalente-pm** [comment]
@andrewm4894 @shyamvalsan is this in a ready state for @novykh to pick? are the issues identified?

**Comment by andrewm4894** [comment]
I need to update #825 into a priority list or breaking and improvements. Going to try do that today and then ping on it.

**Comment by shyamvalsan** [comment]
@andrewm4894 my concern with considering some of the stuff that was broken as improvements is that they will not be prioritized. And some of them are really important for the user journey. 

Maybe we should have a review of the issues with @novykh (if you haven't already had it ie.) as some of them maybe quick fixes.

cc: @hugovalente-pm

**Comment by andrewm4894** [comment]
Closing as we are using #825 to try collect everything.

We can make specific new issues as we need to and add them to the lists in #825
