### ISSUE TITLE
[Bug]: Graph zoom on shift-scrollwheel broken in Firefox

### ISSUE THREAD

**Issue by splatt** [netdata/netdata-cloud#824]
### Bug description

New graph engine - Firefox - shift-scrollwheel zooming of graph time range has stopped working.

This broke when the new graphing frontend was released. I'm not sure the exact date because I've waited a bit to see if it is fixed.

Netdata dashboard loaded from a node (v1.39.0-47-nightly) still works fine.

Current Chrome browser is fine.

### Expected behavior

Mouse over a graph in Netdata Cloud dashboard. Hold shift and turn the scroll wheel. Graph's horizontal time scale should zoom in/out.

### Steps to reproduce

1. Log in to Netdata Cloud, hover over a graph and attempt graph time zoom with shift-scrollwheel.

### Error Logs

![image](https://github.com/netdata/netdata-cloud/assets/630831/985bf47c-e214-467e-b2f3-9b01048c66f2)

Uncaught TypeError: setting getter-only property "offsetX"
    r https://app.netdata.cloud/app.48946fa1bb07400b4c23.js:2
    trigger https://app.netdata.cloud/app.48946fa1bb07400b4c23.js:2
    trigger https://app.netdata.cloud/app.48946fa1bb07400b4c23.js:2
    wheel https://app.netdata.cloud/app.48946fa1bb07400b4c23.js:2
    n https://app.netdata.cloud/app.48946fa1bb07400b4c23.js:2
    r https://app.netdata.cloud/app.48946fa1bb07400b4c23.js:2
6 app.48946fa1bb07400b4c23.js:2:69187

### Desktop

OS: Linux Mint (Ubuntu)
Browser: Firefox
Browser Version: Developer Edition 114.0b7.  Also tested in standard Firefox 107.0.. Same error.

**Comment by novykh** [comment]
@splatt should be fixed after latest release. Re-open if you face any similar issues. Thank you

**Comment by splatt** [comment]
Thank you. :)
