### ISSUE TITLE
[Feat]: Gauges in custom dashboard - Netdata Cloud

### ISSUE THREAD

**Issue by FeminalPanda** [netdata/netdata-cloud#826]
### Problem

Netdata cloud does not have gauges to use as custom dashboards. Would like them implemented for a quicker at a glance. 

### Description

Netdata cloud does not have gauges to use as custom dashboards. Would like them implemented for a quicker at a glance. 

### Importance

nice to have

### Value proposition

Quick at a glance
Easier to see and understand on TV screen.

**Comment by juanra** [comment]
Thanks for this request.  I was looking for something like this.

**Comment by hugovalente-pm** [comment]
this is done
