### ISSUE TITLE
[Bug]:  create a new dashboard and it throws an error "Oops, something unexpected happened!" when I try to load it.

### ISSUE THREAD

**Issue by Austex-AaronCraig** [netdata/netdata-cloud#827]
### Bug description

Trying to create a new dashboard and it throws an error "Oops, something unexpected happened!" when I try to load it.

### Expected behavior

To be able to create a dashboard

### Steps to reproduce

1. Create a new dashboard
2. Load the new dashboard

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/119393783/d9a8fca2-ff82-428d-90dc-83da73631295)

### Desktop

OS: Windows 11 - OS Build 22621.1702
Browser: Microsoft Edge
Browser Version: 113.0.1774.50 (Official build) (64-bit)

**Comment by hugovalente-pm** [comment]
@Austex-AaronCraig, could you share a bit of more details?
do you have any charts inside the new dashboard? if so what charts have you added?

could you also open the browser dev-tools and check if:
1. there are any errors thrown on the Console
2. any requests on the Network tab fail

**Comment by Austex-AaronCraig** [comment]
@hugovalente-pm I apologize, it's all working now as it took a little while for data to populate & once I had data flowing into netdata it is now working fine without crashing.
