### ISSUE TITLE
[Bug]: changes to custom dashboards are not being saved properly

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#829]
### Bug description

If i change multiple charts in a custom dashboard and save each time, when i go out and come back into the custom dashboard it looks like only the last save is actually being saved. And i loose all my painful work! :) 

Video shows this.

https://github.com/netdata/netdata-cloud/assets/2178292/65876a55-6d3b-4565-a215-44f9b98c56f8

### Expected behavior

Saves should happen as expected and not be lost.

### Steps to reproduce

1. Create a custom dashboard.
2. Make a series of chart changes.
3. See if all changes are being applied.

### Desktop

Browser Version [e.g. 22]

### Additional context

[link](https://app.netdata.cloud/spaces/ml-demo-space/rooms/all-nodes/dashboards/anomaly-detection-diagnostics#metrics_correlation=false&after=-21600&before=0&utc=Europe%2FLondon&offset=%2B1&timezoneName=Edinburgh%2C%20London&modal=addChartModal&modalTab=&6045dc92-0a0c-48d8-960c-d2e0f31aa95d--chartName=menu_apps_submenu_mem&6045dc92-0a0c-48d8-960c-d2e0f31aa95d--selectedNodeIds=&modalParams=) to my custom dashboard

**Comment by novykh** [comment]
Fixed.
