### ISSUE TITLE
[BUG] load chart shows a different time frame than other charts

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#83]
See below, the window was selected from the datetime picker and all charts except load seem to be aligned with that window. It may be because of the different `update_every` that the load chart has (5s default).

![image](https://user-images.githubusercontent.com/43294513/115259049-61489100-a0e6-11eb-9588-94022540b1bc.png)

**Comment by hugovalente-pm** [comment]
This has been sorted with Charts 2.0
