### ISSUE TITLE
[Bug]: NC missing contexts

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#832]
### Bug description

Easier to see in video - basically for some reason on one of my nodes most of the `apps.*` contexts were missing. 

[internal slack thread](https://netdata-cloud.slack.com/archives/CCDD80TL7/p1684940577638129)

https://github.com/netdata/netdata-cloud/assets/2178292/2419ca48-2867-4bf4-86ca-6ebd36985734

### Expected behavior

Contexts should not go missing like this as its one of the worst types of missing data or silent type bugs we could have.

### Steps to reproduce

1. Very hard to reproduce, seems somewhat rare and random as best i can tell.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@MrZammler @juacker any feedback on this? I saw you were discussing this on an internal slack thread

**Comment by hugovalente-pm** [comment]
@andrewm4894 is this something you're still experiencing?

**Comment by andrewm4894** [comment]
No, closing
