### ISSUE TITLE
[Bug]: Overlapping columns in the alert configuration view

### ISSUE THREAD

**Issue by vkuznecovas** [netdata/netdata-cloud#833]
### Bug description

The column values overlap.

### Expected behavior

The column values should not overlap.

### Steps to reproduce

1. Go to the alerts configuration

### Screenshots

<img width="1669" alt="Screenshot 2023-05-29 at 15 09 55" src="https://github.com/netdata/netdata-cloud/assets/18392269/cb599b8f-959f-46d6-a9c7-94690ad7d44b">

### Desktop

OS: MacOS
Browser: Firefox

**Comment by hugovalente-pm** [comment]
this is fixed
