### ISSUE TITLE
[Feat]: ability to send test event for notification integrations

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#834]
### Problem

It would be good if i was able to trigger a test notification as:
* part of setting up an integration
  ![image](https://github.com/netdata/netdata-cloud/assets/2178292/56abbe0e-a9d7-4dcf-adcc-0b7d8dcf1964)

* confirming the correct behaviour of a running setup
  ![image](https://github.com/netdata/netdata-cloud/assets/82235632/0b2a671f-2c73-414b-8629-02d5033cfc12)

Together with this failures to dispatch a notification should be record on the Events feed so users can see the results of failed tests there.

### Description

Often you need to have some test events to work with to make sure whatever integration you are setting up is working as expected. 

Its normal practice to be able to send a test event as part of configuring the integration i think we should have this capability in the app.

### Importance

really want

### Value proposition

1. makes it easier to actually configure and test an integration

### Proposed implementation

- add a test button that will send a dummy notification that adheres to the type of events we would really send but just give it fake or random data. 
- the test button should have a delay mechanism with Fibonacci sequence or something until another test can be ran, to avoid abuse

**Comment by hugovalente-pm** [comment]
this is done
