### ISSUE TITLE
[Feat]: Mattermost notification integration

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#835]
### Problem

Add notification integration on Netdata Cloud for Mattermost

### Description

Please add an integration with Mattermost to Netdata Cloud. 

A webhook exists, that we can use to integrate with it: https://developers.mattermost.com/integrate/webhooks/

### Importance

nice to have

### Value proposition

1. Enables Netdata to be used effectively by organizations relying on Mattermost

**Comment by hugovalente-pm** [comment]
this should probably be for the Business plans

**Comment by car12o** [comment]
deployed to prod
