### ISSUE TITLE
[Feat]: RocketChat notification integration

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#836]
### Problem

Add notification integration on Netdata Cloud for RocketChat

### Description

Please add an integration with RocketChat to Netdata Cloud.

 A webhook exists, that we can use to integrate with it: https://martinschoeler.github.io/docs/administrator-guides/integrations/#:~:text=How%20to%20create%20a%20new%20Incoming%20WebHook%20Go,script%20inside%20the%20Script%20field%20Save%20the%20integration

### Importance

nice to have

### Value proposition

1.Enables Netdata to be used effectively by organizations relying on RocketChat

**Comment by hugovalente-pm** [comment]
this should probably be for Pro plans

**Comment by hugovalente-pm** [comment]
this is released
