### ISSUE TITLE
[Bug]: All nodes in custom dashboards does not seem to just work when new nodes are added. 

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#839]
### Bug description

I made a custom dashboard when i have 1 node in a space - i selected all nodes, i added 2 nodes to the space and my custom dashboard still only shows 1 node for some reason. 

its like i have to then recreate the dashboard again to have the 3 nodes show up. 

video showing what i mean in this internal slack thread: https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1685693861157299

### Expected behavior

custom dashboard should always include all nodes when i have set them up that way. 

### Steps to reproduce

1. see video

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
I believe this is working as per the original design, right @novykh ?

when user creates the custom dashboard he's having the context of the the nodes present at the time, we understand the need to make it flexible and allow to link to a _dynamic_ definition of the All nodes (those now or those at any point in time?) but there is UX/UI discussions that need to happen. it was mentioned at some point if we should have a toggle to say _Apply current Global Nodes Filters?_ or _Apply specific custom dashboard definitions? (were nodes selected when the chart was created, etc.)?_  

Example this links to this FR https://github.com/netdata/netdata-cloud/issues/696

**Comment by hugovalente-pm** [comment]
closing this since this is worked as per design, there is a FR to review this https://github.com/netdata/netdata-cloud/issues/696
