### ISSUE TITLE
[BUG] load chart can return weird results in the overview screen

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#84]
This is something I've never seen on any other chart and may have something to do with the longer `update_every` of the load chart. There are cases when we get a long series of high values/low values for each returned calculated timestamp. The chart looks as follows in these cases. A request that triggered such a chart along with the json response are attached.

![image](https://user-images.githubusercontent.com/43294513/115262225-2e53cc80-a0e9-11eb-8f0e-8e7de1231850.png)

[request.txt](https://github.com/netdata/netdata-cloud/files/6337221/request.txt)

[codebeautify.json.txt](https://github.com/netdata/netdata-cloud/files/6337233/codebeautify.json.txt)

**Comment by hugovalente-pm** [comment]
@cakrit wasn't able to reproduce this, so closing for now.
let me know in case you've seen this recently
