### ISSUE TITLE
[Bug]: AR% button not working as expected

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#842]
### Bug description

AR% button not working as expected

https://github.com/netdata/netdata-cloud/assets/2178292/6bd10916-579e-4d5d-988a-ac1f724e019a

### Expected behavior

The pills with AR% from each manu section should better match the AR ribbon on the charts.

### Steps to reproduce

1. use AR% button

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
was trying to look to the response of the `/weights` endpoint but can't understand if this is an issue on Agent, BE or FE
@novykh @juacker can you take a look?

**Comment by novykh** [comment]
This is fixed on the agent branch and will be released in the next days.

**Comment by andrewm4894** [comment]
[example](https://app.netdata.cloud/spaces/netdata-cloud/rooms/demo-sites/overview#metrics_correlation=false&after=1686920369000&before=1686921095000&utc=Europe%2FLondon&offset=%2B1&timezoneName=Edinburgh%2C%20London&modal=&modalTab=&8ff5f814-5739-45bb-8da9-7fbd41b18cb0--chartName=menu_ipv4_submenu_sockets&modalParams=&highlight_after=1686920843000&highlight_before=1686920945000&8ff5f814-5739-45bb-8da9-7fbd41b18cb0-anomalies-chartName=menu_Anomalous_metrics_submenu_apps_threads__ssh&8ff5f814-5739-45bb-8da9-7fbd41b18cb0--selectedNodeIds=92f8d2f0-d9d3-4696-8399-8b61f2f143d7%2Cb972238a-64cf-4624-8bc5-b46187a99370) where this is not working as expected

(seems be ok for 1 node but then for 2 nodes its not behaving as expected)

**Comment by andrewm4894** [comment]
[example](https://app.netdata.cloud/spaces/netdata-demo/rooms/machine-learning/overview#metrics_correlation=false&after=1687132798000&before=1687133298000&utc=Europe%2FLondon&offset=%2B1&timezoneName=Edinburgh%2C%20London&modal=&modalTab=&d8a4e0c5-7c79-4145-900e-83a9f06fcb6a--chartName=menu_system&ae33f57b-b54e-4236-a6de-054da3f0a748--chartName=menu_mem_submenu_system&ae33f57b-b54e-4236-a6de-054da3f0a748--selectedNodeIds=955470a1-3023-4de0-b2ae-6ed43c988a27%2Cc139d17f-f65b-4d1a-8850-6d2cc4fba26f&modalParams=&highlight_after=1687133090000&highlight_before=1687133238000)

**Comment by andrewm4894** [comment]
This looks to have been deployed to production and is working as expected now - thanks @kapantzak !
