### ISSUE TITLE
[Bug]: alert silencing rule name does not seem to wrap nicely

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#843]
### Bug description

The rule name seems to overflow into next column

![image](https://github.com/netdata/netdata-cloud/assets/2178292/b21d8d55-c0c7-4287-9432-d0f79ae992a2)

### Expected behavior

longer name should wrap a bit nicer?

### Steps to reproduce

1. use alert silencing and make a rule name thats one long word eg like an alert name (common use case)

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this is on internal dogfooding state, so not exposed to users yet

**Comment by andrewm4894** [comment]
ill close this so
