### ISSUE TITLE
[Bug]: When on Community plan, after downgrading from a paid plan, I see the cancel button

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#844]
### Bug description

The cancel button should be disabled on a Community plan

![image](https://github.com/netdata/netdata-cloud/assets/82235632/af609df0-59b3-469a-8158-389cebd38ec7)

### Expected behavior

cancel button should be disabled

### Steps to reproduce

1. Go to a paid subscription
2. Downgrade to Community
3. See that cancel button is enabled

### Desktop

Browser Version [e.g. 22]

**Comment by kapantzak** [comment]
Opened [PR #4237](https://github.com/netdata/cloud-frontend/pull/4237)

**Comment by hugovalente-pm** [comment]
this is fixed
