### ISSUE TITLE
[Bug]: unable to horizontal scroll chart legend in alert tab view

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#846]
### Bug description

i am not able to scroll the legend over to see all dims in the chart on the single alert tab

![image](https://github.com/netdata/netdata-cloud/assets/2178292/6c01f488-85c4-4db9-b3c4-661aca51687b)

https://github.com/netdata/netdata-cloud/assets/2178292/ca4092e1-b81e-4cd6-b40c-997d559f943b

### Expected behavior

i should be able to use horizontal scroll similar to how i can on the chart on the overview tab.

### Steps to reproduce

1. open an alert that relates to a chart with a lot of dims.
2. you will see that you can not scroll the legend to see all the dims.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
closing, will be tracked on https://github.com/netdata/netdata-cloud/issues/861
