### ISSUE TITLE
[Bug]: Charts display as 30 minutes ago for recently added node

### ISSUE THREAD

**Issue by StefanSCO** [netdata/netdata-cloud#848]
### Bug description

I added a new node recently and all the data for all the graphs on this node display as if they are 30 minutes behind and there is no data for the last 30 minutes. To see the data on the graphs at all, I need to zoom out until the chart is displaying a full hour of time. This only applies to the cloud portal, the local web interface displays the graphs correctly. 

### Expected behavior

I would expect the graphs to display the current data at the current time. 

### Steps to reproduce

Has only happened on one node, but
1. open app.netdata.cloud
2. select the problem node
3. zoom out chart until data is visible from the left side of the chart. 

### Screenshots

![Screenshot 2023-06-12 at 8 53 43 AM](https://github.com/netdata/netdata-cloud/assets/135734829/5a162fd6-dc72-432d-9e61-c414f2cbb4a3)
![Screenshot 2023-06-12 at 8 54 11 AM](https://github.com/netdata/netdata-cloud/assets/135734829/5dd891f9-5204-4d62-8a1f-c775a2ac0332)

### Error Logs

[app.netdata.cloud.har.zip](https://github.com/netdata/netdata-cloud/files/11724876/app.netdata.cloud.har.zip)

### Desktop

OS: MacOS 13
Browser: Google Chrome
Browser Version: 113.0.5672.126 (Official Build) (arm64)

**Comment by hugovalente-pm** [comment]
@StefanSCO could you had a screenshot of the local agent dashboard as well?

**Comment by StefanSCO** [comment]
Yes, see attached. These are what I see when I open the local web interface and the cloud interface without adjusting the time frame on either.  
![Screenshot 2023-06-14 at 11 57 59 AM](https://github.com/netdata/netdata-cloud/assets/135734829/0cfc70c2-7f3c-4598-b1ee-0560a95f60ea)
![Screenshot 2023-06-14 at 11 58 35 AM](https://github.com/netdata/netdata-cloud/assets/135734829/d37d3385-b343-4118-97a8-ff2c0897b0a5)

**Comment by hugovalente-pm** [comment]
@StefanSCO was looking into the details of your space and it seems that this node `graylog` has a different timezone compared to the other.
If you look at the datetime picker on the agent it shows UTC-6, could you opne the datetime picker on Cloud and check what timezone is selected there?

**Comment by StefanSCO** [comment]
The timezone was the same, but the system clock was wrong on this server. timedatectl showed the NTP service as active, but the system clock wasn't synchronized. I fixed my Chrony config and everything started functioning correctly. @hugovalente-pm, thank you for your help! I'll check timedatectl first next time.
