### ISSUE TITLE
[Feat]: Upgrade warnings should not consider Offline nodes

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#853]
### Problem

When pointing users to upgrade their agents because of the recommended version or latest stable we should remove the `Offline` nodes from those reports
User won't probably be able to do any actions, for example if these are ephemeral nodes, besides deleting the nodes from Cloud.

![image](https://github.com/netdata/netdata-cloud/assets/82235632/706da20c-d161-4256-83de-22a513b117d2)

### Description

When giving warnings about Critical/Warning upgrades don't consider Offline nodes

### Importance

really want

### Value proposition

1. Remove clutter for nodes users won't probably do any action on

**Comment by hugovalente-pm** [comment]
@kapantzak let's also fix the issue we saw on the table
![image](https://github.com/netdata/netdata-cloud/assets/82235632/0d74cff6-e77d-49a5-b846-0187f1c053a4)

**Comment by hugovalente-pm** [comment]
and this 
![image](https://github.com/netdata/netdata-cloud/assets/82235632/51a07fe2-ffa5-44f8-969e-52798094b928)

**Comment by kapantzak** [comment]
Opened [Pull Request #4251](https://github.com/netdata/cloud-frontend/pull/4251)

**Comment by kapantzak** [comment]
Temporary test environment deployed --> [https://cloud-frontend-4251.tmp-env.testing.netdata.cloud](https://cloud-frontend-4251.tmp-env.testing.netdata.cloud)

**Comment by hugovalente-pm** [comment]
not sure something related with what we did but I see some issue on the badges on Central Administration Interface
![image](https://github.com/netdata/netdata-cloud/assets/82235632/722d7b31-56b4-4e30-a26d-a0280c577940)

**Comment by hugovalente-pm** [comment]
this is done
