### ISSUE TITLE
[Bug]: alert urls do not seem to be working

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#856]
### Bug description

when i click an alert link in slack or email i see this:

![image](https://github.com/netdata/netdata-cloud/assets/2178292/67c0d503-7531-49e1-9d3e-0b18ee2b843a)

### Expected behavior

the link should take me to the alert tab as expected

### Steps to reproduce

1. click a link in an alert

### Desktop

Browser Version [e.g. 22]

### Additional context

[internal slack thread with discussion](https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1687275451982169)

**Comment by hugovalente-pm** [comment]
this is fixed
