### ISSUE TITLE
[Bug]: Custom dashboards require saving even when there are no changes performed

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#857]
### Bug description

After visiting dashboards tab and opening a custom dashboard for save, we prompt the user to save the changes even when there are no changes performed to the dasboard, user cannot change tabs and leave this view if he doesn't dismiss the save work popup

### Expected behavior

No changes to custom dashboards shouldn't require saving

### Steps to reproduce

1. Navigate to Netdata Cloud
2. Switch to Dashboards tab
3. open an existing custom dashboard (create one if nothing exists)
4. Leave the page without performing any changesn

### Desktop

OS: Macos
Browser Chrome
Browser Version  113

**Comment by novykh** [comment]
Fixed.
