### ISSUE TITLE
[BUG] Alarm Details showing the alarm calculation encoded

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#86]
See below how the "/" character appears on Alarm Details. The strange thing is that initially it appears as "/" but after about 1 sec the character is replaced with the gibberish you see in the screenshot. You should be able to see it on any `cgroup_ram_in_use` alarm.

![image](https://user-images.githubusercontent.com/43294513/115908426-0208ba80-a41f-11eb-9d26-33cd4e0d3da3.png)

**Comment by dimko** [comment]
This has been fixed. Closing
