### ISSUE TITLE
[Bug]: Notification Integrations Discord URL is reported as invalid

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#860]
### Bug description

The webhook URL below is reported as invalid

![image](https://github.com/netdata/netdata/assets/82235632/ca0271ee-8134-4842-a047-1f1cfc211caa)

### Expected behavior

Being an URL generated by Discord it should be valid

### Steps to reproduce

1.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@juacker I think you worked on this so pinging you here to check how we go about validating these URLs

**Comment by juacker** [comment]
I see the PTB is a testing version of Discord, that receives some features before they are released on the stable version. I don't see a problem allowing discords URLs for this version, will create a PR to allow them

**Comment by juacker** [comment]
fix released
