### ISSUE TITLE
[Bug]: chart seems cut off in alert tab

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#861]
### Bug description

when i click an alert to land on alert view tab - it seems the chart itself flows off to the left of the screen so i cant actually interact with it

<img width="953" alt="image" src="https://github.com/netdata/netdata-cloud/assets/2178292/0e01292f-1a19-464f-a2f2-c1fee196b8df">

### Expected behavior

i should be able to just use the chart as normal and see it all on my screen

### Steps to reproduce

1. go to a single alert tab and see if you can see the full chart

### Desktop

Browser Version [e.g. 22]

**Comment by andrewm4894** [comment]
actually maybe this is a dupe of https://github.com/netdata/netdata-cloud/issues/846

**Comment by hugovalente-pm** [comment]
it seems a dupe but the other was focused on the legend
will close the other one and keep this.

also this happens on smaller viewports, the chart doesn't _adapt_ to the available space on the viewport

**"Normal"** - here it doesn't take the full available space
![image](https://github.com/netdata/netdata-cloud/assets/82235632/402c568c-b5a9-4eaf-aa30-48b59acc7c17)


**Reduced**
![image](https://github.com/netdata/netdata-cloud/assets/82235632/7786a1e6-8893-4e1d-88fa-4edfedefeecd)

**Comment by novykh** [comment]
Fixed.
