### ISSUE TITLE
[Bug]: Agent will not log in to cloud

### ISSUE THREAD

**Issue by KK4ECR** [netdata/netdata-cloud#862]
### Bug description

NetData Agent running on Truenas will not let me login to the cloud from the agent.  The agent says it is connected but not logged in to the cloud.

### Expected behavior

WHen Asked to login to the cloud, from the agent, I shoudl be able to log in.

### Steps to reproduce

1. Open Agent web address
2. click on SIgn in in any of the sign in locations
3. either get an error or it just goes back to the agent without signing in to the cloud

### Desktop

OS: [e.g. iOS]	True NAS
Browser [e.g. chrome, safari]	tried both Firefox and chrome
Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
could you open your devtools console on your browser and check what errors you have both on the Console and on the Network tabs?

**Comment by hugovalente-pm** [comment]
@KK4ECR checking if you saw our previous message. are you still facing this issue? if yes, provide the information mentioned above.

**Comment by hugovalente-pm** [comment]
closing this bug due to no response, if this still persist let us know
