### ISSUE TITLE
[Feat]: increase coverage of missing icons for collectors

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#863]
### Problem

below is a list of collectors that seem to be missing icons in NC (i will add more as i find them)

- [ ] elasticsearch
- [ ] nvidia_smi
- [ ] alarms
- [ ] pandas
- [ ] dns query
- [ ] random
- [ ] example
- [ ] asterisk
- [ ] dnsmasq
- [ ] dnsmasq-dhcp

### Description

would be nice to have nice icons for everything

### Importance

nice to have

### Value proposition

1.

**Comment by hugovalente-pm** [comment]
this was done
