### ISSUE TITLE
[Bug]: Error Clicking on Alert Configuration

### ISSUE THREAD

**Issue by r-walter** [netdata/netdata-cloud#868]
### Bug description

Oops, something unexpected happened!

### Expected behavior

Access to the Alert Configuration tab

### Steps to reproduce

1. Click the Alert Configuration tab

### Screenshots

![Error - Alert Configuration NetData](https://github.com/netdata/netdata-cloud/assets/139411749/1432fbc8-890c-4ab1-9779-fb15251a213c)

### Error Logs

Found this error in Chrome Developer Tools:
TypeError: e.map is not a function
    at 451.a6f7f9858e241afb005c.chunk.js:1:13413
    at li (npm.react.dom.1ffe59388e888b6afb99.js:2:94310)
    at xs (npm.react.dom.1ffe59388e888b6afb99.js:2:114537)
    at npm.react.dom.1ffe59388e888b6afb99.js:2:111127
    at _ (493.fdd7dcd2a8ca36bb46bf.js:2:1616008)
    at MessagePort.P (493.fdd7dcd2a8ca36bb46bf.js:2:1616542)
(anonymous) @ 493.fdd7dcd2a8ca36bb46bf.js:2
du @ npm.react.dom.1ffe59388e888b6afb99.js:2
a.componentDidCatch.t.callback @ npm.react.dom.1ffe59388e888b6afb99.js:2
Ua @ npm.react.dom.1ffe59388e888b6afb99.js:2
wi @ npm.react.dom.1ffe59388e888b6afb99.js:2
ki @ npm.react.dom.1ffe59388e888b6afb99.js:2
ki @ npm.react.dom.1ffe59388e888b6afb99.js:2
ki @ npm.react.dom.1ffe59388e888b6afb99.js:2
ki @ npm.react.dom.1ffe59388e888b6afb99.js:2
ki @ npm.react.dom.1ffe59388e888b6afb99.js:2
ki @ npm.react.dom.1ffe59388e888b6afb99.js:2
ki @ npm.react.dom.1ffe59388e888b6afb99.js:2
bi @ npm.react.dom.1ffe59388e888b6afb99.js:2
(anonymous) @ npm.react.dom.1ffe59388e888b6afb99.js:2
Ss @ npm.react.dom.1ffe59388e888b6afb99.js:2
ss @ npm.react.dom.1ffe59388e888b6afb99.js:2
Hl @ npm.react.dom.1ffe59388e888b6afb99.js:2
xs @ npm.react.dom.1ffe59388e888b6afb99.js:2
(anonymous) @ npm.react.dom.1ffe59388e888b6afb99.js:2
_ @ 493.fdd7dcd2a8ca36bb46bf.js:2
P @ 493.fdd7dcd2a8ca36bb46bf.js:2

### Desktop

Browser Version [e.g. 22]
OS: Windows 11 Pro 22H2 22621.1992
Chrome: Version 114.0.5735.199 (Official Build) (64-bit)
MS Edge: Version 114.0.1823.79 (Official build) (64-bit)
Firefox: 115.0.2 (64-bit)

**Comment by hugovalente-pm** [comment]
thanks for reporting this, we've happened an incident and are currently investigating this
https://status.netdata.cloud/incidents/nwk6jvcy41cd

**Comment by hugovalente-pm** [comment]
the crashing issue is fixed, there is other work in-progress but not related to this bug report:
> We have applied a fix that allows for seeing all configured alerts again, but the detail page for individual alerts may still not render. We are working on addressing that latter issue.

**Comment by r-walter** [comment]
Thanks
