### ISSUE TITLE
[Bug]: Copy to clipboard doesn't copy content

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#869]
### Bug description

Clicking the copy buttons in any of the text boxes in netdata cloud doesn't seem to copy the contents of the text box

### Expected behavior

I should be able to paste what I copied through netdata cloud after clicking the copy to clipboard button e.g claim command, sapce id etc

### Steps to reproduce

1. Click Add nodes
2. Copy claim command

### Error Logs

No errors in logs

### Desktop

OS: Macos
Browser Chrome
Browser 113

**Comment by dimko** [comment]
reducing to low as issue can be bypassed by...selecting the text and copy! (duh!)

**Comment by ralphm** [comment]
If this is the same issue as the copy button not working for getting the JSON representation in the node info and event details, then no, you cannot select the text and copy. There is ticket open for having a JSON _view_, but until then, there is no workaround.

**Comment by hugovalente-pm** [comment]
this is fixed
