### ISSUE TITLE
[Bug]: Adding extra metric in nodes tab crashes page when no data exist for that period

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#870]
### Bug description

Adding extra metric in nodes tab crashes page when no data exist for that period

### Expected behavior

It shouldn't crash

### Steps to reproduce

1. Claim a new node
2. Highlight a time period where agent doesn't have data
3. Navigate to Nodes tab
4. Click to Add new metric
5. Page crash

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/19268853/2b56373a-f52b-4b49-a25c-db04e3fd0c27)

![image](https://github.com/netdata/netdata-cloud/assets/19268853/8fef2c64-ca45-4c40-9d52-7155359e8d40)

### Error Logs

`npm.react.dom.fd9b4001af81902e8957.js:2 No data for this period`

### Desktop

OS: Ubuntu
Browser Chrome
Browser Version 113

**Comment by novykh** [comment]
I believe this is fixed for a long time.
