### ISSUE TITLE
[Bug]: Links in event descriptions don't work

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata-cloud#871]
### Bug description

Each event in the events tab has a description in the table, which some identifiers highlighted and hot-linked to have a quick path to other pages describing the corresponding entity. This includes specific alerts, charts, and nodes, linked by name. For alerts all links now point to `https://app.netdata.cloud/spaces/{space}/rooms/{room}/alerts/undefined`, and the others link to `https://app.netdata.cloud/spaces/{space}/rooms/{room}/events`.

### Expected behavior

Each link should be to the respective locations for nodes (node view), charts (chart in the overview tab), alerts (probably the alert detail page for that specific transition, by ID).

### Steps to reproduce

1. Open the event tab
2. Hover over the bolded parts of an event's description.
3. Observe incorrect URLs.

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/116741/80c94675-189a-4d2a-8126-4f2da3453f9f)

### Desktop

OS: Ubuntu 23.04
Browser: Firefox
Browser Version: 116.0b5

**Comment by ralphm** [comment]
Having rechecked this, the `undefined` issue seems gone, so the hot-linked alert names now do work. The others still point to `.../events`.

**Comment by hugovalente-pm** [comment]
was checking this on my local agent and they seem to be working now, I mean besides the `undefined` that you mentioned that it was fixed already

**Comment by hugovalente-pm** [comment]
was looking to the links and found an issue on this one
![image](https://github.com/netdata/netdata-cloud/assets/82235632/690e299c-96a9-42ba-9577-81db4712da6e)

if I click on the alert name I get the alert landing page
![image](https://github.com/netdata/netdata-cloud/assets/82235632/35dced75-8245-4adc-ab74-defc8e3dff0e)

but if I click the Alert instance I'm just directed to the single node page not the chart with the context (and the chart instance) for the alert

**Comment by novykh** [comment]
Fixed.
