### ISSUE TITLE
[Bug]: functions tab does not work on local ui

### ISSUE THREAD

**Issue by vkuznecovas** [netdata/netdata-cloud#872]
### Bug description

The functions tab refuses to render on the local agent dashboard when signed in to cloud.

<img width="1439" alt="Screenshot 2023-07-14 at 16 37 57" src="https://github.com/netdata/netdata-cloud/assets/18392269/60a4dcd1-1742-44b2-8ff1-037843ff2fc6">

Console output:

```
TypeError: o is undefined
```

### Expected behavior

I would expect the tab to render.

### Steps to reproduce

1. Claim an agent to cloud
2. Open local dashboard
3. On local space(agent), go to functions tab.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this is what you see now
![image](https://github.com/netdata/netdata-cloud/assets/82235632/921c442b-07a3-4b06-9a42-29704772ce13)
