### ISSUE TITLE
[Bug]: Notification settings do not render properly on agent local ui

### ISSUE THREAD

**Issue by vkuznecovas** [netdata/netdata-cloud#873]
### Bug description

When notification settings are opened, the settings tab is empty.

<img width="1363" alt="Screenshot 2023-07-14 at 16 41 14" src="https://github.com/netdata/netdata-cloud/assets/18392269/fb1636c2-ff0f-4248-a927-26990560b06e">

### Expected behavior

This tab should not be empty

### Steps to reproduce

1. Open local agent ui.
2. Sign in to the cloud.
3. Go to a space that exists on the cloud.
4. Click the notification settings button on the bottom left.

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
this is what you see now, both an the "virtual" space and the one that exists
![image](https://github.com/netdata/netdata-cloud/assets/82235632/7a2f26f2-a8c0-4856-b1f6-ddc9cce7df93)
