### ISSUE TITLE
[Bug]: Events tab crashes on local agent ui

### ISSUE THREAD

**Issue by vkuznecovas** [netdata/netdata-cloud#874]
### Bug description

Events tab crashes if opened in the local agents space when not signed in.

<img width="1139" alt="Screenshot 2023-07-14 at 16 55 47" src="https://github.com/netdata/netdata-cloud/assets/18392269/3dcec36f-19a8-4dea-a694-d9757ead8859">

### Expected behavior

Tab is not expected to crash

### Steps to reproduce

1. Sign out off of cloud.
2. Start agent.
3. Go to local ui.
4. Go to events tab.

### Desktop

OS: MacOS
Browser Firefox

**Comment by ralphm** [comment]
I got this in Firefox. Chrome seems to work for me.

**Comment by hugovalente-pm** [comment]
error raised - something unexpected happened. Raises `TypeError: 0 is undefined`

**Comment by ralphm** [comment]
This appears to be fixed in FE 6.21.0.
