### ISSUE TITLE
[Bug]: When viewing a cleared alert, it shows "Triggered" in the "Time Values" section

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#878]
### Bug description

When viewing a cleared alert, it shows "Triggered" in the "Time Values" section, and "Triggered value" on the chart and in the tooltip of the value in "Instance Values". That doesn't make sense, as there is no trigger when an alert is clear. 

### Expected behavior

Maybe we can use "Cleared" instead of "Triggered" for this case

### Steps to reproduce

1. Got to the Alert Config tab
2. Open any alert in Cleared

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/82235632/689a4f0d-0d7d-419e-9731-0a85f75dbb8d)

### Desktop

Browser Version [e.g. 22]

**Comment by ralphm** [comment]
Also in the tooltip for the value here:

![image](https://github.com/netdata/netdata-cloud/assets/116741/648eecc9-b366-4218-b2d0-8402ca5ceb3a)

**Comment by novykh** [comment]
Will be fixed on next release.
