### ISSUE TITLE
[Bug]: overview search bar looks misalligned

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#881]
### Bug description

![image](https://github.com/netdata/netdata-cloud/assets/2178292/22a35ac0-88ef-4e17-a79c-c3fa75fb5be7)

### Expected behavior

like it was before

### Steps to reproduce

1. go [here](https://app.netdata.cloud/spaces/netdata-demo/rooms/all-nodes/overview#metrics_correlation=false&after=-900&before=0&utc=Europe%2FLondon&offset=%2B1&timezoneName=Edinburgh%2C%20London&modal=&modalTab=&d8a4e0c5-7c79-4145-900e-83a9f06fcb6a--chartName=menu_system)

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@novykh is this something you can fix fast?

**Comment by hugovalente-pm** [comment]
@christophidesp just checking if this is something you could probably give a hand?

**Comment by novykh** [comment]
Already fixed will be released soon.

**Comment by novykh** [comment]
Fixed
