### ISSUE TITLE
[Feat]: Support data-legend-position="bottom" in custom dashboard

### ISSUE THREAD

**Issue by zDEFz** [netdata/netdata-cloud#887]
### Problem

Custom dashboards legend is always on the right and `data-legend-position="bottom"` is ignored, even with the class...
```<div data-netdata="smartd_log.read_error_rate" class="netdata-container-with-legend netdata-container-with-legend--bottom" data-legend="yes" data-legend-position="bottom"></div>```

### Description

Add functionality for placing the legend in other positions, like the bottom

### Importance

really want

### Value proposition

The original dashboard is overwhelming and cannot be configured easily to show exactly what I want. Thats why A custom dashboard was created, but now I cannot place the legends where I want them to be.

**Comment by fzyzcjy** [comment]
+1 Did you solve it?

**Comment by zDEFz** [comment]
> +1 Did you solve it?

Kinda. I stopped using netdata.

**Comment by fzyzcjy** [comment]
@zDEFz Then what do you use now? I also noticed the shortcomings of netdata, but I do like its tons of metrics collected per second, thus would like to hear alternatives.

**Comment by MrZammler** [comment]
Hi!

We're sorry this has slipped... Would it be possible though to mention some of the shortcomings? We would like some of this feedback. @fzyzcjy are you still interested in the original request ? (again sorry for this being missed).

**Comment by fzyzcjy** [comment]
@MrZammler Hi thanks for the reply! 

> Would it be possible though to mention some of the shortcomings?

Netdata is great, but because of https://github.com/netdata/netdata/issues/9777 I have to use netdata agent only, *without* netdata cloud. Then it is quite limited because it is hard to aggregate data. :/

> are you still interested in the original request ?

Yes. Without netdata cloud, I have to write some scripts to put metrics of multiple machine in one webpage, thus this issue is helpful.

**Comment by zDEFz** [comment]
> @zDEFz Then what do you use now? I also noticed the shortcomings of netdata, but I do like its tons of metrics collected per second, thus would like to hear alternatives.

I have the metrics displaying seperately in a terminal window via a collection of bash commands over ssh.

One of the major drawbacks of netdata was the difficulty to setup S.M.A.R.T. Even after it had been succesfully setup, after some time, it just stopped working and I had to restart netdata / smartd a couple times. HDD stats being something I would expect to be fundamental, should be really easy to implement and even with very little effort.

Think about it - smartctl tells me those things - there is no need for me to bother with netdata and see it fail to display temperature etc reliably.

Not to mention, there are confusing alert formulas in which the user is meant to derive when a alert will be triggered. Those need to be simplified and explained. As a user, I feel really left alone.

I'd like to see more options, also to configure my local instance - without Netdata Cloud. If Netdata doesnt come with S.M.A.R.T stats/scanning by default, give me the option via the interface to enable/install it. The last thing I want as a user is to bash into the docker image of it and then modify configuration files. 

Exporting / importing the whole configuration would be also something I'd like to see.

**Comment by fzyzcjy** [comment]
@zDEFz I see, thanks for the information (though my case seems to be quite different, so the solution does not work for my case)

**Comment by hugovalente-pm** [comment]
this is outdated, so closing
