### ISSUE TITLE
[Bug]: "No spaces found"

### ISSUE THREAD

**Issue by pzwahlen** [netdata/netdata-cloud#889]
### Bug description

After upgrading some agents to 1.41, one of them couldn't be reached from netdata-cloud.

While searching for a solution it might be that I acccidentally deleted a space and now I cannot reach netdata-cloud anymore.

I have totally cleared my local storage and cookies and when I re-register I instantly get the "No speces found" error, similar to [#589](https://github.com/netdata/netdata-cloud/issues/539)

Cheers, and thanks for the great work on Netdata!

### Expected behavior

Netdata-cloud should be reachable

### Steps to reproduce

1. Clear browser local storage and cookies
2. Go to app.netdata.com
3. Request link
4. Follow received link

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/11704985/508ff0bf-2cfe-4fa2-a5a7-9304ad34cca2)
![image](https://github.com/netdata/netdata-cloud/assets/11704985/b5c3d5c8-80fb-4e0a-9cc9-676a0c22d63f)

### Desktop

OS: Windows 11 22H2
Browser: Chrome
Browser Version: 114.0.5735.201

**Comment by andrewm4894** [comment]
hmm - i think maybe you might need to create a new space potentially (assuming the old one was deleted by mistake) and then claim (or "re-claim" if needed) the nodes into the new one?

when in the new space then you might need to append `--claim-id "$(uuidgen)"` to generate a new claim id and so "re-claim" the nodes into the new space. ([step 4](https://learn.netdata.cloud/docs/configuring/connect-agent-to-cloud#remove-and-reconnect-a-node))

I think if the space has been deleted you might to even need to do this - you might just need to claim the nodes in your fresh new space. 

trying to think if this is a bug or more a side effect of the space being deleted by mistake and so we are no longer on the "happy path" :)

**Comment by pzwahlen** [comment]
Hi and thanks for the super-quick response.

I didn't occur to me that creating a new space on an agent's local dashboard would actually help solve the cloud situation, but it did!

I'm now back to my original issue: my local dashboard is protected by basic auth (via haproxy) and sisnce 1.41 I cannot browse the local dashboard anymore. I am getting an auth popup and auth fails (despite haproxy being happy).

I'll close this issue and open a new one if I needed. Thanks for everything!

**Comment by andrewm4894** [comment]
Oh yes @pzwahlen please do open new issue as any haproxy and local dashboard issues are defo something we need to figure out now that we are attempting to load the latest cloud dashboard and then fall back to locally packaged last version of it. So defo worth a new issue if you having trouble and we can see who can help us.
