### ISSUE TITLE
[Bug]: Room ID empty after refreshing page in Connect Node view

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#897]
### Bug description

After opening the connect node modal and clicking to display the Room ID on the top right corner room ID comes out as empty

### Expected behavior

I should be able to get the Room ID from the connect node modal

### Steps to reproduce

1. NAvigate to a space WITHOUT any connected nodes
2. Refresh the page
3. Click connect a node on the Integrations view blank slate
4. In the connect node modal click Room ID on the top right corner of the screen
5. Room ID is empty

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/19268853/e8de88ef-7f2f-400a-92bc-7c89a5a2b2b3)

### Error Logs

No console error of any kind

### Desktop

OS: MacOS
Browser Chrome
Browser Version 115.0.5790.114

**Comment by hugovalente-pm** [comment]
@kapantzak this seems to be triggered by step 2. if you don't refresh the page it works.
can you take a look?
