### ISSUE TITLE
Drag and drop a card out of the window in a dashboard

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#9]
**Describe the bug**	

**To Reproduce**	
Steps to reproduce the behavior:	Drag a card out of the dashboard. https://www.youtube.com/watch?v=VtAZu_sFoQ4&feature=youtu.be&ab_channel=max232

**Expected behavior**	
The user should be able to see the card which goes out

**Comment by cakrit** [comment]
Shouldn't be on @jacekkolasa , it's for the visualizations team.

**Comment by novykh** [comment]
what's the bug?

**Comment by manos-saratsis** [comment]
Fixed with @apostolidhs magic
