### ISSUE TITLE
[Feat]: Show a more informative warning message if a machine's OS version is EOL/unsupported.

### ISSUE THREAD

**Issue by josephrocca** [netdata/netdata-cloud#900]
### Problem

Current error message (shown below) is misleading.

### Description

![image](https://github.com/netdata/netdata-cloud/assets/1167575/35a76515-c2b2-4807-949d-6e6a87bfbb51)

This message should tell the user that the machine's OS is EOL and not supported (i.e. stuck on an older version), and it should be dismiss-able.

### Importance

nice to have

### Value proposition

1. I wasted half an hour trying to upgrade the netdata version on Ubuntu 18.04: https://github.com/netdata/netdata/issues/15756

**Comment by hugovalente-pm** [comment]
platform versions supported can be checked on https://learn.netdata.cloud/docs/installing/platform-support-policy#currently-supported-platforms
the message has been made dismisable
