### ISSUE TITLE
[Bug]: Chart settings get lost when switching tabs

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#903]
### Bug description

When I'm looking at a chart and make some changes to settings like group by, filter selections (nodes, instances, dimensions, etc.)  these are lost when I switch between tabs
![image](https://github.com/netdata/netdata-cloud/assets/82235632/f0b4bbe8-21aa-4b30-a9a7-7666117ae9be)

Note: this was supported before the release of the new UI on the agent

### Expected behavior

Settings should be kept because these are crucial when users are on a troubleshooting journey, having to re-do all the settings again doesn't help on the process

### Steps to reproduce

1. Go to a chart on Overview or Single Node view
2. Update some setting on the NIDL framework
3. Switch to some other tab and come back
4. See that the previous settings are lost

### Desktop

Browser Version [e.g. 22]

**Comment by novykh** [comment]
This will be part of the personal settings feature. Closing the bug.
