### ISSUE TITLE
[Bug]: double message on magic link sign in 

### ISSUE THREAD

**Issue by car12o** [netdata/netdata-cloud#906]
### Bug description

When sign-in with magic link, two contradictory messages are shown. In my case, the failed message (red) is incorrect as I did receive the email.

### Expected behavior

Only one message should be displayed.

### Screenshots

[Screencast from 2023-08-11 14-17-58.webm](https://github.com/netdata/netdata-cloud/assets/26550862/cd4119c5-d86d-4e2c-b516-1dd3f0dcc45d)

### Desktop

OS: Linux Manjaro
Browser: Brave
Browser Version: Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)

**Comment by hugovalente-pm** [comment]
@car12o can you still reproduce this? I just tried and it is working ok


https://github.com/netdata/netdata-cloud/assets/82235632/92b03b54-24d2-44ce-b1b1-d16d945d352d

**Comment by car12o** [comment]
indeed, this seems to have been fixed, closing.
