### ISSUE TITLE
[Bug]: top dim is not shown on chart hover for apps charts

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#911]
### Bug description

when hovering on some charts recently i have noticed that i am not able to tell what the top dim is as the ordering on hover seems wrong. 

in picture - why is big purple thing not top of legend dims:

![image](https://github.com/netdata/netdata-cloud/assets/2178292/b7f592ec-3242-4747-acf8-a4aaec3e6c78)

it is for maybe like 10% of them as i would expect:

![image](https://github.com/netdata/netdata-cloud/assets/2178292/72104a77-b6e8-4625-a036-05c05429026e)

as best i can see so far its just `apps` charts which is strange and makes me wonder if data related and interpolation or something. 

### Expected behavior

The hover legend on a point should be sorted to show biggest values first as it usually does. 

### Steps to reproduce

1. use a stacked chart in apps. and hover on some points. 

### Screenshots

https://github.com/netdata/netdata-cloud/assets/2178292/40f7f143-9bab-4e48-bd01-e474fb247c9b

### Desktop

Browser Version [e.g. 22]

**Comment by andrewm4894** [comment]
I see it in `apps` and also `services`.

**Comment by hugovalente-pm** [comment]
this is somehow related to this https://github.com/netdata/netdata-cloud/issues/736

**Comment by novykh** [comment]
Fixed.
