### ISSUE TITLE
[Feat]: What to do after installation?

### ISSUE THREAD

**Issue by kronkinatorix** [netdata/netdata-cloud#912]
### Problem

The documentation suffers from a significant gap. While there are reams of information on how to install it and seem to be a lot of info for the things it can, I'm absolutely lost with what I'm supposed to do after it's installed. Is there a web interface I'm supposed to use? There's a netdata process running which is cool and all but I've got no clue what I'm supposed to do with it. Assuming that the program wanted the blood of the innocent, I've sacrificed some local children to netdata in a bloody ritual and may now be wanted by the police, which is a risk I was willing to take, however, I still have no clue what comes after install. 

### Description

Configuration? Demonic rituals? Terminal commands? I have no earthly what comes next. 

### Importance

must have

### Value proposition

1.
Do you want people trying the platform out and bailing out of frustratoin due to something that... I mean how is this not included already? There's so much documentation. How does it not occur to anyone to include the, what, 3 lines it would take to explain ahow to access... the web interface? I have no earthly idea. 

### Proposed implementation

Come on.

**Comment by hugovalente-pm** [comment]
@kronkinatorix thanks for the feedback and we for sure can make improvements on the documentation and one possible cause of confusion was when a new UI was released on the Agent where a previous page was moved to _legacy_
Current page: https://learn.netdata.cloud/docs/visualizations/accessing-netdata-dashboards
Previous page: https://learn.netdata.cloud/docs/visualizations/legacy-agent-dashboard

we can also add this to the [main README](https://github.com/netdata/netdata/blob/master/README.md) of the `netdata/netdata` repo.

there is one place though where we share some suggestions which is right after the installation where we should mention the local dashboard as well
![image](https://github.com/netdata/netdata-cloud/assets/82235632/2145fe7f-9680-48fd-bce2-beb8dfe8b23d) - feature request on the agent for this https://github.com/netdata/netdata/issues/15924

**Comment by hugovalente-pm** [comment]
this was done
![image](https://github.com/netdata/netdata-cloud/assets/82235632/973adf28-016c-499c-b141-1083d6b09d50)
