### ISSUE TITLE
[Bug]: No emails about alerts

### ISSUE THREAD

**Issue by GarrisonD** [netdata/netdata-cloud#913]
### Bug description

I don't receive any emails about warning/critical alerts even when everything is enabled in space/user settings.

### Expected behavior

I receive emails about alerts.

### Steps to reproduce

1. Trigger an alert on one of the nodes

### Screenshots

Space settings:
<img width="1440" alt="Screenshot 2023-08-28 at 21 35 02" src="https://github.com/netdata/netdata-cloud/assets/13675895/ae8393c4-a963-4739-bd5a-885a4e3c0b23">

User settings:
<img width="717" alt="Screenshot 2023-08-28 at 21 36 46" src="https://github.com/netdata/netdata-cloud/assets/13675895/964fd373-8896-466b-bee3-651525188ef5">

### Desktop

OS: macOS Ventura 13.5.1
Browser: Google Chrome 
Browser Version: 116.0.5845.110 (Official Build) (x86_64)

**Comment by andrewm4894** [comment]
@GarrisonD can you email me your email address for the alerts and I can have a look in the backend to see if it can shed any light on things.

My email is andy@netdata.cloud.

**Comment by GarrisonD** [comment]
@andrewm4894 done

**Comment by hugovalente-pm** [comment]
we engaged with @GarrisonD through email and confirmed that all expected alert notifications were going through.
we clarified that some alert configurations were reviewed to actually be silenced in terms of notifications. there was a PR to review the stock alerts and see which alerts should (as per our understanding) notify/awake people https://github.com/netdata/netdata/pull/15590
