### ISSUE TITLE
[Bug]: Dropdowns not working properly

### ISSUE THREAD

**Issue by caduma** [netdata/netdata-cloud#914]
### Bug description

Some dropdowns are not working properly for me. 
Not sure on the other ones but I've seen more for sure, I will add them whenever I see them again.

### Expected behavior

Show a full dropdown, the top one is working properly.

### Steps to reproduce

1. Open the settings tab

### Screenshots

![Screenshot from 2023-09-01 15-30-56](https://github.com/netdata/netdata-cloud/assets/32620114/25333fb8-a5b0-4fa6-aa50-5971314d83be)

### Desktop

OS: [e.g. iOS]	Ubuntu 20.04
Browser [e.g. chrome, safari] Chrome
Browser Version [e.g. 22] 114.0.5735.198 (Official Build) (64-bit)

**Comment by hugovalente-pm** [comment]
@caduma are you still experiencing this issue? was trying to reproduce it from the User Profile -> Notifications tab and couldn't

**Comment by hugovalente-pm** [comment]
we weren't able to reproduce the issue and no recent reports were added.
closing the bug, let us know if you experience this again
