### ISSUE TITLE
[Feat]: Okta SSO

### ISSUE THREAD

**Issue by ss-mbrancato** [netdata/netdata-cloud#917]
### Problem

We would like to leverage SSO to enable access to not just netdata but if possible even rbac permissioning for war rooms.

### Description

Enable Okta SSO
Allow for rbac and war room access via okta groups  

### Importance

really want

### Value proposition

1. Allows another method for SSO
2. Allows larger orgs to better implement RBAC lifecycle policies

**Comment by hugovalente-pm** [comment]
we picked this up recently focusing on the SSO, assuming that this "Allows larger orgs to better implement RBAC lifecycle policies" doesn't apply to managing user directories and mapping to user creationd and roles on Netdata

@ss-mbrancato if we need some early inputs/validation we'll let you know
