### ISSUE TITLE
[BUG] strange date axis behaviour in Overview screen.

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#92]
**Describe the bug**	
In the overview screen a recent window of time is being cut off for some reason. 

**To Reproduce**	

Create a new space, claim 2 or mode nodes into it. 

**Expected behavior**	
I should not have the axis jump around like this. 	

**Screenshots**	
![image](https://user-images.githubusercontent.com/2178292/117687985-42529180-b1b0-11eb-9543-c4a825cb7472.png)

here is a link to a video with much more detail: https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1620660255075800

**Desktop (please complete the following information):**	
 - OS: Windows	
 - Browser: Chrome

**Additional context**	
It seems to happen at the start of the life of a room so will only be able to reproduce this on a new space and room that you claim nodes into.

**Comment by hugovalente-pm** [comment]
This seems to be fixed
