### ISSUE TITLE
[Bug]: space view scrollbar

### ISSUE THREAD

**Issue by vkuznecovas** [netdata/netdata-cloud#920]
### Bug description

A scrollbar appears on the space view if you have too many spaces and looks ugly.

### Expected behavior

It should not look ugly.

### Steps to reproduce

1. Create a bunch of spaces
2. See the scroll bar

### Screenshots

<img width="267" alt="Screenshot 2023-09-14 at 10 53 52" src="https://github.com/netdata/netdata-cloud/assets/18392269/93ff3143-71fa-4a8b-bc43-ad12a43df5d0">

### Desktop

OS: macos
Browser: ff

**Comment by hugovalente-pm** [comment]
@christophidesp is this something you could take a look?

**Comment by novykh** [comment]
Fixed.
