### ISSUE TITLE
[Bug]: Chart info icons are invisible in light mode

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#921]
### Bug description

Chart info icons are invisible in light mode

They become visible when you mouse over the chart, but if you don't they are completely invisible in light mode.

Works fine in dark mode.

### Expected behavior

Chart info icons should always be visible

### Steps to reproduce

1. Just view any chart in light mode and try to find the icons for info, full scree, add to dashboard etc.

### Screenshots

Light mode:

![image](https://github.com/netdata/cloud-frontend/assets/24860547/08e63f05-bb8e-47ad-a171-88390ffdf950)

Dark mode: 

![image](https://github.com/netdata/cloud-frontend/assets/24860547/afe617d9-ff3a-4b77-b0ff-d9bbbef020cf)

### Error Logs

N/A

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@christophidesp this seems a bit serious so we should try to fix asap

**Comment by christophidesp** [comment]
@hugovalente-pm 
https://github.com/netdata/netdata-ui/pull/488
