### ISSUE TITLE
[Feat]: dont show k8s tab on agent dashboard

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#924]
### Problem

i think it makes no sense to show the kubernetes tab on a local agent dashboard.

![image](https://github.com/netdata/netdata-cloud/assets/2178292/bb076765-8e06-4a7a-866e-5e211648be08)

### Description

we should not show this tab by default and maybe hide it behind a config option or based on k8s metrics actually being available

### Importance

nice to have

### Value proposition

1. less noise on FE.
2. feels unprofessional to just blindly show empty tab to most users.

**Comment by hugovalente-pm** [comment]
this seems now to be a kind of a bug we introduced since we were showing marketing materials
we may opt to not show those since we now have the Integrations market place but then if the charts don't exist we should hide the tab

@novykh any thoughts on this?

**Comment by novykh** [comment]
Fixed.
