### ISSUE TITLE
[Bug]: cloud dashboards always thinks there are unsaved modifications

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#925]
### Bug description

If I open a dashboard and then immediately navigate away (without clicking on anything in the dashboard) it always prompts me that “Changes will be lost”. I even created a brand new dashboard and the same thing happens.

Reported here on [Community Forums](https://community.netdata.cloud/t/cloud-dashboards-always-thinks-there-are-unsaved-modifications/4685/1)

### Expected behavior

If no changes are made no prompt should appear about the possible need to save them

### Steps to reproduce

1. Open a custom dashboard
2. Don't change anything and navigate to another tab
3. See the prompt

### Desktop

Browser Version [e.g. 22]

**Comment by novykh** [comment]
Should be fixed after latest release.

**Comment by novykh** [comment]
Rolled back the release because of another issue. Will release later again.
