### ISSUE TITLE
[Bug]: Room won't load, dev tools console indicates net::ERR_FAILED

### ISSUE THREAD

**Issue by ftab** [netdata/netdata-cloud#926]
### Bug description

I just see the blinking Netdata logo and "Loading room"

Contents of the dev tools console after attempting to load in Brave or Edge:
```
Navigated to https://app.netdata.cloud/spaces/ruud-space-space/rooms/lemmy-world?chart=mem.swap&alarm=used_swap&transition=7beb0f91-df4d-40a1-a05b-2a0ee1616576&utm_source=sendgrid.com&utm_medium=email&utm_campaign=website
The FetchEvent for "https://app.posthog.com/static/array.js" resulted in a network error response: the promise was resolved with an error response object.
Promise.then (async)
(anonymous) @ sw.js:1
The FetchEvent for "https://www.googletagmanager.com/gtm.js?id=GTM-N6CBMJD" resulted in a network error response: the promise was resolved with an error response object.
Promise.then (async)
(anonymous) @ sw.js:1
app.02bbebebf4c90db5172f.js:1     GET https://app.posthog.com/static/array.js net::ERR_FAILED
window.envSettings.tracking.t.__SV.t.init @ app.02bbebebf4c90db5172f.js:1
29127 @ app.02bbebebf4c90db5172f.js:1
n @ runtime.ba468e9bdef1e77e0715.js:1
t @ app.02bbebebf4c90db5172f.js:1
(anonymous) @ app.02bbebebf4c90db5172f.js:1
n.O @ runtime.ba468e9bdef1e77e0715.js:1
(anonymous) @ app.02bbebebf4c90db5172f.js:1
t @ runtime.ba468e9bdef1e77e0715.js:1
(anonymous) @ app.02bbebebf4c90db5172f.js:1
app.02bbebebf4c90db5172f.js:1     GET https://www.googletagmanager.com/gtm.js?id=GTM-N6CBMJD net::ERR_FAILED
```

### Expected behavior

The room should load. There's only one node and I would think it has a pretty normal config.

### Steps to reproduce

1. Log in
2. Try to load any page

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/1690894/fb21181f-6c6a-42ff-8fe8-d91d5129613c)

### Error Logs

[app.netdata.cloud.har.zip](https://github.com/netdata/netdata-cloud/files/12684237/app.netdata.cloud.har.zip)

### Desktop

OS: Windows 10
Browser: Tried in Brave, Edge, Firefox (latest of each)
Browser Version:
- Brave 1.58.127 Chromium: 117.0.5938.88 (Official Build) (64-bit)
- Firefox 117.0.1
- Edge 117.0.2045.36 (Official build) (64-bit)

**Comment by hugovalente-pm** [comment]
@novykh could you probably take a look at this?

**Comment by novykh** [comment]
The request to get all rooms for the user's space comes back without the all-nodes room, and there is a condition on the frontend to wait to find this room. I can remove it from the frontend, but the issue remains why this user doesn't have a `all-nodes` room? cc @papazach

**Comment by papazach** [comment]
Hey @novykh , the `all-nodes` room exists for this space as well as for all other spaces.

It is just that this specific user - as an **observer** - is **only** assigned to `lemmy-world` room so he cannot see `all-nodes` .

So we should remove such condition from the front-end. 
It also seems a bit off to have such a check in place, given that the user in the screenshot tries to access the alerts page of the room he actually has access to.

**Comment by novykh** [comment]
If you remember back in the day everyone had `all-nodes` and couldn't leave or be assigned to it. I guess someone forgot about it. Like I wrote before, the fix is underway, tomorrow morning we will have it up.

**Comment by hugovalente-pm** [comment]
@novykh that changed when we released the paid plans and introduced the observer role, you can check the ticket where this was documented https://github.com/netdata/product/issues/3019

**Comment by novykh** [comment]
Should be fixed after latest release. Feel free to re-open if the issue persists.

**Comment by novykh** [comment]
Rolled back the release because of another issue. Will release later again.
