### ISSUE TITLE
[Bug]: Stuck in an endless sign in loop

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#927]
### Bug description

I got logged out and then the app doesn't let me sign back in.

Issue persists while I remain on the same browser (without clearing cache).

It gives me a "Go back to.." link which puts me back in the loop.

(Opening on a separate incognito tab lets me log in without a problem)

### Expected behavior

Let me sign in.

### Steps to reproduce

1. No idea, just happened randomly

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/24860547/09630fb3-db20-441b-8466-9545e53bf429)

And here's a video of what's happening:

https://github.com/netdata/netdata-cloud/assets/24860547/bb66e44f-6505-4b26-a05a-bac83ecf7b58

### Desktop

OS: Windows 11
Browser: Chrome
Browser Version: Version 116.0.5845.188

**Comment by shyamvalsan** [comment]
I haven't killed the browser window with this problem - so if you need more info, let me know.

**Comment by hugovalente-pm** [comment]
@novykh I think I saw this happening sometimes in the past and the clear cache solves it.
Is this usually related with user having in cache an older version of the UI? probably we could display some message to inform the user to try a refresh with clearing cache, if no better option exists

**Comment by hugovalente-pm** [comment]
@shyamvalsan thinking about closing this since I haven't heard of more reports on users experiencing this

**Comment by shyamvalsan** [comment]
Yeah I can't reproduce this anymore either. Closing it.
