### ISSUE TITLE
[Bug]: Local dashboard lets me open the add space section which doesn't do anything

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#929]
### Bug description

- Local dashboard lets me open the add space section which doesn't do anything when I try creating it, no error messages are displayed
- No consistency (I can't click on add rooms, but I can click on add spaces)

### Expected behavior

I think ideally it should work this way. 

Clicking on either add room or add space should show a tooltip/CTA asking the user to sign in. Rather than just an unclickable button.

### Steps to reproduce

1. [Always visible ](https://london.my-netdata.io/spaces/registrymy-netdataio/rooms/local/overview#metrics_correlation=false&after=-900&before=0&utc=Europe%2FKiev&offset=%2B3&timezoneName=Helsinki%2C%20Kyiv%2C%20Riga%2C%20Sofia%2C%20Tallinn%2C%20Vilnius&modal=&modalTab=&modalParams=&selectedIntegrationCategory=deploy.operating-systems&chartName-val=menu_system&local--chartName-val=menu_system)

### Screenshots

This is what I am talking about:

https://github.com/netdata/netdata-cloud/assets/24860547/f2053a7f-9d3b-4678-8d02-50458cd3fa27

### Error Logs

N/A

### Desktop

N/A

**Comment by hugovalente-pm** [comment]
@netdata/cloud-fe like we have disabled the "Add Room" `+` button we should disabled the space as well. placing as `medium` since this takes the user to a dead-end 
![image](https://github.com/netdata/netdata-cloud/assets/82235632/0d21a9df-f33f-4bb9-b69a-9c6a331375b2)

**Comment by novykh** [comment]
Will be fixed in next release.
