### ISSUE TITLE
[Bug]: no email alerts in netdata cloud

### ISSUE THREAD

**Issue by Baton4986** [netdata/netdata-cloud#930]
### Bug description

Hi, I'm playing around with some nodes in netdata, but i do not recieve any alerts per mail, only in the dashboard.

### Expected behavior

alert should send me an email :)

### Steps to reproduce

basic setup of nodes

**Comment by hugovalente-pm** [comment]
@ramon-kramer could you help us by giving some examples of alert emails you aren't receiving?
there was a similar topic around this raised on community https://community.netdata.cloud/t/not-receiving-alert-emails/4489/3 were the definition of the `role` attribute on the alert was to not trigger notifications besides being on the dashboard.

**Comment by Baton4986** [comment]
Hi, I did not recieve any alert until now. As I'm on community theres no option to configure the alert setting except of silencing rules, but there aren't any.

**Comment by hugovalente-pm** [comment]
to further investigate, could you share with me your space id or email? please send it to hugo@netdata.cloud

**Comment by Baton4986** [comment]
hi, for any reason i recieved all alerts at once now. you can remove your personal mail address from this chat to avoid spam :)


anyway, thank you for your help!

**Comment by hugovalente-pm** [comment]
cool, glad everything is sorted now.
will close this for now, if this happens again let us know

p.s.: I think I've already shared my email in a couple of other issues to no running away from spam 😅
