### ISSUE TITLE
[Bug]: cannot invite users

### ISSUE THREAD

**Issue by Baton4986** [netdata/netdata-cloud#931]
### Bug description

i tried to invite another user, and recieved the mail. new user openes the link but url changes to login screnn with some error code in url:

`https://app.netdata.cloud/sign-in?cloudRoute=/spaces/#hidden-info#/join-space#error_code=qU1AkBf4PH-25607333&error_message=tx%2520function%253A%2520unauthenticated&error_msg_key=ErrUnauthenticated&error_retry=%252Fapi%252Fv1%252Fspaces%252F7b2fe004-71e6-4cce-a2c0-0eeaaaea371b%252Fjoin-callback%253Ftoken%253DiyFAAWspG2hBTIWT18b60x%25252F4h19zNyeReDWv5CQmGQS5wfuXK29pz0oawGKZwLNjhNlSww%25253D%25253D%2526utm_source%253Dsendgrid.com%2526utm_medium%253Demail%2526utm_campaign%253Dwebsite&metrics_correlation=false&after=-900&before=0&utc=Europe%2FBerlin&offset=%2B2&timezoneName=Amsterdam%2C%20Berlin%2C%20Bern%2C%20Rome%2C%20Stockholm%2C%20Vienna&modal=&modalTab=&modalParams=&selectedIntegrationCategory=deploy.operating-systems`

### Expected behavior

user should log into space :)

### Steps to reproduce

1. invite
2. open link

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/45063149/587ee630-ec67-4415-887d-35f82c088122)

### Desktop

OS: ZorinOS
Browser Brave, Firefox, Chromium (all same)

**Comment by papazach** [comment]
Hello @ramon-kramer 👋🏼 ,

First of all thanks for using Netdata and for reporting this.

Thanks to your report we've pinpointed a nasty bug in the invitation flow and we're working on having the fix ready and shipped asap. We will keep you posted here.

**PS**: In the _meantime_ there is a _workaround_ you could follow to invite your colleagues to your space.
You could just ask them to _login prior to clicking the invitation URL_ they received in their email.

Best,
Costas

**Comment by papazach** [comment]
Hello again @ramon-kramer,

Just wanted to let you know that we pushed out a fix for this issue and this should not be experienced anymore.

From now on, any colleagues you might invite that are not already logged-in in Netdata Cloud will be successfully joining your space after successful sign-in.

Again, many thanks for bringing this to our attention.
Feel free to validate that this works for you and close this issue afterwards.

Happy Monitoring!
Costas

**Comment by Baton4986** [comment]
Hi, good job, it's working now!
