### ISSUE TITLE
[Feat]: Critical + Unreachable notifications for OpsGenie

### ISSUE THREAD

**Issue by zyxep** [netdata/netdata-cloud#935]
### Problem

I don't see an option for Critical & Unreachable alerts only.

### Description

Critial & Unreachable are the most important alerts we can get notified about and i would personally say they are self explanatory.

![Screenshot 2023-10-03 at 8 17 49 AM](https://github.com/netdata/netdata-cloud/assets/1403731/97041894-8742-45cc-9d3e-5418594e450c)

There are only an option for all alerts & unreachable.

### Importance

really want

### Value proposition

Critical is important in that sense that if anything goes crazy then we get notified, which is obvious.

Unreachable is also important to me, if a node crashes for whatever reason or someone turns it off for some reason then it's like a heartbeat for the node and would be nice to get notified.

**Comment by zyxep** [comment]
this is probably linked to #908 since it seems to be generic and not only for opsgenie :)

**Comment by hugovalente-pm** [comment]
correct, closing this one with preference to the above mentioned ticket
