### ISSUE TITLE
[Bug]: Netdata Mobile App Issues Identified

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata-cloud#936]
### Problem

- [X] New notifications page says "Select War rooms" instead of "Select Spaces"
- [x] Change the descriptions on the Settings options
![image](https://github.com/netdata/netdata-cloud/assets/96257330/8494bdb3-a48b-48a1-8e9e-ab5e968ba1bc)
- [x] The search field says "search services" and should simply be "search"
![Screenshot_20231004-114029](https://github.com/netdata/netdata-cloud/assets/96257330/94c72817-ff72-45ff-9be6-fe898878678a)

- [x] Fix the login journey - The magic link should not redirect to the app on the PC (cc: @kapantzak @car12o @papazach )
- [x] On the day mode - The spaces that do not have access should be darker grey
- [x] Netdata app should not be NETDATA but Netdata.
- [x] On first login show a pop-up which says you will only receive new notifications from the alerts
- [x] BUG: First time change of the theme crashes and takes user to the **login screen on Android**
- [x] BUG: App installation on Android still crashes (after workaround)
- [x] Updated terms and privacy policy required
- [x] Rename Setting to Global Settings page
- [x] On the settings, click enabled everywhere - why only on the arrow
- [x] After marking as unread and going to the home screen, it does not update the unread notifications number
- [x] iOS: Swiping left / right on the app does not work on the new notifications page. And after getting on the new notifications page the swipe does not work anywhere
Note: Not possible to swipe out of New notifications page on iOS.
- [x] Android: Swiping works
- [x] First attempt to look at the webview, it asks you to login. If we go back and click on the alert again, it shows the webview
- [x] Back button on Android --> Goes to the home screen of the phone and has to be opened again
- [x] Replace the Alert name with the summary field for the notifications screen - cc: @car12o @papazach 
- [x] X axis and the Y axis on the chart on the webview are missing - @kapantzak 
- [x] The font on the web-view can be increased - cc: @kapantzak 
- [x] Scrolling / Pulling down on the home screen - does not refresh?
- [x] BUG iOS: Change priority does not take effect until another press - leave the radio buttons empty
- [x] The priority slider should be fixed to the middle of the priority above. The slider needs to be bigger or clicking on the priority automatically drags the slider.
- [x] BUG iOS: Unable to exit the modal for sorting notifications by clicking outside the modal
- [x] BUG: Clicking on the envelope icon on the notification does not do anything. We need to switch between read and unread.
- [x] BUG: Notification retention screen, the font needs to increase
- [x] BUG Android: App crashed while using the app.
- [x] BUG Android: The number of notifications dont match the total unread notifications
- [ ] New ask: If a list of notifications
- [ ] FEATURE Request: To mark as read everything except the last notification from this alert OR Filter to show only latest transitions
- [x] BUG Backend: If the user requests QR Code (by mistake), it logs out the user even without scanning the QR Code - @car12o 
- [x] BUG iOS and Android: The notification numbers on the Home screen do not change until you go into a space and refresh
- [x] BUG iOS and Android: Manually marked "unread" notifications are not counted on the Home screen - they should be.
- [x] BUG iOS and Android: Auto read feature is extremely buggy - randomly marks notifications as read outside the viewport.
- [x] BUG Android: Filter page - Clicking on the name of the filter does not work and clicking on the box works
- [x] BUG iOS: Filter page - Clicking on the name of the filter  works and clicking on the box does not work
- [x] BUG iOS: Clicking on the left side of the modal does not take you out of the filtering
- [x] Design: Boxy look and gradient on the night mode
- [x] BUG Android: Silencing rules not showing up on the home screen and it does not show pop up when you get into the space
- [x] BUG iOS and Android: The pop up for Silence does not go away and you cannot go to the home screen or anywhere
- [x] BUG iOS and Android: The message on the silencing pop up is not correct - rewording needed.
- [x] BUG iOS and Android: After every API call, there is screen blinking issue
- [x] BUG Android: Duplicate silencing rules if you first created a silencing rule forever and then created a silencing rule with an end date
- [x] BUG Android: Disable notifications for all spaces and then removing silencing for one space does not work properly
- [x] BUG iOS: Silencing end date does not allow setting date and time at the same time and calls the API immediately.

### Description

Identify issues based on Dogfooding of the Netdata Mobile App..

### Importance

must have

### Value proposition

Release the Netdata Mobile App readily usable by users

**Comment by MrZammler** [comment]
I saw a notification from a go.d last collected, which the value is in seconds. However, the value is displayed with `%`.

**Comment by sashwathn** [comment]
> I saw a notification from a go.d last collected, which the value is in seconds. However, the value is displayed with `%`.

@MrZammler : Thanks for pointing this out. I think they are using `%` as the unit for all the alerts?

**Comment by MrZammler** [comment]
Looks like it...

Also on the iphone, I think badge count doesn't work, and the app's name appears as `NETDATA` (perhaps better to be `Netdata`).

**Comment by MrZammler** [comment]
Also, in the app library, it is in it's own folder, called `Netdata, Inc` not sure if that's intentional or during the dev phase maybe.

**Comment by MrZammler** [comment]
Just saw now, there is an orange popup when there's new notification, it's wording could be changed, i.e. it reads `New Notification Generated Go on top to see latest notification occurred`.

**Comment by stelfrag** [comment]
Android: 

Initial screen (150 alerts)

![Screenshot_20231009_193406_NETDATA](https://github.com/netdata/netdata-cloud/assets/52996999/92b3ebde-13be-4b0a-ac4c-4a5c0cd1c585)

Going into settings (top right) and immediately back will change the numbers (225 alerts)

![Screenshot_20231009_193451_NETDATA](https://github.com/netdata/netdata-cloud/assets/52996999/4366cbfb-7605-4706-b991-d4b5f5f24c9a)

Going into the space (79 alerts)

![Screenshot_20231009_194250_NETDATA](https://github.com/netdata/netdata-cloud/assets/52996999/5a1dd467-e8d9-4428-a9ea-ecc8f59fb12f)


Slide left when in this view 

![Screenshot_20231009_194229_NETDATA](https://github.com/netdata/netdata-cloud/assets/52996999/1fb29bd6-8f0a-4ddd-babb-42d8249d64d2)

**Comment by stelfrag** [comment]
Android: Going into maintenance mode settings
- Disable notifications for all spaces. The date format suggested is dd/mm/yy HH:MM. I don't know if this uses the phone locale; if not it will be problematic for those that use mm/dd/yy 

- Entering the mode settings produces multiple screen "refresh flashes"
- Attempting to toggle 'disable notifications' for a specific space results in endless loop of "screen flash / refresh"

**Comment by sashwathn** [comment]
> Android: Going into maintenance mode settings
> 
> * Disable notifications for all spaces. The date format suggested is dd/mm/yy HH:MM. I don't know if this uses the phone locale; if not it will be problematic for those that use mm/dd/yy
_[Satya] The date format can be changed and is not based on locale unfortunately_
> * Entering the mode settings produces multiple screen "refresh flashes"
_[Satya] Unfortunately this seems to be the behaviour while calling our APIs to silence the spaces - let me check if this can be fixed._
> * Attempting to toggle 'disable notifications' for a specific space results in endless loop of "screen flash / refresh"
_[Satya]Is it after the Disable all spaces? We need to investigate this issue._

**Comment by kapantzak** [comment]
> X axis and the Y axis on the chart on the webview are missing

If we render X and Y axis, the chart gets wider and user has to scroll to the left to see the remaining chart


https://github.com/netdata/netdata-cloud/assets/12742884/218755f4-1f3a-414d-9338-96d162d1834d

**Comment by M4itee** [comment]
when silencing with the exact date and time of expiration the "picking" section crashes after first selection causing only an ability to pick data OR hour OR minutes. When you will try to do it in a "3 step" process it will not work as it always starts from `now()`
Newest IOS here.

**Comment by hugovalente-pm** [comment]
is this to be closed @sashwathn since we are on the release process already?
