### ISSUE TITLE
[Bug]: virtual machine reported as "bare metal" in info panel

### ISSUE THREAD

**Issue by Cris70** [netdata/netdata-cloud#937]
### Bug description

I have a few Proxmox VMs that I am adding to Netdata Cloud (i.e. I'm installing the agent on the VMs).
Netdata correctly reports "kvm" in the Nodes panel, but if I open the "Node information" side panel, I see "Bare metal" reported there as "Type", which is obviously incorrect.

### Expected behavior

The "Node information" side panel should report "KVM" or something like that, indicating that the machine is a VM.

### Steps to reproduce

1. Install the Netdata agent into a Proxmox Virtual Machine
2. Open the Nodes panel of the room where you added the new Virtual Machine
3. See that the new Virtual Machine reports "kvm" as machine type
4. Click on the "i" icon next to the virtual machine name to open the Node Information side panel
5. Check that the Node Information side panel reports "Bare Metal" as machine type in the "System Info" section

### Screenshots

![immagine](https://github.com/netdata/netdata-cloud/assets/5107224/f71e7dce-1002-40cc-9091-326a433fcc5c)

### Error Logs

n/a

### Desktop

OS: openSuse Tumbleweed (linux)
Browser: Firefox
Browser Version: 118.0.1

**Comment by hugovalente-pm** [comment]
we have this case on the Demo room as well
![image](https://github.com/netdata/netdata-cloud/assets/82235632/3ea657c0-8e0b-4b56-a2ab-53b1a623b965)


noticed that this also happens on containers running on k8s cluster
![image](https://github.com/netdata/netdata-cloud/assets/82235632/eddf54b2-f285-4be1-811c-0282e76dac72)


the `/info` and our internal node metadata shows both the `labels._virtualization` and `hw.virtualization` as `kvm

<details>

```json
{
	"name": "cassandra",
	"version": "v1.40.0-9-g000884005",
	"hasAccessibleData": true,
	"isOffline": false,
	"isUnseen": false,
	"isLive": true,
	"updateSeverity": null,
	"capabilities": {
		"health": {
			"name": "health",
			"version": 1,
			"enabled": true
		},
		"req_cancel": {
			"name": "req_cancel",
			"version": 1,
			"enabled": true
		},
		"proto": {
			"name": "proto",
			"version": 1,
			"enabled": true
		},
		"ml": {
			"name": "ml",
			"version": 1,
			"enabled": false
		},
		"mc": {
			"name": "mc",
			"version": 1,
			"enabled": true
		},
		"ctx": {
			"name": "ctx",
			"version": 1,
			"enabled": true
		},
		"funcs": {
			"name": "funcs",
			"version": 1,
			"enabled": true
		},
		"http_api_v2": {
			"name": "http_api_v2",
			"version": 3,
			"enabled": true
		}
	},
	"nd": "45428773-5f00-457f-94a3-22a0e9e04e5f",
	"mg": "69b45a08-4bf4-11ed-b29f-1eee970aea79",
	"labels": {
		"_aclk_available": "true",
		"_aclk_ng_new_cloud_protocol": "true",
		"_aclk_proxy": "none",
		"_architecture": "x86_64",
		"_cloud_instance_region": "unknown",
		"_cloud_instance_type": "unknown",
		"_cloud_provider_type": "unknown",
		"_container": "none",
		"_container_detection": "systemd-detect-virt",
		"_has_unstable_connection": "false",
		"_install_type": "custom",
		"_is_ephemeral": "false",
		"_is_k8s_node": "false",
		"_is_parent": "false",
		"_kernel_version": "5.10.0-14-amd64",
		"_mqtt_version": "5",
		"_os_name": "Debian GNU/Linux",
		"_os_version": "11 (bullseye)",
		"_system_cores": "4",
		"_system_cpu_freq": "2000000000",
		"_system_disk_space": "107374182400",
		"_system_ram_total": "8343302144",
		"_virt_detection": "systemd-detect-virt",
		"_virtualization": "kvm"
	},
	"hw": {
		"architecture": "x86_64",
		"cpuFrequency": "2000000000",
		"cpus": "4",
		"memory": "8343302144",
		"diskSpace": "107374182400",
		"virtualization": "kvm",
		"container": "none"
	},
	"os": {
		"id": "linux",
		"nm": "Debian GNU/Linux",
		"v": "11 (bullseye)",
		"kernel": {
			"nm": "Linux",
			"v": "5.10.0-14-amd64"
		}
	},
	"health": {
		"status": "online",
		"alerts": {
			"warning": 0,
			"critical": 0
		}
	},
	"state": "reachable",
	"id": "45428773-5f00-457f-94a3-22a0e9e04e5f",
	"loaded": true
}
```

</details>

but the FE is also looking to the container entity there are cases where:
* this is coming with `"_container": "container",` example the k8s
* this is coming as `"_container": "none",` example the kvm one

one @netdata/cloud-fe investigation is needed and the other one maybe check on the agent collection (@ilyam8 ?) of this metrics and/or validate the logic

**Comment by ilyam8** [comment]
I think we need to check "virtualization" - if it is not "none" we are in a virtualized environment (not bare metal). cc @Ferroin

**Comment by hugovalente-pm** [comment]
@netdata/agent-sre can you guys help on this one?

**Comment by miranyx** [comment]
I also noticed it on docker.

**Comment by novykh** [comment]
Yep, it's a frontend issue reading the wrong key in the node info section. Will push a hotfix, thanks.

**Comment by novykh** [comment]
Should be fixed on latest. Make sure to re-open if this or something similar arises. Cheers
