### ISSUE TITLE
[Bug]: Switch from nightly build to stable doesn't impact "Copy" output

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#940]
### Bug description

While adding a node the modal shows the previewed command if user changes this to stable, which changes the preview from “–nightly-channel” to “–stable-channel” this change does not affect the actual copied string when clicking “copy-button”.

Issue raised https://community.netdata.cloud/t/switch-from-nightly-build-to-stable/3269/4

### Expected behavior

Copied command should be the same as preview

### Steps to reproduce

1. Go to Add node modal
2. Switch the channel toggle
3. Confirm preview text changes
4. Click the Copy button and see it doesn't get updated

### Desktop

Browser Version [e.g. 22]

**Comment by kapantzak** [comment]
Fixed in `6.54.1`
