### ISSUE TITLE
[Feat]: Make PID, Cmd and Category columns optional in Netdata Functions UI

### ISSUE THREAD

**Issue by luisj1983** [netdata/netdata-cloud#941]
### Problem

The PID, Cmd and Category columns in the Netdata Functions UI cannot be deselected.
1. I'd like to choose what I consider useful information for my given purposes at a given time
2. The columns compromise about 1/3 of the usable width that I could be using to fit in other columns.

I am not suggesting to remove these columns for the UI as they are extremely useful; I'm just asking for the ability to de-select them if I need to.

### Description

Please make those columns de-selectable; or at least perhaps the Category and PID?

### Importance

really want

### Value proposition

1. This issue applies when using a browser maximised but it's especially acute when I have the browser taking up half of my screen; this is typical since while I'm looking at Netdata information I'll be logging into servers and looking up information (which I suspect is what a lot of other people end up doing).

**Comment by novykh** [comment]
Should be fixed on latest UI.
