### ISSUE TITLE
[Bug]: Misaglined numbers on tables on Home tab

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#942]
### Bug description

![image](https://github.com/netdata/netdata-cloud/assets/82235632/5514adb9-7c3b-43f6-9d11-1ec8efdb6fdc)

reported on [Discord](https://discord.com/channels/847502280503590932/1164852309889663006)

### Expected behavior

Numbers should align to the right

### Steps to reproduce

1.

### Desktop

Browser Version [e.g. 22]

**Comment by novykh** [comment]
Will be fixed in next release.
