### ISSUE TITLE
[Bug]: Alerts view when enabling displayName the table will not scroll to the bottom

### ISSUE THREAD

**Issue by Ancairon** [netdata/netdata-cloud#943]
### Bug description

When I enable the displayName filter in the cogwheel in the Alerts view, the table expands height-wise, but I can't scroll to the bottom.

Also it might be good to put a scroll indicator somewhere if possible, as it is not obvious more columns appear.

My window size was 1300x1000, so try it in this manner, as in a huge screen it will look fine probably

### Expected behavior

To be able to see the entire table 

### Steps to reproduce

1. Go to the Alerts tab
2. Resize the window to something around 1300x1000
3. Select the displayName column to appear

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/70198089/1a1ab719-ce6a-4290-a4e2-cd1bf0b4bd8b)

### Desktop

OS: Linux
Browser: Google Chrome

**Comment by novykh** [comment]
Should be already fixed.
