### ISSUE TITLE
[Bug]: Image in the create new dashboard modal seems to be missing

### ISSUE THREAD

**Issue by Ancairon** [netdata/netdata-cloud#944]
### Bug description

Check my screenshot, this is from app.netdata.cloud

### Expected behavior

If there is supposed to be an image there, I should be able to see it	

### Steps to reproduce

1. Go to dashboards
2. Create a new bashboard

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/70198089/85037887-cc3f-453d-8e32-b52e4347c456)

**Comment by hugovalente-pm** [comment]
closed
