### ISSUE TITLE
[Bug]: Anomaly Advisor charts don't get displayed in full width

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#948]
### Bug description

The charts in Anomaly Advisor don't get displayed in full-width

![image](https://github.com/netdata/netdata-cloud/assets/82235632/f99d4573-0f6a-4add-8284-5cc966dc8029)

![image](https://github.com/netdata/netdata-cloud/assets/82235632/9ec85a0c-e063-4471-9178-bc2450030a72)

### Expected behavior

Charts should take the full horizontal width
![image](https://github.com/netdata/netdata-cloud/assets/82235632/c2a8e354-8dfe-49f6-936b-49bbc41e569b)

### Steps to reproduce

1. Open the Anomaly Advisor tab

### Desktop

Browser Version [e.g. 22]

**Comment by novykh** [comment]
Will be fixed in next hotfix release later today. It was a regression issue.

**Comment by novykh** [comment]
Should be fixed on latest release.
