### ISSUE TITLE
[Bug]: anomaly advisor filtering broken

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#951]
### Bug description

I have filtered just for one node of interest in the global filter so i should not be seeing these other lines

![image](https://github.com/netdata/netdata-cloud/assets/2178292/87c53f56-1870-4cb7-bfcf-e727c0e5a53b)

### Expected behavior

anomaly advisor tab should respect the global filter.

### Steps to reproduce

1. use it

### Desktop

Browser Version [e.g. 22]

**Comment by andrewm4894** [comment]
given the global node filter i had selected for just this one node, i should be seeing something like this (except with the node side filter unselected - i just had to do it here to make this screenshot): 

![image](https://github.com/netdata/netdata-cloud/assets/2178292/e3bd2fcb-adb1-4b22-993f-f0580cf3cc46)

**Comment by hugovalente-pm** [comment]
this is fixed
