### ISSUE TITLE
[Bug]: Global node filter not correctly applied

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata-cloud#953]
### Bug description

When selecting nodes in the global node filter, the filter is not applied in the Events, Alerts, and Anomaly tabs, when no selection was made in the tab's local filter.

### Expected behavior

Global node filter is applied globally.

### Steps to reproduce

1. Open the alerts tab
2. Select one node
3. Observe that the list still shows alerts from other nodes

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/116741/ab2b0e76-8fd4-455f-ab22-087f669d6f0f)

### Desktop

OS: Ubuntu 23.04
Browser Firefox
Browser 119.0b8

**Comment by hugovalente-pm** [comment]
this is fixed
