### ISSUE TITLE
[Bug]: Type in information page is not correct

### ISSUE THREAD

**Issue by miranyx** [netdata/netdata-cloud#957]
### Bug description

The bug occurs on the nodes view. In the nodes view you can see the type of the machine kvm/docker/etc... The one shown below the name is correct, but if you press the information "I", you can also see the type and every type is bare metal even if below the machine hostname it says kvm (kvm is correct). It also says for docker bare metal in the information pannel.

### Expected behavior

The machine type in the information panel is the same as the one below the hostname.

### Steps to reproduce

1. Add a node which is not bare metal.
2. Press the I to open the information pannel

### Screenshots

<img width="646" alt="Screenshot 2023-12-06 at 10 13 50" src="https://github.com/netdata/netdata-cloud/assets/64905406/62b80c4e-920f-44cf-bab1-b4e99ddd513a">
<img width="300" alt="Screenshot 2023-12-06 at 10 14 00" src="https://github.com/netdata/netdata-cloud/assets/64905406/9b0a81d0-51cd-441d-bc1c-a443e9b2c4b4">

### Desktop

OS: macOS 14.1 
Browser FireFox
Browser 119.0.1

**Comment by hugovalente-pm** [comment]
thanks for raising this. I've noticed this is the same as this https://github.com/netdata/netdata-cloud/issues/957 so closing as duplicate
