### ISSUE TITLE
[BUG] Cloud ignores 'delay' setting of alarms

### ISSUE THREAD

**Issue by Pingger** [netdata/netdata-cloud#96]
**Describe the bug**	
The Netdata cloud ignores the `delay` setting of alarms causing extreme mail spam, when an alarm is jumping around the threshold

**To Reproduce**	
1. Have an alarm to trigger at e.g. 2% packetloss (with `delay: up 1m multiplier 2 max 6h down 10m multiplier 2 max 12h`)
2. let the packetloss jump between 1% and 3%
3. Get hundreds of mail every day

**Expected behavior**	
delay setting being respected severely reducing the amount of mails.

**Screenshots**	
![image](https://user-images.githubusercontent.com/4761298/118643007-4dbf4180-b7dc-11eb-977a-5b11c6c9b534.png)

**Error logs**	
N/A, maybe there are some on your 'cloud'-servers ...

**Desktop (please complete the following information):**	
N/A, independent from desktop

**Additional context**	
My local notifications respect the setting. I only got 5 Notifications regarding that specific alarm over the last day ...

**Comment by Pingger** [comment]
The issue just got even worse. It got so bad, that I received the "Flood Protection"-Mail

> The alarms for Node XXX are changing status too frequently and so notifications for it will be suspended until it falls below a threshold of 30 alarm changes per 1 hour

With a minimum `up` delay (as stated) of 1 minute and minimum `down` delay of 10 minutes, this shouldn't even remotely occur!

**Comment by Pingger** [comment]
Small update: The issue still persists

**Comment by manos-saratsis** [comment]
@Pingger within the next couple of weeks we will deploy major changes that resolve this issue

**Comment by Pingger** [comment]
> @Pingger within the next couple of weeks we will deploy major changes that resolve this issue

not sure if those major changes have already been deployed, but the issue _still_ persists

**Comment by manos-saratsis** [comment]
@Pingger We are testing our new architecture that will solve this issue. It is expected to be solved by end of Jan for all users. In case you would like to contribute in testing the new architecture please share your space_id that you can find under `Manage Space`, important is that all your agent should have the latest agent

**Comment by Pingger** [comment]
I'd love to participate in that preview: 5f10b8d2-cb62-420a-bfc7-c3586c8d584b
1. Since have a few Rasperry Pis, that are currently running on stable, is there an easy way to switch them to nightly? (since it takes quite some time to build netdata on Pis ...)
1. Is feedback accepted/requested from Preview-Participants? If yes, where?
1. I am aware, that it is a Preview and thus some glitches might exist. Should I report those? Where should I report those?

Greetings

**Comment by manos-saratsis** [comment]
@Pingger thanks
1. You need to reinstall with default on nightly @cpipilas any other advice?
2. and 3. Feel free to join the discussion on Discord and report your findings https://discord.gg/qbuSThuw

**Comment by Pingger** [comment]
OK ... managed to switch my Raspberries to Nightly.

**Comment by dimko** [comment]
@vkuznecovas has this been implemented? Can you share the PR number?

**Comment by dimko** [comment]
This seems to be fixed in the new architecture. Closing it.
