### ISSUE TITLE
[Bug]: 400 error after changing graph settings

### ISSUE THREAD

**Issue by chunguscodes** [netdata/netdata-cloud#960]
### Bug description

After the most recent Functions update (nice feature by the way), I begun to spend more time in customizing my Netdata Cloud setup so that the graphs were more useful for my use case.

I was specifically modifying the cgroup.io graph, changing it from dimensions to node, allowing me to specifically see what node was using I/O rather than an overall calculation of all nodes in my space. After doing this, everything 'froze' and now none of my servers are pulling data on Netdata Cloud.

### Expected behavior

To be able to load my servers.

### Steps to reproduce

1. Update the cgroup.io graph from dimension to node with 50+ servers enabled.

### Screenshots

![SS6Yi5ReWJ](https://github.com/netdata/netdata-cloud/assets/15911948/6950e28a-aa8d-4f84-8972-176dbfa5c519)

### Error Logs

No errors in console, but 400 errors to the data POST endpoint found in screenshots above.

### Desktop

Windows 10 Latest Version, Google Chrome latest version

**Comment by chunguscodes** [comment]
After a bit of time, servers are now going offline and online randomly according to Netdata Cloud. Of course, the agents are online and working as expected (including going direct to them on the nodes and bypassing the Cloud aspect). I can't find any logging and can only put this down to Netdata Cloud itself.

**Comment by chunguscodes** [comment]
Update: I resolved this by uninstalling Netdata on the machines, removing them from Netdata Cloud, and then reinstalling the Netdata agent. 10 seconds on the data endpoints down to 600ms, and loading as expected.

![image](https://github.com/netdata/netdata-cloud/assets/15911948/066a5ca4-3b28-4204-9b76-e4fd40add163)

**Comment by hugovalente-pm** [comment]
@chunguscodes to confirm, you're no longer experiencing this situation right?
in between the uninstall and re-install of the agents do you know if the agent versions' changed?

**Comment by chunguscodes** [comment]
Correct, I resolved it by uninstalling and installing the agent on all 55~ servers. The agent version didn't change, I was on the latest nightly build on all servers before and after. @hugovalente-pm 

I can provide my user information if needed to diagnose further, but it's not an existing issue at least so not super urgent from my side. Appreciate the reply! @hugovalente-pm

**Comment by hugovalente-pm** [comment]
if you could share you're space id by email I could try to find something, hugo@netdata.cloud

I'll close the bug for now, let us know if this comes back again for any reason
