### ISSUE TITLE
[Bug]: visited nodes empty with local registry

### ISSUE THREAD

**Issue by olivluca** [netdata/netdata-cloud#965]
### Bug description

I have configured a local registry, I see that the browser is contacting the registry url and it gets back a list of urls, but the visited nodes list is empty.
I'm now on 1.35.0 but this started a couple of versions (years?) ago, when the collapsible menu on the left was introduced.
In case it is relevant, all nodes are fronted by the same nginx host, so there is no cookie problem.
Also, in the node where I enabled the registry, in the /var/lib/netdata/registry there is no registry.db file, only netdata.public.unique.id and registry-log.db (which is not what it says [here](https://learn.netdata.cloud/docs/agent/registry#where-is-the-registry-database-stored)).

### Expected behavior

I expect the list of visited nodes list to be populated

### Steps to reproduce

1. configure a local registry by following the instructions [here](https://learn.netdata.cloud/docs/agent/registry#run-your-own-registry)
2. visit your netdata instances
3. check in the browser developer console, network tab, that the browser is contacting the registry and getting back a list of urls
4. but the visited nodes list is not populated

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
ersion: netdata v1.35.0
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

Just as an experiment I deleted the files in /var/lib/netdata/registry, restarted netdata and visited a couple of nodes and this is the json I get back from the registry:

```

{
	"action": "access",
	"status": "ok",
	"hostname": "helpdesk",
	"machine_guid": "bebc6412-e7c4-11ec-a5f2-0050569b7cc4",
	"person_guid": "4e8e836f-f480-4ab4-843a-0e3bc5b8cee5",
	"urls": [
		[
			"31e6db44-8957-11ea-b266-0050569b61bb",
			"https://intranet.wetron.es/netdata/nctest/",
			1654760029000,
			1,
			"nctest"
		],
		[
			"31e6db44-8957-11ea-b266-0050569b61bb",
			"https://intranet.wetron.es/netdata/nc/",
			1654759303000,
			2,
			"nc"
		]
	]
}
```

On the browser console I just see these two errors (the first one because the registry sends the netdata_registry_id twice, once with no samesite and the other with "SameSite=None; Secure").

```
Some cookies are misusing the recommended “SameSite“ attribute 2
Cookie “netdata_registry_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite registry
Cookie “netdata_registry_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite registry
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. nctest


```

**Comment by olivluca** [comment]
The new dashboard in the latest version (1.41.0) broke again this functionality.
The browser tries to contact app.netdata.cloud and search-api.swiftype.com (I see Cross-Originn request blocked in the console), I don't think it should if I'm using a local registry.
I also see that it's accessing the local registry and it's correctly getting a list of machines.
If I'm quick enough to click on the link leading to the old dashboard I can see the list of nodes there, but I guess the old dashboard will eventually be unmaintained and disappear.
One last gripe is that I cannot find a way to change the color scheme from dark to light (the settings icon says that I need to connect to the cloud to see and change the settings).

**Comment by hugovalente-pm** [comment]
thanks for bringing this up, we will look into this

**Comment by ilyam8** [comment]
@hugovalente-pm what do we do with this issue? No Visited Nodes if not signed in - is that a bug or expected?

**Comment by hugovalente-pm** [comment]
> @hugovalente-pm what do we do with this issue? No Visited Nodes if not signed in - is that a bug or expected?

@ilyam8 from my understanding this worked on old dashboard, as an example reported by a user [here](https://github.com/netdata/netdata-cloud/issues/965), and looking to the `/v1` we can see visited nodes while not signed-in
![image](https://github.com/netdata/netdata/assets/82235632/b8b7ee9b-936d-4f1c-a88a-23c18f563a21)

so considering that we should consider it as a bug for now and look into this to check if there is any technical limitation to not allow this while not signed-in
