### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mserver67** [netdata/netdata-cloud#967]
### Bug description

Oops, something unexpected happened!
We track these errors automatically, but if the problem persists feel free to contact us with a [ticket](https://github.com/netdata/netdata-cloud/issues/new/choose), a [post in the forum](https://community.netdata.cloud/) or through [Discord](https://discord.com/invite/mPZ6WZKKG2).In the meantime you can refresh this page
server1matrix-viroviticacom

### Expected behavior

![Screenshot 2023-12-29 at 06-40-34 server1 matrix-virovitica com Netdata Agent Console](https://github.com/netdata/netdata-cloud/assets/80481918/5d4bb98b-63dc-47d3-9163-9e59029df0d4)

### Steps to reproduce

1.

### Screenshots

![Screenshot 2023-12-29 at 06-40-34 server1 matrix-virovitica com Netdata Agent Console](https://github.com/netdata/netdata-cloud/assets/80481918/5f018afc-2883-4307-96fe-2e2b737ffc6f)

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@mserver67 could you give a bit of more context on what action you were trying to do?

**Comment by hugovalente-pm** [comment]
@mserver67 can you provide some more details on this?

**Comment by hugovalente-pm** [comment]
closing since we haven't more details to check the issue
