### ISSUE TITLE
Server went unreachable. No email received.

### ISSUE THREAD

**Issue by bazwalt** [netdata/netdata-cloud#97]
Hi there,

To test my service, I shut off one of my virtual servers which have the netdata agent installed.

I've received alerts for this very recently without issue but for some reason when my node goes unreachable I do not get any email at all.

My netdata email is a gmail account. I know for certain that those nodes are configured to send an email for all alert types.

What can I do? I have checked spam/junk and its not appearing in there or being filtered to any folder. Flat-out, its just not arriving at all. I don't even know if the email is being sent at all.

Update: I have added a separate user as an admin with a mailbox not on gmail and still no notification for this unreachable node. I am also pretty certain that none of the nodes should have caused flood protection either as the last alert was over 5 hours ago.

**Comment by manos-saratsis** [comment]
@bazwalt apologies for the very late response. Did you check under your account/Notifications to see if you receive notifications when your node is unreachable?

**Comment by bazwalt** [comment]
I did yes.

**Comment by OdysLam** [comment]
Hey @bazwalt, 

Just to make sure that we are on the same page. You are talking about alerts that have been set up on Netdata cloud, are you correct?

Can you please send me your email over email at odysseas@netdata.cloud, so that we can find you in our systems and see if everything has been setup correctly?

**Comment by dimko** [comment]
This has been handled. Reachability Notifications are off by default as a business decision. FE was showing them as enabled due to a bug. Closing it.
