### ISSUE TITLE
[Bug]: Visited nodes doesn't get updated with new entries or counts

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#971]
### Bug description

When navigating to a node from Netdata Cloud or an Agent I don't see the entries being updated on Visited Nodes

### Expected behavior

Visited nodes should keep track of new nodes I visit and update counts on nodes I had already visited
More details: https://github.com/netdata/cloud-frontend/issues/3040

### Steps to reproduce

1. Sign-in to Cloud
2. Go to a node that isn't on the Visited Nodes list
3. Entry is not added
4. Go to a node that is on the Visited Nodes list
5. See that no call is made to `/api1/v1/accounts/{ACCOUNT_ID}/nodes/{MACHINE_GUID}/touch`

### Desktop

Browser Version [e.g. 22]

**Comment by novykh** [comment]
Fixed.
