### ISSUE TITLE
Logging doesn't populate

### ISSUE THREAD

**Issue by douglasjthomas** [netdata/netdata-cloud#974]
### Bug description

On netdata cloud, logging never populates.  Just shows "Loading Logs" forever.

### Expected behavior

I expected to see some logs from my nodes, expeically my Linux box.

### Steps to reproduce

1.

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/122920118/e13b08f0-fe7a-433d-9383-90d92c32d442)

### Error Logs

<html>
<body>

  | <!doctype html><html><head><script>window.envSettings = {
-- | --
  | apiUrl: "https://app.netdata.cloud",
  | cloudUrl: "https://app.netdata.cloud",
  | demoSlug: "netdata-demo",
  | demoFavourites: {"postgresql":["postgres"],"redis":["redis"],"dns-query":["dns_query"],"http-endpoints":["httpcheck"],"nginx":["web_log","nginx"],"apache":["apache"],"host-reachability":["ping"],"cassandra":["cassandra"],"coredns":["coredns"],"logind":["logind"],"iis":["iis"],"active-directory":["ad"],"windows":["windows","ad","iis","mssql","exchange","netframework"],"docker":["cgroup","docker"],"ups":["upsd"]},
  | isAgent: false,
  | webpackPublicPath: "",
  | version: "6.80.0",
  | posthogToken: "phc_hnhlqe6D2Q4IcQNrFItaqdXJAxQ8RcHkPAFAp74pubv",
  | cookieDomain: ".netdata.cloud",
  | tracking: true,
  | onprem: false,
  | nodeEnv: "production"
  | }</script><title>Netdata Console</title><meta property="og:description" content="Slash your time to detect, troubleshoot and resolve infrastructure performance anomalies. Netdata: architected for speed, automated for easy."><meta property="og:image" content="https://netdatacloud20.kinsta.cloud/wp-content/uploads/2022/03/netdata-cloud-dashboard-1.png"><meta name="application-name" content="netdata"/><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/><meta name="viewport" content="width=device-width,height=device-height,initial-scale=1,minimum-scale=1"/><meta name="apple-mobile-web-app-capable" content="yes"/><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/><script defer="defer" src="/runtime.afb80bb9acb6f358e089.js"></script><script defer="defer" src="/npm.react.dom.ee15b5aace15c30d865d.js"></script><script defer="defer" src="/2533.bf4d01701753af029fad.js"></script><script defer="defer" src="/1911.65c2b30429de5981c29a.js"></script><script defer="defer" src="/3495.dcac0fd31993169856c3.js"></script><script defer="defer" src="/4586.a9c7d5544aab62c143b9.js"></script><script defer="defer" src="/1282.11cfdd41f0a52c562df0.js"></script><script defer="defer" src="/8024.d61ab8330ee7daab9255.js"></script><script defer="defer" src="/7122.063e5afb0fe6c64c83f7.js"></script><script defer="defer" src="/1059.10d94055886a78152385.js"></script><script defer="defer" src="/8784.e81d3fae189d1b23e0fb.js"></script><script defer="defer" src="/2406.bc73a5d1eaa9a2c8f934.js"></script><script defer="defer" src="/app.ec7177f5151d365dc8dc.js"></script><link href="/app.cb2e9f9a81cf9533384e.css" rel="stylesheet"></head><body><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N6CBMJD" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><div id="app"></div></body></html>

</body>
</html><!doctype html><html><head><script>window.envSettings = {
        apiUrl: "https://app.netdata.cloud",
        cloudUrl: "https://app.netdata.cloud",
        demoSlug: "netdata-demo",
        demoFavourites: {"postgresql":["postgres"],"redis":["redis"],"dns-query":["dns_query"],"http-endpoints":["httpcheck"],"nginx":["web_log","nginx"],"apache":["apache"],"host-reachability":["ping"],"cassandra":["cassandra"],"coredns":["coredns"],"logind":["logind"],"iis":["iis"],"active-directory":["ad"],"windows":["windows","ad","iis","mssql","exchange","netframework"],"docker":["cgroup","docker"],"ups":["upsd"]},
        isAgent: false,
        webpackPublicPath: "",
        version: "6.80.0",
        posthogToken: "phc_hnhlqe6D2Q4IcQNrFItaqdXJAxQ8RcHkPAFAp74pubv",
        cookieDomain: ".netdata.cloud",
        tracking: true,
        onprem: false,
        nodeEnv: "production"
      }</script><title>Netdata Console</title><meta property="og:title" content="Netdata: Monitoring and troubleshooting transformed."><meta property="og:description" content="Slash your time to detect, troubleshoot and resolve infrastructure performance anomalies. Netdata: architected for speed, automated for easy."><meta property="og:image" content="https://netdatacloud20.kinsta.cloud/wp-content/uploads/2022/03/netdata-cloud-dashboard-1.png"><meta name="application-name" content="netdata"/><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/><meta name="viewport" content="width=device-width,height=device-height,initial-scale=1,minimum-scale=1"/><meta name="apple-mobile-web-app-capable" content="yes"/><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/><script defer="defer" src="[/runtime.afb80bb9acb6f358e089.js](https://app.netdata.cloud/runtime.afb80bb9acb6f358e089.js)"></script><script defer="defer" src="[/npm.react.dom.ee15b5aace15c30d865d.js](https://app.netdata.cloud/npm.react.dom.ee15b5aace15c30d865d.js)"></script><script defer="defer" src="[/2533.bf4d01701753af029fad.js](https://app.netdata.cloud/2533.bf4d01701753af029fad.js)"></script><script defer="defer" src="[/1911.65c2b30429de5981c29a.js](https://app.netdata.cloud/1911.65c2b30429de5981c29a.js)"></script><script defer="defer" src="[/3495.dcac0fd31993169856c3.js](https://app.netdata.cloud/3495.dcac0fd31993169856c3.js)"></script><script defer="defer" src="[/4586.a9c7d5544aab62c143b9.js](https://app.netdata.cloud/4586.a9c7d5544aab62c143b9.js)"></script><script defer="defer" src="[/1282.11cfdd41f0a52c562df0.js](https://app.netdata.cloud/1282.11cfdd41f0a52c562df0.js)"></script><script defer="defer" src="[/8024.d61ab8330ee7daab9255.js](https://app.netdata.cloud/8024.d61ab8330ee7daab9255.js)"></script><script defer="defer" src="[/7122.063e5afb0fe6c64c83f7.js](https://app.netdata.cloud/7122.063e5afb0fe6c64c83f7.js)"></script><script defer="defer" src="[/1059.10d94055886a78152385.js](https://app.netdata.cloud/1059.10d94055886a78152385.js)"></script><script defer="defer" src="[/8784.e81d3fae189d1b23e0fb.js](https://app.netdata.cloud/8784.e81d3fae189d1b23e0fb.js)"></script><script defer="defer" src="[/2406.bc73a5d1eaa9a2c8f934.js](https://app.netdata.cloud/2406.bc73a5d1eaa9a2c8f934.js)"></script><script defer="defer" src="[/app.ec7177f5151d365dc8dc.js](https://app.netdata.cloud/app.ec7177f5151d365dc8dc.js)"></script><link href="[/app.cb2e9f9a81cf9533384e.css](https://app.netdata.cloud/app.cb2e9f9a81cf9533384e.css)" rel="stylesheet"></head><body><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N6CBMJD" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><div id="app"></div></body></html>

### Desktop

Browser Version [e.g. 22]
Windows 11, Edge browser.

**Comment by hugovalente-pm** [comment]
@douglasjthomas thanks for raising this bug to us, from the look of it it seems your systems is not running or able to run `systemd-journal` which, atm, is our currently log integration available.
can you provide more details on where and how your agent is running on the node?

for reference: the prerequisites to be able to run this - https://learn.netdata.cloud/docs/logs/systemd-journal/#plugin-availability

we'll fix the UI to show something meaning like:

> There isn't any log integration available on your node. Please check your integrations setup.
> Get more information on available log integrations [here](https://learn.netdata.cloud/docs/logs/).

@netdata/cloud-fe while trying to reproduce this, deploying netdata with docker remove the `ro` mapped volumes, case I got two different screens

1st time I went to the Logs tab
![image](https://github.com/netdata/netdata-cloud/assets/82235632/4c92555b-b172-4c7a-9529-9c66ec8e0794)

Other attempts
![image](https://github.com/netdata/netdata-cloud/assets/82235632/37e52026-4a89-432b-bfae-92520c287e06)

suggestion is to place the message mentioned above

**Comment by novykh** [comment]
Is this still an issue?

**Comment by douglasjthomas** [comment]
Looks good after the latest update.

Thank you,
Doug Thomas

Sent with [Proton Mail](https://proton.me/) secure email.
