### ISSUE TITLE
[Bug]: Alerts tab can't scroll to bottom of list (last item cut off)

### ISSUE THREAD

**Issue by gdevenyi** [netdata/netdata-cloud#977]
### Bug description

In the alerts list, scrolling to the bottom of the list, I can see one cutoff alert I can't get to.

### Expected behavior

Alert is accessible in list

### Steps to reproduce

Have more than a page of alerts such that scrolling is needed, try to scroll to bottom.

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/3001850/8b7e5f4c-645d-47d5-ad83-eb61881b59dc)

### Desktop

OS: Ubuntu 22.04
Browser Firefox
Browser Version 122

**Comment by novykh** [comment]
Should be fixed.
