### ISSUE TITLE
[Bug]: Unnecessary emails regarding disabled notification methods are being sent

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#978]
### Bug description

A month or two ago I had installed the mobile app and tested it out, and since then I deleted the mobile app. But I continue to receive emails about disabled notification service every few days NON-STOP. This doesn't make sense.

### Expected behavior

Notify the user ONCE about their notification service being disabled.

### Steps to reproduce

1. In my case it just happened after I deleted the mobile app. 

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/24860547/dd68ade7-e81f-4852-9f69-9f027fd6a2ab)

All the emails except the crossed out ones are about the same thing.

![image](https://github.com/netdata/netdata-cloud/assets/24860547/d2c13ed3-f41a-45e4-9011-ad55757638ec)

### Error Logs

N/A

### Desktop

I was using the Android app before I uninstalled it - not that it should matter.

**Comment by juacker** [comment]
We were enabling the `Mobile App` integration on every account update, so on the next alert, we would fail sending the notification and disable the integration again, generating a new user email. On the next account update we would enter again the same loop. 

we've released a fix to add extra constraints before enabling the integration again on every account update.

**Comment by juacker** [comment]
fix was released, closing.
