### ISSUE TITLE
[Bug]: Billing usage when showing the timeseries and the help message of usage vs committed nodes 0 was shown

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#979]
### Bug description

When checking the Plan & Billing and the usage there was a chance you would see a value of 0 (zero) if the calculation hadn't yet happened for the current day.

In the example for today, 5th of February, we have the:
* the help message "You are using 0 out of 3 committed nodes." where 0 is because no value was calculated yet
* timeseries has a entry with Daily count and Period count as 0.

![image](https://github.com/netdata/netdata-cloud/assets/82235632/5c2cb52f-cfbc-4ad1-a0a8-02c82dc5e48f)
 

### Expected behavior

If the values haven't been computed the best is to display the previous day figures until the current day is calculated

### Steps to reproduce

1.

### Desktop

Browser Version [e.g. 22]

**Comment by papazach** [comment]
The change has been merged by @vkuznecovas . Will give you a heads up when this gets released everywhere

**Comment by AleksCee** [comment]
Wow! That is fast, less than a day from my q&a post to this commit. I‘m really impressed!

**Comment by vkuznecovas** [comment]
The fix is now live. Thanks for the report @AleksCee!
