### ISSUE TITLE
[Bug]: Global node filter doesn't affect custom dashboards

### ISSUE THREAD

**Issue by mja00** [netdata/netdata-cloud#983]
### Bug description

When attempting to filter a custom dashboard globally to 1 node it's ignoring the filter and still shows all the nodes in the room.

### Expected behavior

The charts in the custom dashboard would be filtered down to the selected nodes.

### Steps to reproduce

1. Create a custom dashboard with any chart, I use `system.load`. 
2. Select a node in the global filter from the top right.
3. The `system.load` chart still shows all the nodes.

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/11252574/99c56071-b98a-4802-8041-6ff01899cd22)

### Error Logs

N/A

### Desktop

OS: Windows 11
Browser: Edge
Browser Version: `Version 121.0.2277.128 (Official build) (64-bit)`

**Comment by hugovalente-pm** [comment]
this was an implementation decision which we know it is confusing. we will need to allow users to decide if global filters should apply on the dashboard or not - FR https://github.com/netdata/netdata-cloud/issues/696
