### ISSUE TITLE
[Bug]: Windows node has gone stale and no longer showing in the parent Netdata instance.

### ISSUE THREAD

**Issue by mcdent** [netdata/netdata-cloud#986]
### Bug description

A windows node, running the prometheus endpoint is now showing as 'stale' in the netdata cloud (NC) this was added as a vnode. It used to show but for some reason now it does now. 
It also does not show at the end of the list in the Linux node which is scraping its data. I can connect 

### Expected behavior

I should actually be seeing 2 windows nodes at the bottom of the screenshot on the right side. As you can see in the screenshot neither are showing.

### Steps to reproduce

Try to view the windows node in the list under the linux host that is configured locally to run netdata.
This is the same output when viewing via the cloud login or going direct to the local IP of netdata.
I can also curl to the prometheus endpoint running on the windows host.

### Screenshots

<img width="1750" alt="here there should be 2 windows nodes showing" src="https://github.com/netdata/netdata-cloud/assets/8769856/57287037-3f52-42c6-8a85-66fbdd4e9be8">
<img width="1001" alt="windows and vnode config files" src="https://github.com/netdata/netdata-cloud/assets/8769856/c227a77d-4cba-4c1e-881f-532550d62a9c">
<img width="795" alt="metrics access ok" src="https://github.com/netdata/netdata-cloud/assets/8769856/f35cb63c-feec-48a3-ac22-95a6ba1038e2">
<img width="552" alt="vnode shows as stale" src="https://github.com/netdata/netdata-cloud/assets/8769856/8562d84d-7a50-4c5d-aaf2-dd085aec9f95">
<img width="1563" alt="curl to the windows endpoint" src="https://github.com/netdata/netdata-cloud/assets/8769856/bb5a9235-e4a6-476e-8d34-e9fe963ed4e2">

### Desktop

OS: MAcOS
Browser Firefox	
Browser Version 123.0 64 bit

**Comment by hugovalente-pm** [comment]
@mcdent do you have the same issue if you open your Linux machine local agent dashboard?
Have you also tried to run the `go.d.plugin` in debug mode from the Linux machine? https://learn.netdata.cloud/docs/collecting-metrics/windows-systems/windows#debug-mode

**Comment by mcdent** [comment]
Thanks for the tip @hugovalente-pm. I recreated the windows.conf and vnode.conf files, with fresh UIDs and now there seems to be no errors in the debug mode.
My remaining problem is the node which is marked as 'stale' is not collecting/sending any data, despite me being able to curl to the prometheus metric endpoint from the linux host. It shows as stale still in the linux host dashboard.

Is the fact it is marked as stay preventing this?

One other thing, no hardware spec of the windows machine is showing, I assume this is a limitation of prometheus?

Thanks
Mike

**Comment by hugovalente-pm** [comment]
> My remaining problem is the node which is marked as 'stale' is not collecting/sending any data, despite me being able to curl to the prometheus metric endpoint from the linux host. It shows as stale still in the linux host dashboard.

can you try just having just that node configured on your Linux machine and then run the debug mode? also try to access your Linux machine local agent dashboard?

> Is the fact it is marked as stay preventing this?

Stale means your Linux node has past data for that node but it doesn't "find" any current data.
a gut feeling, could there be a clock sync issue on that machine?

> One other thing, no hardware spec of the windows machine is showing, I assume this is a limitation of prometheus?

yes and no, atm we only get those specs for nodes where the agent is locally running there. we know we need to find a way to get this for remote Windows machines but it something currently on our backlog

**Comment by mcdent** [comment]
> > My remaining problem is the node which is marked as 'stale' is not collecting/sending any data, despite me being able to curl to the prometheus metric endpoint from the linux host. It shows as stale still in the linux host dashboard.
> 
> can you try just having just that node configured on your Linux machine and then run the debug mode? also try to access your Linux machine local agent dashboard?

Ok, doing this has now brought the errant asdf123 windows machine back. I have not tried adding the config file again for the windows box wiresx1, I will do that next?
Notice although the asdf123 is now reporting, it still shows as stale?

![Screenshot 2024-03-14 at 19 13 39](https://github.com/netdata/netdata-cloud/assets/8769856/047fefed-5c0f-40e7-8599-7b71581e32ef)

> 
> > Is the fact it is marked as stay preventing this?
> 
> Stale means your Linux node has past data for that node but it doesn't "find" any current data. a gut feeling, could there be a clock sync issue on that machine?

I checked the time on both windows boxes and they are both set to automatic and the time seems to align with that from the linux box collecting the stats.

> 
> > One other thing, no hardware spec of the windows machine is showing, I assume this is a limitation of prometheus?
> 
> yes and no, atm we only get those specs for nodes where the agent is locally running there. we know we need to find a way to get this for remote Windows machines but it something currently on our backlog

IS this why I am missing memory stats for one thing?
![Screenshot 2024-03-14 at 19 14 13](https://github.com/netdata/netdata-cloud/assets/8769856/38ce4a39-69f1-47aa-8581-b9bf30904464)

I also note that the average CPU utilisation does not seem to align with that of the Windows 11 pc?
Task manager on windows shows a fairly steady 20% cpu (whilst running some programs) however looking back over the same period on Netdata shows it as much lower?
![Screenshot 2024-03-14 at 16 44 28](https://github.com/netdata/netdata-cloud/assets/8769856/2f81c2cb-7075-4c51-aa1a-eae9bc2b993d)
![IMG_4504](https://github.com/netdata/netdata-cloud/assets/8769856/f2383730-4034-4a9b-9279-614848410be2)
Am I expecting too much from the windows clients? I don't really want to run the full agent on these boxes if possible.

Thanks
Mike

**Comment by mcdent** [comment]
Hmm, now I set the configs back I have ended up with 2 stale asdf123 windows nodes?
![Screenshot 2024-03-14 at 19 34 00](https://github.com/netdata/netdata-cloud/assets/8769856/7c287531-dc0f-4f19-9560-3bbd892f321a)

**Comment by mcdent** [comment]
Ok, lets update this here, think I have 3 days left on my trial and have been unsuccessful to add more than 1 windows node at a time.
I tried adding a completely new windows 10 pro machine, installed the prometheus endpoint via the instructions, I can curl to the endpoint just fine. Added the new windows node to the windows.conf and vnode.conf and restarted net data.
Now I see the last working windows node as stale and my new one shows up? What am I doing wrong?


![Screenshot 2024-03-17 at 16 57 59](https://github.com/netdata/netdata-cloud/assets/8769856/bff9a060-a39d-4b3c-9f7f-e8a34c72ed4b)
![Screenshot 2024-03-17 at 16 58 56](https://github.com/netdata/netdata-cloud/assets/8769856/268a186b-e815-4858-a5ca-913bc5ba4104)

**Comment by hugovalente-pm** [comment]
Can you share the vnode.conf file? What it seems is that the UUID is
clashing since you seem to get the last one connected to Cloud and the
other becomes stale - we saw this same issue when VMs are copied and for
the new one a new UUID isn't generated.

Btw, if you need a couple of more days to complete your tests we can extend
the trial for a bit longer

**Comment by hugovalente-pm** [comment]
seems there was already feedback on the possible issue, shared on Discord [here](https://discord.com/channels/847502280503590932/1212760101581094922/1218984588714704997)

> Remove the extra jobs, keep just one on top
That's an array in yaml

@mcdent if this works please update the result here

**Comment by mcdent** [comment]
Ok, the issue here was that I had a separate `job` entry for each host. They should all have been under the one `job` section. e.g. 
![Screenshot 2024-03-18 at 19 18 46](https://github.com/netdata/netdata-cloud/assets/8769856/6becc69a-c5d1-4d71-b402-fa68e3d9136d)

My bad all sorted.
