### ISSUE TITLE
[Feat]: Topology view of nodes

### ISSUE THREAD

**Issue by brodonalds** [netdata/netdata-cloud#987]
### Problem

I would like to see a topology/network view of my nodes

### Description

Ideally this view would show the parent nodes, replication between them, and also the children nodes feeding them. 

### Importance

nice to have

### Value proposition

1. Would help troubleshoot non-redundant nodes
2. Would help find any nodes feeding the cloud directly vs via a parent
3. Could allow for confirmation of misconfigured nodes.

**Comment by shyamvalsan** [comment]
duplicated by https://github.com/netdata/netdata-cloud/issues/1029
