### ISSUE TITLE
[Bug]: When passing before and after as absolute value parameters on an URL these aren't respected

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#995]
### Bug description

When a URL that contains the `before` and `after` parameters is opened in a new tab these aren't respected.
It seems if the absolute values are passed as value parameters they are _converted_ to relative value parameters

### Expected behavior

Before and After values should be respected

### Steps to reproduce

1. Select a specific time in the past
2. Copy the URL that has the absolute values
3. See that these aren't respected

### Screenshots

URL from "source"
![image](https://github.com/netdata/netdata-cloud/assets/82235632/c34aa36c-3009-42fc-845b-720911be09cf)

URL after opening in a new tab
![image](https://github.com/netdata/netdata-cloud/assets/82235632/c20d18b5-1e11-4c2a-956b-a09de35b7178)

### Desktop

Browser Version [e.g. 22]

**Comment by BenasPaulikas** [comment]
This must be quite a recent change.
I've used before/after params as timestamp(in ms) for years now. 
And only recently it broke.

**Comment by novykh** [comment]
Fixed and deployed.
