### ISSUE TITLE
[Bug]: Nodes tab / right bar not honoring space with quick charts

### ISSUE THREAD

**Issue by Ancairon** [netdata/netdata-cloud#998]
### Bug description

The right bar does not collapse the charts back to a smaller size if it is collapsed and then expanded

### Expected behavior

The available space should change in regards to what the bar is doing (given that by default it is set as expanded by default)

### Steps to reproduce

1. collapse right hand bar
2. expand

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/70198089/c8ffb33c-f6a7-4bec-92a8-201bcb902759)

![image](https://github.com/netdata/netdata-cloud/assets/70198089/37847158-7883-4c98-8c20-09c57d6a54b0)

### Desktop

OS: Ubuntu and Win 11	
Browser: Google chrome
Browser Version: -

**Comment by novykh** [comment]
Should be fixed.
